import type { Lesson } from '../../../types';

export const japaneseA2DailyLifeLessons: Lesson[] = [
  {
    id: 'ja-a2-l1-1-daily-routine',
    unitId: 'ja-a2-u1-daily-life',
    title: '一日の生活',
    titleVi: 'Thói quen hằng ngày',
    objectiveVi: "Mô tả các việc bạn làm hằng ngày bằng thì quá khứ 'ました'.",
    estimatedMinutes: 7,
    grammarNoteVi: "ました là dạng quá khứ lịch sự của ます. Ví dụ: 起きます (thức dậy) → 起きました (đã thức dậy).",
    vocabulary: [
      { id: 'ja-a2-l1-1-v1', term: '起きます', translationVi: 'Thức dậy', partOfSpeech: 'verb', exampleSentenceId: 'ja-a2-l1-1-s1', usageNoteVi: 'Cách đọc (romaji): okimasu' },
      { id: 'ja-a2-l1-1-v2', term: 'シャワーを浴びます', translationVi: 'Tắm vòi sen', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): shawā o abimasu' },
      { id: 'ja-a2-l1-1-v3', term: '会社に行きます', translationVi: 'Đi làm', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l1-1-s2', usageNoteVi: 'Cách đọc (romaji): kaisha ni ikimasu' },
      { id: 'ja-a2-l1-1-v4', term: '家に帰ります', translationVi: 'Về nhà', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ie ni kaerimasu' },
      { id: 'ja-a2-l1-1-v5', term: '昨日', translationVi: 'Hôm qua', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l1-1-s3', usageNoteVi: 'Cách đọc (romaji): kinou' },
      { id: 'ja-a2-l1-1-v6', term: 'いつも', translationVi: 'Luôn luôn, thường thì', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): itsumo' },
    ],
    sentences: [
      { id: 'ja-a2-l1-1-s1', text: '私はいつも七時に起きます。', translationVi: '(Watashi wa itsumo shichiji ni okimasu.) Tôi luôn thức dậy lúc bảy giờ.' },
      { id: 'ja-a2-l1-1-s2', text: '私は九時に会社に行きます。', translationVi: '(Watashi wa kuji ni kaisha ni ikimasu.) Tôi đi làm lúc chín giờ.' },
      { id: 'ja-a2-l1-1-s3', text: '昨日、六時に起きました。', translationVi: '(Kinou, rokuji ni okimashita.) Hôm qua tôi đã thức dậy lúc sáu giờ.' },
    ],
    exercises: [
      {
        id: 'ja-a2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng quá khứ đúng của '起きます'.",
        question: '昨日、六時に___。',
        options: ['起きます', '起きました', '起きています', '起きるつもりです'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-a2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '私は九時に会社に___。',
        wordBank: ['行きます', '帰ります', '昨日'],
        correctAnswer: '行きます',
      },
      {
        id: 'ja-a2-l1-1-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của 'いつも'.",
        question: 'いつも',
        options: ['Hôm qua', 'Luôn luôn, thường thì', 'Hôm nay', 'Ngày mai'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ja-a2-l1-2-time',
    unitId: 'ja-a2-u1-daily-life',
    title: '時間',
    titleVi: 'Giờ giấc',
    objectiveVi: "Nói giờ và hành động đang diễn ra bằng 'ています'.",
    estimatedMinutes: 7,
    grammarNoteVi: "ています diễn tả hành động đang diễn ra hoặc trạng thái tiếp diễn. Ví dụ: 食べています (đang ăn).",
    vocabulary: [
      { id: 'ja-a2-l1-2-v1', term: '今', translationVi: 'Bây giờ', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l1-2-s1', usageNoteVi: 'Cách đọc (romaji): ima' },
      { id: 'ja-a2-l1-2-v2', term: '何時ですか', translationVi: 'Mấy giờ rồi?', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l1-2-s2', usageNoteVi: 'Cách đọc (romaji): nanji desu ka' },
      { id: 'ja-a2-l1-2-v3', term: '半', translationVi: 'Rưỡi (30 phút)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): han' },
      { id: 'ja-a2-l1-2-v4', term: '早く', translationVi: 'Sớm', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): hayaku' },
      { id: 'ja-a2-l1-2-v5', term: '遅く', translationVi: 'Muộn', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l1-2-s3', usageNoteVi: 'Cách đọc (romaji): osoku' },
      { id: 'ja-a2-l1-2-v6', term: 'もう', translationVi: 'Đã, rồi', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): mou' },
    ],
    sentences: [
      { id: 'ja-a2-l1-2-s1', text: '今、何時ですか。', translationVi: '(Ima, nanji desu ka.) Bây giờ mấy giờ rồi?' },
      { id: 'ja-a2-l1-2-s2', text: '私は今、ご飯を食べています。', translationVi: '(Watashi wa ima, gohan o tabete imasu.) Tôi đang ăn cơm bây giờ.' },
      { id: 'ja-a2-l1-2-s3', text: '今日は遅く起きました。', translationVi: '(Kyou wa osoku okimashita.) Hôm nay tôi dậy muộn.' },
    ],
    exercises: [
      {
        id: 'ja-a2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: hành động đang diễn ra.',
        question: '私は今、ご飯を___。',
        options: ['食べます', '食べました', '食べています', '食べるつもりです'],
        correctOptionIndex: 2,
      },
      {
        id: 'ja-a2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '今、___ですか。',
        wordBank: ['何時', '半', '遅く'],
        correctAnswer: '何時',
      },
      {
        id: 'ja-a2-l1-2-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '早く'.",
        question: '早く',
        options: ['Muộn', 'Sớm', 'Bây giờ', 'Đã rồi'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ja-a2-l1-3-hobbies',
    unitId: 'ja-a2-u1-daily-life',
    title: '趣味',
    titleVi: 'Sở thích',
    objectiveVi: "Nói về sở thích và so sánh bằng 'より' (hơn).",
    estimatedMinutes: 7,
    grammarNoteVi: "より đặt sau danh từ để so sánh, nghĩa là 'hơn'. Ví dụ: 映画より音楽が好きです (Tôi thích âm nhạc hơn phim).",
    vocabulary: [
      { id: 'ja-a2-l1-3-v1', term: '趣味', translationVi: 'Sở thích', partOfSpeech: 'noun', exampleSentenceId: 'ja-a2-l1-3-s1', usageNoteVi: 'Cách đọc (romaji): shumi' },
      { id: 'ja-a2-l1-3-v2', term: '音楽を聞きます', translationVi: 'Nghe nhạc', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ongaku o kikimasu' },
      { id: 'ja-a2-l1-3-v3', term: '運動します', translationVi: 'Tập thể dục', partOfSpeech: 'verb', exampleSentenceId: 'ja-a2-l1-3-s2', usageNoteVi: 'Cách đọc (romaji): undou shimasu' },
      { id: 'ja-a2-l1-3-v4', term: 'より', translationVi: 'Hơn (so sánh)', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l1-3-s3', usageNoteVi: 'Cách đọc (romaji): yori' },
      { id: 'ja-a2-l1-3-v5', term: '映画を見ます', translationVi: 'Xem phim', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): eiga o mimasu' },
    ],
    sentences: [
      { id: 'ja-a2-l1-3-s1', text: '私の趣味は音楽を聞くことです。', translationVi: '(Watashi no shumi wa ongaku o kiku koto desu.) Sở thích của tôi là nghe nhạc.' },
      { id: 'ja-a2-l1-3-s2', text: '私は毎日運動します。', translationVi: '(Watashi wa mainichi undou shimasu.) Tôi tập thể dục mỗi ngày.' },
      { id: 'ja-a2-l1-3-s3', text: '映画より音楽のほうが好きです。', translationVi: '(Eiga yori ongaku no hou ga suki desu.) Tôi thích âm nhạc hơn phim.' },
    ],
    exercises: [
      {
        id: 'ja-a2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '趣味'.",
        question: '趣味',
        options: ['Nghề nghiệp', 'Sở thích', 'Gia đình', 'Thời gian'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-a2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ so sánh còn thiếu.',
        sentenceTemplate: '映画___音楽のほうが好きです。',
        wordBank: ['より', 'では', 'から'],
        correctAnswer: 'より',
      },
      {
        id: 'ja-a2-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi tập thể dục mỗi ngày."',
        words: ['運動します', '私は', '毎日'],
        correctOrder: ['私は', '毎日', '運動します'],
      },
    ],
  },
];
