import type { Lesson } from '../../../types';

export const japaneseA2TravelLessons: Lesson[] = [
  {
    id: 'ja-a2-l2-1-transportation',
    unitId: 'ja-a2-u2-travel',
    title: '交通',
    titleVi: 'Phương tiện giao thông',
    objectiveVi: "Nói cách di chuyển bằng 'から/まで' (từ/đến).",
    estimatedMinutes: 7,
    grammarNoteVi: "から nghĩa là 'từ', まで nghĩa là 'đến'. Dùng cùng nhau để chỉ điểm bắt đầu và kết thúc: 家から会社まで (từ nhà đến công ty).",
    vocabulary: [
      { id: 'ja-a2-l2-1-v1', term: '地下鉄', translationVi: 'Tàu điện ngầm', partOfSpeech: 'noun', exampleSentenceId: 'ja-a2-l2-1-s1', usageNoteVi: 'Cách đọc (romaji): chikatetsu' },
      { id: 'ja-a2-l2-1-v2', term: 'バス', translationVi: 'Xe buýt', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): basu' },
      { id: 'ja-a2-l2-1-v3', term: '乗ります', translationVi: 'Đi (phương tiện), lên xe', partOfSpeech: 'verb', exampleSentenceId: 'ja-a2-l2-1-s2', usageNoteVi: 'Cách đọc (romaji): norimasu' },
      { id: 'ja-a2-l2-1-v4', term: 'どのくらいかかりますか', translationVi: 'Mất bao lâu?', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l2-1-s3', usageNoteVi: 'Cách đọc (romaji): dono kurai kakarimasu ka' },
      { id: 'ja-a2-l2-1-v5', term: '駅', translationVi: 'Ga (tàu)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): eki' },
      { id: 'ja-a2-l2-1-v6', term: '乗り換えます', translationVi: 'Chuyển tuyến, đổi xe', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): norikaemasu' },
    ],
    sentences: [
      { id: 'ja-a2-l2-1-s1', text: '私は地下鉄に乗ります。', translationVi: '(Watashi wa chikatetsu ni norimasu.) Tôi đi tàu điện ngầm.' },
      { id: 'ja-a2-l2-1-s2', text: 'この駅でバスに乗り換えてください。', translationVi: '(Kono eki de basu ni norikaete kudasai.) Hãy chuyển sang xe buýt ở ga này.' },
      { id: 'ja-a2-l2-1-s3', text: '家から会社までどのくらいかかりますか。', translationVi: '(Ie kara kaisha made dono kurai kakarimasu ka.) Từ nhà đến công ty mất bao lâu?' },
    ],
    exercises: [
      {
        id: 'ja-a2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '地下鉄'.",
        question: '地下鉄',
        options: ['Xe buýt', 'Tàu điện ngầm', 'Taxi', 'Xe đạp'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-a2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền trợ từ 'từ' còn thiếu.",
        sentenceTemplate: '家___会社まで、どのくらいかかりますか。',
        wordBank: ['から', 'は', 'を'],
        correctAnswer: 'から',
      },
      {
        id: 'ja-a2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đi tàu điện ngầm."',
        words: ['乗ります', '私は', '地下鉄に'],
        correctOrder: ['私は', '地下鉄に', '乗ります'],
      },
    ],
  },
  {
    id: 'ja-a2-l2-2-shopping',
    unitId: 'ja-a2-u2-travel',
    title: '買い物',
    titleVi: 'Mua sắm',
    objectiveVi: "Hỏi giá và mặc cả khi mua sắm, dùng 'けど' (nhưng).",
    estimatedMinutes: 7,
    grammarNoteVi: "けど nghĩa là 'nhưng' (thân mật hơn が), nối hai vế câu đối lập. Ví dụ: かわいいけど高いです (Dễ thương nhưng đắt).",
    vocabulary: [
      { id: 'ja-a2-l2-2-v1', term: 'いくらですか', translationVi: 'Bao nhiêu tiền?', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l2-2-s1', usageNoteVi: 'Cách đọc (romaji): ikura desu ka' },
      { id: 'ja-a2-l2-2-v2', term: '高い', translationVi: 'Đắt', partOfSpeech: 'adjective', exampleSentenceId: 'ja-a2-l2-2-s2', usageNoteVi: 'Cách đọc (romaji): takai' },
      { id: 'ja-a2-l2-2-v3', term: '安い', translationVi: 'Rẻ', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (romaji): yasui' },
      { id: 'ja-a2-l2-2-v4', term: '少し安くしてください', translationVi: 'Bớt cho tôi một chút', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l2-2-s3', usageNoteVi: 'Cách đọc (romaji): sukoshi yasuku shite kudasai' },
      { id: 'ja-a2-l2-2-v5', term: '試着します', translationVi: 'Mặc thử', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): shichaku shimasu' },
    ],
    sentences: [
      { id: 'ja-a2-l2-2-s1', text: 'これはいくらですか。', translationVi: '(Kore wa ikura desu ka.) Cái này bao nhiêu tiền?' },
      { id: 'ja-a2-l2-2-s2', text: 'かわいいけど少し高いです。', translationVi: '(Kawaii kedo sukoshi takai desu.) Dễ thương nhưng hơi đắt.' },
      { id: 'ja-a2-l2-2-s3', text: '少し安くしてください。', translationVi: '(Sukoshi yasuku shite kudasai.) Bớt cho tôi một chút.' },
    ],
    exercises: [
      {
        id: 'ja-a2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '高い'.",
        question: '高い',
        options: ['Rẻ', 'Đắt', 'Dễ thương', 'Nhỏ'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-a2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: "Điền từ nối 'nhưng' còn thiếu.",
        sentenceTemplate: 'かわいい___高いです。',
        wordBank: ['けど', 'から', 'より'],
        correctAnswer: 'けど',
      },
      {
        id: 'ja-a2-l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi giá.',
        question: '正しい質問を選んでください。',
        options: ['これはいくらですか。', '今何時ですか。', 'どこから来ましたか。', '趣味は何ですか。'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'ja-a2-l2-3-food',
    unitId: 'ja-a2-u2-travel',
    title: '注文',
    titleVi: 'Gọi món ăn',
    objectiveVi: "Gọi món tại nhà hàng bằng 'たいです' (muốn).",
    estimatedMinutes: 7,
    grammarNoteVi: "たいです gắn vào gốc động từ (dạng ます bỏ ます) để diễn tả mong muốn. Ví dụ: 食べます→食べたいです (muốn ăn).",
    vocabulary: [
      { id: 'ja-a2-l2-3-v1', term: 'メニュー', translationVi: 'Thực đơn', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): menyuu' },
      { id: 'ja-a2-l2-3-v2', term: 'おすすめ', translationVi: 'Món gợi ý', partOfSpeech: 'noun', exampleSentenceId: 'ja-a2-l2-3-s1', usageNoteVi: 'Cách đọc (romaji): osusume' },
      { id: 'ja-a2-l2-3-v3', term: '辛い', translationVi: 'Cay', partOfSpeech: 'adjective', exampleSentenceId: 'ja-a2-l2-3-s2', usageNoteVi: 'Cách đọc (romaji): karai' },
      { id: 'ja-a2-l2-3-v4', term: '食べたいです', translationVi: 'Tôi muốn ăn', partOfSpeech: 'phrase', exampleSentenceId: 'ja-a2-l2-3-s3', usageNoteVi: 'Cách đọc (romaji): tabetai desu' },
      { id: 'ja-a2-l2-3-v5', term: 'お会計', translationVi: 'Tính tiền', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): okaikei' },
    ],
    sentences: [
      { id: 'ja-a2-l2-3-s1', text: 'おすすめは何ですか。', translationVi: '(Osusume wa nan desu ka.) Bạn gợi ý món gì?' },
      { id: 'ja-a2-l2-3-s2', text: 'この料理は辛いですか。', translationVi: '(Kono ryouri wa karai desu ka.) Món này có cay không?' },
      { id: 'ja-a2-l2-3-s3', text: 'ラーメンを食べたいです。', translationVi: '(Rāmen o tabetai desu.) Tôi muốn ăn mì ramen.' },
    ],
    exercises: [
      {
        id: 'ja-a2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '辛い'.",
        question: '辛い',
        options: ['Ngọt', 'Cay', 'Mặn', 'Chua'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-a2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng mong muốn đúng của 'ăn' (食べます).",
        sentenceTemplate: 'ラーメンを___。',
        wordBank: ['食べたいです', '食べました', '食べています'],
        correctAnswer: '食べたいです',
      },
      {
        id: 'ja-a2-l2-3-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để xin gợi ý món ăn.',
        question: '正しい質問を選んでください。',
        options: ['おすすめは何ですか。', 'いくらですか。', '何時ですか。', 'どこから来ましたか。'],
        correctOptionIndex: 0,
      },
    ],
  },
];
