import type { Lesson } from '../../../types';

export const englishA2DailyLifeLessons: Lesson[] = [
  {
    id: 'en-a2-l1-1-daily-routines',
    unitId: 'en-a2-u1-daily-life',
    title: 'Daily routines',
    titleVi: 'Thói quen hằng ngày',
    objectiveVi: "Mô tả các việc bạn làm hằng ngày, phân biệt Present Simple với Present Continuous.",
    estimatedMinutes: 7,
    grammarNoteVi:
      "Present Simple dùng cho thói quen lặp lại ('I get up at 7'). Present Continuous dùng cho việc đang xảy ra ngay lúc nói ('I'm getting up now').",
    vocabulary: [
      { id: 'en-a2-l1-1-v1', term: 'get up', translationVi: 'Thức dậy', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l1-1-s1' },
      { id: 'en-a2-l1-1-v2', term: 'commute', translationVi: 'Đi làm/đi học (di chuyển hằng ngày)', partOfSpeech: 'verb' },
      { id: 'en-a2-l1-1-v3', term: 'routine', translationVi: 'Thói quen, lịch trình', partOfSpeech: 'noun' },
      { id: 'en-a2-l1-1-v4', term: 'get dressed', translationVi: 'Mặc quần áo', partOfSpeech: 'phrase' },
      {
        id: 'en-a2-l1-1-v5',
        term: 'right now',
        translationVi: 'Ngay bây giờ',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'en-a2-l1-1-s2',
        usageNoteVi: 'Dấu hiệu thường đi cùng Present Continuous.',
      },
      { id: 'en-a2-l1-1-v6', term: 'usually', translationVi: 'Thường thì', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l1-1-s3' },
      { id: 'en-a2-l1-1-v7', term: 'go to bed', translationVi: 'Đi ngủ', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-a2-l1-1-s1', text: 'I get up at seven every day.', translationVi: 'Tôi thức dậy lúc 7 giờ mỗi ngày.' },
      { id: 'en-a2-l1-1-s2', text: "She's getting dressed right now.", translationVi: 'Cô ấy đang mặc quần áo ngay bây giờ.' },
      { id: 'en-a2-l1-1-s3', text: 'I usually commute by bus.', translationVi: 'Tôi thường đi làm bằng xe buýt.' },
    ],
    exercises: [
      {
        id: 'en-a2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: hành động đang xảy ra ngay lúc nói.',
        question: 'Look! She ___ (get dressed).',
        options: ['gets dressed', 'is getting dressed', 'get dressed', 'got dressed'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-a2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng của động từ cho thói quen lặp lại.',
        sentenceTemplate: 'I ___ up at seven every day.',
        wordBank: ['get', 'getting', 'got'],
        correctAnswer: 'get',
      },
      {
        id: 'en-a2-l1-1-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của 'routine'.",
        question: 'routine',
        options: ['Chuyến đi', 'Thói quen, lịch trình', 'Bữa ăn', 'Giấc ngủ'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'en-a2-l1-2-hobbies',
    unitId: 'en-a2-u1-daily-life',
    title: 'Hobbies and free time',
    titleVi: 'Sở thích và thời gian rảnh',
    objectiveVi: "Nói về sở thích bằng cấu trúc 'like/enjoy + V-ing'.",
    estimatedMinutes: 7,
    grammarNoteVi:
      "Sau 'like', 'enjoy', 'love', 'hate' khi diễn tả sở thích, động từ theo sau thường ở dạng V-ing: 'I enjoy reading', không phải 'I enjoy to read'.",
    vocabulary: [
      { id: 'en-a2-l1-2-v1', term: 'hobby', translationVi: 'Sở thích', partOfSpeech: 'noun', exampleSentenceId: 'en-a2-l1-2-s1' },
      { id: 'en-a2-l1-2-v2', term: 'enjoy', translationVi: 'Thích, tận hưởng', partOfSpeech: 'verb', exampleSentenceId: 'en-a2-l1-2-s2' },
      { id: 'en-a2-l1-2-v3', term: 'free time', translationVi: 'Thời gian rảnh', partOfSpeech: 'noun' },
      { id: 'en-a2-l1-2-v4', term: 'go jogging', translationVi: 'Đi chạy bộ', partOfSpeech: 'phrase' },
      { id: 'en-a2-l1-2-v5', term: 'paint', translationVi: 'Vẽ tranh', partOfSpeech: 'verb', exampleSentenceId: 'en-a2-l1-2-s3' },
      { id: 'en-a2-l1-2-v6', term: 'board game', translationVi: 'Trò chơi cờ bàn', partOfSpeech: 'noun' },
      {
        id: 'en-a2-l1-2-v7',
        term: 'be into',
        translationVi: 'Đam mê, thích thú với',
        partOfSpeech: 'phrase',
        usageNoteVi: "Cách nói thân mật hơn 'like', ví dụ: 'I'm into photography.'",
      },
    ],
    sentences: [
      { id: 'en-a2-l1-2-s1', text: 'My favorite hobby is painting.', translationVi: 'Sở thích yêu thích của tôi là vẽ tranh.' },
      { id: 'en-a2-l1-2-s2', text: 'I enjoy playing board games with friends.', translationVi: 'Tôi thích chơi cờ bàn với bạn bè.' },
      { id: 'en-a2-l1-2-s3', text: 'She paints every weekend.', translationVi: 'Cô ấy vẽ tranh mỗi cuối tuần.' },
    ],
    exercises: [
      {
        id: 'en-a2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng sau enjoy.',
        question: 'I enjoy ___ (read) before bed.',
        options: ['read', 'reading', 'to read', 'reads'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-a2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: 'My favorite ___ is painting.',
        wordBank: ['hobby', 'routine', 'commute'],
        correctAnswer: 'hobby',
      },
      {
        id: 'en-a2-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['jogging', 'go', 'I', 'every morning'],
        correctOrder: ['I', 'go', 'jogging', 'every morning'],
      },
    ],
  },
  {
    id: 'en-a2-l1-3-frequency',
    unitId: 'en-a2-u1-daily-life',
    title: 'Adverbs of frequency',
    titleVi: 'Trạng từ chỉ tần suất',
    objectiveVi: "Sử dụng always/usually/often/sometimes/rarely/never để mô tả tần suất.",
    estimatedMinutes: 6,
    grammarNoteVi:
      "Trạng từ tần suất đứng TRƯỚC động từ thường ('I often walk') nhưng SAU động từ 'to be' ('I am often late').",
    vocabulary: [
      { id: 'en-a2-l1-3-v1', term: 'always', translationVi: 'Luôn luôn', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l1-3-s1' },
      { id: 'en-a2-l1-3-v2', term: 'often', translationVi: 'Thường xuyên', partOfSpeech: 'phrase' },
      { id: 'en-a2-l1-3-v3', term: 'sometimes', translationVi: 'Thỉnh thoảng', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l1-3-s2' },
      { id: 'en-a2-l1-3-v4', term: 'rarely', translationVi: 'Hiếm khi', partOfSpeech: 'phrase' },
      { id: 'en-a2-l1-3-v5', term: 'never', translationVi: 'Không bao giờ', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l1-3-s3' },
      { id: 'en-a2-l1-3-v6', term: 'how often', translationVi: 'Bao lâu một lần / tần suất thế nào', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-a2-l1-3-s1', text: 'I always brush my teeth before bed.', translationVi: 'Tôi luôn đánh răng trước khi ngủ.' },
      { id: 'en-a2-l1-3-s2', text: 'We sometimes eat out on weekends.', translationVi: 'Chúng tôi thỉnh thoảng ăn ngoài vào cuối tuần.' },
      { id: 'en-a2-l1-3-s3', text: "He's never late for work.", translationVi: 'Anh ấy không bao giờ đi làm muộn.' },
    ],
    exercises: [
      {
        id: 'en-a2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn vị trí đúng của trạng từ tần suất với động từ thường.',
        question: 'Choose the correct sentence.',
        options: ['I often walk to work.', 'I walk often to work.', 'Often I walk to work.', 'I walk to work often always.'],
        correctOptionIndex: 0,
      },
      {
        id: 'en-a2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: "Điền trạng từ tần suất đúng vị trí với động từ 'to be'.",
        sentenceTemplate: "He's ___ late for meetings.",
        wordBank: ['never', 'commute', 'routine'],
        correctAnswer: 'never',
      },
      {
        id: 'en-a2-l1-3-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của 'rarely'.",
        question: 'rarely',
        options: ['Luôn luôn', 'Thường xuyên', 'Hiếm khi', 'Thỉnh thoảng'],
        correctOptionIndex: 2,
      },
    ],
  },
];
