import type { Lesson } from '../../../types';

export const englishA2TravelLessons: Lesson[] = [
  {
    id: 'en-a2-l2-1-directions',
    unitId: 'en-a2-u2-travel',
    title: 'Asking for directions',
    titleVi: 'Hỏi đường',
    objectiveVi: 'Hỏi và hiểu chỉ dẫn đường cơ bản (turn left/right, straight ahead).',
    estimatedMinutes: 7,
    grammarNoteVi:
      "Chỉ dẫn đường thường dùng câu mệnh lệnh (Imperative): 'Turn left', 'Go straight' — bỏ chủ ngữ, động từ đứng đầu câu.",
    vocabulary: [
      { id: 'en-a2-l2-1-v1', term: 'turn left', translationVi: 'Rẽ trái', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l2-1-s1' },
      { id: 'en-a2-l2-1-v2', term: 'turn right', translationVi: 'Rẽ phải', partOfSpeech: 'phrase' },
      { id: 'en-a2-l2-1-v3', term: 'go straight ahead', translationVi: 'Đi thẳng', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l2-1-s2' },
      { id: 'en-a2-l2-1-v4', term: 'intersection', translationVi: 'Ngã tư/giao lộ', partOfSpeech: 'noun' },
      { id: 'en-a2-l2-1-v5', term: 'across from', translationVi: 'Đối diện với', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l2-1-s3' },
      { id: 'en-a2-l2-1-v6', term: 'excuse me, how do I get to...', translationVi: 'Xin lỗi, làm sao để tới...', partOfSpeech: 'phrase' },
      { id: 'en-a2-l2-1-v7', term: 'landmark', translationVi: 'Địa điểm/mốc dễ nhận biết', partOfSpeech: 'noun' },
    ],
    sentences: [
      { id: 'en-a2-l2-1-s1', text: 'Turn left at the second traffic light.', translationVi: 'Rẽ trái ở đèn giao thông thứ hai.' },
      { id: 'en-a2-l2-1-s2', text: 'Go straight ahead for two blocks.', translationVi: 'Đi thẳng khoảng hai dãy nhà.' },
      { id: 'en-a2-l2-1-s3', text: 'The bank is across from the post office.', translationVi: 'Ngân hàng đối diện với bưu điện.' },
    ],
    exercises: [
      {
        id: 'en-a2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của 'intersection'.",
        question: 'intersection',
        options: ['Ngã tư/giao lộ', 'Con đường', 'Bến xe', 'Cây cầu'],
        correctOptionIndex: 0,
      },
      {
        id: 'en-a2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '___ left at the corner.',
        wordBank: ['Turn', 'Turning', 'Turns'],
        correctAnswer: 'Turn',
      },
      {
        id: 'en-a2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['ahead', 'straight', 'go', 'please'],
        correctOrder: ['go', 'straight', 'ahead', 'please'],
      },
    ],
  },
  {
    id: 'en-a2-l2-2-shopping',
    unitId: 'en-a2-u2-travel',
    title: 'Shopping',
    titleVi: 'Mua sắm',
    objectiveVi: 'Hỏi giá, kích cỡ và thương lượng khi mua sắm.',
    estimatedMinutes: 7,
    grammarNoteVi: "Danh từ đếm được (size, item) dùng 'How many', danh từ không đếm được (money, price nói chung) dùng 'How much'.",
    vocabulary: [
      { id: 'en-a2-l2-2-v1', term: 'how much is this?', translationVi: 'Cái này giá bao nhiêu?', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l2-2-s1' },
      { id: 'en-a2-l2-2-v2', term: 'try on', translationVi: 'Thử (quần áo)', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l2-2-s2' },
      { id: 'en-a2-l2-2-v3', term: 'size', translationVi: 'Kích cỡ', partOfSpeech: 'noun' },
      { id: 'en-a2-l2-2-v4', term: 'discount', translationVi: 'Giảm giá', partOfSpeech: 'noun', exampleSentenceId: 'en-a2-l2-2-s3' },
      { id: 'en-a2-l2-2-v5', term: 'cash', translationVi: 'Tiền mặt', partOfSpeech: 'noun' },
      { id: 'en-a2-l2-2-v6', term: 'receipt', translationVi: 'Hoá đơn', partOfSpeech: 'noun' },
      { id: 'en-a2-l2-2-v7', term: 'too expensive', translationVi: 'Quá đắt', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-a2-l2-2-s1', text: 'How much is this jacket?', translationVi: 'Cái áo khoác này giá bao nhiêu?' },
      { id: 'en-a2-l2-2-s2', text: 'Can I try this on?', translationVi: 'Tôi có thể thử cái này không?' },
      { id: 'en-a2-l2-2-s3', text: 'Is there a discount today?', translationVi: 'Hôm nay có giảm giá không?' },
    ],
    exercises: [
      {
        id: 'en-a2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của 'discount'.",
        question: 'discount',
        options: ['Hoá đơn', 'Giảm giá', 'Kích cỡ', 'Tiền mặt'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-a2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: 'Can I ___ this on?',
        wordBank: ['try', 'tried', 'trying'],
        correctAnswer: 'try',
      },
      {
        id: 'en-a2-l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi giá.',
        question: 'Choose the correct question.',
        options: ['How much is this?', 'How many is this?', 'How this is much?', 'This is how much?'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'en-a2-l2-3-ordering-food',
    unitId: 'en-a2-u2-travel',
    title: 'Ordering food',
    titleVi: 'Gọi món ăn',
    objectiveVi: "Gọi món tại nhà hàng và dùng 'would like' một cách lịch sự.",
    estimatedMinutes: 7,
    grammarNoteVi:
      "'Would like' lịch sự hơn 'want' khi gọi món: 'I would like a coffee' thay vì 'I want a coffee'. Có thể rút gọn 'I'd like'.",
    vocabulary: [
      { id: 'en-a2-l2-3-v1', term: "I'd like...", translationVi: 'Tôi muốn gọi...', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l2-3-s1' },
      { id: 'en-a2-l2-3-v2', term: 'menu', translationVi: 'Thực đơn', partOfSpeech: 'noun' },
      { id: 'en-a2-l2-3-v3', term: 'recommend', translationVi: 'Gợi ý, đề xuất', partOfSpeech: 'verb', exampleSentenceId: 'en-a2-l2-3-s2' },
      { id: 'en-a2-l2-3-v4', term: 'check, please', translationVi: 'Cho tôi xin hoá đơn', partOfSpeech: 'phrase', exampleSentenceId: 'en-a2-l2-3-s3' },
      { id: 'en-a2-l2-3-v5', term: 'spicy', translationVi: 'Cay', partOfSpeech: 'adjective' },
      { id: 'en-a2-l2-3-v6', term: 'reservation', translationVi: 'Đặt bàn/đặt chỗ', partOfSpeech: 'noun' },
    ],
    sentences: [
      { id: 'en-a2-l2-3-s1', text: "I'd like the grilled chicken, please.", translationVi: 'Tôi muốn gọi món gà nướng, làm ơn.' },
      { id: 'en-a2-l2-3-s2', text: 'What do you recommend?', translationVi: 'Bạn gợi ý món gì?' },
      { id: 'en-a2-l2-3-s3', text: 'Can I have the check, please?', translationVi: 'Cho tôi xin hoá đơn được không?' },
    ],
    exercises: [
      {
        id: 'en-a2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn cách gọi món lịch sự nhất.",
        question: 'Choose the most polite way to order.',
        options: ['I want a coffee.', "I'd like a coffee, please.", 'Give me a coffee.', 'Coffee now.'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-a2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: 'What do you ___?',
        wordBank: ['recommend', 'reservation', 'spicy'],
        correctAnswer: 'recommend',
      },
      {
        id: 'en-a2-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['please', 'the check', 'have', 'can I'],
        correctOrder: ['can I', 'have', 'the check', 'please'],
      },
    ],
  },
];
