import type { ConversationScenario } from '../../types';

export const chineseA2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'zh-a2-conv-daily-routine',
    languageCode: 'zh',
    level: 'A2',
    title: '谈论一天的生活',
    titleVi: 'Nói về một ngày của bạn',
    descriptionVi: 'Luyện hội thoại hỏi và kể về thói quen hằng ngày bằng tiếng Trung.',
    contextVi: 'Lan và An trò chuyện về lịch trình một ngày bình thường.',
    dialogue: [
      { id: 'zh-a2-daily-turn-01', speaker: 'A', text: '你一般几点起床？', translationVi: '(Nǐ yìbān jǐ diǎn qǐchuáng?) Bạn thường dậy lúc mấy giờ?' },
      { id: 'zh-a2-daily-turn-02', speaker: 'B', text: '我一般七点起床。', translationVi: '(Wǒ yìbān qī diǎn qǐchuáng.) Tôi thường dậy lúc bảy giờ.' },
      { id: 'zh-a2-daily-turn-03', speaker: 'A', text: '这么早？然后做什么？', translationVi: '(Zhème zǎo? Ránhòu zuò shénme?) Sớm vậy? Sau đó bạn làm gì?' },
      { id: 'zh-a2-daily-turn-04', speaker: 'B', text: '洗澡，然后吃早饭。', translationVi: '(Xǐzǎo, ránhòu chī zǎofàn.) Tôi tắm rửa rồi ăn sáng.' },
      { id: 'zh-a2-daily-turn-05', speaker: 'A', text: '你怎么去公司？', translationVi: '(Nǐ zěnme qù gōngsī?) Bạn đi đến công ty bằng gì?' },
      { id: 'zh-a2-daily-turn-06', speaker: 'B', text: '我坐地铁。', translationVi: '(Wǒ zuò dìtiě.) Tôi đi tàu điện ngầm.' },
      { id: 'zh-a2-daily-turn-07', speaker: 'A', text: '你现在在做什么？', translationVi: '(Nǐ xiànzài zài zuò shénme?) Bây giờ bạn đang làm gì?' },
      { id: 'zh-a2-daily-turn-08', speaker: 'B', text: '我在跟同事吃午饭。', translationVi: '(Wǒ zài gēn tóngshì chī wǔfàn.) Tôi đang ăn trưa với đồng nghiệp.' },
    ],
    relatedVocabularyIds: ['zh-a2-l1-1-v1', 'zh-a2-l1-1-v6', 'zh-a2-l1-2-v1', 'zh-a2-l2-1-v3'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '你一般几点起床？'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: '我一般七点起床。' },
        { id: 'o2', text: '这个多少钱？' },
        { id: 'o3', text: '下个月我会去留学。' },
        { id: 'o4', text: '虽然辣，但是好吃。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về thói quen hỏi giờ giấc, nên trả lời bằng thời gian bạn thường thức dậy.",
    },
  },
  {
    id: 'zh-a2-conv-shopping-trip',
    languageCode: 'zh',
    level: 'A2',
    title: '购物',
    titleVi: 'Chuyến đi mua sắm',
    descriptionVi: 'Luyện hội thoại hỏi giá và mặc cả khi mua sắm bằng tiếng Trung.',
    contextVi: 'Lan đang mua một chiếc áo khoác tại cửa hàng quần áo.',
    dialogue: [
      { id: 'zh-a2-shop-turn-01', speaker: 'A', text: '这件外套多少钱？', translationVi: '(Zhè jiàn wàitào duōshao qián?) Áo khoác này giá bao nhiêu?' },
      { id: 'zh-a2-shop-turn-02', speaker: 'B', text: '五十块。你要试穿吗？', translationVi: '(Wǔshí kuài. Nǐ yào shìchuān ma?) Giá 50 tệ. Bạn muốn mặc thử không?' },
      { id: 'zh-a2-shop-turn-03', speaker: 'A', text: '好的。有小一点儿的吗？', translationVi: '(Hǎo de. Yǒu xiǎo yìdiǎnr de ma?) Được. Bạn có cỡ nhỏ hơn không?' },
      { id: 'zh-a2-shop-turn-04', speaker: 'B', text: '有，给你。', translationVi: '(Yǒu, gěi nǐ.) Có, đây bạn.' },
      { id: 'zh-a2-shop-turn-05', speaker: 'A', text: '虽然漂亮，但是有点贵。能便宜一点儿吗？', translationVi: '(Suīrán piàoliang, dànshì yǒudiǎn guì. Néng piányi yìdiǎnr ma?) Đẹp nhưng hơi đắt. Bớt được không?' },
      { id: 'zh-a2-shop-turn-06', speaker: 'B', text: '好，给你便宜五块。', translationVi: '(Hǎo, gěi nǐ piányi wǔ kuài.) Được, tôi bớt cho bạn 5 tệ.' },
      { id: 'zh-a2-shop-turn-07', speaker: 'A', text: '谢谢，我付现金。', translationVi: '(Xièxiè, wǒ fù xiànjīn.) Cảm ơn, tôi trả tiền mặt.' },
      { id: 'zh-a2-shop-turn-08', speaker: 'B', text: '好的，这是你的收据。', translationVi: '(Hǎo de, zhè shì nǐ de shōujù.) Được, đây là hoá đơn của bạn.' },
    ],
    relatedVocabularyIds: ['zh-a2-l2-2-v1', 'zh-a2-l2-2-v2', 'zh-a2-l2-2-v4', 'zh-a2-l2-2-v5'],
    task: {
      type: 'choose-reply',
      promptVi: "Nhân viên hỏi '你要试穿吗？'. Bạn muốn thử, trả lời thế nào?",
      options: [
        { id: 'o1', text: '好的。' },
        { id: 'o2', text: '要多长时间？' },
        { id: 'o3', text: '买单。' },
        { id: 'o4', text: '去年我旅行了。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Đồng ý làm gì đó, cách trả lời tự nhiên và ngắn gọn nhất là '好的。'",
    },
  },
  {
    id: 'zh-a2-conv-making-plans',
    languageCode: 'zh',
    level: 'A2',
    title: '安排计划',
    titleVi: 'Lên kế hoạch và mời bạn',
    descriptionVi: 'Luyện hội thoại mời bạn bè và nói về kế hoạch tương lai bằng tiếng Trung.',
    contextVi: 'Minh mời An đi xem phim vào cuối tuần.',
    dialogue: [
      { id: 'zh-a2-plans-turn-01', speaker: 'A', text: '这周末一起看电影吧？', translationVi: '(Zhè zhōumò yìqǐ kàn diànyǐng ba?) Cuối tuần này cùng xem phim nhé?' },
      { id: 'zh-a2-plans-turn-02', speaker: 'B', text: '好啊！几点？', translationVi: '(Hǎo a! Jǐ diǎn?) Được đấy! Mấy giờ?' },
      { id: 'zh-a2-plans-turn-03', speaker: 'A', text: '我会买晚上七点的票。', translationVi: '(Wǒ huì mǎi wǎnshang qī diǎn de piào.) Tôi sẽ mua vé lúc 7 giờ tối.' },
      { id: 'zh-a2-plans-turn-04', speaker: 'B', text: '好，我们那儿见。', translationVi: '(Hǎo, wǒmen nàr jiàn.) Được, gặp nhau ở đó nhé.' },
      { id: 'zh-a2-plans-turn-05', speaker: 'A', text: '你看过新的动作电影吗？', translationVi: '(Nǐ kànguo xīn de dòngzuò diànyǐng ma?) Bạn đã xem phim hành động mới chưa?' },
      { id: 'zh-a2-plans-turn-06', speaker: 'B', text: '还没有，听说很好看。', translationVi: '(Hái méiyǒu, tīngshuō hěn hǎokàn.) Chưa. Nghe nói hay lắm.' },
      { id: 'zh-a2-plans-turn-07', speaker: 'A', text: '对了，下个月你有时间吗？', translationVi: '(Duìle, xià gè yuè nǐ yǒu shíjiān ma?) À, tháng sau bạn có rảnh không?' },
      { id: 'zh-a2-plans-turn-08', speaker: 'B', text: '对不起，我不能去，因为要去旅行。', translationVi: '(Duìbuqǐ, wǒ bùnéng qù, yīnwèi yào qù lǚxíng.) Xin lỗi, tôi không đi được, vì phải đi du lịch.' },
    ],
    relatedVocabularyIds: ['zh-a2-l3-2-v1', 'zh-a2-l3-2-v2', 'zh-a2-l3-2-v3', 'zh-a2-l3-2-v4'],
    task: {
      type: 'complete-reply',
      promptVi: "Hoàn thành câu trả lời phù hợp cho lời mời '一起看电影吧？'",
      options: [
        { id: 'o1', text: '好啊！' },
        { id: 'o2', text: '多少钱？' },
        { id: 'o3', text: '我坐地铁。' },
        { id: 'o4', text: '几点了？' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi nhận lời mời một cách vui vẻ, cách trả lời tự nhiên là '好啊！'",
    },
  },
];
