import type { GrammarTopic } from '../../types';

export const chineseA2GrammarTopics: GrammarTopic[] = [
  {
    id: 'zh-a2-gr-guo',
    languageCode: 'zh',
    level: 'A2',
    title: '过 (guò)',
    titleVi: 'Trợ từ kinh nghiệm "过"',
    explanationVi:
      "过 đặt sau động từ để nói về kinh nghiệm ĐÃ TỪNG làm, không quan trọng thời điểm cụ thể. Khác 了 (nhấn vào việc vừa hoàn thành gần đây).",
    structure: '动词 + 过',
    keyPoints: ['我去过日本 (Tôi đã từng đi Nhật)', '我没去过美国 (Tôi chưa từng đi Mỹ — phủ định dùng 没, không dùng 不)', "过 trả lời câu hỏi 'đã từng bao giờ chưa', 了 trả lời 'đã làm xong chưa'"],
    examples: [
      { id: 'zh-a2-gr-guo-s1', text: '我去过韩国。', translationVi: 'Tôi đã từng đi Hàn Quốc.' },
      { id: 'zh-a2-gr-guo-s2', text: '我没吃过这个菜。', translationVi: 'Tôi chưa từng ăn món này.' },
      { id: 'zh-a2-gr-guo-s3', text: '你看过这部电影吗？', translationVi: 'Bạn đã từng xem bộ phim này chưa?' },
    ],
    commonMistakesVi: "Người mới học hay dùng 不 để phủ định 过 thay vì 没, ví dụ nói '不去过' thay vì '没去过'.",
    exercises: [
      {
        id: 'zh-a2-gr-guo-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng để nói kinh nghiệm đã từng làm.',
        question: '我去___韩国。',
        options: ['过', '了', '在', '会'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-a2-gr-guo-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ phủ định đúng cho 过.',
        sentenceTemplate: '我___吃过这个菜。',
        wordBank: ['没', '不', '别'],
        correctAnswer: '没',
      },
      {
        id: 'zh-a2-gr-guo-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu hỏi đúng.',
        words: ['吗', '看过', '你', '这部电影'],
        correctOrder: ['你', '看过', '这部电影', '吗'],
      },
    ],
  },
  {
    id: 'zh-a2-gr-le',
    languageCode: 'zh',
    level: 'A2',
    title: '了 (le)',
    titleVi: 'Trợ từ hoàn thành "了"',
    explanationVi: "了 đặt sau động từ (hoặc cuối câu) để chỉ hành động đã hoàn thành hoặc có sự thay đổi.",
    structure: '动词 + 了',
    keyPoints: ['我吃饭了 (Tôi đã ăn cơm rồi)', '他来了 (Anh ấy đến rồi)', "Khác 过: 了 nhấn vào việc VỪA hoàn thành, không nhấn 'đã từng'"],
    examples: [
      { id: 'zh-a2-gr-le-s1', text: '我吃饭了。', translationVi: 'Tôi đã ăn cơm rồi.' },
      { id: 'zh-a2-gr-le-s2', text: '他已经走了。', translationVi: 'Anh ấy đã đi rồi.' },
      { id: 'zh-a2-gr-le-s3', text: '我买了一件衣服。', translationVi: 'Tôi đã mua một cái áo.' },
    ],
    commonMistakesVi: "Người mới học hay dùng 了 và 过 thay thế cho nhau dù sắc thái khác nhau (vừa hoàn thành vs. đã từng).",
    exercises: [
      {
        id: 'zh-a2-gr-le-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng để nói hành động vừa hoàn thành.',
        question: '我吃饭___。',
        options: ['了', '过', '在', '要'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-a2-gr-le-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '他已经走___。',
        wordBank: ['了', '过', '吗'],
        correctAnswer: '了',
      },
      {
        id: 'zh-a2-gr-le-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đã mua một cái áo."',
        words: ['一件衣服', '了', '我买'],
        correctOrder: ['我买', '了', '一件衣服'],
      },
    ],
  },
  {
    id: 'zh-a2-gr-hui-yao',
    languageCode: 'zh',
    level: 'A2',
    title: '会 / 要',
    titleVi: 'Diễn tả tương lai: "会" và "要"',
    explanationVi:
      "会 diễn tả khả năng/dự định trong tương lai (đôi khi mang tính dự đoán). 要 diễn tả ý định/kế hoạch gần, chắc chắn hơn 会.",
    structure: '主语 + 会/要 + 动词',
    keyPoints: ["下个月我会去留学 (Tháng tới tôi sẽ đi du học)", '我要坐地铁 (Tôi sẽ/muốn đi tàu điện ngầm)', '会 cũng dùng để nói về kỹ năng: 我会说中文 (Tôi biết nói tiếng Trung)'],
    examples: [
      { id: 'zh-a2-gr-huiyao-s1', text: '明天会下雨。', translationVi: 'Ngày mai trời sẽ mưa.' },
      { id: 'zh-a2-gr-huiyao-s2', text: '我要去超市。', translationVi: 'Tôi sẽ đi siêu thị.' },
      { id: 'zh-a2-gr-huiyao-s3', text: '我会说一点儿中文。', translationVi: 'Tôi biết nói một chút tiếng Trung.' },
    ],
    commonMistakesVi: "Người mới học hay lẫn lộn 会 (khả năng/dự đoán) với 要 (ý định gần) dù cả hai đều dịch là 'sẽ'.",
    exercises: [
      {
        id: 'zh-a2-gr-huiyao-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ đúng để nói về kỹ năng: 'Tôi biết nói tiếng Trung.'",
        question: '我___说中文。',
        options: ['会', '要', '了', '过'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-a2-gr-huiyao-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '我___去超市。',
        wordBank: ['要', '过', '在'],
        correctAnswer: '要',
      },
      {
        id: 'zh-a2-gr-huiyao-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu dự đoán đúng: "Ngày mai trời sẽ mưa."',
        question: '选择正确的句子。',
        options: ['明天会下雨。', '明天要下雨了。', '明天下雨过。', '明天在下雨。'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'zh-a2-gr-bi',
    languageCode: 'zh',
    level: 'A2',
    title: '比 (bǐ)',
    titleVi: 'So sánh hơn với "比"',
    explanationVi: "比 dùng để so sánh: A 比 B + tính từ, nghĩa là 'A hơn B'.",
    structure: 'A + 比 + B + 形容词',
    keyPoints: ['这个比那个贵 (Cái này đắt hơn cái kia)', '今天比昨天冷 (Hôm nay lạnh hơn hôm qua)', 'Phủ định: A 没有 B + 形容词 (A không bằng B)'],
    examples: [
      { id: 'zh-a2-gr-bi-s1', text: '这个比那个贵。', translationVi: 'Cái này đắt hơn cái kia.' },
      { id: 'zh-a2-gr-bi-s2', text: '今天比昨天冷。', translationVi: 'Hôm nay lạnh hơn hôm qua.' },
      { id: 'zh-a2-gr-bi-s3', text: '弟弟比我高。', translationVi: 'Em trai cao hơn tôi.' },
    ],
    commonMistakesVi: "Người mới học hay quên trật tự A比B+tính từ, đặt tính từ sai vị trí.",
    exercises: [
      {
        id: 'zh-a2-gr-bi-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ so sánh đúng.',
        question: '这个___那个贵。',
        options: ['比', '过', '了', '会'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-a2-gr-bi-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '今天___昨天冷。',
        wordBank: ['比', '在', '要'],
        correctAnswer: '比',
      },
      {
        id: 'zh-a2-gr-bi-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Em trai cao hơn tôi."',
        words: ['高', '弟弟', '比我'],
        correctOrder: ['弟弟', '比我', '高'],
      },
    ],
  },
  {
    id: 'zh-a2-gr-suiran-danshi',
    languageCode: 'zh',
    level: 'A2',
    title: '虽然...但是...',
    titleVi: 'Nối câu đối lập "虽然...但是..."',
    explanationVi: "虽然...但是... nghĩa là 'mặc dù...nhưng...', nối hai vế câu có ý đối lập.",
    structure: '虽然 + 分句1，但是 + 分句2',
    keyPoints: ['虽然漂亮，但是贵 (Mặc dù đẹp nhưng đắt)', '虽然辣，但是好吃 (Mặc dù cay nhưng ngon)', '但是 có thể lược bỏ 虽然 nếu ngữ cảnh đã rõ, nhưng nên giữ đủ cặp khi mới học'],
    examples: [
      { id: 'zh-a2-gr-srds-s1', text: '虽然漂亮，但是贵。', translationVi: 'Mặc dù đẹp nhưng đắt.' },
      { id: 'zh-a2-gr-srds-s2', text: '虽然辣，但是好吃。', translationVi: 'Mặc dù cay nhưng ngon.' },
      { id: 'zh-a2-gr-srds-s3', text: '虽然累，但是我很开心。', translationVi: 'Mặc dù mệt nhưng tôi rất vui.' },
    ],
    commonMistakesVi: "Người mới học hay chỉ dùng một trong hai từ (chỉ 虽然 hoặc chỉ 但是) mà không ghép thành cặp.",
    exercises: [
      {
        id: 'zh-a2-gr-srds-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn cặp từ đúng cho 'mặc dù...nhưng...'.",
        question: '选择正确的连词。',
        options: ['虽然...但是...', '因为...所以...', '还是...还是...', '比...了...'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-a2-gr-srds-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '虽然辣，___好吃。',
        wordBank: ['但是', '因为', '还是'],
        correctAnswer: '但是',
      },
      {
        id: 'zh-a2-gr-srds-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Mặc dù mệt nhưng tôi rất vui."',
        words: ['我很开心', '虽然累', '但是'],
        correctOrder: ['虽然累', '但是', '我很开心'],
      },
    ],
  },
];
