import type { ConversationScenario } from '../../types';

export const japaneseA2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'ja-a2-conv-daily-routine',
    languageCode: 'ja',
    level: 'A2',
    title: '一日について話す',
    titleVi: 'Nói về một ngày của bạn',
    descriptionVi: 'Luyện hội thoại hỏi và kể về thói quen hằng ngày bằng tiếng Nhật.',
    contextVi: 'Lan và An trò chuyện về lịch trình một ngày bình thường.',
    dialogue: [
      { id: 'ja-a2-daily-turn-01', speaker: 'A', text: 'いつも何時に起きますか。', translationVi: '(Itsumo nanji ni okimasu ka.) Bạn thường thức dậy lúc mấy giờ?' },
      { id: 'ja-a2-daily-turn-02', speaker: 'B', text: '私はいつも七時に起きます。', translationVi: '(Watashi wa itsumo shichiji ni okimasu.) Tôi luôn thức dậy lúc bảy giờ.' },
      { id: 'ja-a2-daily-turn-03', speaker: 'A', text: 'そんなに早く？その後何をしますか。', translationVi: '(Sonna ni hayaku? Sonogo nani o shimasu ka.) Sớm vậy? Sau đó bạn làm gì?' },
      { id: 'ja-a2-daily-turn-04', speaker: 'B', text: 'シャワーを浴びて、朝ご飯を食べます。', translationVi: '(Shawā o abite, asagohan o tabemasu.) Tôi tắm rồi ăn sáng.' },
      { id: 'ja-a2-daily-turn-05', speaker: 'A', text: '会社までどうやって行きますか。', translationVi: '(Kaisha made douyatte ikimasu ka.) Bạn đi đến công ty bằng gì?' },
      { id: 'ja-a2-daily-turn-06', speaker: 'B', text: '地下鉄に乗ります。', translationVi: '(Chikatetsu ni norimasu.) Tôi đi tàu điện ngầm.' },
      { id: 'ja-a2-daily-turn-07', speaker: 'A', text: '今何をしていますか。', translationVi: '(Ima nani o shite imasu ka.) Bây giờ bạn đang làm gì?' },
      { id: 'ja-a2-daily-turn-08', speaker: 'B', text: '同僚とお昼ご飯を食べています。', translationVi: '(Douryou to ohirugohan o tabete imasu.) Tôi đang ăn trưa với đồng nghiệp.' },
    ],
    relatedVocabularyIds: ['ja-a2-l1-1-v1', 'ja-a2-l1-1-v6', 'ja-a2-l1-2-v1', 'ja-a2-l2-1-v3'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi 'いつも何時に起きますか。'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: '私はいつも七時に起きます。' },
        { id: 'o2', text: 'これはいくらですか。' },
        { id: 'o3', text: '来月、留学するつもりです。' },
        { id: 'o4', text: 'かわいいけど高いです。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về thói quen hỏi giờ giấc, nên trả lời bằng thời gian bạn thường thức dậy.",
    },
  },
  {
    id: 'ja-a2-conv-shopping-trip',
    languageCode: 'ja',
    level: 'A2',
    title: '買い物',
    titleVi: 'Chuyến đi mua sắm',
    descriptionVi: 'Luyện hội thoại hỏi giá và mặc cả khi mua sắm bằng tiếng Nhật.',
    contextVi: 'Lan đang mua một chiếc áo khoác tại cửa hàng quần áo.',
    dialogue: [
      { id: 'ja-a2-shop-turn-01', speaker: 'A', text: 'すみません、このジャケットはいくらですか。', translationVi: '(Sumimasen, kono jaketto wa ikura desu ka.) Xin lỗi, áo khoác này giá bao nhiêu?' },
      { id: 'ja-a2-shop-turn-02', speaker: 'B', text: '五千円です。試着しますか。', translationVi: '(Gosen en desu. Shichaku shimasu ka.) Giá 5000 yên. Bạn muốn mặc thử không?' },
      { id: 'ja-a2-shop-turn-03', speaker: 'A', text: 'はい、お願いします。もっと小さいサイズはありますか。', translationVi: '(Hai, onegaishimasu. Motto chiisai saizu wa arimasu ka.) Vâng, làm ơn. Bạn có cỡ nhỏ hơn không?' },
      { id: 'ja-a2-shop-turn-04', speaker: 'B', text: 'はい、どうぞ。', translationVi: '(Hai, douzo.) Có, đây bạn.' },
      { id: 'ja-a2-shop-turn-05', speaker: 'A', text: 'かわいいけど少し高いです。少し安くしてください。', translationVi: '(Kawaii kedo sukoshi takai desu. Sukoshi yasuku shite kudasai.) Dễ thương nhưng hơi đắt. Bớt cho tôi chút nhé.' },
      { id: 'ja-a2-shop-turn-06', speaker: 'B', text: 'わかりました、少し安くします。', translationVi: '(Wakarimashita, sukoshi yasuku shimasu.) Được, tôi sẽ bớt một chút.' },
      { id: 'ja-a2-shop-turn-07', speaker: 'A', text: 'ありがとうございます。現金で払います。', translationVi: '(Arigatou gozaimasu. Genkin de haraimasu.) Cảm ơn. Tôi trả tiền mặt.' },
      { id: 'ja-a2-shop-turn-08', speaker: 'B', text: 'はい、こちらがレシートです。', translationVi: '(Hai, kochira ga reshiito desu.) Vâng, đây là hoá đơn của bạn.' },
    ],
    relatedVocabularyIds: ['ja-a2-l2-2-v1', 'ja-a2-l2-2-v2', 'ja-a2-l2-2-v4', 'ja-a2-l2-2-v5'],
    task: {
      type: 'choose-reply',
      promptVi: "Nhân viên hỏi '試着しますか。'. Bạn muốn thử, trả lời thế nào?",
      options: [
        { id: 'o1', text: 'はい、お願いします。' },
        { id: 'o2', text: 'どのくらいかかりますか。' },
        { id: 'o3', text: 'お会計お願いします。' },
        { id: 'o4', text: '去年、旅行しました。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Đồng ý làm gì đó, cách trả lời tự nhiên và lịch sự nhất là 'はい、お願いします。'",
    },
  },
  {
    id: 'ja-a2-conv-making-plans',
    languageCode: 'ja',
    level: 'A2',
    title: '計画を立てる',
    titleVi: 'Lên kế hoạch và mời bạn',
    descriptionVi: 'Luyện hội thoại mời bạn bè và nói về kế hoạch tương lai bằng tiếng Nhật.',
    contextVi: 'Minh mời An đi xem phim vào cuối tuần.',
    dialogue: [
      { id: 'ja-a2-plans-turn-01', speaker: 'A', text: '今週末、映画を見に行きませんか。', translationVi: '(Konshuumatsu, eiga o mi ni ikimasen ka.) Cuối tuần này bạn có muốn đi xem phim không?' },
      { id: 'ja-a2-plans-turn-02', speaker: 'B', text: 'いいですね！何時ですか。', translationVi: '(Ii desu ne! Nanji desu ka.) Được đấy! Mấy giờ vậy?' },
      { id: 'ja-a2-plans-turn-03', speaker: 'A', text: '七時のチケットを買うつもりです。', translationVi: '(Shichiji no chiketto o kau tsumori desu.) Tôi định mua vé lúc 7 giờ.' },
      { id: 'ja-a2-plans-turn-04', speaker: 'B', text: 'いいですね、そこで会いましょう。', translationVi: '(Ii desu ne, soko de aimashou.) Được, gặp nhau ở đó nhé.' },
      { id: 'ja-a2-plans-turn-05', speaker: 'A', text: '新しいアクション映画を見ましたか。', translationVi: '(Atarashii akushon eiga o mimashita ka.) Bạn đã xem phim hành động mới chưa?' },
      { id: 'ja-a2-plans-turn-06', speaker: 'B', text: 'まだです。面白いと聞きました。', translationVi: '(Mada desu. Omoshiroi to kikimashita.) Chưa. Tôi nghe nói hay lắm.' },
      { id: 'ja-a2-plans-turn-07', speaker: 'A', text: 'ところで、来月も時間がありますか。', translationVi: '(Tokorode, raigetsu mo jikan ga arimasu ka.) À, tháng sau bạn có rảnh không?' },
      { id: 'ja-a2-plans-turn-08', speaker: 'B', text: 'すみません、旅行するので行けません。', translationVi: '(Sumimasen, ryokou suru node ikemasen.) Xin lỗi, vì đi du lịch nên tôi không đi được.' },
    ],
    relatedVocabularyIds: ['ja-a2-l3-2-v1', 'ja-a2-l3-2-v2', 'ja-a2-l3-2-v3', 'ja-a2-l3-2-v4'],
    task: {
      type: 'complete-reply',
      promptVi: "Hoàn thành câu trả lời phù hợp cho lời mời '見に行きませんか。'",
      options: [
        { id: 'o1', text: 'いいですね！' },
        { id: 'o2', text: 'いくらですか。' },
        { id: 'o3', text: '地下鉄に乗ります。' },
        { id: 'o4', text: '何時ですか。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi nhận lời mời một cách vui vẻ, cách trả lời tự nhiên là 'いいですね！'",
    },
  },
];
