import type { GrammarTopic } from '../../types';

export const japaneseA2GrammarTopics: GrammarTopic[] = [
  {
    id: 'ja-a2-gr-mashita',
    languageCode: 'ja',
    level: 'A2',
    title: 'ました',
    titleVi: 'Thì quá khứ lịch sự ました',
    explanationVi: "ました là dạng quá khứ lịch sự của ます, gắn vào gốc động từ dạng ます. Ví dụ: 食べます→食べました (đã ăn).",
    structure: '動詞(ます形) → ました',
    keyPoints: ['行きます → 行きました', '見ます → 見ました', "Phủ định quá khứ: ませんでした"],
    examples: [
      { id: 'ja-a2-gr-mashita-s1', text: '昨日、学校へ行きました。', translationVi: 'Hôm qua tôi đã đi học.' },
      { id: 'ja-a2-gr-mashita-s2', text: '昼ご飯を食べました。', translationVi: 'Tôi đã ăn trưa.' },
      { id: 'ja-a2-gr-mashita-s3', text: '昨日、テレビを見ませんでした。', translationVi: 'Hôm qua tôi đã không xem TV.' },
    ],
    commonMistakesVi: "Người mới học hay quên đổi ません thành ませんでした khi phủ định ở thì quá khứ.",
    exercises: [
      {
        id: 'ja-a2-gr-mashita-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng quá khứ đúng của '行きます'.",
        question: '昨日、学校へ___。',
        options: ['行きます', '行きました', '行っています', '行くつもりです'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-a2-gr-mashita-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng phủ định quá khứ đúng.',
        sentenceTemplate: '昨日、テレビを見___。',
        wordBank: ['ませんでした', 'ません', 'ました'],
        correctAnswer: 'ませんでした',
      },
      {
        id: 'ja-a2-gr-mashita-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đã ăn trưa."',
        words: ['食べました', '昼ご飯を'],
        correctOrder: ['昼ご飯を', '食べました'],
      },
    ],
  },
  {
    id: 'ja-a2-gr-teimasu',
    languageCode: 'ja',
    level: 'A2',
    title: 'ています',
    titleVi: 'Hành động đang diễn ra ています',
    explanationVi: "ています diễn tả hành động đang diễn ra hoặc trạng thái tiếp diễn, tương đương '-ing' trong tiếng Anh.",
    structure: '動詞(て形) + います',
    keyPoints: ['食べる → 食べています (đang ăn)', '勉強する → 勉強しています (đang học)', 'Cũng dùng cho trạng thái kéo dài: 住んでいます (đang sống ở...)'],
    examples: [
      { id: 'ja-a2-gr-teimasu-s1', text: '私は今、勉強しています。', translationVi: 'Tôi đang học bây giờ.' },
      { id: 'ja-a2-gr-teimasu-s2', text: '彼はご飯を食べています。', translationVi: 'Anh ấy đang ăn cơm.' },
      { id: 'ja-a2-gr-teimasu-s3', text: '私たちは映画を見ています。', translationVi: 'Chúng tôi đang xem phim.' },
    ],
    commonMistakesVi: "Người mới học hay nhầm ています (đang làm) với ました (đã làm).",
    exercises: [
      {
        id: 'ja-a2-gr-teimasu-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: hành động đang diễn ra.',
        question: '私は今、勉強___。',
        options: ['しました', 'しています', 'するつもりです', 'したいです'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-a2-gr-teimasu-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '彼はご飯を食べて___。',
        wordBank: ['います', 'した', 'から'],
        correctAnswer: 'います',
      },
      {
        id: 'ja-a2-gr-teimasu-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Chúng tôi đang xem phim."',
        words: ['見ています', '映画を', '私たちは'],
        correctOrder: ['私たちは', '映画を', '見ています'],
      },
    ],
  },
  {
    id: 'ja-a2-gr-tsumori',
    languageCode: 'ja',
    level: 'A2',
    title: 'つもりです',
    titleVi: 'Diễn tả dự định つもりです',
    explanationVi: "つもりです gắn sau động từ dạng nguyên thể (辞書形) để diễn tả dự định/ý định đã có từ trước.",
    structure: '動詞(辞書形) + つもりです',
    keyPoints: ['留学するつもりです (Tôi định đi du học)', '行かないつもりです (Tôi định không đi — phủ định)', 'Khác たいです: つもり là dự định cụ thể, たい là mong muốn chung chung'],
    examples: [
      { id: 'ja-a2-gr-tsumori-s1', text: '来年、日本へ行くつもりです。', translationVi: 'Năm sau tôi định đi Nhật Bản.' },
      { id: 'ja-a2-gr-tsumori-s2', text: '今日は勉強するつもりです。', translationVi: 'Hôm nay tôi định học bài.' },
      { id: 'ja-a2-gr-tsumori-s3', text: '週末は働かないつもりです。', translationVi: 'Cuối tuần tôi định không đi làm.' },
    ],
    commonMistakesVi: "Người mới học hay dùng dạng ます thay vì dạng từ điển (辞書形) trước つもりです.",
    exercises: [
      {
        id: 'ja-a2-gr-tsumori-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng để nói về dự định.',
        question: '来年、日本へ___つもりです。',
        options: ['行く', '行きます', '行った', '行って'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-a2-gr-tsumori-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '今日は勉強する___。',
        wordBank: ['つもりです', 'ています', 'ました'],
        correctAnswer: 'つもりです',
      },
      {
        id: 'ja-a2-gr-tsumori-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Năm sau tôi định đi Nhật Bản."',
        words: ['つもりです', '来年', '日本へ行く'],
        correctOrder: ['来年', '日本へ行く', 'つもりです'],
      },
    ],
  },
  {
    id: 'ja-a2-gr-kara-node',
    languageCode: 'ja',
    level: 'A2',
    title: 'から / ので',
    titleVi: 'Nối câu nguyên nhân-kết quả から/ので',
    explanationVi: "から và ので đều nghĩa là 'vì...nên...'. から mang tính chủ quan, thường dùng trong hội thoại thân mật; ので lịch sự và khách quan hơn.",
    structure: '理由 + から/ので + 結果',
    keyPoints: ['時間がないから、行けません (thân mật)', '時間がないので、行けません (lịch sự)', 'ので thường dùng khi giải thích lý do một cách lịch sự với người lạ'],
    examples: [
      { id: 'ja-a2-gr-karanode-s1', text: '時間がないので、行けません。', translationVi: 'Vì không có thời gian nên tôi không đi được.' },
      { id: 'ja-a2-gr-karanode-s2', text: '疲れたから、早く寝ました。', translationVi: 'Vì mệt nên tôi đã ngủ sớm.' },
      { id: 'ja-a2-gr-karanode-s3', text: 'お腹が空いたので、ご飯を食べました。', translationVi: 'Vì đói bụng nên tôi đã ăn cơm.' },
    ],
    commonMistakesVi: "Người mới học hay dùng ので trong văn nói thân mật quá trang trọng, hoặc から trong tình huống cần lịch sự.",
    exercises: [
      {
        id: 'ja-a2-gr-karanode-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ nối đúng (lịch sự) cho 'vì không có thời gian'.",
        question: '時間がない___、行けません。',
        options: ['ので', 'けど', 'より'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-a2-gr-karanode-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ nối còn thiếu (thân mật).',
        sentenceTemplate: '疲れた___、早く寝ました。',
        wordBank: ['から', 'ので', 'つもり'],
        correctAnswer: 'から',
      },
      {
        id: 'ja-a2-gr-karanode-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì đói bụng nên tôi đã ăn cơm."',
        words: ['食べました', 'お腹が空いたので', 'ご飯を'],
        correctOrder: ['お腹が空いたので', 'ご飯を', '食べました'],
      },
    ],
  },
  {
    id: 'ja-a2-gr-hou-ga',
    languageCode: 'ja',
    level: 'A2',
    title: 'ほうが / より',
    titleVi: 'So sánh hơn với より và ほうが',
    explanationVi: "より đặt sau danh từ để so sánh ('hơn'). ほうが thường dùng cùng より để nhấn mạnh lựa chọn tốt hơn: A のほうが B より + tính từ.",
    structure: 'A + は + B + より + 形容詞 / A のほうが B より + 形容詞',
    keyPoints: ['映画より音楽のほうが好きです (Tôi thích âm nhạc hơn phim)', '今日は昨日より寒いです (Hôm nay lạnh hơn hôm qua)', 'ほうが thường dùng khi so sánh trực tiếp 2 lựa chọn'],
    examples: [
      { id: 'ja-a2-gr-houga-s1', text: '今日は昨日より寒いです。', translationVi: 'Hôm nay lạnh hơn hôm qua.' },
      { id: 'ja-a2-gr-houga-s2', text: 'バスより電車のほうが速いです。', translationVi: 'Tàu điện nhanh hơn xe buýt.' },
      { id: 'ja-a2-gr-houga-s3', text: '弟は私より背が高いです。', translationVi: 'Em trai cao hơn tôi.' },
    ],
    commonMistakesVi: "Người mới học hay quên trật tự đúng, đặt より sai vị trí trong câu.",
    exercises: [
      {
        id: 'ja-a2-gr-houga-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ so sánh đúng.',
        question: '今日は昨日___寒いです。',
        options: ['より', 'から', 'ので'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-a2-gr-houga-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: 'バスより電車の___速いです。',
        wordBank: ['ほうが', 'つもりが', 'ので'],
        correctAnswer: 'ほうが',
      },
      {
        id: 'ja-a2-gr-houga-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Em trai cao hơn tôi."',
        words: ['背が高いです', '弟は', '私より'],
        correctOrder: ['弟は', '私より', '背が高いです'],
      },
    ],
  },
];
