import type { Lesson } from '../../../types';

export const koreanB1HonorificsLessons: Lesson[] = [
  {
    id: 'ko-b1-l3-1-honorific-si',
    unitId: 'ko-b1-u3-honorifics-reporting',
    title: '-(으)시-',
    titleVi: 'Kính ngữ chủ ngữ -(으)시-',
    objectiveVi: "Dùng kính ngữ chủ ngữ '-(으)시-' và trợ từ '께서' khi nói về người lớn tuổi hoặc cấp trên.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "동사/형용사 어간 + (으)시- thể hiện sự tôn trọng với chủ ngữ. 받침 없음: 시 (오다→오시다), 받침 있음: 으시 (읽다→읽으시다). Trợ từ chủ ngữ kính ngữ: 께서 (thay cho 이/가). Một số động từ có dạng kính ngữ đặc biệt: 먹다→드시다, 있다→계시다, 자다→주무시다, 말하다→말씀하시다.",
    vocabulary: [
      { id: 'ko-b1-l3-1-v1', term: '-(으)시-', translationVi: 'Kính ngữ chủ ngữ', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: (eu)si' },
      { id: 'ko-b1-l3-1-v2', term: '께서', translationVi: 'Trợ từ chủ ngữ kính ngữ (thay cho 이/가)', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l3-1-s1', usageNoteVi: 'Cách đọc: kkeseo' },
      { id: 'ko-b1-l3-1-v3', term: '드시다', translationVi: 'Dùng bữa (kính ngữ của 먹다/마시다)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l3-1-s1', usageNoteVi: 'Cách đọc: deusida' },
      { id: 'ko-b1-l3-1-v4', term: '계시다', translationVi: 'Có mặt, ở (kính ngữ của 있다)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l3-1-s2', usageNoteVi: 'Cách đọc: gyesida' },
      { id: 'ko-b1-l3-1-v5', term: '주무시다', translationVi: 'Ngủ (kính ngữ của 자다)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l3-1-s4', usageNoteVi: 'Cách đọc: jumusida' },
      { id: 'ko-b1-l3-1-v6', term: '말씀하시다', translationVi: 'Nói (kính ngữ của 말하다)', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: malsseumhasida' },
      { id: 'ko-b1-l3-1-v7', term: '연세', translationVi: 'Tuổi (kính ngữ của 나이)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: yeonse' },
      { id: 'ko-b1-l3-1-v8', term: '성함', translationVi: 'Tên (kính ngữ của 이름)', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l3-1-s5', usageNoteVi: 'Cách đọc: seongham' },
      { id: 'ko-b1-l3-1-v9', term: '사장님', translationVi: 'Giám đốc', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l3-1-s2', usageNoteVi: 'Cách đọc: sajangnim' },
      { id: 'ko-b1-l3-1-v10', term: '어르신', translationVi: 'Người lớn tuổi (cách gọi kính trọng)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: eoreusin' },
      { id: 'ko-b1-l3-1-v11', term: '편찮으시다', translationVi: 'Khó chịu trong người (kính ngữ của 아프다)', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: pyeonchaneusida' },
      { id: 'ko-b1-l3-1-v12', term: '뵙다', translationVi: 'Gặp (dạng khiêm nhường)', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: boepda' },
      { id: 'ko-b1-l3-1-v13', term: '존댓말', translationVi: 'Kính ngữ, cách nói lịch sự', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: jondaenmal' },
    ],
    sentences: [
      { id: 'ko-b1-l3-1-s1', text: '할머니께서 진지를 드세요.', translationVi: '(halmeonikkeseo jinjireul deuseyo.) Bà đang dùng bữa.' },
      { id: 'ko-b1-l3-1-s2', text: '사장님은 지금 회의실에 계세요.', translationVi: '(sajangnimeun jigeum hoeuisire gyeseyo.) Giám đốc hiện đang ở phòng họp.' },
      { id: 'ko-b1-l3-1-s3', text: '아버지께서 신문을 읽으세요.', translationVi: '(abeojikkeseo sinmuneul ilgeuseyo.) Bố đang đọc báo.' },
      { id: 'ko-b1-l3-1-s4', text: '할아버지께서는 일찍 주무세요.', translationVi: '(harabeojikkeseoneun iljjik jumuseyo.) Ông thường ngủ sớm.' },
      { id: 'ko-b1-l3-1-s5', text: '선생님, 성함이 어떻게 되세요?', translationVi: '(seonsaengnim, seonghami eotteoke doeseyo?) Thưa thầy/cô, tên của thầy/cô là gì ạ?' },
    ],
    exercises: [
      {
        id: 'ko-b1-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn trợ từ chủ ngữ kính ngữ đúng.',
        question: '할머니___ 진지를 드세요.',
        options: ['이', '가', '께서', '은'],
        correctOptionIndex: 2,
      },
      {
        id: 'ko-b1-l3-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng kính ngữ đúng của '있다'.",
        sentenceTemplate: '사장님은 지금 회의실에 ___.',
        wordBank: ['계세요', '있으세요', '있어요'],
        correctAnswer: '계세요',
        explanationVi: "'있다' có dạng kính ngữ đặc biệt là '계시다', không chia theo quy tắc thông thường.",
      },
      {
        id: 'ko-b1-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Bố đang đọc báo."',
        words: ['읽으세요', '아버지께서', '신문을'],
        correctOrder: ['아버지께서', '신문을', '읽으세요'],
      },
    ],
  },
  {
    id: 'ko-b1-l3-2-dago-hada',
    unitId: 'ko-b1-u3-honorifics-reporting',
    title: '-다고 하다',
    titleVi: 'Lời nói gián tiếp -다고 하다',
    objectiveVi: "Tường thuật lại lời nói của người khác bằng '-다고 하다'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "동사: -ㄴ/는다고 하다 (hiện tại), -았/었다고 하다 (quá khứ), -(으)ㄹ 거라고 하다 (tương lai). 형용사: -다고 하다. 명사: (이)라고 하다. Ví dụ: 바쁘다→바쁘다고 해요, 오다→올 거라고 해요, 학생→학생이라고 해요.",
    vocabulary: [
      { id: 'ko-b1-l3-2-v1', term: '다고 하다', translationVi: 'Nghe nói rằng, (ai đó) nói rằng', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: dago hada' },
      { id: 'ko-b1-l3-2-v2', term: '(이)라고 하다', translationVi: '(Ai đó) nói là (dùng cho danh từ)', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l3-2-s3', usageNoteVi: 'Cách đọc: (i)rago hada' },
      { id: 'ko-b1-l3-2-v3', term: '전하다', translationVi: 'Truyền đạt, chuyển lời', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l3-2-s5', usageNoteVi: 'Cách đọc: jeonhada' },
      { id: 'ko-b1-l3-2-v4', term: '소문', translationVi: 'Tin đồn', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: somun' },
      { id: 'ko-b1-l3-2-v5', term: '뉴스', translationVi: 'Tin tức', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l3-2-s4', usageNoteVi: 'Cách đọc: nyuseu' },
      { id: 'ko-b1-l3-2-v6', term: '발표하다', translationVi: 'Thông báo, công bố', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: balpyohada' },
      { id: 'ko-b1-l3-2-v7', term: '예보', translationVi: 'Dự báo', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l3-2-s2', usageNoteVi: 'Cách đọc: yebo' },
      { id: 'ko-b1-l3-2-v8', term: '알리다', translationVi: 'Báo cho biết', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: allida' },
      { id: 'ko-b1-l3-2-v9', term: '들리다', translationVi: 'Nghe được, nghe nói', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: deullida' },
      { id: 'ko-b1-l3-2-v10', term: '확인하다', translationVi: 'Xác nhận', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: hwaginhada' },
      { id: 'ko-b1-l3-2-v11', term: '정확하다', translationVi: 'Chính xác', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: jeonghwakhada' },
      { id: 'ko-b1-l3-2-v12', term: '메시지를 전달하다', translationVi: 'Chuyển tin nhắn', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: mesijireul jeondalhada' },
      { id: 'ko-b1-l3-2-v13', term: '인터뷰', translationVi: 'Phỏng vấn', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: inteobyu' },
    ],
    sentences: [
      { id: 'ko-b1-l3-2-s1', text: '친구가 오늘 바쁘다고 했어요.', translationVi: '(chinguga oneul bappeudago haesseoyo.) Bạn tôi nói rằng hôm nay bạn ấy bận.' },
      { id: 'ko-b1-l3-2-s2', text: '일기 예보에서 내일 비가 올 거라고 해요.', translationVi: '(ilgi yeboeseo naeil biga ol georago haeyo.) Dự báo thời tiết nói ngày mai trời sẽ mưa.' },
      { id: 'ko-b1-l3-2-s3', text: '그 사람은 자기가 학생이라고 했어요.', translationVi: '(geu sarameun jagiga haksaengirago haesseoyo.) Người đó nói rằng mình là học sinh.' },
      { id: 'ko-b1-l3-2-s4', text: '뉴스에서 물가가 올랐다고 발표했어요.', translationVi: '(nyuseueseo mulgaga ollatdago balpyohaesseoyo.) Tin tức thông báo rằng giá cả đã tăng.' },
      { id: 'ko-b1-l3-2-s5', text: '사장님께서 회의가 취소됐다고 전하셨어요.', translationVi: '(sajangnimkkeseo hoeuiga chwisodwaetdago jeonhasyeosseoyo.) Giám đốc đã truyền đạt rằng cuộc họp đã bị hủy.' },
    ],
    exercises: [
      {
        id: 'ko-b1-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng tường thuật đúng ở thì tương lai.',
        question: '일기 예보에서 내일 비가 ___ 해요.',
        options: ['온다고', '올 거라고', '왔다고', '오는 것 같다고'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-l3-2-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng tường thuật đúng của tính từ '바쁘다'.",
        sentenceTemplate: '친구가 오늘 ___ 했어요.',
        wordBank: ['바쁘다고', '바빠서', '바쁜데'],
        correctAnswer: '바쁘다고',
      },
      {
        id: 'ko-b1-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Người đó nói rằng mình là học sinh."',
        words: ['학생이라고', '그 사람은', '했어요', '자기가'],
        correctOrder: ['그 사람은', '자기가', '학생이라고', '했어요'],
      },
    ],
  },
];
