import type { Lesson } from '../../../types';

export const koreanB1OpinionsLessons: Lesson[] = [
  {
    id: 'ko-b1-l1-1-geot-gatda',
    unitId: 'ko-b1-u1-opinions-reasons',
    title: '것 같다',
    titleVi: 'Phỏng đoán 것 같다',
    objectiveVi: "Nêu phỏng đoán, nhận định dựa trên quan sát bằng '것 같다'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "동사 + 는 것 같다 (phỏng đoán về hành động), 형용사 + (으)ㄴ 것 같다 (phỏng đoán về trạng thái), 명사 + 인 것 같다. Ví dụ: 오다→오는 것 같다, 맵다→매운 것 같다, 학생→학생인 것 같다.",
    vocabulary: [
      { id: 'ko-b1-l1-1-v1', term: '것 같다', translationVi: 'Có vẻ như, hình như', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: geot gatda' },
      { id: 'ko-b1-l1-1-v2', term: '아마', translationVi: 'Có lẽ', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l1-1-s5', usageNoteVi: 'Cách đọc: ama' },
      { id: 'ko-b1-l1-1-v3', term: '확실히', translationVi: 'Chắc chắn', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: hwaksilhi' },
      { id: 'ko-b1-l1-1-v4', term: '표정', translationVi: 'Biểu cảm khuôn mặt', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l1-1-s4', usageNoteVi: 'Cách đọc: pyojeong' },
      { id: 'ko-b1-l1-1-v5', term: '분위기', translationVi: 'Bầu không khí', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: bunwigi' },
      { id: 'ko-b1-l1-1-v6', term: '피곤해 보이다', translationVi: 'Trông có vẻ mệt', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l1-1-s2', usageNoteVi: 'Cách đọc: pigonhae boida' },
      { id: 'ko-b1-l1-1-v7', term: '짐작하다', translationVi: 'Phỏng đoán', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: jimjakhada' },
      { id: 'ko-b1-l1-1-v8', term: '눈치채다', translationVi: 'Nhận ra, để ý thấy', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: nunchichaeda' },
      { id: 'ko-b1-l1-1-v9', term: '아무래도', translationVi: 'Dù sao thì, có lẽ là', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: amuraedo' },
      { id: 'ko-b1-l1-1-v10', term: '상황', translationVi: 'Tình huống', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: sanghwang' },
      { id: 'ko-b1-l1-1-v11', term: '이상하다', translationVi: 'Kỳ lạ', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b1-l1-1-s3', usageNoteVi: 'Cách đọc: isanghada' },
      { id: 'ko-b1-l1-1-v12', term: '최근', translationVi: 'Gần đây', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: choegeun' },
      { id: 'ko-b1-l1-1-v13', term: '힘들다', translationVi: 'Vất vả, khó khăn', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: himdeulda' },
    ],
    sentences: [
      { id: 'ko-b1-l1-1-s1', text: '하늘을 보니까 비가 오는 것 같아요.', translationVi: '(haneureul bonikka biga oneun geot gatayo.) Nhìn trời có vẻ như trời sắp mưa.' },
      { id: 'ko-b1-l1-1-s2', text: '그 사람은 요즘 많이 피곤해 보여요.', translationVi: '(geu sarameun yojeum mani pigonhae boyeoyo.) Dạo này người đó trông có vẻ rất mệt.' },
      { id: 'ko-b1-l1-1-s3', text: '표정을 보니까 뭔가 이상한 것 같아요.', translationVi: '(pyojeongeul bonikka mwonga isanghan geot gatayo.) Nhìn biểu cảm có vẻ như có gì đó kỳ lạ.' },
      { id: 'ko-b1-l1-1-s4', text: '이 라면은 좀 매운 것 같아요.', translationVi: '(i ramyeoneun jom maeun geot gatayo.) Mì này có vẻ hơi cay.' },
      { id: 'ko-b1-l1-1-s5', text: '아마 그 사람은 학생인 것 같아요.', translationVi: '(ama geu sarameun haksaengin geot gatayo.) Có lẽ người đó là học sinh.' },
    ],
    exercises: [
      {
        id: 'ko-b1-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng phỏng đoán đúng cho '오다' (trời có vẻ sắp mưa).",
        question: '하늘이 흐려요. 비가 ___.',
        options: ['와요', '온 것 같아요', '오는 것 같아요', '왔어요'],
        correctOptionIndex: 2,
        explanationVi: "Động từ ở thì hiện tại dùng '는 것 같다', nên 오다 → 오는 것 같아요.",
      },
      {
        id: 'ko-b1-l1-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng phỏng đoán đúng của tính từ '맵다'.",
        sentenceTemplate: '이 라면은 좀 ___.',
        wordBank: ['매운 것 같아요', '매워요', '매웠어요'],
        correctAnswer: '매운 것 같아요',
      },
      {
        id: 'ko-b1-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Có lẽ người đó là học sinh."',
        words: ['것 같아요', '학생인', '그 사람은'],
        correctOrder: ['그 사람은', '학생인', '것 같아요'],
      },
    ],
  },
  {
    id: 'ko-b1-l1-2-gi-ttaemune',
    unitId: 'ko-b1-u1-opinions-reasons',
    title: '기 때문에',
    titleVi: 'Nguyên nhân trang trọng 기 때문에',
    objectiveVi: "Giải thích nguyên nhân-kết quả một cách trang trọng bằng '기 때문에', dùng được cả với danh từ.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "동사/형용사 어간 + 기 때문에, hoặc 명사 + 때문에. Trang trọng hơn 아/어서, thường dùng trong văn viết và giải thích rõ ràng. Ví dụ: 오다→오기 때문에, 시험→시험 때문에.",
    vocabulary: [
      { id: 'ko-b1-l1-2-v1', term: '때문에', translationVi: 'Vì, do (nguyên nhân)', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l1-2-s2', usageNoteVi: 'Cách đọc: ttaemune' },
      { id: 'ko-b1-l1-2-v2', term: '원인', translationVi: 'Nguyên nhân', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: wonin' },
      { id: 'ko-b1-l1-2-v3', term: '결과', translationVi: 'Kết quả', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: gyeolgwa' },
      { id: 'ko-b1-l1-2-v4', term: '스트레스를 받다', translationVi: 'Bị căng thẳng', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: seuteureseureul batda' },
      { id: 'ko-b1-l1-2-v5', term: '지각하다', translationVi: 'Đi trễ, đến muộn', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l1-2-s3', usageNoteVi: 'Cách đọc: jigakhada' },
      { id: 'ko-b1-l1-2-v6', term: '감기에 걸리다', translationVi: 'Bị cảm', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: gamgie geollida' },
      { id: 'ko-b1-l1-2-v7', term: '야근하다', translationVi: 'Làm thêm giờ, tăng ca', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l1-2-s5', usageNoteVi: 'Cách đọc: yageunhada' },
      { id: 'ko-b1-l1-2-v8', term: '교통 체증', translationVi: 'Kẹt xe', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l1-2-s4', usageNoteVi: 'Cách đọc: gyotong chejeung' },
      { id: 'ko-b1-l1-2-v9', term: '마감', translationVi: 'Hạn chót', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: magam' },
      { id: 'ko-b1-l1-2-v10', term: '부담스럽다', translationVi: 'Cảm thấy áp lực', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: budamseureopda' },
      { id: 'ko-b1-l1-2-v11', term: '이유', translationVi: 'Lý do', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: iyu' },
      { id: 'ko-b1-l1-2-v12', term: '실수하다', translationVi: 'Phạm sai lầm', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: silsuhada' },
      { id: 'ko-b1-l1-2-v13', term: '미루다', translationVi: 'Trì hoãn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: miruda' },
    ],
    sentences: [
      { id: 'ko-b1-l1-2-s1', text: '비가 오기 때문에 우산을 가져가야 해요.', translationVi: '(biga ogi ttaemune usaneul gajyeogaya haeyo.) Vì trời mưa nên phải mang theo ô.' },
      { id: 'ko-b1-l1-2-s2', text: '시험 때문에 요즘 스트레스를 많이 받아요.', translationVi: '(siheom ttaemune yojeum seuteureseureul mani badayo.) Vì kỳ thi nên dạo này tôi bị căng thẳng nhiều.' },
      { id: 'ko-b1-l1-2-s3', text: '늦게 일어났기 때문에 학교에 지각했어요.', translationVi: '(neutge ireonatgi ttaemune hakgyoe jigakhaesseoyo.) Vì dậy muộn nên tôi đã đi học trễ.' },
      { id: 'ko-b1-l1-2-s4', text: '교통 체증 때문에 회의에 늦었어요.', translationVi: '(gyotong chejeung ttaemune hoeuie neujeosseoyo.) Vì kẹt xe nên tôi đã đến trễ cuộc họp.' },
      { id: 'ko-b1-l1-2-s5', text: '마감이 얼마 안 남았기 때문에 오늘 야근해야 해요.', translationVi: '(magami eolma an namatgi ttaemune oneul yageunhaeya haeyo.) Vì gần đến hạn chót nên hôm nay tôi phải tăng ca.' },
    ],
    exercises: [
      {
        id: 'ko-b1-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng khi nguyên nhân là một danh từ.",
        question: '시험 ___ 스트레스를 많이 받아요.',
        options: ['때문에', '기 때문에', '아서', '지만'],
        correctOptionIndex: 0,
        explanationVi: "Danh từ đi trực tiếp với '때문에', không cần thêm '기'.",
      },
      {
        id: 'ko-b1-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng cho động từ ở thì quá khứ.',
        sentenceTemplate: '늦게 일어났___ 학교에 지각했어요.',
        wordBank: ['기 때문에', '아서요', '지만'],
        correctAnswer: '기 때문에',
      },
      {
        id: 'ko-b1-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì kẹt xe nên tôi đã đến trễ cuộc họp."',
        words: ['늦었어요', '교통 체증', '회의에', '때문에'],
        correctOrder: ['교통 체증', '때문에', '회의에', '늦었어요'],
      },
    ],
  },
  {
    id: 'ko-b1-l1-3-neunde',
    unitId: 'ko-b1-u1-opinions-reasons',
    title: '는데',
    titleVi: 'Nối câu nêu bối cảnh 는데',
    objectiveVi: "Nêu bối cảnh trước khi nói tiếp, hoặc thể hiện sự tương phản nhẹ bằng '는데/(으)ㄴ데'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사 + 는데, 형용사 + (으)ㄴ데, 명사 + 인데. Dùng để giới thiệu bối cảnh trước khi đưa ra thông tin/yêu cầu tiếp theo, hoặc thể hiện đối lập nhẹ nhàng hơn 지만. Ví dụ: 오다→오는데, 예쁘다→예쁜데, 학생→학생인데.",
    vocabulary: [
      { id: 'ko-b1-l1-3-v1', term: '는데/(으)ㄴ데', translationVi: 'Nhưng, mà (nêu bối cảnh)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: neunde' },
      { id: 'ko-b1-l1-3-v2', term: '아르바이트', translationVi: 'Việc làm thêm', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l1-3-s3', usageNoteVi: 'Cách đọc: areubaiteu' },
      { id: 'ko-b1-l1-3-v3', term: '우산', translationVi: 'Cái ô, cái dù', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l1-3-s1', usageNoteVi: 'Cách đọc: usan' },
      { id: 'ko-b1-l1-3-v4', term: '사실은', translationVi: 'Thực ra thì', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l1-3-s5', usageNoteVi: 'Cách đọc: sasireun' },
      { id: 'ko-b1-l1-3-v5', term: '그런데', translationVi: 'Tuy nhiên, nhưng mà', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: geureonde' },
      { id: 'ko-b1-l1-3-v6', term: '배경', translationVi: 'Bối cảnh', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: baegyeong' },
      { id: 'ko-b1-l1-3-v7', term: '초대하다', translationVi: 'Mời', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: chodaehada' },
      { id: 'ko-b1-l1-3-v8', term: '약속이 있다', translationVi: 'Có hẹn', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l1-3-s4', usageNoteVi: 'Cách đọc: yaksogi itda' },
      { id: 'ko-b1-l1-3-v9', term: '미리', translationVi: 'Trước, sẵn', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: miri' },
      { id: 'ko-b1-l1-3-v10', term: '갑자기', translationVi: 'Đột nhiên', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: gapjagi' },
      { id: 'ko-b1-l1-3-v11', term: '부탁하다', translationVi: 'Nhờ vả', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: butakhada' },
      { id: 'ko-b1-l1-3-v12', term: '괜찮다', translationVi: 'Ổn, không sao', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: gwaenchanta' },
      { id: 'ko-b1-l1-3-v13', term: '아쉽다', translationVi: 'Tiếc nuối', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: aswipda' },
    ],
    sentences: [
      { id: 'ko-b1-l1-3-s1', text: '밖에 비가 오는데 우산이 없어요.', translationVi: '(bakke biga oneunde usani eopseoyo.) Bên ngoài đang mưa nhưng tôi không có ô.' },
      { id: 'ko-b1-l1-3-s2', text: '이 옷은 예쁜데 좀 비싸요.', translationVi: '(i oseun yeppeunde jom bissayo.) Bộ đồ này đẹp nhưng hơi đắt.' },
      { id: 'ko-b1-l1-3-s3', text: '저는 학생인데 아르바이트도 해요.', translationVi: '(jeoneun haksaenginde areubaiteudo haeyo.) Tôi là học sinh, nhưng tôi cũng làm thêm.' },
      { id: 'ko-b1-l1-3-s4', text: '오늘 파티에 가고 싶은데 약속이 있어요.', translationVi: '(oneul patie gago sipeunde yaksogi isseoyo.) Hôm nay tôi muốn đi dự tiệc nhưng tôi có hẹn rồi.' },
      { id: 'ko-b1-l1-3-s5', text: '사실은 배가 고픈데 지금 시간이 없어요.', translationVi: '(sasireun baega gopeunde jigeum sigani eopseoyo.) Thực ra thì tôi đang đói bụng nhưng bây giờ không có thời gian.' },
    ],
    exercises: [
      {
        id: 'ko-b1-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng của tính từ '예쁘다' để nối câu tương phản nhẹ.",
        question: '이 옷은 ___ 좀 비싸요.',
        options: ['예뻐서', '예쁜데', '예쁘기 때문에', '예뻤어요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng của động từ.',
        sentenceTemplate: '밖에 비가 ___ 우산이 없어요.',
        wordBank: ['오는데', '와서', '오지만'],
        correctAnswer: '오는데',
      },
      {
        id: 'ko-b1-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi là học sinh, nhưng tôi cũng làm thêm."',
        words: ['아르바이트도', '학생인데', '저는', '해요'],
        correctOrder: ['저는', '학생인데', '아르바이트도', '해요'],
      },
    ],
  },
];
