import type { Lesson } from '../../../types';

export const koreanB1PlansLessons: Lesson[] = [
  {
    id: 'ko-b1-l2-1-ryeogo-hada',
    unitId: 'ko-b1-u2-plans-decisions',
    title: '(으)려고 하다',
    titleVi: 'Dự định (으)려고 하다',
    objectiveVi: "Diễn tả dự định, ý định làm gì đó (chưa chắc chắn bằng quyết định cuối cùng) bằng '(으)려고 하다'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "동사 어간 + (으)려고 하다: không받침/ㄹ받침 thêm 려고 하다, có받침 thêm 으려고 하다. Diễn tả dự định. Ví dụ: 가다→가려고 해요, 먹다→먹으려고 해요.",
    vocabulary: [
      { id: 'ko-b1-l2-1-v1', term: '(으)려고 하다', translationVi: 'Định làm gì đó', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: (eu)ryeogo hada' },
      { id: 'ko-b1-l2-1-v2', term: '계획을 세우다', translationVi: 'Lập kế hoạch', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l2-1-s5', usageNoteVi: 'Cách đọc: gyehoegeul seuuda' },
      { id: 'ko-b1-l2-1-v3', term: '이사하다', translationVi: 'Chuyển nhà', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l2-1-s3', usageNoteVi: 'Cách đọc: isahada' },
      { id: 'ko-b1-l2-1-v4', term: '취직하다', translationVi: 'Xin được việc làm', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: chwijikhada' },
      { id: 'ko-b1-l2-1-v5', term: '유학 가다', translationVi: 'Đi du học', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: yuhak gada' },
      { id: 'ko-b1-l2-1-v6', term: '결심하다', translationVi: 'Quyết tâm', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: gyeolsimhada' },
      { id: 'ko-b1-l2-1-v7', term: '목표', translationVi: 'Mục tiêu', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: mokpyo' },
      { id: 'ko-b1-l2-1-v8', term: '저축하다', translationVi: 'Tiết kiệm (tiền)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l2-1-s4', usageNoteVi: 'Cách đọc: jeochukhada' },
      { id: 'ko-b1-l2-1-v9', term: '자격증', translationVi: 'Chứng chỉ', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l2-1-s2', usageNoteVi: 'Cách đọc: jagyeokjeung' },
      { id: 'ko-b1-l2-1-v10', term: '준비하다', translationVi: 'Chuẩn bị', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: junbihada' },
      { id: 'ko-b1-l2-1-v11', term: '도전하다', translationVi: 'Thử sức, thử thách bản thân', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: dojeonhada' },
      { id: 'ko-b1-l2-1-v12', term: '앞으로', translationVi: 'Từ nay về sau, sắp tới', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: apeuro' },
      { id: 'ko-b1-l2-1-v13', term: '다짐하다', translationVi: 'Tự hứa với bản thân', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: dajimhada' },
    ],
    sentences: [
      { id: 'ko-b1-l2-1-s1', text: '이번 주말에 여행을 가려고 해요.', translationVi: '(ibeon jumare yeohaengeul garyeogo haeyo.) Cuối tuần này tôi định đi du lịch.' },
      { id: 'ko-b1-l2-1-s2', text: '한국어 자격증 시험에 도전하려고 해요.', translationVi: '(hangugeo jagyeokjeung siheome dojeonharyeogo haeyo.) Tôi định thử sức với kỳ thi chứng chỉ tiếng Hàn.' },
      { id: 'ko-b1-l2-1-s3', text: '다음 달에 이사하려고 해요.', translationVi: '(daeum dare isaharyeogo haeyo.) Tháng sau tôi định chuyển nhà.' },
      { id: 'ko-b1-l2-1-s4', text: '앞으로 돈을 더 저축하려고 해요.', translationVi: '(apeuro doneul deo jeochukharyeogo haeyo.) Từ nay tôi định tiết kiệm tiền nhiều hơn.' },
      { id: 'ko-b1-l2-1-s5', text: '저는 내년에 유학 가려고 계획을 세우고 있어요.', translationVi: '(jeoneun naenyeone yuhak garyeogo gyehoegeul seuugo isseoyo.) Tôi đang lập kế hoạch để đi du học vào năm sau.' },
    ],
    exercises: [
      {
        id: 'ko-b1-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng thể hiện dự định của '이사하다'.",
        question: '다음 달에 ___.',
        options: ['이사해요', '이사하려고 해요', '이사했어요', '이사하는 것 같아요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-l2-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng đúng của '도전하다'.",
        sentenceTemplate: '한국어 자격증 시험에 ___.',
        wordBank: ['도전하려고 해요', '도전해서', '도전하는데'],
        correctAnswer: '도전하려고 해요',
      },
      {
        id: 'ko-b1-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Cuối tuần này tôi định đi du lịch."',
        words: ['가려고 해요', '이번 주말에', '여행을'],
        correctOrder: ['이번 주말에', '여행을', '가려고 해요'],
      },
    ],
  },
  {
    id: 'ko-b1-l2-2-giro-hada',
    unitId: 'ko-b1-u2-plans-decisions',
    title: '기로 하다',
    titleVi: 'Quyết định 기로 하다',
    objectiveVi: "Diễn tả một quyết định đã chốt (của bản thân hoặc thỏa thuận với người khác) bằng '기로 하다'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사 어간 + 기로 하다: nhấn mạnh quyết định đã chốt, chắc chắn hơn (으)려고 하다. Ví dụ: 운동하다→운동하기로 했어요, 만나다→만나기로 했어요.",
    vocabulary: [
      { id: 'ko-b1-l2-2-v1', term: '기로 하다', translationVi: 'Quyết định làm gì (đã chốt)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: giro hada' },
      { id: 'ko-b1-l2-2-v2', term: '다이어트', translationVi: 'Ăn kiêng, giảm cân', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: daieoteu' },
      { id: 'ko-b1-l2-2-v3', term: '담배를 끊다', translationVi: 'Bỏ/cai thuốc lá', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l2-2-s3', usageNoteVi: 'Cách đọc: dambaereul kkeunta' },
      { id: 'ko-b1-l2-2-v4', term: '약속하다', translationVi: 'Hứa, hẹn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: yaksokhada' },
      { id: 'ko-b1-l2-2-v5', term: '결정하다', translationVi: 'Quyết định', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: gyeoljeonghada' },
      { id: 'ko-b1-l2-2-v6', term: '헤어지다', translationVi: 'Chia tay', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: heeojida' },
      { id: 'ko-b1-l2-2-v7', term: '화해하다', translationVi: 'Làm hòa', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l2-2-s4', usageNoteVi: 'Cách đọc: hwahaehada' },
      { id: 'ko-b1-l2-2-v8', term: '습관', translationVi: 'Thói quen', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: seupgwan' },
      { id: 'ko-b1-l2-2-v9', term: '규칙적으로', translationVi: 'Một cách đều đặn', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: gyuchikjeogeuro' },
      { id: 'ko-b1-l2-2-v10', term: '그만두다', translationVi: 'Dừng lại, bỏ (việc/thói quen)', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: geumanduda' },
      { id: 'ko-b1-l2-2-v11', term: '마음을 먹다', translationVi: 'Quyết tâm, nhất quyết', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: maeumeul meokda' },
      { id: 'ko-b1-l2-2-v12', term: '절약하다', translationVi: 'Tiết kiệm (chi tiêu)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l2-2-s5', usageNoteVi: 'Cách đọc: jeoryakhada' },
      { id: 'ko-b1-l2-2-v13', term: '합의하다', translationVi: 'Đồng thuận, thỏa thuận', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: habuihada' },
    ],
    sentences: [
      { id: 'ko-b1-l2-2-s1', text: '저는 매일 운동하기로 했어요.', translationVi: '(jeoneun maeil undonghagiro haesseoyo.) Tôi đã quyết định tập thể dục mỗi ngày.' },
      { id: 'ko-b1-l2-2-s2', text: '우리는 내일 오후에 만나기로 했어요.', translationVi: '(urineun naeil ohue mannagiro haesseoyo.) Chúng tôi đã hẹn gặp nhau vào chiều mai.' },
      { id: 'ko-b1-l2-2-s3', text: '올해는 담배를 끊기로 결심했어요.', translationVi: '(olhaeneun dambaereul kkeunkkigiro gyeolsimhaesseoyo.) Năm nay tôi đã quyết tâm bỏ thuốc lá.' },
      { id: 'ko-b1-l2-2-s4', text: '두 사람은 화해하기로 했어요.', translationVi: '(du sarameun hwahaehagiro haesseoyo.) Hai người đã quyết định làm hòa.' },
      { id: 'ko-b1-l2-2-s5', text: '이제부터 돈을 절약하기로 했어요.', translationVi: '(ijebuteo doneul jeoryakhagiro haesseoyo.) Từ giờ tôi đã quyết định tiết kiệm tiền.' },
    ],
    exercises: [
      {
        id: 'ko-b1-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng: quyết định đã chốt để gặp nhau.",
        question: '우리는 내일 오후에 ___.',
        options: ['만나요', '만나기로 했어요', '만날 거예요', '만나는 것 같아요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-l2-2-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng đúng của '끊다'.",
        sentenceTemplate: '올해는 담배를 ___ 결심했어요.',
        wordBank: ['끊기로', '끊어서', '끊는데'],
        correctAnswer: '끊기로',
      },
      {
        id: 'ko-b1-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đã quyết định tập thể dục mỗi ngày."',
        words: ['운동하기로', '저는', '매일', '했어요'],
        correctOrder: ['저는', '매일', '운동하기로', '했어요'],
      },
    ],
  },
  {
    id: 'ko-b1-l2-3-lkka-hada',
    unitId: 'ko-b1-u2-plans-decisions',
    title: '(으)ㄹ까 하다',
    titleVi: 'Ý định đang cân nhắc (으)ㄹ까 하다',
    objectiveVi: "Diễn tả một ý định chưa chắc chắn, đang cân nhắc bằng '(으)ㄹ까 하다'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사 어간 + (으)ㄹ까 하다: diễn tả ý định chưa chắc chắn, nhẹ hơn (으)려고 하다 và 기로 하다, có thể thay đổi. Ví dụ: 가다→갈까 해요, 먹다→먹을까 해요.",
    vocabulary: [
      { id: 'ko-b1-l2-3-v1', term: '(으)ㄹ까 하다', translationVi: 'Đang cân nhắc, có ý định (chưa chắc)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: (eu)lkka hada' },
      { id: 'ko-b1-l2-3-v2', term: '고민하다', translationVi: 'Đắn đo, trăn trở', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l2-3-s2', usageNoteVi: 'Cách đọc: gominhada' },
      { id: 'ko-b1-l2-3-v3', term: '망설이다', translationVi: 'Do dự', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: mangseorida' },
      { id: 'ko-b1-l2-3-v4', term: '방학', translationVi: 'Kỳ nghỉ (học sinh, sinh viên)', partOfSpeech: 'noun', exampleSentenceId: 'ko-b1-l2-3-s1', usageNoteVi: 'Cách đọc: banghak' },
      { id: 'ko-b1-l2-3-v5', term: '선택하다', translationVi: 'Lựa chọn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: seontaekhada' },
      { id: 'ko-b1-l2-3-v6', term: '취미를 시작하다', translationVi: 'Bắt đầu một sở thích', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l2-3-s3', usageNoteVi: 'Cách đọc: chwimireul sijakhada' },
      { id: 'ko-b1-l2-3-v7', term: '아직 결정 못 했다', translationVi: 'Vẫn chưa quyết định được', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b1-l2-3-s4', usageNoteVi: 'Cách đọc: ajik gyeoljeong mot haetda' },
      { id: 'ko-b1-l2-3-v8', term: '고려하다', translationVi: 'Cân nhắc, xem xét', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: goryeohada' },
      { id: 'ko-b1-l2-3-v9', term: '새롭다', translationVi: 'Mới mẻ', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: saeropda' },
      { id: 'ko-b1-l2-3-v10', term: '여행지', translationVi: 'Điểm đến du lịch', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: yeohaengji' },
      { id: 'ko-b1-l2-3-v11', term: '옵션', translationVi: 'Lựa chọn, phương án', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: opsyeon' },
      { id: 'ko-b1-l2-3-v12', term: '바꾸다', translationVi: 'Thay đổi', partOfSpeech: 'verb', exampleSentenceId: 'ko-b1-l2-3-s5', usageNoteVi: 'Cách đọc: bakkuda' },
      { id: 'ko-b1-l2-3-v13', term: '잠깐', translationVi: 'Một lát, một chút', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: jamkkan' },
    ],
    sentences: [
      { id: 'ko-b1-l2-3-s1', text: '이번 방학에 부산에 갈까 해요.', translationVi: '(ibeon banghage busane galkka haeyo.) Kỳ nghỉ này tôi đang nghĩ là sẽ đi Busan.' },
      { id: 'ko-b1-l2-3-s2', text: '저녁에 뭘 먹을까 고민하고 있어요.', translationVi: '(jeonyeoge mwol meogeulkka gominhago isseoyo.) Tôi đang đắn đo không biết tối nay ăn gì.' },
      { id: 'ko-b1-l2-3-s3', text: '새로운 취미를 시작할까 해요.', translationVi: '(saeroun chwimireul sijakhalkka haeyo.) Tôi đang nghĩ đến việc bắt đầu một sở thích mới.' },
      { id: 'ko-b1-l2-3-s4', text: '아직 여행지를 결정 못 했어요.', translationVi: '(ajik yeohaengjireul gyeoljeong mot haesseoyo.) Tôi vẫn chưa quyết định được điểm đến du lịch.' },
      { id: 'ko-b1-l2-3-s5', text: '계획을 좀 바꿀까 해요.', translationVi: '(gyehoegeul jom bakkulkka haeyo.) Tôi đang nghĩ đến việc thay đổi kế hoạch một chút.' },
    ],
    exercises: [
      {
        id: 'ko-b1-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: ý định chưa chắc chắn, đang cân nhắc.',
        question: '이번 방학에 부산에 ___.',
        options: ['가요', '갈까 해요', '가기로 했어요', '갔어요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-l2-3-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng đúng của '시작하다'.",
        sentenceTemplate: '새로운 취미를 ___.',
        wordBank: ['시작할까 해요', '시작해서', '시작하는데'],
        correctAnswer: '시작할까 해요',
      },
      {
        id: 'ko-b1-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đang đắn đo không biết tối nay ăn gì."',
        words: ['먹을까', '저녁에', '고민하고 있어요', '뭘'],
        correctOrder: ['저녁에', '뭘', '먹을까', '고민하고 있어요'],
      },
    ],
  },
];
