import type { Lesson } from '../../../types';

export const englishB1DescribingLessons: Lesson[] = [
  {
    id: 'en-b1-l3-1-describing-people-things',
    unitId: 'en-b1-u3-describing-reporting',
    title: 'Describing people and things',
    titleVi: 'Mô tả người và sự vật',
    objectiveVi: 'Mô tả người, vật và nơi chốn chi tiết hơn bằng mệnh đề quan hệ xác định (defining relative clauses).',
    estimatedMinutes: 8,
    grammarNoteVi:
      "Mệnh đề quan hệ xác định bổ nghĩa cho danh từ đứng trước, dùng who/that (người), which/that (vật), where (nơi chốn): 'The woman who lives next door is a doctor.' Không dùng dấu phẩy khi mệnh đề là thông tin cần thiết để xác định danh từ.",
    vocabulary: [
      { id: 'en-b1-l3-1-v1', term: 'who', translationVi: 'Người mà (đại từ quan hệ chỉ người)', partOfSpeech: 'pronoun', exampleSentenceId: 'en-b1-l3-1-s1' },
      { id: 'en-b1-l3-1-v2', term: 'which', translationVi: 'Cái mà (đại từ quan hệ chỉ vật)', partOfSpeech: 'pronoun', exampleSentenceId: 'en-b1-l3-1-s2' },
      { id: 'en-b1-l3-1-v3', term: 'that', translationVi: 'Mà (thay cho who/which trong mệnh đề xác định)', partOfSpeech: 'pronoun' },
      { id: 'en-b1-l3-1-v4', term: 'where', translationVi: 'Nơi mà', partOfSpeech: 'pronoun', exampleSentenceId: 'en-b1-l3-1-s3' },
      { id: 'en-b1-l3-1-v5', term: 'whose', translationVi: 'Của người/vật mà (chỉ sở hữu)', partOfSpeech: 'pronoun' },
      { id: 'en-b1-l3-1-v6', term: 'neighbor', translationVi: 'Hàng xóm', partOfSpeech: 'noun' },
      { id: 'en-b1-l3-1-v7', term: 'reliable', translationVi: 'Đáng tin cậy', partOfSpeech: 'adjective' },
      { id: 'en-b1-l3-1-v8', term: 'colleague', translationVi: 'Đồng nghiệp', partOfSpeech: 'noun', exampleSentenceId: 'en-b1-l3-1-s4' },
      { id: 'en-b1-l3-1-v9', term: 'device', translationVi: 'Thiết bị', partOfSpeech: 'noun' },
      { id: 'en-b1-l3-1-v10', term: 'located', translationVi: 'Nằm ở, tọa lạc', partOfSpeech: 'adjective' },
      { id: 'en-b1-l3-1-v11', term: 'skill set', translationVi: 'Bộ kỹ năng', partOfSpeech: 'noun' },
      { id: 'en-b1-l3-1-v12', term: 'grew up', translationVi: 'Lớn lên', partOfSpeech: 'verb' },
      { id: 'en-b1-l3-1-v13', term: 'accurate', translationVi: 'Chính xác', partOfSpeech: 'adjective' },
    ],
    sentences: [
      { id: 'en-b1-l3-1-s1', text: "The woman who lives next door is a doctor.", translationVi: 'Người phụ nữ sống bên cạnh là bác sĩ.' },
      { id: 'en-b1-l3-1-s2', text: "This is the device which broke down last week.", translationVi: 'Đây là thiết bị đã hỏng vào tuần trước.' },
      { id: 'en-b1-l3-1-s3', text: "That's the town where I grew up.", translationVi: 'Đó là thị trấn nơi tôi đã lớn lên.' },
      { id: 'en-b1-l3-1-s4', text: "He's a colleague whose advice I always trust.", translationVi: 'Anh ấy là đồng nghiệp mà tôi luôn tin tưởng lời khuyên.' },
    ],
    exercises: [
      {
        id: 'en-b1-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn đại từ quan hệ đúng cho người.',
        question: 'The man ___ called yesterday is my new manager.',
        options: ['which', 'who', 'where', 'whose'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-b1-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền đại từ quan hệ đúng cho nơi chốn.',
        sentenceTemplate: "That's the café ___ we first met.",
        wordBank: ['where', 'who', 'which'],
        correctAnswer: 'where',
      },
      {
        id: 'en-b1-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['a doctor', 'is', 'who', 'next door', 'lives', 'the woman'],
        correctOrder: ['the woman', 'who', 'lives', 'next door', 'is', 'a doctor'],
      },
    ],
  },
  {
    id: 'en-b1-l3-2-reporting-speech',
    unitId: 'en-b1-u3-describing-reporting',
    title: 'Reporting what people say',
    titleVi: 'Tường thuật lời nói',
    objectiveVi: 'Tường thuật lại lời nói của người khác bằng lời nói gián tiếp, và mô tả sự việc bằng câu bị động cơ bản.',
    estimatedMinutes: 9,
    grammarNoteVi:
      "Lời nói gián tiếp thường lùi thì một bậc: 'I am tired' → 'She said (that) she was tired.' Câu bị động (be + V3) dùng khi người/vật thực hiện hành động không quan trọng bằng chính hành động: 'The bridge was built in 1990.'",
    vocabulary: [
      { id: 'en-b1-l3-2-v1', term: 'said (that)', translationVi: 'Đã nói rằng', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l3-2-s1' },
      { id: 'en-b1-l3-2-v2', term: 'told (someone)', translationVi: 'Đã bảo (ai đó)', partOfSpeech: 'phrase', usageNoteVi: "'tell' luôn cần tân ngữ chỉ người nghe, 'say' thì không bắt buộc." },
      { id: 'en-b1-l3-2-v3', term: 'mentioned', translationVi: 'Đã đề cập', partOfSpeech: 'verb', exampleSentenceId: 'en-b1-l3-2-s2' },
      { id: 'en-b1-l3-2-v4', term: 'explained', translationVi: 'Đã giải thích', partOfSpeech: 'verb' },
      { id: 'en-b1-l3-2-v5', term: 'was built', translationVi: 'Đã được xây dựng (bị động)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l3-2-s3' },
      { id: 'en-b1-l3-2-v6', term: 'was founded', translationVi: 'Được thành lập (bị động)', partOfSpeech: 'phrase' },
      { id: 'en-b1-l3-2-v7', term: 'is manufactured', translationVi: 'Được sản xuất (bị động)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l3-2-s4' },
      { id: 'en-b1-l3-2-v8', term: 'announcement', translationVi: 'Thông báo', partOfSpeech: 'noun' },
      { id: 'en-b1-l3-2-v9', term: 'according to', translationVi: 'Theo như', partOfSpeech: 'phrase' },
      { id: 'en-b1-l3-2-v10', term: 'quote', translationVi: 'Trích dẫn', partOfSpeech: 'verb' },
      { id: 'en-b1-l3-2-v11', term: 'headquarters', translationVi: 'Trụ sở chính', partOfSpeech: 'noun' },
      { id: 'en-b1-l3-2-v12', term: 'construction', translationVi: 'Việc xây dựng', partOfSpeech: 'noun' },
      { id: 'en-b1-l3-2-v13', term: 'release (a statement)', translationVi: 'Đưa ra (tuyên bố)', partOfSpeech: 'verb' },
    ],
    sentences: [
      { id: 'en-b1-l3-2-s1', text: "She said that she was going to be late.", translationVi: 'Cô ấy nói rằng cô ấy sẽ bị trễ.' },
      { id: 'en-b1-l3-2-s2', text: "He mentioned that the meeting had been postponed.", translationVi: 'Anh ấy đề cập rằng cuộc họp đã bị hoãn lại.' },
      { id: 'en-b1-l3-2-s3', text: "This bridge was built in 1990.", translationVi: 'Cây cầu này được xây dựng vào năm 1990.' },
      { id: 'en-b1-l3-2-s4', text: "These phones are manufactured in Vietnam.", translationVi: 'Những chiếc điện thoại này được sản xuất tại Việt Nam.' },
    ],
    exercises: [
      {
        id: 'en-b1-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn câu tường thuật đúng cho 'I am tired,' she said.",
        question: 'She said that she ___ tired.',
        options: ['is', 'was', 'has been', 'be'],
        correctOptionIndex: 1,
        explanationVi: 'Lời nói gián tiếp thường lùi thì hiện tại đơn thành quá khứ đơn.',
      },
      {
        id: 'en-b1-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng bị động đúng.',
        sentenceTemplate: 'This bridge ___ (build) in 1990.',
        wordBank: ['was built', 'built', 'has built'],
        correctAnswer: 'was built',
      },
      {
        id: 'en-b1-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['in Vietnam', 'are', 'these phones', 'manufactured'],
        correctOrder: ['these phones', 'are', 'manufactured', 'in Vietnam'],
      },
    ],
  },
];
