import type { Lesson } from '../../../types';

export const englishB1ExperiencesLessons: Lesson[] = [
  {
    id: 'en-b1-l1-1-life-experiences',
    unitId: 'en-b1-u1-experiences-opinions',
    title: 'Life experiences',
    titleVi: 'Trải nghiệm sống',
    objectiveVi:
      'Kể về trải nghiệm sống bằng thì hiện tại hoàn thành (Present Perfect), phân biệt với quá khứ đơn khi có mốc thời gian cụ thể.',
    estimatedMinutes: 9,
    grammarNoteVi:
      "Present Perfect (have/has + V3) dùng cho trải nghiệm không gắn mốc thời gian cụ thể ('I have visited Japan'). Past Simple dùng khi có mốc thời gian cụ thể đã kết thúc ('I visited Japan in 2019'). Từ tín hiệu Present Perfect: ever, never, already, just, so far; Past Simple: yesterday, last year, in 2020, ago.",
    vocabulary: [
      { id: 'en-b1-l1-1-v1', term: 'achievement', translationVi: 'Thành tựu', partOfSpeech: 'noun', exampleSentenceId: 'en-b1-l1-1-s1' },
      { id: 'en-b1-l1-1-v2', term: 'accomplish', translationVi: 'Hoàn thành, đạt được', partOfSpeech: 'verb' },
      { id: 'en-b1-l1-1-v3', term: 'challenge', translationVi: 'Thử thách', partOfSpeech: 'noun', exampleSentenceId: 'en-b1-l1-1-s2' },
      { id: 'en-b1-l1-1-v4', term: 'career', translationVi: 'Sự nghiệp', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-1-v5', term: 'abroad', translationVi: 'Ở nước ngoài', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l1-1-s3' },
      { id: 'en-b1-l1-1-v6', term: 'so far', translationVi: 'Cho đến nay', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l1-1-s4', usageNoteVi: 'Thường đi cùng Present Perfect để nói về khoảng thời gian chưa kết thúc.' },
      { id: 'en-b1-l1-1-v7', term: 'recently', translationVi: 'Gần đây', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-1-v8', term: 'milestone', translationVi: 'Cột mốc quan trọng', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-1-v9', term: 'journey', translationVi: 'Hành trình', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-1-v10', term: 'skill', translationVi: 'Kỹ năng', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-1-v11', term: 'graduate', translationVi: 'Tốt nghiệp', partOfSpeech: 'verb', exampleSentenceId: 'en-b1-l1-1-s5' },
      { id: 'en-b1-l1-1-v12', term: 'relocate', translationVi: 'Chuyển đến nơi ở/làm việc mới', partOfSpeech: 'verb' },
      { id: 'en-b1-l1-1-v13', term: 'have you ever...?', translationVi: 'Bạn đã từng... chưa?', partOfSpeech: 'phrase', usageNoteVi: "Câu hỏi hỏi về trải nghiệm, luôn dùng với Present Perfect." },
    ],
    sentences: [
      { id: 'en-b1-l1-1-s1', text: 'Graduating from university was a huge achievement for me.', translationVi: 'Tốt nghiệp đại học là một thành tựu lớn đối với tôi.' },
      { id: 'en-b1-l1-1-s2', text: "Learning a new language is always a challenge, but it's worth it.", translationVi: 'Học một ngôn ngữ mới luôn là một thử thách, nhưng rất xứng đáng.' },
      { id: 'en-b1-l1-1-s3', text: 'Have you ever worked abroad?', translationVi: 'Bạn đã từng làm việc ở nước ngoài chưa?' },
      { id: 'en-b1-l1-1-s4', text: 'I have visited ten countries so far.', translationVi: 'Cho đến nay tôi đã đến thăm mười quốc gia.' },
      { id: 'en-b1-l1-1-s5', text: 'She graduated from medical school in 2018.', translationVi: 'Cô ấy tốt nghiệp trường y vào năm 2018.' },
    ],
    exercises: [
      {
        id: 'en-b1-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Câu có mốc thời gian cụ thể (2019) — chọn thì đúng.',
        question: 'I ___ (visit) Japan in 2019.',
        options: ['have visited', 'visited', 'visit', 'was visiting'],
        correctOptionIndex: 1,
        explanationVi: "'In 2019' là mốc thời gian cụ thể đã kết thúc, nên dùng Past Simple.",
      },
      {
        id: 'en-b1-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng cho trải nghiệm không có mốc thời gian cụ thể.',
        sentenceTemplate: 'I ___ (visit) ten countries so far.',
        wordBank: ['have visited', 'visited', 'visit'],
        correctAnswer: 'have visited',
        explanationVi: "'So far' báo hiệu khoảng thời gian chưa kết thúc, dùng Present Perfect.",
      },
      {
        id: 'en-b1-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu hỏi đúng.',
        words: ['ever', 'worked', 'you', 'abroad', 'have'],
        correctOrder: ['have', 'you', 'ever', 'worked', 'abroad'],
      },
    ],
  },
  {
    id: 'en-b1-l1-2-memorable-events',
    unitId: 'en-b1-u1-experiences-opinions',
    title: 'Memorable events',
    titleVi: 'Sự kiện đáng nhớ',
    objectiveVi: 'Mô tả một hoạt động đã kéo dài đến gần đây bằng thì hiện tại hoàn thành tiếp diễn (Present Perfect Continuous).',
    estimatedMinutes: 8,
    grammarNoteVi:
      "Present Perfect Continuous (have/has been + V-ing) nhấn mạnh khoảng thời gian một hành động đã diễn ra, thường vẫn tiếp tục hoặc vừa mới kết thúc: 'I have been studying English for three years.' Khác với Present Perfect đơn (nhấn mạnh kết quả): 'I have studied three chapters.'",
    vocabulary: [
      { id: 'en-b1-l1-2-v1', term: 'lately', translationVi: 'Gần đây (thường dùng với thì hoàn thành)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l1-2-s1' },
      { id: 'en-b1-l1-2-v2', term: 'for/since', translationVi: 'Trong (khoảng)/từ (mốc)', partOfSpeech: 'phrase', usageNoteVi: "'for' + khoảng thời gian (for 3 years), 'since' + mốc thời gian (since 2020)." },
      { id: 'en-b1-l1-2-v3', term: 'exhausted', translationVi: 'Kiệt sức', partOfSpeech: 'adjective', exampleSentenceId: 'en-b1-l1-2-s2' },
      { id: 'en-b1-l1-2-v4', term: 'preparation', translationVi: 'Sự chuẩn bị', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-2-v5', term: 'rehearse', translationVi: 'Luyện tập, diễn tập', partOfSpeech: 'verb', exampleSentenceId: 'en-b1-l1-2-s3' },
      { id: 'en-b1-l1-2-v6', term: 'ceremony', translationVi: 'Buổi lễ', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-2-v7', term: 'anniversary', translationVi: 'Ngày kỷ niệm', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-2-v8', term: 'organize', translationVi: 'Tổ chức', partOfSpeech: 'verb' },
      { id: 'en-b1-l1-2-v9', term: 'get ready for', translationVi: 'Chuẩn bị cho', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-2-v10', term: 'plan ahead', translationVi: 'Lên kế hoạch trước', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-2-v11', term: 'run into a problem', translationVi: 'Gặp phải vấn đề', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l1-2-s4' },
      { id: 'en-b1-l1-2-v12', term: 'so far', translationVi: 'Cho đến nay', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-2-v13', term: 'wear someone out', translationVi: 'Làm ai đó kiệt sức', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-b1-l1-2-s1', text: "I haven't slept well lately because of the wedding preparations.", translationVi: 'Gần đây tôi ngủ không ngon vì việc chuẩn bị đám cưới.' },
      { id: 'en-b1-l1-2-s2', text: "We have been rehearsing for the ceremony all week, and we're exhausted.", translationVi: 'Chúng tôi đã diễn tập cho buổi lễ cả tuần nay, và chúng tôi kiệt sức rồi.' },
      { id: 'en-b1-l1-2-s3', text: 'The band has been rehearsing since six o\'clock.', translationVi: 'Ban nhạc đã diễn tập từ sáu giờ đến giờ.' },
      { id: 'en-b1-l1-2-s4', text: "We've run into a few problems while organizing the anniversary party.", translationVi: 'Chúng tôi đã gặp phải vài vấn đề khi tổ chức tiệc kỷ niệm.' },
    ],
    exercises: [
      {
        id: 'en-b1-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng nhấn mạnh khoảng thời gian hành động diễn ra liên tục.',
        question: 'We ___ (rehearse) for the ceremony all week.',
        options: ['have rehearsed', 'have been rehearsing', 'rehearsed', 'rehearse'],
        correctOptionIndex: 1,
        explanationVi: "'All week' nhấn mạnh khoảng thời gian liên tục, phù hợp với Present Perfect Continuous.",
      },
      {
        id: 'en-b1-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền giới từ đúng: khoảng thời gian hay mốc thời gian?',
        sentenceTemplate: "The band has been rehearsing ___ six o'clock.",
        wordBank: ['since', 'for', 'ago'],
        correctAnswer: 'since',
        explanationVi: "'Six o'clock' là một mốc thời gian, nên dùng 'since'.",
      },
      {
        id: 'en-b1-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['well', "haven't", 'lately', 'slept', 'I'],
        correctOrder: ['I', "haven't", 'slept', 'well', 'lately'],
      },
    ],
  },
  {
    id: 'en-b1-l1-3-opinions',
    unitId: 'en-b1-u1-experiences-opinions',
    title: 'Sharing opinions',
    titleVi: 'Nêu ý kiến',
    objectiveVi: 'Nêu ý kiến, đồng ý và không đồng ý một cách lịch sự bằng các cụm từ tự nhiên trong tiếng Anh.',
    estimatedMinutes: 8,
    grammarNoteVi:
      "Nêu ý kiến: 'In my opinion, ...', 'I think/believe that...'. Đồng ý: 'I couldn't agree more.', 'That's a good point.'. Không đồng ý lịch sự: 'I see your point, but...', 'I'm not so sure about that.' — tránh phủ định trực tiếp gây mất lịch sự.",
    vocabulary: [
      { id: 'en-b1-l1-3-v1', term: 'in my opinion', translationVi: 'Theo ý kiến của tôi', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l1-3-s1' },
      { id: 'en-b1-l1-3-v2', term: 'I would argue that', translationVi: 'Tôi cho rằng', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-3-v3', term: "I couldn't agree more", translationVi: 'Tôi hoàn toàn đồng ý', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l1-3-s2' },
      { id: 'en-b1-l1-3-v4', term: "that's a fair point", translationVi: 'Đó là một ý kiến hợp lý', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-3-v5', term: "I see your point, but...", translationVi: 'Tôi hiểu ý bạn, nhưng...', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l1-3-s3', usageNoteVi: 'Cách bày tỏ không đồng ý một cách lịch sự.' },
      { id: 'en-b1-l1-3-v6', term: "I'm not so sure about that", translationVi: 'Tôi không chắc lắm về điều đó', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-3-v7', term: 'on the other hand', translationVi: 'Mặt khác', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-3-v8', term: 'to be honest', translationVi: 'Thành thật mà nói', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-3-v9', term: 'as far as I know', translationVi: 'Theo như tôi biết', partOfSpeech: 'phrase' },
      { id: 'en-b1-l1-3-v10', term: 'debate', translationVi: 'Tranh luận', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-3-v11', term: 'perspective', translationVi: 'Quan điểm, góc nhìn', partOfSpeech: 'noun' },
      { id: 'en-b1-l1-3-v12', term: 'convince', translationVi: 'Thuyết phục', partOfSpeech: 'verb', exampleSentenceId: 'en-b1-l1-3-s4' },
      { id: 'en-b1-l1-3-v13', term: 'controversial', translationVi: 'Gây tranh cãi', partOfSpeech: 'adjective' },
    ],
    sentences: [
      { id: 'en-b1-l1-3-s1', text: 'In my opinion, remote work makes people more productive.', translationVi: 'Theo ý kiến của tôi, làm việc từ xa giúp mọi người làm việc năng suất hơn.' },
      { id: 'en-b1-l1-3-s2', text: "I couldn't agree more — public transport should be free.", translationVi: 'Tôi hoàn toàn đồng ý — phương tiện công cộng nên được miễn phí.' },
      { id: 'en-b1-l1-3-s3', text: "I see your point, but I still think we need more evidence.", translationVi: 'Tôi hiểu ý bạn, nhưng tôi vẫn nghĩ chúng ta cần thêm bằng chứng.' },
      { id: 'en-b1-l1-3-s4', text: 'His argument didn\'t convince me at all.', translationVi: 'Lập luận của anh ấy không thuyết phục được tôi chút nào.' },
    ],
    exercises: [
      {
        id: 'en-b1-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cách diễn đạt lịch sự nhất để KHÔNG đồng ý.',
        question: 'Choose the most polite way to disagree.',
        options: ["You're wrong.", "I see your point, but I'm not so sure about that.", 'No, that\'s not true.', "That's a bad idea."],
        correctOptionIndex: 1,
      },
      {
        id: 'en-b1-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền cụm từ đúng để nêu ý kiến.',
        sentenceTemplate: '___, I think remote work is more productive.',
        wordBank: ['In my opinion', 'On the other hand', 'As far as'],
        correctAnswer: 'In my opinion',
      },
      {
        id: 'en-b1-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['agree', "couldn't", 'more', 'I'],
        correctOrder: ['I', "couldn't", 'agree', 'more'],
      },
    ],
  },
];
