import type { Lesson } from '../../../types';

export const englishB1HypotheticalsLessons: Lesson[] = [
  {
    id: 'en-b1-l2-1-hypothetical-situations',
    unitId: 'en-b1-u2-hypotheticals-requests',
    title: 'Hypothetical situations',
    titleVi: 'Tình huống có thể xảy ra',
    objectiveVi: 'Nói về điều kiện và kết quả có thể xảy ra trong tương lai bằng câu điều kiện loại 1 (First Conditional).',
    estimatedMinutes: 8,
    grammarNoteVi:
      "First Conditional: If + S + V (hiện tại đơn), S + will + V. Diễn tả điều kiện có thật, có khả năng xảy ra trong tương lai: 'If it rains, I will stay home.'",
    vocabulary: [
      { id: 'en-b1-l2-1-v1', term: 'unless', translationVi: 'Trừ khi', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-1-s1', usageNoteVi: "'Unless' = 'if...not', dùng thay cho 'if not' trong câu điều kiện." },
      { id: 'en-b1-l2-1-v2', term: 'in case', translationVi: 'Phòng khi', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-1-v3', term: 'as long as', translationVi: 'Miễn là', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-1-s2' },
      { id: 'en-b1-l2-1-v4', term: 'postpone', translationVi: 'Hoãn lại', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-1-v5', term: 'forecast', translationVi: 'Dự báo', partOfSpeech: 'noun' },
      { id: 'en-b1-l2-1-v6', term: 'deadline', translationVi: 'Hạn chót', partOfSpeech: 'noun', exampleSentenceId: 'en-b1-l2-1-s3' },
      { id: 'en-b1-l2-1-v7', term: 'submit', translationVi: 'Nộp (bài, hồ sơ)', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-1-v8', term: 'get promoted', translationVi: 'Được thăng chức', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-1-v9', term: 'make it (to somewhere)', translationVi: 'Đến kịp (nơi nào đó)', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-1-v10', term: 'traffic jam', translationVi: 'Kẹt xe', partOfSpeech: 'noun', exampleSentenceId: 'en-b1-l2-1-s4' },
      { id: 'en-b1-l2-1-v11', term: 'condition', translationVi: 'Điều kiện', partOfSpeech: 'noun' },
      { id: 'en-b1-l2-1-v12', term: 'outcome', translationVi: 'Kết quả', partOfSpeech: 'noun' },
      { id: 'en-b1-l2-1-v13', term: 'run late', translationVi: 'Bị trễ giờ', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-b1-l2-1-s1', text: "I won't finish the report unless you help me.", translationVi: 'Tôi sẽ không hoàn thành báo cáo trừ khi bạn giúp tôi.' },
      { id: 'en-b1-l2-1-s2', text: "You can borrow my car as long as you drive carefully.", translationVi: 'Bạn có thể mượn xe tôi miễn là bạn lái xe cẩn thận.' },
      { id: 'en-b1-l2-1-s3', text: "If we miss the deadline, we will have to submit it next week.", translationVi: 'Nếu chúng ta trễ hạn, chúng ta sẽ phải nộp vào tuần sau.' },
      { id: 'en-b1-l2-1-s4', text: "If there's a traffic jam, I will run late for the meeting.", translationVi: 'Nếu kẹt xe, tôi sẽ bị trễ cuộc họp.' },
    ],
    exercises: [
      {
        id: 'en-b1-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng cho câu điều kiện loại 1.',
        question: "If it ___ (rain), we will cancel the picnic.",
        options: ['rains', 'will rain', 'rained', 'would rain'],
        correctOptionIndex: 0,
        explanationVi: 'Mệnh đề if trong câu điều kiện loại 1 dùng thì hiện tại đơn.',
      },
      {
        id: 'en-b1-l2-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền từ đúng nghĩa 'trừ khi'.",
        sentenceTemplate: "I won't finish on time ___ you help me.",
        wordBank: ['unless', 'in case', 'as long as'],
        correctAnswer: 'unless',
      },
      {
        id: 'en-b1-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['carefully', 'as long as', 'you', 'drive', 'you can borrow my car'],
        correctOrder: ['you can borrow my car', 'as long as', 'you', 'drive', 'carefully'],
      },
    ],
  },
  {
    id: 'en-b1-l2-2-imagining-differently',
    unitId: 'en-b1-u2-hypotheticals-requests',
    title: 'Imagining a different situation',
    titleVi: 'Tưởng tượng một tình huống khác',
    objectiveVi: 'Nói về tình huống không có thật ở hiện tại bằng câu điều kiện loại 2 (Second Conditional).',
    estimatedMinutes: 8,
    grammarNoteVi:
      "Second Conditional: If + S + V-ed (quá khứ đơn), S + would + V. Diễn tả tình huống giả định, không có thật ở hiện tại: 'If I won the lottery, I would travel the world.' Dùng 'were' cho tất cả các ngôi với 'to be': 'If I were you...'",
    vocabulary: [
      { id: 'en-b1-l2-2-v1', term: 'win the lottery', translationVi: 'Trúng số', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-2-s1' },
      { id: 'en-b1-l2-2-v2', term: 'if I were you', translationVi: 'Nếu tôi là bạn', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-2-s2', usageNoteVi: "Dùng 'were' thay vì 'was' cho mọi ngôi trong câu điều kiện loại 2." },
      { id: 'en-b1-l2-2-v3', term: 'imaginary', translationVi: 'Tưởng tượng, không có thật', partOfSpeech: 'adjective' },
      { id: 'en-b1-l2-2-v4', term: 'quit (a job)', translationVi: 'Nghỉ việc', partOfSpeech: 'verb', exampleSentenceId: 'en-b1-l2-2-s3' },
      { id: 'en-b1-l2-2-v5', term: 'afford', translationVi: 'Có đủ khả năng (tài chính)', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-2-v6', term: 'resign', translationVi: 'Từ chức', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-2-v7', term: 'if only', translationVi: 'Giá như', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-2-s4', usageNoteVi: 'Diễn tả sự tiếc nuối về một điều không có thật ở hiện tại.' },
      { id: 'en-b1-l2-2-v8', term: 'settle down', translationVi: 'Ổn định cuộc sống', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-2-v9', term: 'pursue (a dream)', translationVi: 'Theo đuổi (ước mơ)', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-2-v10', term: 'in someone\'s shoes', translationVi: 'Ở vào vị trí của ai đó', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-2-v11', term: 'realistic', translationVi: 'Thực tế', partOfSpeech: 'adjective' },
      { id: 'en-b1-l2-2-v12', term: 'daydream', translationVi: 'Mơ mộng viển vông', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-2-v13', term: 'take a risk', translationVi: 'Chấp nhận rủi ro', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-b1-l2-2-s1', text: 'If I won the lottery, I would travel the world.', translationVi: 'Nếu trúng số, tôi sẽ đi du lịch khắp thế giới.' },
      { id: 'en-b1-l2-2-s2', text: "If I were you, I wouldn't take that risk.", translationVi: 'Nếu tôi là bạn, tôi sẽ không chấp nhận rủi ro đó.' },
      { id: 'en-b1-l2-2-s3', text: "She would quit her job if she could afford it.", translationVi: 'Cô ấy sẽ nghỉ việc nếu có đủ khả năng tài chính.' },
      { id: 'en-b1-l2-2-s4', text: "If only I had more free time to pursue my hobbies.", translationVi: 'Giá như tôi có nhiều thời gian rảnh hơn để theo đuổi sở thích.' },
    ],
    exercises: [
      {
        id: 'en-b1-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng cho tình huống giả định không có thật.',
        question: 'If I ___ (be) you, I would apologize.',
        options: ['am', 'was', 'were', 'will be'],
        correctOptionIndex: 2,
        explanationVi: "Câu điều kiện loại 2 dùng 'were' cho mọi ngôi với động từ 'to be'.",
      },
      {
        id: 'en-b1-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng ở mệnh đề kết quả.',
        sentenceTemplate: 'If I won the lottery, I ___ (travel) the world.',
        wordBank: ['would travel', 'will travel', 'travel'],
        correctAnswer: 'would travel',
      },
      {
        id: 'en-b1-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['risk', "wouldn't", 'that', 'take', 'I'],
        correctOrder: ['I', "wouldn't", 'take', 'that', 'risk'],
      },
    ],
  },
  {
    id: 'en-b1-l2-3-making-deductions',
    unitId: 'en-b1-u2-hypotheticals-requests',
    title: 'Making deductions and giving advice',
    titleVi: 'Suy đoán và đưa lời khuyên',
    objectiveVi: "Suy đoán về khả năng bằng must/might/can't, và đưa lời khuyên về quá khứ bằng should have.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "Suy đoán: 'must be' (chắc chắn), 'might/could be' (có thể), 'can't be' (chắc chắn không). Lời khuyên về việc đã xảy ra: 'should have + V3' (đáng lẽ nên làm), 'shouldn't have + V3' (đáng lẽ không nên làm).",
    vocabulary: [
      { id: 'en-b1-l2-3-v1', term: 'must be', translationVi: 'Chắc hẳn là', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-3-s1' },
      { id: 'en-b1-l2-3-v2', term: "can't be", translationVi: 'Không thể nào là', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-3-s2' },
      { id: 'en-b1-l2-3-v3', term: 'might/could be', translationVi: 'Có thể là', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-3-v4', term: 'should have', translationVi: 'Đáng lẽ nên (đã làm)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-3-s3' },
      { id: 'en-b1-l2-3-v5', term: "shouldn't have", translationVi: 'Đáng lẽ không nên (đã làm)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b1-l2-3-s4' },
      { id: 'en-b1-l2-3-v6', term: 'exhausted', translationVi: 'Kiệt sức', partOfSpeech: 'adjective' },
      { id: 'en-b1-l2-3-v7', term: 'overslept', translationVi: 'Ngủ quên', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-3-v8', term: 'regret', translationVi: 'Hối tiếc', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-3-v9', term: 'assume', translationVi: 'Cho rằng, giả định', partOfSpeech: 'verb' },
      { id: 'en-b1-l2-3-v10', term: 'evidence', translationVi: 'Bằng chứng', partOfSpeech: 'noun' },
      { id: 'en-b1-l2-3-v11', term: 'in hindsight', translationVi: 'Nhìn lại thì', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-3-v12', term: 'lock oneself out', translationVi: 'Tự khóa mình bên ngoài (quên chìa khóa)', partOfSpeech: 'phrase' },
      { id: 'en-b1-l2-3-v13', term: 'stressed out', translationVi: 'Căng thẳng, áp lực', partOfSpeech: 'adjective' },
    ],
    sentences: [
      { id: 'en-b1-l2-3-s1', text: "She hasn't answered any calls today — she must be busy.", translationVi: 'Hôm nay cô ấy không nghe cuộc gọi nào — chắc hẳn cô ấy đang bận.' },
      { id: 'en-b1-l2-3-s2', text: "That can't be his house — he told me he lives downtown.", translationVi: 'Không thể nào là nhà anh ấy — anh ấy nói với tôi anh ấy sống ở trung tâm.' },
      { id: 'en-b1-l2-3-s3', text: "You should have called me before you left.", translationVi: 'Đáng lẽ bạn nên gọi cho tôi trước khi rời đi.' },
      { id: 'en-b1-l2-3-s4', text: "I shouldn't have stayed up so late; now I'm exhausted.", translationVi: 'Đáng lẽ tôi không nên thức khuya như vậy; giờ tôi kiệt sức rồi.' },
    ],
    exercises: [
      {
        id: 'en-b1-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cách suy đoán đúng: có bằng chứng mạnh cho thấy điều đó đúng.',
        question: "She hasn't slept in two days. She ___ be exhausted.",
        options: ['must', "can't", 'shouldn\'t', 'might not'],
        correctOptionIndex: 0,
      },
      {
        id: 'en-b1-l2-3-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng đúng để nói về điều đáng lẽ nên làm ở quá khứ.",
        sentenceTemplate: 'You ___ (should / call) me before you left.',
        wordBank: ['should have called', 'should call', 'call'],
        correctAnswer: 'should have called',
      },
      {
        id: 'en-b1-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['late', 'stayed up', "shouldn't have", 'I', 'so'],
        correctOrder: ['I', "shouldn't have", 'stayed up', 'so', 'late'],
      },
    ],
  },
];
