import type { ConversationScenario } from '../../types';

export const englishB1ConversationScenarios: ConversationScenario[] = [
  {
    id: 'en-b1-conv-job-interview',
    languageCode: 'en',
    level: 'B1',
    title: 'A job interview',
    titleVi: 'Phỏng vấn xin việc',
    descriptionVi: 'Luyện hội thoại kể về kinh nghiệm làm việc bằng thì hiện tại hoàn thành trong một buổi phỏng vấn.',
    contextVi: 'An đang phỏng vấn xin việc tại một công ty marketing.',
    dialogue: [
      { id: 'en-b1-interview-turn-01', speaker: 'A', text: 'Have you ever worked in marketing before?', translationVi: 'Bạn đã từng làm việc trong ngành marketing chưa?' },
      { id: 'en-b1-interview-turn-02', speaker: 'B', text: "Yes, I've worked at two agencies over the past three years.", translationVi: 'Vâng, tôi đã làm việc tại hai agency trong ba năm qua.' },
      { id: 'en-b1-interview-turn-03', speaker: 'A', text: "That's great. What's your biggest achievement so far?", translationVi: 'Tuyệt vời. Thành tựu lớn nhất của bạn cho đến nay là gì?' },
      { id: 'en-b1-interview-turn-04', speaker: 'B', text: "I've led a campaign that increased our client's sales by 30%.", translationVi: 'Tôi đã dẫn dắt một chiến dịch giúp doanh số của khách hàng tăng 30%.' },
      { id: 'en-b1-interview-turn-05', speaker: 'A', text: 'Impressive. Have you managed a team before?', translationVi: 'Ấn tượng đấy. Bạn đã từng quản lý một nhóm chưa?' },
      { id: 'en-b1-interview-turn-06', speaker: 'B', text: "Yes, I've been managing a team of four for the last year.", translationVi: 'Vâng, tôi đã quản lý một nhóm bốn người trong năm vừa qua.' },
      { id: 'en-b1-interview-turn-07', speaker: 'A', text: 'Why do you want to leave your current job?', translationVi: 'Vì sao bạn muốn rời công việc hiện tại?' },
      { id: 'en-b1-interview-turn-08', speaker: 'B', text: "I'm looking for a bigger challenge and a chance to grow my career.", translationVi: 'Tôi đang tìm kiếm một thử thách lớn hơn và cơ hội phát triển sự nghiệp.' },
    ],
    relatedVocabularyIds: ['en-b1-l1-1-v1', 'en-b1-l1-1-v3', 'en-b1-l1-1-v4', 'en-b1-l1-1-v13'],
    task: {
      type: 'choose-reply',
      promptVi: "Nhà tuyển dụng hỏi 'Have you ever worked in marketing before?'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: "Yes, I've worked at two agencies over the past three years." },
        { id: 'o2', text: "If I were you, I wouldn't take that risk." },
        { id: 'o3', text: 'The report was written by the marketing team.' },
        { id: 'o4', text: 'I see your point, but I disagree.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi hỏi về trải nghiệm nghề nghiệp trong quá khứ, nên trả lời bằng Present Perfect kể về kinh nghiệm đã có.",
    },
  },
  {
    id: 'en-b1-conv-what-would-you-do',
    languageCode: 'en',
    level: 'B1',
    title: 'What would you do?',
    titleVi: 'Bạn sẽ làm gì?',
    descriptionVi: 'Luyện hội thoại đặt ra tình huống giả định bằng câu điều kiện loại 2.',
    contextVi: 'Minh và Lan đang trò chuyện về việc họ sẽ làm gì nếu có một năm nghỉ phép dài.',
    dialogue: [
      { id: 'en-b1-wwyd-turn-01', speaker: 'A', text: "If you had a year off, what would you do?", translationVi: 'Nếu bạn có một năm nghỉ, bạn sẽ làm gì?' },
      { id: 'en-b1-wwyd-turn-02', speaker: 'B', text: "I would travel around South America. What about you?", translationVi: 'Tôi sẽ đi du lịch khắp Nam Mỹ. Còn bạn thì sao?' },
      { id: 'en-b1-wwyd-turn-03', speaker: 'A', text: "If I could afford it, I would learn to paint full-time.", translationVi: 'Nếu có đủ khả năng tài chính, tôi sẽ học vẽ toàn thời gian.' },
      { id: 'en-b1-wwyd-turn-04', speaker: 'B', text: "That sounds relaxing. Wouldn't you miss working, though?", translationVi: 'Nghe thư giãn đấy. Nhưng bạn sẽ không nhớ công việc à?' },
      { id: 'en-b1-wwyd-turn-05', speaker: 'A', text: "Honestly, I think I would miss my colleagues the most.", translationVi: 'Thành thật mà nói, tôi nghĩ tôi sẽ nhớ đồng nghiệp nhất.' },
      { id: 'en-b1-wwyd-turn-06', speaker: 'B', text: "If I were you, I'd take the risk and try it anyway.", translationVi: 'Nếu tôi là bạn, tôi sẽ chấp nhận rủi ro và cứ thử xem sao.' },
      { id: 'en-b1-wwyd-turn-07', speaker: 'A', text: 'Maybe you\'re right. What would you do first in South America?', translationVi: 'Có lẽ bạn đúng. Bạn sẽ làm gì đầu tiên ở Nam Mỹ?' },
      { id: 'en-b1-wwyd-turn-08', speaker: 'B', text: "I'd probably hike through the mountains in Peru.", translationVi: 'Chắc là tôi sẽ đi bộ đường dài qua những ngọn núi ở Peru.' },
    ],
    relatedVocabularyIds: ['en-b1-l2-2-v1', 'en-b1-l2-2-v2', 'en-b1-l2-2-v5', 'en-b1-l2-2-v13'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa hỏi 'If you had a year off, what would you do?'. Chọn câu trả lời phù hợp nhất.",
      options: [
        { id: 'o1', text: 'I would travel around South America.' },
        { id: 'o2', text: 'You should have called me earlier.' },
        { id: 'o3', text: 'This bridge was built in 1990.' },
        { id: 'o4', text: 'The man who called earlier left a message.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi dùng câu điều kiện loại 2, nên trả lời cũng bằng câu điều kiện loại 2 diễn tả điều giả định.",
    },
  },
  {
    id: 'en-b1-conv-giving-advice',
    languageCode: 'en',
    level: 'B1',
    title: 'A problem shared with a friend',
    titleVi: 'Chia sẻ vấn đề với bạn bè',
    descriptionVi: 'Luyện hội thoại suy đoán nguyên nhân và đưa lời khuyên bằng động từ khuyết thiếu.',
    contextVi: 'An đang kể với Minh về việc bị trễ một cuộc họp quan trọng.',
    dialogue: [
      { id: 'en-b1-advice-turn-01', speaker: 'A', text: "I missed an important meeting this morning. I feel terrible.", translationVi: 'Sáng nay tôi đã lỡ một cuộc họp quan trọng. Tôi cảm thấy rất tệ.' },
      { id: 'en-b1-advice-turn-02', speaker: 'B', text: "What happened? You must have overslept.", translationVi: 'Chuyện gì đã xảy ra vậy? Chắc hẳn bạn đã ngủ quên.' },
      { id: 'en-b1-advice-turn-03', speaker: 'A', text: "Actually, there was a huge traffic jam on the highway.", translationVi: 'Thực ra là do kẹt xe nghiêm trọng trên đường cao tốc.' },
      { id: 'en-b1-advice-turn-04', speaker: 'B', text: "That's rough. You should have left home earlier, just in case.", translationVi: 'Nghe cũng khổ đấy. Đáng lẽ bạn nên rời nhà sớm hơn, để phòng trường hợp đó.' },
      { id: 'en-b1-advice-turn-05', speaker: 'A', text: "You're right. I shouldn't have assumed the road would be clear.", translationVi: 'Bạn nói đúng. Đáng lẽ tôi không nên cho rằng đường sẽ thông thoáng.' },
      { id: 'en-b1-advice-turn-06', speaker: 'B', text: "Have you talked to your manager about it?", translationVi: 'Bạn đã nói chuyện với quản lý về việc này chưa?' },
      { id: 'en-b1-advice-turn-07', speaker: 'A', text: "Not yet. She might be busy right now.", translationVi: 'Chưa. Có thể cô ấy đang bận ngay lúc này.' },
      { id: 'en-b1-advice-turn-08', speaker: 'B', text: "I think you should explain what happened as soon as possible.", translationVi: 'Tôi nghĩ bạn nên giải thích chuyện gì đã xảy ra càng sớm càng tốt.' },
    ],
    relatedVocabularyIds: ['en-b1-l2-3-v1', 'en-b1-l2-3-v3', 'en-b1-l2-3-v4', 'en-b1-l2-3-v5'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn muốn nhẹ nhàng khuyên ai đó rằng đáng lẽ họ nên rời nhà sớm hơn. Chọn câu lịch sự và tự nhiên nhất.",
      options: [
        { id: 'o1', text: 'You should have left home earlier, just in case.' },
        { id: 'o2', text: 'You are always late, it is your fault.' },
        { id: 'o3', text: 'Why are you always making excuses?' },
        { id: 'o4', text: "That's your problem, not mine." },
      ],
      correctOptionId: 'o1',
      explanationVi: "'Should have + V3' là cách đưa nhận xét/lời khuyên về quá khứ một cách nhẹ nhàng, không đổ lỗi trực tiếp.",
    },
  },
];
