import type { ConversationScenario } from '../../types';

export const japaneseB1ConversationScenarios: ConversationScenario[] = [
  {
    id: 'ja-b1-conv-keiken-hanashi',
    languageCode: 'ja',
    level: 'B1',
    title: '経験について話す',
    titleVi: 'Nói về kinh nghiệm',
    descriptionVi: 'Luyện hội thoại kể về kinh nghiệm và nêu ý kiến bằng ～たことがあります và ～と思います。',
    contextVi: 'AさんとBさんが旅行の経験について話しています。An và Minh đang nói chuyện về kinh nghiệm du lịch.',
    dialogue: [
      { id: 'ja-b1-keiken-turn-01', speaker: 'A', text: '海外旅行をしたことがありますか。', translationVi: '(Kaigai ryokou o shita koto ga arimasu ka?) Bạn đã từng đi du lịch nước ngoài chưa?' },
      { id: 'ja-b1-keiken-turn-02', speaker: 'B', text: 'はい、日本に行ったことがあります。', translationVi: '(Hai, Nihon ni itta koto ga arimasu.) Có, tôi đã từng đi Nhật Bản.' },
      { id: 'ja-b1-keiken-turn-03', speaker: 'A', text: 'どうでしたか。', translationVi: '(Dou deshita ka?) Chuyến đi thế nào?' },
      { id: 'ja-b1-keiken-turn-04', speaker: 'B', text: 'とても楽しかったです。もう一度行きたいと思います。', translationVi: '(Totemo tanoshikatta desu. Mou ichido ikitai to omoimasu.) Rất vui. Tôi nghĩ tôi muốn đi lại một lần nữa.' },
      { id: 'ja-b1-keiken-turn-05', speaker: 'A', text: '富士山に登ったことがありますか。', translationVi: '(Fujisan ni nobotta koto ga arimasu ka?) Bạn đã từng leo núi Phú Sĩ chưa?' },
      { id: 'ja-b1-keiken-turn-06', speaker: 'B', text: 'いいえ、一度もありません。でも、いつか登ってみたいと思います。', translationVi: '(Iie, ichido mo arimasen. Demo, itsuka nobotte mitai to omoimasu.) Chưa, chưa từng lần nào. Nhưng tôi nghĩ một ngày nào đó tôi muốn thử leo.' },
      { id: 'ja-b1-keiken-turn-07', speaker: 'A', text: '私は難しいと思います。準備が必要ですね。', translationVi: '(Watashi wa muzukashii to omoimasu. Junbi ga hitsuyou desu ne.) Tôi nghĩ nó khó đấy. Cần chuẩn bị nhỉ.' },
      { id: 'ja-b1-keiken-turn-08', speaker: 'B', text: 'そうですね。まず本で調べてみます。', translationVi: '(Sou desu ne. Mazu hon de shirabete mimasu.) Đúng vậy nhỉ. Trước tiên tôi sẽ thử tìm hiểu qua sách.' },
    ],
    relatedVocabularyIds: ['ja-b1-l1-1-v1', 'ja-b1-l1-1-v5', 'ja-b1-l1-2-v1', 'ja-b1-l1-2-v13'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '海外旅行をしたことがありますか。'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: 'はい、日本に行ったことがあります。' },
        { id: 'o2', text: '雨が降ったら、行きません。' },
        { id: 'o3', text: '規則を守らなければなりません。' },
        { id: 'o4', text: '彼は忙しいみたいです。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi hỏi về kinh nghiệm du lịch trong quá khứ, nên trả lời bằng cấu trúc ～たことがあります.",
    },
  },
  {
    id: 'ja-b1-conv-keikaku-jouken',
    languageCode: 'ja',
    level: 'B1',
    title: '週末の計画',
    titleVi: 'Kế hoạch cuối tuần',
    descriptionVi: 'Luyện hội thoại đặt điều kiện và nói về nghĩa vụ bằng ～たら và ～なければなりません。',
    contextVi: 'LanさんとMinhさんが週末の計画について話しています。Lan và Minh đang bàn về kế hoạch cuối tuần.',
    dialogue: [
      { id: 'ja-b1-keikaku-turn-01', speaker: 'A', text: '週末、天気が良かったら、山に行きませんか。', translationVi: '(Shuumatsu, tenki ga yokattara, yama ni ikimasen ka?) Cuối tuần này, nếu thời tiết đẹp thì mình đi núi nhé?' },
      { id: 'ja-b1-keikaku-turn-02', speaker: 'B', text: 'いいですね。でも、土曜日は仕事をしなければなりません。', translationVi: '(Ii desu ne. Demo, doyoubi wa shigoto o shinakereba narimasen.) Hay đấy. Nhưng thứ Bảy tôi phải làm việc.' },
      { id: 'ja-b1-keikaku-turn-03', speaker: 'A', text: 'それなら、日曜日はどうですか。', translationVi: '(Sorenara, nichiyoubi wa dou desu ka?) Vậy thì Chủ nhật thì sao?' },
      { id: 'ja-b1-keikaku-turn-04', speaker: 'B', text: 'いいですよ。もし雨が降ったら、どうしますか。', translationVi: '(Ii desu yo. Moshi ame ga futtara, dou shimasu ka?) Được đấy. Nếu lỡ trời mưa thì làm sao?' },
      { id: 'ja-b1-keikaku-turn-05', speaker: 'A', text: '雨が降ったら、映画を見に行きましょう。', translationVi: '(Ame ga futtara, eiga o mi ni ikimashou.) Nếu trời mưa thì mình đi xem phim nhé.' },
      { id: 'ja-b1-keikaku-turn-06', speaker: 'B', text: '早く起きなければなりませんね。', translationVi: '(Hayaku okinakereba narimasen ne.) Vậy phải dậy sớm nhỉ.' },
      { id: 'ja-b1-keikaku-turn-07', speaker: 'A', text: 'そうですね。でも、お弁当は作らなくてもいいですよ。', translationVi: '(Sou desu ne. Demo, obentou wa tsukuranakutemo ii desu yo.) Đúng vậy. Nhưng không cần làm cơm hộp cũng được đâu.' },
      { id: 'ja-b1-keikaku-turn-08', speaker: 'B', text: '良かったです。楽しみです。', translationVi: '(Yokatta desu. Tanoshimi desu.) May quá. Tôi rất mong chờ.' },
    ],
    relatedVocabularyIds: ['ja-b1-l2-2-v1', 'ja-b1-l2-3-v1', 'ja-b1-l2-3-v2', 'ja-b1-l2-1-v1'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa hỏi 'もし雨が降ったら、どうしますか。'. Chọn câu trả lời phù hợp nhất.",
      options: [
        { id: 'o1', text: '雨が降ったら、映画を見に行きましょう。' },
        { id: 'o2', text: 'この店は人気があるようです。' },
        { id: 'o3', text: '田中さんは来月引っ越すそうです。' },
        { id: 'o4', text: '私はその考え方に反対です。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi đặt ra tình huống điều kiện (nếu trời mưa), nên trả lời cũng bằng cấu trúc điều kiện ～たら.",
    },
  },
  {
    id: 'ja-b1-conv-uwasa-tsutaeru',
    languageCode: 'ja',
    level: 'B1',
    title: '噂を伝える',
    titleVi: 'Kể lại tin nghe được',
    descriptionVi: 'Luyện hội thoại phỏng đoán và tường thuật thông tin nghe được bằng ～ようです và ～そうです。',
    contextVi: 'AさんとBさんが同僚についての話を伝えています。An và Minh đang kể lại thông tin nghe được về một đồng nghiệp.',
    dialogue: [
      { id: 'ja-b1-uwasa-turn-01', speaker: 'A', text: '田中さんの様子がおかしいですね。何かあったようです。', translationVi: '(Tanaka-san no yousu ga okashii desu ne. Nanika atta you desu.) Trông thái độ của Tanaka có vẻ lạ nhỉ. Có vẻ như đã xảy ra chuyện gì đó.' },
      { id: 'ja-b1-uwasa-turn-02', speaker: 'B', text: '実は、来月引っ越すそうですよ。', translationVi: '(Jitsu wa, raigetsu hikkosu sou desu yo.) Thực ra, nghe nói tháng sau anh ấy sẽ chuyển nhà đấy.' },
      { id: 'ja-b1-uwasa-turn-03', speaker: 'A', text: 'そうなんですか。誰から聞きましたか。', translationVi: '(Sou nan desu ka? Dare kara kikimashita ka?) Vậy à? Bạn nghe từ ai vậy?' },
      { id: 'ja-b1-uwasa-turn-04', speaker: 'B', text: '部長の話によると、昇進するみたいです。', translationVi: '(Buchou no hanashi ni yoru to, shoushin suru mitai desu.) Theo lời trưởng phòng, nghe nói anh ấy sẽ được thăng chức.' },
      { id: 'ja-b1-uwasa-turn-05', speaker: 'A', text: 'それは良かったですね。でも、まだ確認していません。', translationVi: '(Sore wa yokatta desu ne. Demo, mada kakunin shite imasen.) Vậy thì tốt quá nhỉ. Nhưng vẫn chưa xác nhận đâu.' },
      { id: 'ja-b1-uwasa-turn-06', speaker: 'B', text: '本人に直接聞いたほうがいいと思います。', translationVi: '(Honnin ni chokusetsu kiita hou ga ii to omoimasu.) Tôi nghĩ nên hỏi trực tiếp anh ấy thì tốt hơn.' },
      { id: 'ja-b1-uwasa-turn-07', speaker: 'A', text: 'そうですね。今度会ったら聞いてみます。', translationVi: '(Sou desu ne. Kondo attara kiite mimasu.) Đúng vậy nhỉ. Lần tới gặp thì tôi sẽ thử hỏi.' },
      { id: 'ja-b1-uwasa-turn-08', speaker: 'B', text: 'それがいいと思います。', translationVi: '(Sore ga ii to omoimasu.) Tôi nghĩ vậy là tốt nhất.' },
    ],
    relatedVocabularyIds: ['ja-b1-l3-1-v1', 'ja-b1-l3-2-v1', 'ja-b1-l3-2-v2', 'ja-b1-l3-2-v10'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn nghe được một tin từ người khác (chưa xác nhận) và muốn kể lại một cách chính xác, không khẳng định chắc chắn. Chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: '実は、来月引っ越すそうですよ。' },
        { id: 'o2', text: '来月絶対に引っ越します。' },
        { id: 'o3', text: '引っ越すに決まっています。' },
        { id: 'o4', text: '引っ越すことは確実です。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi truyền đạt thông tin nghe được từ người khác mà chưa tự mình xác nhận, nên dùng ～そうです để tránh khẳng định chắc chắn quá mức.",
    },
  },
];
