import type { GrammarTopic } from '../../types';

export const japaneseB1GrammarTopics: GrammarTopic[] = [
  {
    id: 'ja-b1-gr-keiken',
    languageCode: 'ja',
    level: 'B1',
    title: '～たことがあります',
    titleVi: 'Kinh nghiệm ～たことがあります',
    explanationVi:
      "～たことがあります gắn vào động từ dạng た (quá khứ thường) để diễn tả kinh nghiệm đã từng làm, không quan trọng thời điểm cụ thể. Phủ định: ～たことがありません (chưa từng làm).",
    structure: '動詞(た形) + ことがあります',
    keyPoints: ['見る → 見たことがあります', '行く → 行ったことがあります', 'Phủ định: ことがありません (chưa từng)'],
    examples: [
      { id: 'ja-b1-gr-keiken-s1', text: '韓国に行ったことがあります。', translationVi: 'Tôi đã từng đi Hàn Quốc.' },
      { id: 'ja-b1-gr-keiken-s2', text: 'この歌を聞いたことがありません。', translationVi: 'Tôi chưa từng nghe bài hát này.' },
      { id: 'ja-b1-gr-keiken-s3', text: '着物を着たことがありますか。', translationVi: 'Bạn đã từng mặc kimono chưa?' },
    ],
    commonMistakesVi: "Người mới học hay dùng động từ dạng ます thay vì dạng た trước ことがあります, ví dụ nói sai '行きますことがあります' thay vì '行ったことがあります'.",
    exercises: [
      {
        id: 'ja-b1-gr-keiken-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng của '行く'.",
        question: '韓国に___ことがあります。',
        options: ['行く', '行った', '行きます', '行って'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-b1-gr-keiken-ex2',
        type: 'fill-blank',
        promptVi: 'Điền cụm từ còn thiếu (phủ định).',
        sentenceTemplate: 'この歌を聞いた___ありません。',
        wordBank: ['ことが', 'ものが', 'のが'],
        correctAnswer: 'ことが',
      },
      {
        id: 'ja-b1-gr-keiken-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu hỏi đúng: "Bạn đã từng mặc kimono chưa?"',
        words: ['ありますか', '着物を', '着たことが'],
        correctOrder: ['着物を', '着たことが', 'ありますか'],
      },
    ],
  },
  {
    id: 'ja-b1-gr-to-omoimasu',
    languageCode: 'ja',
    level: 'B1',
    title: '～と思います',
    titleVi: 'Nêu ý kiến ～と思います',
    explanationVi:
      "～と思います gắn sau mệnh đề (thể thường) để nêu ý kiến, suy nghĩ cá nhân, nhẹ nhàng và ít áp đặt hơn khẳng định trực tiếp bằng です/ます.",
    structure: '普通形（thể thường） + と思います',
    keyPoints: ['高い → 高いと思います', '便利だ → 便利だと思います (な形容詞 cần だ)', '行かない → 行かないと思います'],
    examples: [
      { id: 'ja-b1-gr-toomou-s1', text: 'このアプリは便利だと思います。', translationVi: 'Tôi nghĩ ứng dụng này tiện lợi.' },
      { id: 'ja-b1-gr-toomou-s2', text: '彼女は来ないと思います。', translationVi: 'Tôi nghĩ cô ấy sẽ không đến.' },
      { id: 'ja-b1-gr-toomou-s3', text: 'この道は危ないと思います。', translationVi: 'Tôi nghĩ con đường này nguy hiểm.' },
    ],
    commonMistakesVi: "Người mới học hay quên thêm だ sau tính từ đuôi -na trước と思います, ví dụ nói sai '便利と思います' thay vì '便利だと思います'.",
    exercises: [
      {
        id: 'ja-b1-gr-toomou-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng của '便利だ' trước と思います.",
        question: 'このアプリは___思います。',
        options: ['便利', '便利だと', '便利のと', '便利なと'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-b1-gr-toomou-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '彼女は来ない___思います。',
        wordBank: ['と', 'が', 'を'],
        correctAnswer: 'と',
      },
      {
        id: 'ja-b1-gr-toomou-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi nghĩ con đường này nguy hiểm."',
        words: ['危ないと思います', 'この道は'],
        correctOrder: ['この道は', '危ないと思います'],
      },
    ],
  },
  {
    id: 'ja-b1-gr-ba-tara',
    languageCode: 'ja',
    level: 'B1',
    title: '～ば・～たら',
    titleVi: 'Câu điều kiện ～ば và ～たら',
    explanationVi:
      "～ば diễn tả điều kiện tổng quát, quy luật (văn viết/trang trọng hơn). ～たら diễn tả điều kiện cụ thể hoặc hành động nối tiếp, dùng nhiều trong hội thoại thân mật. Hai dạng có thể thay thế nhau trong nhiều trường hợp.",
    structure: '動詞(え段) + ば / 動詞(た形) + ら',
    keyPoints: ['安ければ (nếu rẻ thì) — dạng ば, mang tính quy luật/tổng quát', '安かったら (nếu rẻ thì) — dạng たら, cụ thể/thân mật hơn', '～たら còn dùng để nói "khi...thì..." cho một sự kiện cụ thể trong tương lai'],
    examples: [
      { id: 'ja-b1-gr-batara-s1', text: '時間があれば、映画を見ます。', translationVi: 'Nếu có thời gian thì tôi sẽ xem phim.' },
      { id: 'ja-b1-gr-batara-s2', text: '駅に着いたら、電話します。', translationVi: 'Khi đến ga thì tôi sẽ gọi điện.' },
      { id: 'ja-b1-gr-batara-s3', text: '安ければ、買います。', translationVi: 'Nếu rẻ thì tôi sẽ mua.' },
    ],
    commonMistakesVi: "Người mới học hay chia sai dạng ば của động từ nhóm 1, ví dụ nói sai '飲むば' thay vì '飲めば'.",
    exercises: [
      {
        id: 'ja-b1-gr-batara-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng ば đúng của '飲む'.",
        question: 'お茶を___、元気になります。',
        options: ['飲むば', '飲めば', '飲んだば', '飲みば'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-b1-gr-batara-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng たら đúng của '着く'.",
        sentenceTemplate: '駅に___、電話します。',
        wordBank: ['着いたら', '着けば', '着いて'],
        correctAnswer: '着いたら',
      },
      {
        id: 'ja-b1-gr-batara-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Nếu có thời gian thì tôi sẽ xem phim."',
        words: ['映画を見ます', '時間があれば'],
        correctOrder: ['時間があれば', '映画を見ます'],
      },
    ],
  },
  {
    id: 'ja-b1-gr-obligation',
    languageCode: 'ja',
    level: 'B1',
    title: '～なければなりません／～なくてもいいです',
    titleVi: 'Nghĩa vụ bắt buộc và không cần thiết',
    explanationVi:
      "～なければなりません (bỏ ない của động từ ない形, thêm なければなりません) diễn tả việc bắt buộc phải làm. ～なくてもいいです diễn tả việc không cần làm cũng được.",
    structure: '動詞(ない形，bỏ ない) + なければなりません / + なくてもいいです',
    keyPoints: ['行く → 行かなければなりません (phải đi)', '行く → 行かなくてもいいです (không cần đi)', "Dạng thân mật hơn: ～なきゃ (khẩu ngữ, không dùng trong văn trang trọng)"],
    examples: [
      { id: 'ja-b1-gr-obligation-s1', text: '毎日薬を飲まなければなりません。', translationVi: 'Phải uống thuốc mỗi ngày.' },
      { id: 'ja-b1-gr-obligation-s2', text: '今日は残業しなくてもいいです。', translationVi: 'Hôm nay không cần làm thêm giờ cũng được.' },
      { id: 'ja-b1-gr-obligation-s3', text: 'ビザを申請しなければなりません。', translationVi: 'Phải xin visa.' },
    ],
    commonMistakesVi: "Người mới học hay nhầm ～なくてもいいです (không cần làm) với ～てはいけません (không được làm, cấm) — hai cấu trúc mang nghĩa hoàn toàn khác nhau.",
    exercises: [
      {
        id: 'ja-b1-gr-obligation-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: bắt buộc phải làm.',
        question: '毎日薬を___。',
        options: ['飲まなければなりません', '飲まなくてもいいです', '飲みます', '飲んだ'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-gr-obligation-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng: không cần làm.',
        sentenceTemplate: '今日は残業___。',
        wordBank: ['しなくてもいいです', 'しなければなりません', 'しています'],
        correctAnswer: 'しなくてもいいです',
      },
      {
        id: 'ja-b1-gr-obligation-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Phải xin visa."',
        words: ['申請しなければなりません', 'ビザを'],
        correctOrder: ['ビザを', '申請しなければなりません'],
      },
    ],
  },
  {
    id: 'ja-b1-gr-you-mitai',
    languageCode: 'ja',
    level: 'B1',
    title: '～ようです／～みたいです',
    titleVi: 'Phỏng đoán ～ようです／～みたいです',
    explanationVi:
      "～ようです và ～みたいです diễn tả phỏng đoán dựa trên quan sát/giác quan của người nói. ～ようです trang trọng hơn, thường dùng trong văn viết; ～みたいです thân mật hơn, dùng nhiều trong hội thoại.",
    structure: '普通形 + ようです / 普通形 + みたいです（danh từ + みたい không cần の）',
    keyPoints: ['忙しい → 忙しいようです／忙しいみたいです', '先生 → 先生のようです／先生みたいです (danh từ + よう cần の, + みたい thì không)', 'Dựa trên quan sát/giác quan, khác với と思います (ý kiến chủ quan)'],
    examples: [
      { id: 'ja-b1-gr-youmitai-s1', text: '外は寒いようです。', translationVi: 'Bên ngoài có vẻ như đang lạnh.' },
      { id: 'ja-b1-gr-youmitai-s2', text: '彼は疲れているみたいです。', translationVi: 'Có vẻ như anh ấy đang mệt.' },
      { id: 'ja-b1-gr-youmitai-s3', text: 'この店は人気があるようです。', translationVi: 'Cửa hàng này có vẻ được yêu thích.' },
    ],
    commonMistakesVi: "Người mới học hay quên thêm の khi danh từ đứng trước ようです, ví dụ nói sai '先生ようです' thay vì '先生のようです'.",
    exercises: [
      {
        id: 'ja-b1-gr-youmitai-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng phỏng đoán đúng.',
        question: '外は寒い___。',
        options: ['ようです', 'そうです（nghe nói）', 'と思います', 'なければなりません'],
        correctOptionIndex: 0,
        explanationVi: "Dựa trên cảm nhận trực tiếp (nhìn/cảm thấy) nên dùng ようです, không phải そうです (nghe nói từ người khác).",
      },
      {
        id: 'ja-b1-gr-youmitai-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ đúng cho danh từ + ようです.',
        sentenceTemplate: 'あの人は先生___ようです。',
        wordBank: ['の', 'な', 'だ'],
        correctAnswer: 'の',
      },
      {
        id: 'ja-b1-gr-youmitai-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Có vẻ như anh ấy đang mệt."',
        words: ['疲れているみたいです', '彼は'],
        correctOrder: ['彼は', '疲れているみたいです'],
      },
    ],
  },
];
