import type { Lesson } from '../../../types';

export const japaneseB1ConditionsLessons: Lesson[] = [
  {
    id: 'ja-b1-l2-1-ba',
    unitId: 'ja-b1-u2-conditions-obligations',
    title: '～ば',
    titleVi: 'Điều kiện ～ば',
    objectiveVi: "Diễn tả điều kiện tổng quát, quy luật hoặc giả định bằng '～ば'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "動詞: đổi âm cuối う→え rồi thêm ば (行く→行けば). い形容詞: đổi い→ければ (高い→高ければ). な形容詞/名詞: thêm なら(ば). Diễn tả điều kiện tổng quát, quy luật tự nhiên hoặc giả định.",
    vocabulary: [
      { id: 'ja-b1-l2-1-v1', term: '～ば', translationVi: 'Nếu... thì... (điều kiện tổng quát)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~ba' },
      { id: 'ja-b1-l2-1-v2', term: '安い', translationVi: 'Rẻ', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b1-l2-1-s1', usageNoteVi: 'Cách đọc (romaji): yasui' },
      { id: 'ja-b1-l2-1-v3', term: '手伝う', translationVi: 'Giúp đỡ', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-1-s2', usageNoteVi: 'Cách đọc (romaji): tetsudau' },
      { id: 'ja-b1-l2-1-v4', term: '分かる', translationVi: 'Hiểu', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-1-s3', usageNoteVi: 'Cách đọc (romaji): wakaru' },
      { id: 'ja-b1-l2-1-v5', term: '聞く', translationVi: 'Hỏi, nghe', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): kiku' },
      { id: 'ja-b1-l2-1-v6', term: 'ボタン', translationVi: 'Nút bấm', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l2-1-s4', usageNoteVi: 'Cách đọc (romaji): botan' },
      { id: 'ja-b1-l2-1-v7', term: '押す', translationVi: 'Nhấn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): osu' },
      { id: 'ja-b1-l2-1-v8', term: '天気予報', translationVi: 'Dự báo thời tiết', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): tenki yohou' },
      { id: 'ja-b1-l2-1-v9', term: '成功する', translationVi: 'Thành công', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): seikou suru' },
      { id: 'ja-b1-l2-1-v10', term: '努力する', translationVi: 'Nỗ lực', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): doryoku suru' },
      { id: 'ja-b1-l2-1-v11', term: '静かだ', translationVi: 'Yên tĩnh', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b1-l2-1-s5', usageNoteVi: 'Cách đọc (romaji): shizuka da' },
      { id: 'ja-b1-l2-1-v12', term: '眠れる', translationVi: 'Ngủ được', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-1-s5', usageNoteVi: 'Cách đọc (romaji): nemureru' },
      { id: 'ja-b1-l2-1-v13', term: '電気がつく', translationVi: 'Đèn bật sáng', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l2-1-s4', usageNoteVi: 'Cách đọc (romaji): denki ga tsuku' },
    ],
    sentences: [
      { id: 'ja-b1-l2-1-s1', text: '安ければ買います。', translationVi: '(Yasukereba kaimasu.) Nếu rẻ thì tôi sẽ mua.' },
      { id: 'ja-b1-l2-1-s2', text: '時間があれば手伝います。', translationVi: '(Jikan ga areba tetsudaimasu.) Nếu có thời gian thì tôi sẽ giúp.' },
      { id: 'ja-b1-l2-1-s3', text: '分からなければ聞いてください。', translationVi: '(Wakaranakereba kiite kudasai.) Nếu không hiểu thì hãy hỏi.' },
      { id: 'ja-b1-l2-1-s4', text: 'このボタンを押せば、電気がつきます。', translationVi: '(Kono botan o oseba, denki ga tsukimasu.) Nếu nhấn nút này thì đèn sẽ bật.' },
      { id: 'ja-b1-l2-1-s5', text: '静かであれば、よく眠れます。', translationVi: '(Shizuka de areba, yoku nemuremasu.) Nếu yên tĩnh thì tôi sẽ ngủ ngon.' },
    ],
    exercises: [
      {
        id: 'ja-b1-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng ば đúng của '安い'.",
        question: '安___買います。',
        options: ['ければ', 'かった', 'くて', 'い'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-l2-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng ば đúng của 'ある'.",
        sentenceTemplate: '時間が___手伝います。',
        wordBank: ['あれば', 'あって', 'あるから'],
        correctAnswer: 'あれば',
      },
      {
        id: 'ja-b1-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Nếu không hiểu thì hãy hỏi."',
        words: ['聞いてください', '分からなければ'],
        correctOrder: ['分からなければ', '聞いてください'],
      },
    ],
  },
  {
    id: 'ja-b1-l2-2-tara',
    unitId: 'ja-b1-u2-conditions-obligations',
    title: '～たら',
    titleVi: 'Điều kiện ～たら',
    objectiveVi: "Diễn tả điều kiện cụ thể hoặc hành động nối tiếp bằng '～たら', thân mật và tự nhiên hơn ば trong hội thoại.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "動詞(た形) + ら diễn tả điều kiện cụ thể ('nếu...thì...') hoặc hành động xảy ra sau khi điều kiện được đáp ứng ('khi...thì...'). Ví dụ: 降る→降ったら, 着く→着いたら. Dùng nhiều trong hội thoại hơn ば.",
    vocabulary: [
      { id: 'ja-b1-l2-2-v1', term: '～たら', translationVi: 'Nếu/khi... thì... (thân mật, cụ thể)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~tara' },
      { id: 'ja-b1-l2-2-v2', term: '雨が降る', translationVi: 'Trời mưa', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l2-2-s1', usageNoteVi: 'Cách đọc (romaji): ame ga furu' },
      { id: 'ja-b1-l2-2-v3', term: '着く', translationVi: 'Đến nơi', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-2-s2', usageNoteVi: 'Cách đọc (romaji): tsuku' },
      { id: 'ja-b1-l2-2-v4', term: 'お金', translationVi: 'Tiền', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l2-2-s3', usageNoteVi: 'Cách đọc (romaji): okane' },
      { id: 'ja-b1-l2-2-v5', term: '宝くじ', translationVi: 'Xổ số', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l2-2-s4', usageNoteVi: 'Cách đọc (romaji): takarakuji' },
      { id: 'ja-b1-l2-2-v6', term: '当たる', translationVi: 'Trúng (giải)', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): ataru' },
      { id: 'ja-b1-l2-2-v7', term: '卒業する', translationVi: 'Tốt nghiệp', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-2-s5', usageNoteVi: 'Cách đọc (romaji): sotsugyou suru' },
      { id: 'ja-b1-l2-2-v8', term: '就職する', translationVi: 'Xin được việc làm', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-2-s5', usageNoteVi: 'Cách đọc (romaji): shuushoku suru' },
      { id: 'ja-b1-l2-2-v9', term: '疲れる', translationVi: 'Mệt', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): tsukareru' },
      { id: 'ja-b1-l2-2-v10', term: '休む', translationVi: 'Nghỉ ngơi', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): yasumu' },
      { id: 'ja-b1-l2-2-v11', term: '連絡する', translationVi: 'Liên lạc', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): renraku suru' },
      { id: 'ja-b1-l2-2-v12', term: 'もし', translationVi: 'Nếu như', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l2-2-s4', usageNoteVi: 'Cách đọc (romaji): moshi' },
      { id: 'ja-b1-l2-2-v13', term: '旅行する', translationVi: 'Đi du lịch', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-2-s3', usageNoteVi: 'Cách đọc (romaji): ryokou suru' },
    ],
    sentences: [
      { id: 'ja-b1-l2-2-s1', text: '雨が降ったら、行きません。', translationVi: '(Ame ga futtara, ikimasen.) Nếu trời mưa thì tôi sẽ không đi.' },
      { id: 'ja-b1-l2-2-s2', text: '家に着いたら、電話してください。', translationVi: '(Ie ni tsuitara, denwa shite kudasai.) Khi về đến nhà thì hãy gọi điện cho tôi.' },
      { id: 'ja-b1-l2-2-s3', text: 'お金があったら、旅行したいです。', translationVi: '(Okane ga attara, ryokou shitai desu.) Nếu có tiền thì tôi muốn đi du lịch.' },
      { id: 'ja-b1-l2-2-s4', text: 'もし宝くじが当たったら、家を買います。', translationVi: '(Moshi takarakuji ga atattara, ie o kaimasu.) Nếu trúng số thì tôi sẽ mua nhà.' },
      { id: 'ja-b1-l2-2-s5', text: '卒業したら、就職するつもりです。', translationVi: '(Sotsugyou shitara, shuushoku suru tsumori desu.) Sau khi tốt nghiệp, tôi định xin việc làm.' },
    ],
    exercises: [
      {
        id: 'ja-b1-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng たら đúng của '降る'.",
        question: '雨が___、行きません。',
        options: ['降ったら', '降ると', '降って', '降り'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-l2-2-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng たら đúng của '着く'.",
        sentenceTemplate: '家に___、電話してください。',
        wordBank: ['着いたら', '着くと', '着いて'],
        correctAnswer: '着いたら',
      },
      {
        id: 'ja-b1-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Nếu có tiền thì tôi muốn đi du lịch."',
        words: ['旅行したいです', 'お金があったら'],
        correctOrder: ['お金があったら', '旅行したいです'],
      },
    ],
  },
  {
    id: 'ja-b1-l2-3-obligation',
    unitId: 'ja-b1-u2-conditions-obligations',
    title: '～なければなりません／～なくてもいいです',
    titleVi: 'Nghĩa vụ bắt buộc / không cần thiết',
    objectiveVi: "Diễn tả việc bắt buộc phải làm bằng '～なければなりません', và việc không cần làm bằng '～なくてもいいです'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "動詞(ない形、bỏ ない) + なければなりません: phải làm (bắt buộc). 動詞(ない形、bỏ い) + くてもいいです: không cần làm cũng được. Ví dụ: 行かない→行かなければなりません, 行かない→行かなくてもいいです.",
    vocabulary: [
      { id: 'ja-b1-l2-3-v1', term: '～なければなりません', translationVi: 'Phải làm (bắt buộc)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~nakereba narimasen' },
      { id: 'ja-b1-l2-3-v2', term: '～なくてもいいです', translationVi: 'Không cần làm cũng được', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~nakutemo ii desu' },
      { id: 'ja-b1-l2-3-v3', term: '宿題', translationVi: 'Bài tập về nhà', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l2-3-s1', usageNoteVi: 'Cách đọc (romaji): shukudai' },
      { id: 'ja-b1-l2-3-v4', term: '提出する', translationVi: 'Nộp', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-3-s1', usageNoteVi: 'Cách đọc (romaji): teishutsu suru' },
      { id: 'ja-b1-l2-3-v5', term: '規則', translationVi: 'Quy tắc, quy định', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l2-3-s2', usageNoteVi: 'Cách đọc (romaji): kisoku' },
      { id: 'ja-b1-l2-3-v6', term: '守る', translationVi: 'Tuân thủ', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-3-s2', usageNoteVi: 'Cách đọc (romaji): mamoru' },
      { id: 'ja-b1-l2-3-v7', term: 'パスポート', translationVi: 'Hộ chiếu', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l2-3-s3', usageNoteVi: 'Cách đọc (romaji): pasupooto' },
      { id: 'ja-b1-l2-3-v8', term: '持参する', translationVi: 'Mang theo', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-3-s3', usageNoteVi: 'Cách đọc (romaji): jisan suru' },
      { id: 'ja-b1-l2-3-v9', term: '予約する', translationVi: 'Đặt trước', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-3-s5', usageNoteVi: 'Cách đọc (romaji): yoyaku suru' },
      { id: 'ja-b1-l2-3-v10', term: '制服', translationVi: 'Đồng phục', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l2-3-s4', usageNoteVi: 'Cách đọc (romaji): seifuku' },
      { id: 'ja-b1-l2-3-v11', term: '遅刻する', translationVi: 'Đi trễ', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): chikoku suru' },
      { id: 'ja-b1-l2-3-v12', term: '許可', translationVi: 'Sự cho phép', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): kyoka' },
      { id: 'ja-b1-l2-3-v13', term: '着る', translationVi: 'Mặc', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l2-3-s4', usageNoteVi: 'Cách đọc (romaji): kiru' },
    ],
    sentences: [
      { id: 'ja-b1-l2-3-s1', text: '明日までに宿題を提出しなければなりません。', translationVi: '(Ashita made ni shukudai o teishutsu shinakereba narimasen.) Đến hết ngày mai tôi phải nộp bài tập.' },
      { id: 'ja-b1-l2-3-s2', text: '規則を守らなければなりません。', translationVi: '(Kisoku o mamoranakereba narimasen.) Phải tuân thủ quy định.' },
      { id: 'ja-b1-l2-3-s3', text: 'パスポートを持参しなければなりません。', translationVi: '(Pasupooto o jisan shinakereba narimasen.) Phải mang theo hộ chiếu.' },
      { id: 'ja-b1-l2-3-s4', text: '今日は制服を着なくてもいいです。', translationVi: '(Kyou wa seifuku o kinakutemo ii desu.) Hôm nay không cần mặc đồng phục cũng được.' },
      { id: 'ja-b1-l2-3-s5', text: '予約しなくてもいいですか。', translationVi: '(Yoyaku shinakutemo ii desu ka?) Không cần đặt trước cũng được phải không?' },
    ],
    exercises: [
      {
        id: 'ja-b1-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: bắt buộc phải làm.',
        question: '明日までに宿題を___。',
        options: ['提出しなければなりません', '提出しなくてもいいです', '提出します', '提出した'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng: không cần làm.',
        sentenceTemplate: '今日は制服を___。',
        wordBank: ['着なくてもいいです', '着なければなりません', '着ています'],
        correctAnswer: '着なくてもいいです',
      },
      {
        id: 'ja-b1-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Phải tuân thủ quy định."',
        words: ['守らなければなりません', '規則を'],
        correctOrder: ['規則を', '守らなければなりません'],
      },
    ],
  },
];
