import type { Lesson } from '../../../types';

export const japaneseB1ConjectureLessons: Lesson[] = [
  {
    id: 'ja-b1-l3-1-you-mitai',
    unitId: 'ja-b1-u3-conjecture-hearsay',
    title: '～ようです／～みたいです',
    titleVi: 'Phỏng đoán ～ようです／～みたいです',
    objectiveVi: "Nêu phỏng đoán dựa trên quan sát, giác quan bằng '～ようです' (trang trọng) và '～みたいです' (thân mật).",
    estimatedMinutes: 8,
    grammarNoteVi:
      "動詞/形容詞(thể thường) + ようです diễn tả phỏng đoán dựa trên quan sát, trang trọng hơn みたいです. 名詞 + の + ようです; 名詞 + みたいです (không cần の). Ví dụ: 忙しい→忙しいようです/忙しいみたいです, 先生→先生のようです/先生みたいです.",
    vocabulary: [
      { id: 'ja-b1-l3-1-v1', term: '～ようです', translationVi: 'Có vẻ như (trang trọng)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~you desu' },
      { id: 'ja-b1-l3-1-v2', term: '～みたいです', translationVi: 'Có vẻ như (thân mật)', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l3-1-s2', usageNoteVi: 'Cách đọc (romaji): ~mitai desu' },
      { id: 'ja-b1-l3-1-v3', term: '忙しい', translationVi: 'Bận rộn', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b1-l3-1-s2', usageNoteVi: 'Cách đọc (romaji): isogashii' },
      { id: 'ja-b1-l3-1-v4', term: '先生', translationVi: 'Giáo viên', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l3-1-s3', usageNoteVi: 'Cách đọc (romaji): sensei' },
      { id: 'ja-b1-l3-1-v5', term: '様子', translationVi: 'Dáng vẻ, tình hình', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): yousu' },
      { id: 'ja-b1-l3-1-v6', term: '熱がある', translationVi: 'Bị sốt', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l3-1-s5', usageNoteVi: 'Cách đọc (romaji): netsu ga aru' },
      { id: 'ja-b1-l3-1-v7', term: '元気がない', translationVi: 'Trông không khỏe, không có sức sống', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l3-1-s4', usageNoteVi: 'Cách đọc (romaji): genki ga nai' },
      { id: 'ja-b1-l3-1-v8', term: '顔色', translationVi: 'Sắc mặt', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): kaoiro' },
      { id: 'ja-b1-l3-1-v9', term: '悪い', translationVi: 'Xấu, tệ', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (romaji): warui' },
      { id: 'ja-b1-l3-1-v10', term: '具合', translationVi: 'Tình trạng (sức khỏe)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): guai' },
      { id: 'ja-b1-l3-1-v11', term: '観察する', translationVi: 'Quan sát', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): kansatsu suru' },
      { id: 'ja-b1-l3-1-v12', term: '印象', translationVi: 'Ấn tượng', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): inshou' },
      { id: 'ja-b1-l3-1-v13', term: 'どうやら', translationVi: 'Hình như, có lẽ', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l3-1-s5', usageNoteVi: 'Cách đọc (romaji): douyara' },
    ],
    sentences: [
      { id: 'ja-b1-l3-1-s1', text: '雨が降っているようです。', translationVi: '(Ame ga futte iru you desu.) Có vẻ như trời đang mưa.' },
      { id: 'ja-b1-l3-1-s2', text: '彼は忙しいみたいです。', translationVi: '(Kare wa isogashii mitai desu.) Có vẻ như anh ấy đang bận.' },
      { id: 'ja-b1-l3-1-s3', text: 'あの人は先生のようです。', translationVi: '(Ano hito wa sensei no you desu.) Người kia có vẻ là giáo viên.' },
      { id: 'ja-b1-l3-1-s4', text: '彼女は元気がないみたいです。', translationVi: '(Kanojo wa genki ga nai mitai desu.) Có vẻ như cô ấy không được khỏe.' },
      { id: 'ja-b1-l3-1-s5', text: 'どうやら熱があるようです。', translationVi: '(Douyara netsu ga aru you desu.) Hình như là bị sốt rồi.' },
    ],
    exercises: [
      {
        id: 'ja-b1-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng phỏng đoán thân mật đúng.',
        question: '彼は忙しい___。',
        options: ['みたいです', 'そうです', 'たことがあります', 'なければなりません'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-l3-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền trợ từ đúng cho danh từ + ようです.",
        sentenceTemplate: 'あの人は先生___ようです。',
        wordBank: ['の', 'な', 'だ'],
        correctAnswer: 'の',
      },
      {
        id: 'ja-b1-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Có vẻ như trời đang mưa."',
        words: ['降っているようです', '雨が'],
        correctOrder: ['雨が', '降っているようです'],
      },
    ],
  },
  {
    id: 'ja-b1-l3-2-sou-desu',
    unitId: 'ja-b1-u3-conjecture-hearsay',
    title: '～そうです',
    titleVi: 'Tường thuật ～そうです (nghe nói)',
    objectiveVi: "Truyền đạt thông tin nghe được từ người khác hoặc nguồn khác bằng '～そうです'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "動詞/形容詞(thể thường) + そうです diễn tả thông tin nghe được từ nguồn khác (không phải nhận định cá nhân của người nói). Thường đi cùng ～によると (theo như...). Ví dụ: 雨だ→雨だそうです, 帰った→帰ったそうです.",
    vocabulary: [
      { id: 'ja-b1-l3-2-v1', term: '～そうです', translationVi: 'Nghe nói rằng', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~sou desu' },
      { id: 'ja-b1-l3-2-v2', term: '～によると', translationVi: 'Theo như...', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l3-2-s1', usageNoteVi: 'Cách đọc (romaji): ~ni yoru to' },
      { id: 'ja-b1-l3-2-v3', term: '天気予報', translationVi: 'Dự báo thời tiết', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l3-2-s1', usageNoteVi: 'Cách đọc (romaji): tenki yohou' },
      { id: 'ja-b1-l3-2-v4', term: '帰る', translationVi: 'Về (nhà)', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l3-2-s2', usageNoteVi: 'Cách đọc (romaji): kaeru' },
      { id: 'ja-b1-l3-2-v5', term: 'レストラン', translationVi: 'Nhà hàng', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l3-2-s3', usageNoteVi: 'Cách đọc (romaji): resutoran' },
      { id: 'ja-b1-l3-2-v6', term: 'おいしい', translationVi: 'Ngon', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b1-l3-2-s3', usageNoteVi: 'Cách đọc (romaji): oishii' },
      { id: 'ja-b1-l3-2-v7', term: 'ニュース', translationVi: 'Tin tức', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l3-2-s4', usageNoteVi: 'Cách đọc (romaji): nyuusu' },
      { id: 'ja-b1-l3-2-v8', term: '事故', translationVi: 'Tai nạn', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l3-2-s4', usageNoteVi: 'Cách đọc (romaji): jiko' },
      { id: 'ja-b1-l3-2-v9', term: '起こる', translationVi: 'Xảy ra', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l3-2-s4', usageNoteVi: 'Cách đọc (romaji): okoru' },
      { id: 'ja-b1-l3-2-v10', term: '引っ越す', translationVi: 'Chuyển nhà', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l3-2-s5', usageNoteVi: 'Cách đọc (romaji): hikkosu' },
      { id: 'ja-b1-l3-2-v11', term: '昇進する', translationVi: 'Được thăng chức', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): shoushin suru' },
      { id: 'ja-b1-l3-2-v12', term: '確認する', translationVi: 'Xác nhận', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): kakunin suru' },
      { id: 'ja-b1-l3-2-v13', term: '話によると', translationVi: 'Theo như câu chuyện/lời kể', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): hanashi ni yoru to' },
    ],
    sentences: [
      { id: 'ja-b1-l3-2-s1', text: '天気予報によると、明日は雨だそうです。', translationVi: '(Tenki yohou ni yoru to, ashita wa ame da sou desu.) Theo dự báo thời tiết, nghe nói ngày mai trời mưa.' },
      { id: 'ja-b1-l3-2-s2', text: '彼はもう帰ったそうです。', translationVi: '(Kare wa mou kaetta sou desu.) Nghe nói anh ấy đã về rồi.' },
      { id: 'ja-b1-l3-2-s3', text: 'そのレストランはおいしいそうです。', translationVi: '(Sono resutoran wa oishii sou desu.) Nghe nói nhà hàng đó ngon.' },
      { id: 'ja-b1-l3-2-s4', text: 'ニュースによると、駅前で事故が起こったそうです。', translationVi: '(Nyuusu ni yoru to, ekimae de jiko ga okotta sou desu.) Theo tin tức, nghe nói đã xảy ra tai nạn trước ga.' },
      { id: 'ja-b1-l3-2-s5', text: '田中さんは来月引っ越すそうです。', translationVi: '(Tanaka-san wa raigetsu hikkosu sou desu.) Nghe nói anh Tanaka sẽ chuyển nhà vào tháng sau.' },
    ],
    exercises: [
      {
        id: 'ja-b1-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng tường thuật đúng (nghe nói).',
        question: '明日は雨だ___。',
        options: ['そうです', 'ようです', 'と思います', 'かもしれません'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: 'そのレストランはおいしい___。',
        wordBank: ['そうです', 'そうだ', 'そうな'],
        correctAnswer: 'そうです',
      },
      {
        id: 'ja-b1-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Nghe nói anh ấy đã về rồi."',
        words: ['帰ったそうです', '彼は', 'もう'],
        correctOrder: ['彼は', 'もう', '帰ったそうです'],
      },
    ],
  },
];
