import type { Lesson } from '../../../types';

export const japaneseB1ExperienceLessons: Lesson[] = [
  {
    id: 'ja-b1-l1-1-keiken',
    unitId: 'ja-b1-u1-experience-opinions',
    title: '～たことがあります',
    titleVi: 'Kinh nghiệm ～たことがあります',
    objectiveVi: "Kể về những việc đã từng làm trong quá khứ (kinh nghiệm) bằng '～たことがあります'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "動詞(た形) + ことがあります diễn tả kinh nghiệm đã từng làm, không quan trọng thời điểm cụ thể. Phủ định: 動詞(た形) + ことがありません (chưa từng làm). Ví dụ: 行く→行ったことがあります.",
    vocabulary: [
      { id: 'ja-b1-l1-1-v1', term: '～たことがあります', translationVi: 'Đã từng làm (kinh nghiệm)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~ta koto ga arimasu' },
      { id: 'ja-b1-l1-1-v2', term: '経験', translationVi: 'Kinh nghiệm', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l1-1-s4', usageNoteVi: 'Cách đọc (romaji): keiken' },
      { id: 'ja-b1-l1-1-v3', term: '一度も', translationVi: 'Chưa từng một lần nào', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l1-1-s3', usageNoteVi: 'Cách đọc (romaji): ichido mo' },
      { id: 'ja-b1-l1-1-v4', term: '留学する', translationVi: 'Đi du học', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l1-1-s2', usageNoteVi: 'Cách đọc (romaji): ryuugaku suru' },
      { id: 'ja-b1-l1-1-v5', term: '富士山', translationVi: 'Núi Phú Sĩ', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l1-1-s1', usageNoteVi: 'Cách đọc (romaji): Fujisan' },
      { id: 'ja-b1-l1-1-v6', term: '登る', translationVi: 'Leo, trèo', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): noboru' },
      { id: 'ja-b1-l1-1-v7', term: '挑戦する', translationVi: 'Thử thách, thử sức', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): chousen suru' },
      { id: 'ja-b1-l1-1-v8', term: '珍しい', translationVi: 'Hiếm, lạ', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b1-l1-1-s4', usageNoteVi: 'Cách đọc (romaji): mezurashii' },
      { id: 'ja-b1-l1-1-v9', term: '一度', translationVi: 'Một lần', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l1-1-s5', usageNoteVi: 'Cách đọc (romaji): ichido' },
      { id: 'ja-b1-l1-1-v10', term: '海外', translationVi: 'Nước ngoài', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): kaigai' },
      { id: 'ja-b1-l1-1-v11', term: '体験する', translationVi: 'Trải nghiệm', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): taiken suru' },
      { id: 'ja-b1-l1-1-v12', term: '機会', translationVi: 'Cơ hội', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): kikai' },
      { id: 'ja-b1-l1-1-v13', term: '驚く', translationVi: 'Ngạc nhiên', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): odoroku' },
    ],
    sentences: [
      { id: 'ja-b1-l1-1-s1', text: '富士山に登ったことがあります。', translationVi: '(Fujisan ni nobotta koto ga arimasu.) Tôi đã từng leo núi Phú Sĩ.' },
      { id: 'ja-b1-l1-1-s2', text: '海外に留学したことがありますか。', translationVi: '(Kaigai ni ryuugaku shita koto ga arimasu ka?) Bạn đã từng đi du học nước ngoài chưa?' },
      { id: 'ja-b1-l1-1-s3', text: '一度もお寿司を食べたことがありません。', translationVi: '(Ichido mo osushi o tabeta koto ga arimasen.) Tôi chưa từng ăn sushi lần nào.' },
      { id: 'ja-b1-l1-1-s4', text: '珍しい経験をしたことがあります。', translationVi: '(Mezurashii keiken o shita koto ga arimasu.) Tôi đã từng có một trải nghiệm hiếm có.' },
      { id: 'ja-b1-l1-1-s5', text: 'この映画は一度見たことがあります。', translationVi: '(Kono eiga wa ichido mita koto ga arimasu.) Bộ phim này tôi đã từng xem một lần rồi.' },
    ],
    exercises: [
      {
        id: 'ja-b1-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng của '登る' để nói về kinh nghiệm.",
        question: '富士山に___ことがあります。',
        options: ['登る', '登った', '登って', '登ります'],
        correctOptionIndex: 1,
        explanationVi: "Kinh nghiệm dùng động từ dạng た (quá khứ thường) + ことがあります.",
      },
      {
        id: 'ja-b1-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền cụm từ còn thiếu.',
        sentenceTemplate: '海外に留学した___ありますか。',
        wordBank: ['ことが', 'のが', 'もの'],
        correctAnswer: 'ことが',
      },
      {
        id: 'ja-b1-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi chưa từng ăn sushi lần nào."',
        words: ['食べたことがありません', '一度も', 'お寿司を'],
        correctOrder: ['一度も', 'お寿司を', '食べたことがありません'],
      },
    ],
  },
  {
    id: 'ja-b1-l1-2-to-omoimasu',
    unitId: 'ja-b1-u1-experience-opinions',
    title: '～と思います',
    titleVi: 'Nêu ý kiến ～と思います',
    objectiveVi: "Nêu ý kiến, suy nghĩ cá nhân bằng '～と思います'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "Mệnh đề (thể thường) + と思います diễn tả ý kiến cá nhân. Tính từ đuôi -i và động từ giữ nguyên thể thường; danh từ/tính từ đuôi -na cần thêm だ trước と (trừ khi ở thể quá khứ/phủ định). Ví dụ: 面白い→面白いと思います, 大切だ→大切だと思います.",
    vocabulary: [
      { id: 'ja-b1-l1-2-v1', term: '～と思います', translationVi: 'Tôi nghĩ rằng', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~to omoimasu' },
      { id: 'ja-b1-l1-2-v2', term: '意見', translationVi: 'Ý kiến', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): iken' },
      { id: 'ja-b1-l1-2-v3', term: '賛成する', translationVi: 'Tán thành', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l1-2-s4', usageNoteVi: 'Cách đọc (romaji): sansei suru' },
      { id: 'ja-b1-l1-2-v4', term: '反対する', translationVi: 'Phản đối', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): hantai suru' },
      { id: 'ja-b1-l1-2-v5', term: '大切だ', translationVi: 'Quan trọng', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b1-l1-2-s3', usageNoteVi: 'Cách đọc (romaji): taisetsu da' },
      { id: 'ja-b1-l1-2-v6', term: '確かに', translationVi: 'Đúng là, quả thật', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): tashika ni' },
      { id: 'ja-b1-l1-2-v7', term: '個人的に', translationVi: 'Theo cá nhân tôi', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l1-2-s4', usageNoteVi: 'Cách đọc (romaji): kojinteki ni' },
      { id: 'ja-b1-l1-2-v8', term: '立場', translationVi: 'Lập trường, quan điểm', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): tachiba' },
      { id: 'ja-b1-l1-2-v9', term: '説明する', translationVi: 'Giải thích', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): setsumei suru' },
      { id: 'ja-b1-l1-2-v10', term: '理由', translationVi: 'Lý do', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): riyuu' },
      { id: 'ja-b1-l1-2-v11', term: '場合によって', translationVi: 'Tùy trường hợp', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): baai ni yotte' },
      { id: 'ja-b1-l1-2-v12', term: '正直に言うと', translationVi: 'Nói thật lòng thì', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l1-2-s5', usageNoteVi: 'Cách đọc (romaji): shoujiki ni iu to' },
      { id: 'ja-b1-l1-2-v13', term: '難しい', translationVi: 'Khó', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b1-l1-2-s5', usageNoteVi: 'Cách đọc (romaji): muzukashii' },
    ],
    sentences: [
      { id: 'ja-b1-l1-2-s1', text: 'この映画は面白いと思います。', translationVi: '(Kono eiga wa omoshiroi to omoimasu.) Tôi nghĩ bộ phim này thú vị.' },
      { id: 'ja-b1-l1-2-s2', text: '彼は明日来ないと思います。', translationVi: '(Kare wa ashita konai to omoimasu.) Tôi nghĩ anh ấy sẽ không đến vào ngày mai.' },
      { id: 'ja-b1-l1-2-s3', text: '日本語の勉強は大切だと思います。', translationVi: '(Nihongo no benkyou wa taisetsu da to omoimasu.) Tôi nghĩ việc học tiếng Nhật là quan trọng.' },
      { id: 'ja-b1-l1-2-s4', text: '個人的には、この考え方に賛成です。', translationVi: '(Kojinteki ni wa, kono kangaekata ni sansei desu.) Theo cá nhân tôi, tôi tán thành với cách nghĩ này.' },
      { id: 'ja-b1-l1-2-s5', text: '正直に言うと、少し難しいと思います。', translationVi: '(Shoujiki ni iu to, sukoshi muzukashii to omoimasu.) Nói thật lòng thì tôi nghĩ hơi khó.' },
    ],
    exercises: [
      {
        id: 'ja-b1-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cách nêu ý kiến đúng.',
        question: 'この映画は面白い___。',
        options: ['と思います', 'ようです', 'そうです', 'たことがあります'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-l1-2-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng đúng của '大切だ' trước と思います.",
        sentenceTemplate: '日本語の勉強は大切___思います。',
        wordBank: ['だと', 'だが', 'だの'],
        correctAnswer: 'だと',
      },
      {
        id: 'ja-b1-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi nghĩ anh ấy sẽ không đến vào ngày mai."',
        words: ['来ないと思います', '彼は', '明日'],
        correctOrder: ['彼は', '明日', '来ないと思います'],
      },
    ],
  },
  {
    id: 'ja-b1-l1-3-sansei-hantai',
    unitId: 'ja-b1-u1-experience-opinions',
    title: '賛成です／反対です',
    titleVi: 'Đồng ý / Phản đối',
    objectiveVi: 'Đồng ý và không đồng ý với ý kiến của người khác một cách lịch sự.',
    estimatedMinutes: 8,
    grammarNoteVi:
      "Đồng ý: ～に賛成です (tán thành với...). Phản đối: ～に反対です (phản đối...). Không đồng ý một cách lịch sự: そうですね、でも...（Đúng vậy nhỉ, nhưng...）、ちょっと違うと思います。",
    vocabulary: [
      { id: 'ja-b1-l1-3-v1', term: '賛成です', translationVi: 'Tôi tán thành', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l1-3-s1', usageNoteVi: 'Cách đọc (romaji): sansei desu' },
      { id: 'ja-b1-l1-3-v2', term: '反対です', translationVi: 'Tôi phản đối', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l1-3-s2', usageNoteVi: 'Cách đọc (romaji): hantai desu' },
      { id: 'ja-b1-l1-3-v3', term: 'そうですね', translationVi: 'Đúng vậy nhỉ', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l1-3-s3', usageNoteVi: 'Cách đọc (romaji): sou desu ne' },
      { id: 'ja-b1-l1-3-v4', term: '違う', translationVi: 'Khác, sai', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l1-3-s3', usageNoteVi: 'Cách đọc (romaji): chigau' },
      { id: 'ja-b1-l1-3-v5', term: '考え方', translationVi: 'Cách suy nghĩ', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l1-3-s2', usageNoteVi: 'Cách đọc (romaji): kangaekata' },
      { id: 'ja-b1-l1-3-v6', term: '～に対して', translationVi: 'Đối với...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~ni taishite' },
      { id: 'ja-b1-l1-3-v7', term: '一部', translationVi: 'Một phần', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l1-3-s4', usageNoteVi: 'Cách đọc (romaji): ichibu' },
      { id: 'ja-b1-l1-3-v8', term: '全体的に', translationVi: 'Nhìn chung', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b1-l1-3-s4', usageNoteVi: 'Cách đọc (romaji): zentaiteki ni' },
      { id: 'ja-b1-l1-3-v9', term: '納得する', translationVi: 'Đồng tình, thấy hợp lý', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): nattoku suru' },
      { id: 'ja-b1-l1-3-v10', term: '疑問', translationVi: 'Nghi vấn, thắc mắc', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): gimon' },
      { id: 'ja-b1-l1-3-v11', term: '議論する', translationVi: 'Tranh luận', partOfSpeech: 'verb', exampleSentenceId: 'ja-b1-l1-3-s5', usageNoteVi: 'Cách đọc (romaji): giron suru' },
      { id: 'ja-b1-l1-3-v12', term: '結論', translationVi: 'Kết luận', partOfSpeech: 'noun', exampleSentenceId: 'ja-b1-l1-3-s5', usageNoteVi: 'Cách đọc (romaji): ketsuron' },
      { id: 'ja-b1-l1-3-v13', term: '出す', translationVi: 'Đưa ra', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): dasu' },
    ],
    sentences: [
      { id: 'ja-b1-l1-3-s1', text: 'その意見に賛成です。', translationVi: '(Sono iken ni sansei desu.) Tôi tán thành với ý kiến đó.' },
      { id: 'ja-b1-l1-3-s2', text: '私はその考え方に反対です。', translationVi: '(Watashi wa sono kangaekata ni hantai desu.) Tôi phản đối cách nghĩ đó.' },
      { id: 'ja-b1-l1-3-s3', text: 'そうですね、でも少し違うと思います。', translationVi: '(Sou desu ne, demo sukoshi chigau to omoimasu.) Đúng vậy nhỉ, nhưng tôi nghĩ hơi khác một chút.' },
      { id: 'ja-b1-l1-3-s4', text: '全体的には納得しますが、一部は疑問があります。', translationVi: '(Zentaiteki ni wa nattoku shimasu ga, ichibu wa gimon ga arimasu.) Nhìn chung thì tôi thấy hợp lý, nhưng có một phần tôi còn thắc mắc.' },
      { id: 'ja-b1-l1-3-s5', text: 'もう少し議論してから結論を出しましょう。', translationVi: '(Mou sukoshi giron shite kara ketsuron o dashimashou.) Hãy tranh luận thêm một chút rồi mới đưa ra kết luận.' },
    ],
    exercises: [
      {
        id: 'ja-b1-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn trợ từ đúng.',
        question: 'その意見___賛成です。',
        options: ['に', 'を', 'が', 'で'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b1-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ nối còn thiếu.',
        sentenceTemplate: 'そうですね、___少し違うと思います。',
        wordBank: ['でも', 'そして', 'それで'],
        correctAnswer: 'でも',
      },
      {
        id: 'ja-b1-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi phản đối cách nghĩ đó."',
        words: ['反対です', '私は', 'その考え方に'],
        correctOrder: ['私は', 'その考え方に', '反対です'],
      },
    ],
  },
];
