import type { Lesson } from '../../types';

export const familyLessons: Lesson[] = [
  {
    id: 'l3-1-family-members',
    unitId: 'u3-family',
    title: 'Family members',
    titleVi: 'Các thành viên trong gia đình',
    objectiveVi: 'Gọi tên được các thành viên cơ bản trong gia đình.',
    estimatedMinutes: 6,
    grammarNoteVi: "'Parents' luôn ở dạng số nhiều vì từ này chỉ cả bố và mẹ.",
    vocabulary: [
      { id: 'l3-1-v1', term: 'family', translationVi: 'Gia đình', partOfSpeech: 'noun', exampleSentenceId: 'l3-1-s1' },
      { id: 'l3-1-v2', term: 'father', translationVi: 'Bố', partOfSpeech: 'noun', exampleSentenceId: 'l3-1-s2' },
      { id: 'l3-1-v3', term: 'mother', translationVi: 'Mẹ', partOfSpeech: 'noun', exampleSentenceId: 'l3-1-s2' },
      {
        id: 'l3-1-v4',
        term: 'brother',
        translationVi: 'Anh trai / em trai',
        partOfSpeech: 'noun',
        exampleSentenceId: 'l3-1-s3',
      },
      {
        id: 'l3-1-v5',
        term: 'sister',
        translationVi: 'Chị gái / em gái',
        partOfSpeech: 'noun',
        exampleSentenceId: 'l3-1-s3',
      },
      {
        id: 'l3-1-v6',
        term: 'parents',
        translationVi: 'Bố mẹ',
        partOfSpeech: 'noun',
        usageNoteVi: 'Luôn ở dạng số nhiều vì từ này chỉ cả bố và mẹ.',
      },
    ],
    sentences: [
      { id: 'l3-1-s1', text: 'This is my family.', translationVi: 'Đây là gia đình của tôi.' },
      {
        id: 'l3-1-s2',
        text: 'This is my father and my mother.',
        translationVi: 'Đây là bố và mẹ của tôi.',
      },
      {
        id: 'l3-1-s3',
        text: 'I have one brother and one sister.',
        translationVi: 'Tôi có một anh trai và một chị gái.',
      },
    ],
    exercises: [
      {
        id: 'l3-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'mother'.",
        question: 'mother',
        options: ['Bố', 'Mẹ', 'Chị gái', 'Bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: 'This is my ___.',
        wordBank: ['father', 'student', 'name'],
        correctAnswer: 'father',
      },
      {
        id: 'l3-1-ex3',
        type: 'multiple-choice',
        promptVi: "Từ 'gia đình' trong tiếng Anh là gì?",
        question: 'family (in Vietnamese: gia đình)',
        options: ['friend', 'family', 'teacher', 'name'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'l3-2-talking-about-family',
    unitId: 'u3-family',
    title: 'Talking about your family',
    titleVi: 'Nói về gia đình bạn',
    objectiveVi: "Sử dụng 'have' để mô tả số lượng thành viên trong gia đình.",
    estimatedMinutes: 6,
    grammarNoteVi:
      "Dùng 'have' với I/you/we/they và 'has' với he/she/it. Ví dụ: 'I have two siblings.', 'She has one sister.'",
    vocabulary: [
      { id: 'l3-2-v1', term: 'have', translationVi: 'Có', partOfSpeech: 'verb', exampleSentenceId: 'l3-2-s1' },
      {
        id: 'l3-2-v2',
        term: 'siblings',
        translationVi: 'Anh chị em ruột',
        partOfSpeech: 'noun',
        exampleSentenceId: 'l3-2-s1',
      },
      {
        id: 'l3-2-v3',
        term: 'big family',
        translationVi: 'Gia đình đông người',
        partOfSpeech: 'phrase',
        usageNoteVi: "Trái nghĩa với 'small family'.",
      },
      {
        id: 'l3-2-v4',
        term: 'small family',
        translationVi: 'Gia đình ít người',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l3-2-s3',
      },
      {
        id: 'l3-2-v5',
        term: 'live with',
        translationVi: 'Sống cùng',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l3-2-s2',
      },
    ],
    sentences: [
      { id: 'l3-2-s1', text: 'I have two siblings.', translationVi: 'Tôi có hai anh chị em.' },
      { id: 'l3-2-s2', text: 'I live with my parents.', translationVi: 'Tôi sống cùng bố mẹ.' },
      { id: 'l3-2-s3', text: 'We are a small family.', translationVi: 'Chúng tôi là một gia đình nhỏ.' },
    ],
    exercises: [
      {
        id: 'l3-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'siblings'.",
        question: 'siblings',
        options: ['Bố mẹ', 'Anh chị em ruột', 'Bạn bè', 'Hàng xóm'],
        correctOptionIndex: 1,
      },
      {
        id: 'l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: 'I ___ two siblings.',
        wordBank: ['have', 'has', 'am'],
        correctAnswer: 'have',
      },
      {
        id: 'l3-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp.',
        question: 'Choose the correct sentence.',
        options: ['I have two siblings.', 'I has two siblings.', 'I having two siblings.', 'I to have two siblings.'],
        correctOptionIndex: 0,
      },
    ],
  },
];
