import type { Lesson } from '../../types';

export const greetingsLessons: Lesson[] = [
  {
    id: 'l1-1-basic-greetings',
    unitId: 'u1-greetings',
    title: 'Basic greetings',
    titleVi: 'Lời chào cơ bản',
    objectiveVi: 'Sử dụng được các lời chào và tạm biệt cơ bản trong giao tiếp hằng ngày.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "Dùng 'Good morning' vào buổi sáng, 'Good afternoon' vào buổi chiều và 'Good evening' vào buổi tối.",
    vocabulary: [
      { id: 'l1-1-v1', term: 'hello', translationVi: 'Xin chào', partOfSpeech: 'greeting', exampleSentenceId: 'l1-1-s1' },
      {
        id: 'l1-1-v2',
        term: 'hi',
        translationVi: 'Chào (thân mật)',
        partOfSpeech: 'greeting',
        usageNoteVi: "Thân mật hơn 'hello', thường dùng với bạn bè.",
      },
      {
        id: 'l1-1-v3',
        term: 'good morning',
        translationVi: 'Chào buổi sáng',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'l1-1-s2',
      },
      {
        id: 'l1-1-v4',
        term: 'good evening',
        translationVi: 'Chào buổi tối',
        partOfSpeech: 'greeting',
        usageNoteVi: 'Dùng để chào khi gặp ai đó vào buổi tối.',
      },
      { id: 'l1-1-v5', term: 'goodbye', translationVi: 'Tạm biệt', partOfSpeech: 'greeting', exampleSentenceId: 'l1-1-s3' },
      {
        id: 'l1-1-v6',
        term: 'see you later',
        translationVi: 'Hẹn gặp lại',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l1-1-s3',
      },
    ],
    sentences: [
      { id: 'l1-1-s1', text: 'Hello, how are you?', translationVi: 'Xin chào, bạn khỏe không?' },
      {
        id: 'l1-1-s2',
        text: 'Good morning! Have a nice day.',
        translationVi: 'Chào buổi sáng! Chúc bạn một ngày tốt lành.',
      },
      { id: 'l1-1-s3', text: 'Goodbye, see you later!', translationVi: 'Tạm biệt, hẹn gặp lại nhé!' },
    ],
    exercises: [
      {
        id: 'l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'goodbye'.",
        question: 'goodbye',
        options: ['Xin chào', 'Tạm biệt', 'Cảm ơn', 'Xin lỗi'],
        correctOptionIndex: 1,
      },
      {
        id: 'l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu chào hỏi.',
        sentenceTemplate: '___, how are you?',
        wordBank: ['Hello', 'Goodbye', 'Please'],
        correctAnswer: 'Hello',
      },
      {
        id: 'l1-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Bây giờ là 8 giờ sáng. Bạn nói gì khi gặp ai đó?',
        question: "It's 8 AM. What do you say?",
        options: ['Good evening', 'Good morning', 'Good night', 'Goodbye'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'l1-2-how-are-you',
    unitId: 'u1-greetings',
    title: 'How are you?',
    titleVi: 'Hỏi thăm sức khỏe',
    objectiveVi: 'Hỏi và trả lời đơn giản về tình trạng sức khỏe, cảm xúc.',
    estimatedMinutes: 5,
    grammarNoteVi: "'I'm' là dạng viết tắt của 'I am'. Người bản xứ thường dùng dạng rút gọn này khi nói chuyện.",
    vocabulary: [
      {
        id: 'l1-2-v1',
        term: 'how are you',
        translationVi: 'Bạn khỏe không',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l1-2-s1',
      },
      { id: 'l1-2-v2', term: 'fine', translationVi: 'Khỏe', partOfSpeech: 'adjective', exampleSentenceId: 'l1-2-s2' },
      {
        id: 'l1-2-v3',
        term: 'great',
        translationVi: 'Rất tốt',
        partOfSpeech: 'adjective',
        usageNoteVi: "Diễn tả cảm giác rất tốt, tích cực hơn 'fine'.",
      },
      {
        id: 'l1-2-v4',
        term: 'not bad',
        translationVi: 'Cũng ổn',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách trả lời trung tính, không quá tốt cũng không quá tệ.',
      },
      { id: 'l1-2-v5', term: 'tired', translationVi: 'Mệt', partOfSpeech: 'adjective', exampleSentenceId: 'l1-2-s3' },
      {
        id: 'l1-2-v6',
        term: 'and you',
        translationVi: 'Còn bạn thì sao',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l1-2-s2',
      },
    ],
    sentences: [
      { id: 'l1-2-s1', text: 'How are you today?', translationVi: 'Hôm nay bạn khỏe không?' },
      {
        id: 'l1-2-s2',
        text: "I'm fine, thank you. And you?",
        translationVi: 'Tôi khỏe, cảm ơn. Còn bạn thì sao?',
      },
      { id: 'l1-2-s3', text: "I'm a little tired today.", translationVi: 'Hôm nay tôi hơi mệt.' },
    ],
    exercises: [
      {
        id: 'l1-2-ex1',
        type: 'multiple-choice',
        promptVi: "Đâu là câu trả lời phù hợp cho câu hỏi 'How are you?'",
        question: 'How are you?',
        options: ["I'm from Vietnam", "I'm fine, thank you", 'My name is Lan', 'See you later'],
        correctOptionIndex: 1,
      },
      {
        id: 'l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: "I'm fine, thank you. ___ you?",
        wordBank: ['And', 'But', 'So'],
        correctAnswer: 'And',
      },
      {
        id: 'l1-2-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'tired'.",
        question: 'tired',
        options: ['Vui', 'Mệt', 'Khỏe', 'Buồn'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'l1-3-politeness',
    unitId: 'u1-greetings',
    title: 'Basic politeness',
    titleVi: 'Phép lịch sự cơ bản',
    objectiveVi: 'Sử dụng các từ lịch sự cơ bản: làm ơn, cảm ơn, xin lỗi.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "'Excuse me' dùng để xin phép hoặc gọi ai đó trước khi nói; 'Sorry' dùng khi bạn đã làm điều gì chưa đúng.",
    vocabulary: [
      {
        id: 'l1-3-v1',
        term: 'please',
        translationVi: 'Làm ơn',
        partOfSpeech: 'phrase',
        usageNoteVi: "Thêm vào cuối câu yêu cầu để lịch sự hơn, ví dụ: 'Water, please.'",
      },
      {
        id: 'l1-3-v2',
        term: 'thank you',
        translationVi: 'Cảm ơn',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l1-3-s2',
      },
      {
        id: 'l1-3-v3',
        term: "you're welcome",
        translationVi: 'Không có gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l1-3-s2',
      },
      {
        id: 'l1-3-v4',
        term: 'excuse me',
        translationVi: 'Xin phép / xin lỗi (để hỏi)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l1-3-s1',
        usageNoteVi: "Dùng để xin phép hoặc gọi ai đó trước khi nói, khác với 'sorry'.",
      },
      {
        id: 'l1-3-v5',
        term: 'sorry',
        translationVi: 'Xin lỗi (khi mắc lỗi)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l1-3-s3',
        usageNoteVi: "Dùng khi bạn đã làm điều gì chưa đúng, khác với 'excuse me'.",
      },
      {
        id: 'l1-3-v6',
        term: 'no problem',
        translationVi: 'Không sao',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đáp lại thân mật khi ai đó cảm ơn hoặc xin lỗi bạn.',
      },
    ],
    sentences: [
      { id: 'l1-3-s1', text: 'Excuse me, where is the bathroom?', translationVi: 'Xin lỗi, nhà vệ sinh ở đâu ạ?' },
      { id: 'l1-3-s2', text: 'Thank you very much! — You\'re welcome.', translationVi: 'Cảm ơn bạn rất nhiều! — Không có gì.' },
      { id: 'l1-3-s3', text: "I'm sorry, I'm late.", translationVi: 'Xin lỗi, tôi đến muộn.' },
    ],
    exercises: [
      {
        id: 'l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Khi ai đó nói 'Thank you' với bạn, bạn đáp lại thế nào?",
        question: 'Thank you!',
        options: ['Sorry', "You're welcome", 'Goodbye', 'Please'],
        correctOptionIndex: 1,
      },
      {
        id: 'l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '___, where is the bathroom?',
        wordBank: ['Excuse me', 'Thank you', 'Goodbye'],
        correctAnswer: 'Excuse me',
      },
      {
        id: 'l1-3-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'please'.",
        question: 'please',
        options: ['Làm ơn', 'Cảm ơn', 'Xin lỗi', 'Tạm biệt'],
        correctOptionIndex: 0,
      },
    ],
  },
];
