import type { Lesson } from '../../types';

export const introductionsLessons: Lesson[] = [
  {
    id: 'l2-1-whats-your-name',
    unitId: 'u2-introductions',
    title: "What's your name?",
    titleVi: 'Tên của bạn là gì?',
    objectiveVi: "Hỏi tên người khác và giới thiệu tên của mình bằng câu 'My name is...'.",
    estimatedMinutes: 6,
    grammarNoteVi: "Dùng 'I am' + tên hoặc 'My name is' + tên để giới thiệu bản thân.",
    vocabulary: [
      { id: 'l2-1-v1', term: 'name', translationVi: 'Tên', partOfSpeech: 'noun', exampleSentenceId: 'l2-1-s2' },
      {
        id: 'l2-1-v2',
        term: "what's your name",
        translationVi: 'Tên bạn là gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l2-1-s1',
      },
      {
        id: 'l2-1-v3',
        term: 'my name is',
        translationVi: 'Tên tôi là',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l2-1-s2',
      },
      {
        id: 'l2-1-v4',
        term: 'nice to meet you',
        translationVi: 'Rất vui được gặp bạn',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l2-1-s2',
      },
      { id: 'l2-1-v5', term: 'I am', translationVi: 'Tôi là', partOfSpeech: 'phrase', exampleSentenceId: 'l2-1-s3' },
    ],
    sentences: [
      { id: 'l2-1-s1', text: "What's your name?", translationVi: 'Tên bạn là gì?' },
      {
        id: 'l2-1-s2',
        text: 'My name is Lan. Nice to meet you.',
        translationVi: 'Tên tôi là Lan. Rất vui được gặp bạn.',
      },
      { id: 'l2-1-s3', text: 'I am Minh.', translationVi: 'Tôi là Minh.' },
    ],
    exercises: [
      {
        id: 'l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Câu 'What's your name?' có nghĩa là gì?",
        question: "What's your name?",
        options: ['Bạn khỏe không?', 'Tên bạn là gì?', 'Bạn đến từ đâu?', 'Rất vui được gặp bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: 'My ___ is Lan.',
        wordBank: ['name', 'fine', 'please'],
        correctAnswer: 'name',
      },
      {
        id: 'l2-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng để giới thiệu tên của bạn là Minh.',
        question: 'Choose the correct sentence.',
        options: ['I name is Minh.', 'My name is Minh.', 'Name my is Minh.', 'Minh name is.'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'l2-2-where-are-you-from',
    unitId: 'u2-introductions',
    title: 'Where are you from?',
    titleVi: 'Bạn đến từ đâu?',
    objectiveVi: 'Nói được quốc gia của mình và hỏi người khác đến từ đâu.',
    estimatedMinutes: 6,
    grammarNoteVi: "Dùng 'from' + tên quốc gia để nói bạn đến từ đâu. Ví dụ: from Vietnam, from Japan.",
    vocabulary: [
      {
        id: 'l2-2-v1',
        term: 'where are you from',
        translationVi: 'Bạn đến từ đâu',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l2-2-s1',
      },
      {
        id: 'l2-2-v2',
        term: "I'm from",
        translationVi: 'Tôi đến từ',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l2-2-s2',
      },
      { id: 'l2-2-v3', term: 'Vietnam', translationVi: 'Việt Nam', partOfSpeech: 'noun', exampleSentenceId: 'l2-2-s2' },
      {
        id: 'l2-2-v4',
        term: 'country',
        translationVi: 'Quốc gia',
        partOfSpeech: 'noun',
        usageNoteVi: 'Danh từ chỉ một quốc gia nói chung.',
      },
      {
        id: 'l2-2-v5',
        term: 'Vietnamese',
        translationVi: 'Người Việt Nam',
        partOfSpeech: 'noun',
        exampleSentenceId: 'l2-2-s3',
      },
    ],
    sentences: [
      { id: 'l2-2-s1', text: 'Where are you from?', translationVi: 'Bạn đến từ đâu?' },
      { id: 'l2-2-s2', text: "I'm from Vietnam.", translationVi: 'Tôi đến từ Việt Nam.' },
      { id: 'l2-2-s3', text: 'I am Vietnamese.', translationVi: 'Tôi là người Việt Nam.' },
    ],
    exercises: [
      {
        id: 'l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'country'.",
        question: 'country',
        options: ['Thành phố', 'Quốc gia', 'Ngôn ngữ', 'Gia đình'],
        correctOptionIndex: 1,
      },
      {
        id: 'l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: "I'm ___ Vietnam.",
        wordBank: ['from', 'name', 'fine'],
        correctAnswer: 'from',
      },
      {
        id: 'l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi quê quán của ai đó.',
        question: 'Choose the correct question.',
        options: ["What's your name?", 'Where are you from?', 'How are you?', 'Thank you.'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'l2-3-age-job',
    unitId: 'u2-introductions',
    title: 'Age and occupation',
    titleVi: 'Tuổi và nghề nghiệp',
    objectiveVi: 'Nói được tuổi và nghề nghiệp của bản thân bằng các mẫu câu đơn giản.',
    estimatedMinutes: 6,
    grammarNoteVi: "Dùng 'I am a/an' + nghề nghiệp. Dùng 'an' trước nguyên âm, ví dụ: 'an engineer'.",
    vocabulary: [
      {
        id: 'l2-3-v1',
        term: 'how old are you',
        translationVi: 'Bạn bao nhiêu tuổi',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l2-3-s1',
      },
      {
        id: 'l2-3-v2',
        term: 'years old',
        translationVi: '... tuổi',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'l2-3-s2',
      },
      {
        id: 'l2-3-v3',
        term: 'student',
        translationVi: 'Học sinh / sinh viên',
        partOfSpeech: 'noun',
        exampleSentenceId: 'l2-3-s3',
      },
      { id: 'l2-3-v4', term: 'teacher', translationVi: 'Giáo viên', partOfSpeech: 'noun' },
      {
        id: 'l2-3-v5',
        term: 'engineer',
        translationVi: 'Kỹ sư',
        partOfSpeech: 'noun',
        usageNoteVi: "Dùng 'an engineer' vì 'engineer' bắt đầu bằng nguyên âm.",
      },
      { id: 'l2-3-v6', term: 'job', translationVi: 'Nghề nghiệp', partOfSpeech: 'noun' },
    ],
    sentences: [
      { id: 'l2-3-s1', text: 'How old are you?', translationVi: 'Bạn bao nhiêu tuổi?' },
      { id: 'l2-3-s2', text: 'I am twenty years old.', translationVi: 'Tôi hai mươi tuổi.' },
      { id: 'l2-3-s3', text: 'I am a student.', translationVi: 'Tôi là một sinh viên.' },
    ],
    exercises: [
      {
        id: 'l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'student'.",
        question: 'student',
        options: ['Giáo viên', 'Học sinh / sinh viên', 'Kỹ sư', 'Bác sĩ'],
        correctOptionIndex: 1,
      },
      {
        id: 'l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu (nghề nghiệp).',
        sentenceTemplate: 'I am a ___.',
        wordBank: ['teacher', 'from', 'fine'],
        correctAnswer: 'teacher',
      },
      {
        id: 'l2-3-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi tuổi của ai đó.',
        question: 'Choose the correct question.',
        options: ["What's your name?", 'How old are you?', 'Where are you from?', 'Nice to meet you.'],
        correctOptionIndex: 1,
      },
    ],
  },
];
