import type { Lesson } from '../../../types';

export const koreanB2ArgumentationLessons: Lesson[] = [
  {
    id: 'ko-b2-l2-1-lppunman-anira',
    unitId: 'ko-b2-u2-argumentation-contrast',
    title: '(으)ㄹ 뿐만 아니라',
    titleVi: 'Liệt kê bổ sung (으)ㄹ 뿐만 아니라',
    objectiveVi: "Liệt kê hai đặc điểm liên quan, ý sau bổ sung/nâng cao ý trước, bằng '(으)ㄹ 뿐만 아니라'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사/형용사 어간 + (으)ㄹ 뿐만 아니라: không chỉ A mà còn B, thường kèm 도 ở vế sau để nhấn mạnh thêm. Ví dụ: 맛있다 → 맛있을 뿐만 아니라.",
    vocabulary: [
      { id: 'ko-b2-l2-1-v1', term: '(으)ㄹ 뿐만 아니라', translationVi: 'Không chỉ...mà còn...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: (eu)l ppunman anira' },
      { id: 'ko-b2-l2-1-v2', term: '성실하다', translationVi: 'Chăm chỉ, tận tâm', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l2-1-s2', usageNoteVi: 'Cách đọc: seongsilhada' },
      { id: 'ko-b2-l2-1-v3', term: '서비스', translationVi: 'Dịch vụ', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-1-s1', usageNoteVi: 'Cách đọc: seobiseu' },
      { id: 'ko-b2-l2-1-v4', term: '해소하다', translationVi: 'Giải tỏa', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l2-1-s3', usageNoteVi: 'Cách đọc: haesohada' },
      { id: 'ko-b2-l2-1-v5', term: '도움이 되다', translationVi: 'Có ích, giúp ích', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l2-1-s3', usageNoteVi: 'Cách đọc: doumi doeda' },
      { id: 'ko-b2-l2-1-v6', term: '능력', translationVi: 'Năng lực', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: neungnyeok' },
      { id: 'ko-b2-l2-1-v7', term: '갖추다', translationVi: 'Trang bị, có đủ', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: gatchuda' },
      { id: 'ko-b2-l2-1-v8', term: '경쟁력', translationVi: 'Năng lực cạnh tranh', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: gyeongjaengnyeok' },
      { id: 'ko-b2-l2-1-v9', term: '품질', translationVi: 'Chất lượng', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-1-s4', usageNoteVi: 'Cách đọc: pumjil' },
      { id: 'ko-b2-l2-1-v10', term: '저렴하다', translationVi: 'Rẻ', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l2-1-s4', usageNoteVi: 'Cách đọc: jeoryeomhada' },
      { id: 'ko-b2-l2-1-v11', term: '다양하다', translationVi: 'Đa dạng', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l2-1-s5', usageNoteVi: 'Cách đọc: dayanghada' },
      { id: 'ko-b2-l2-1-v12', term: '만족도', translationVi: 'Mức độ hài lòng', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-1-s5', usageNoteVi: 'Cách đọc: manjokdo' },
      { id: 'ko-b2-l2-1-v13', term: '신뢰하다', translationVi: 'Tin tưởng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: sillroehada' },
    ],
    sentences: [
      { id: 'ko-b2-l2-1-s1', text: '이 식당은 음식이 맛있을 뿐만 아니라 서비스도 좋아요.', translationVi: '(i sikdangeun eumsigi masisseul ppunman anira seobiseudo joayo.) Nhà hàng này không chỉ ngon mà dịch vụ cũng tốt.' },
      { id: 'ko-b2-l2-1-s2', text: '그는 똑똑할 뿐만 아니라 성실해요.', translationVi: '(geuneun ttokttokhal ppunman anira seongsilhaeyo.) Anh ấy không chỉ thông minh mà còn chăm chỉ.' },
      { id: 'ko-b2-l2-1-s3', text: '운동은 건강에 좋을 뿐만 아니라 스트레스 해소에도 도움이 돼요.', translationVi: '(undongeun geongange joeul ppunman anira seuteureseu haesoedo doumi dwaeyo.) Tập thể dục không chỉ tốt cho sức khỏe mà còn giúp giải tỏa căng thẳng.' },
      { id: 'ko-b2-l2-1-s4', text: '이 제품은 품질이 좋을 뿐만 아니라 가격도 저렴해요.', translationVi: '(i jepumeun pumjiri joeul ppunman anira gagyeokdo jeoryeomhaeyo.) Sản phẩm này không chỉ chất lượng tốt mà giá cũng rẻ.' },
      { id: 'ko-b2-l2-1-s5', text: '그 회사는 다양한 서비스를 제공할 뿐만 아니라 고객 만족도도 높아요.', translationVi: '(geu hoesaneun dayanghan seobiseureul jegonghal ppunman anira gogaek manjokdodo nopayo.) Công ty đó không chỉ cung cấp dịch vụ đa dạng mà mức độ hài lòng của khách hàng cũng cao.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '그는 똑똑___ 성실해요.',
        options: ['할 뿐만 아니라', '하는 바람에', '할수록', '하더라도'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '이 제품은 품질이 좋___ 가격도 저렴해요.',
        wordBank: ['을 뿐만 아니라', '기 때문에', '는데'],
        correctAnswer: '을 뿐만 아니라',
      },
      {
        id: 'ko-b2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Nhà hàng này không chỉ ngon mà dịch vụ cũng tốt."',
        words: ['서비스도 좋아요', '이 식당은', '음식이 맛있을 뿐만 아니라'],
        correctOrder: ['이 식당은', '음식이 맛있을 뿐만 아니라', '서비스도 좋아요'],
      },
    ],
  },
  {
    id: 'ko-b2-l2-2-neun-banmyeone',
    unitId: 'ko-b2-u2-argumentation-contrast',
    title: '는 반면에',
    titleVi: 'Đối lập nâng cao 는 반면에',
    objectiveVi: "So sánh hai mặt đối lập của cùng một vấn đề bằng '는/(으)ㄴ 반면에', trang trọng và rõ ràng hơn 지만.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사 + 는 반면에, 형용사 + (으)ㄴ 반면에: diễn tả sự tương phản giữa hai vế, trang trọng và rõ ràng hơn 지만/는데, thường dùng để so sánh 2 mặt (ưu điểm/nhược điểm) của cùng một vấn đề.",
    vocabulary: [
      { id: 'ko-b2-l2-2-v1', term: '는/(으)ㄴ 반면에', translationVi: 'Mặt khác, trái lại', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: neun/(eu)n banmyeone' },
      { id: 'ko-b2-l2-2-v2', term: '월급', translationVi: 'Lương tháng', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-2-s1', usageNoteVi: 'Cách đọc: wolgeup' },
      { id: 'ko-b2-l2-2-v3', term: '빈부격차', translationVi: 'Khoảng cách giàu nghèo', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-2-s2', usageNoteVi: 'Cách đọc: binbugyeokcha' },
      { id: 'ko-b2-l2-2-v4', term: '경제가 발전하다', translationVi: 'Kinh tế phát triển', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l2-2-s2', usageNoteVi: 'Cách đọc: gyeongjega baljeonhada' },
      { id: 'ko-b2-l2-2-v5', term: '집중하다', translationVi: 'Tập trung', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l2-2-s3', usageNoteVi: 'Cách đọc: jipjunghada' },
      { id: 'ko-b2-l2-2-v6', term: '장점', translationVi: 'Ưu điểm', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: jangjeom' },
      { id: 'ko-b2-l2-2-v7', term: '단점', translationVi: 'Nhược điểm', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: danjeom' },
      { id: 'ko-b2-l2-2-v8', term: '편리하다', translationVi: 'Tiện lợi', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l2-2-s3', usageNoteVi: 'Cách đọc: pyeollihada' },
      { id: 'ko-b2-l2-2-v9', term: '안정적이다', translationVi: 'Ổn định', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: anjeongjeogida' },
      { id: 'ko-b2-l2-2-v10', term: '불안정하다', translationVi: 'Bất ổn', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l2-2-s4', usageNoteVi: 'Cách đọc: buranjeonghada' },
      { id: 'ko-b2-l2-2-v11', term: '자유롭다', translationVi: 'Tự do', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l2-2-s4', usageNoteVi: 'Cách đọc: jayuropda' },
      { id: 'ko-b2-l2-2-v12', term: '책임감', translationVi: 'Trách nhiệm', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-2-s5', usageNoteVi: 'Cách đọc: chaegimgam' },
      { id: 'ko-b2-l2-2-v13', term: '보람', translationVi: 'Sự ý nghĩa, niềm vui khi làm được việc có ích', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-2-s5', usageNoteVi: 'Cách đọc: boram' },
    ],
    sentences: [
      { id: 'ko-b2-l2-2-s1', text: '이 일은 월급이 높은 반면에 스트레스도 많아요.', translationVi: '(i ireun wolgeubi nopeun banmyeone seuteureseudo manayo.) Công việc này lương cao, mặt khác căng thẳng cũng nhiều.' },
      { id: 'ko-b2-l2-2-s2', text: '그 나라는 경제가 발전한 반면에 빈부격차가 심해요.', translationVi: '(geu nawaneun gyeongjega baljeonhan banmyeone binbugyeokchaga simhaeyo.) Đất nước đó kinh tế phát triển, nhưng trái lại khoảng cách giàu nghèo lại nghiêm trọng.' },
      { id: 'ko-b2-l2-2-s3', text: '온라인 수업은 편리한 반면에 집중하기 어려워요.', translationVi: '(ollain sueobeun pyeollihan banmyeone jipjunghagi eoryeowoyo.) Học trực tuyến tiện lợi, nhưng mặt khác lại khó tập trung.' },
      { id: 'ko-b2-l2-2-s4', text: '프리랜서는 시간이 자유로운 반면에 수입이 불안정해요.', translationVi: '(peurilraenseoneun sigani jayuroun banmyeone suibi buranjeonghaeyo.) Người làm tự do có thời gian tự do, nhưng mặt khác thu nhập lại bất ổn.' },
      { id: 'ko-b2-l2-2-s5', text: '이 직업은 책임감이 필요한 반면에 보람도 커요.', translationVi: '(i jigeobeun chaegimgami piryohan banmyeone boramdo keoyo.) Nghề này cần trách nhiệm, nhưng mặt khác cũng rất ý nghĩa.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '이 일은 월급이 ___ 스트레스도 많아요.',
        options: ['높은 반면에', '높을 뿐만 아니라', '높기 마련이에요', '높더라도'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '온라인 수업은 편리___ 집중하기 어려워요.',
        wordBank: ['한 반면에', '해서', '하지만'],
        correctAnswer: '한 반면에',
      },
      {
        id: 'ko-b2-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Người làm tự do có thời gian tự do, nhưng thu nhập bất ổn."',
        words: ['수입이 불안정해요', '시간이 자유로운 반면에', '프리랜서는'],
        correctOrder: ['프리랜서는', '시간이 자유로운 반면에', '수입이 불안정해요'],
      },
    ],
  },
  {
    id: 'ko-b2-l2-3-deorado',
    unitId: 'ko-b2-u2-argumentation-contrast',
    title: '더라도',
    titleVi: 'Nhượng bộ giả định 더라도',
    objectiveVi: "Diễn tả một tình huống giả định cực đoan nhưng kết quả không thay đổi bằng '더라도' — mạnh hơn 아/어도.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "동사/형용사 어간 + 더라도: dù có...đi chăng nữa, giả định một tình huống khó khăn/cực đoan nhưng kết quả/quyết định không thay đổi. Thường đi cùng 아무리 (dù có...đến đâu). Mạnh và trang trọng hơn 아/어도.",
    vocabulary: [
      { id: 'ko-b2-l2-3-v1', term: '더라도', translationVi: 'Dù có...đi nữa', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: deorado' },
      { id: 'ko-b2-l2-3-v2', term: '아무리', translationVi: 'Dù có...đến đâu', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l2-3-s1', usageNoteVi: 'Cách đọc: amuri' },
      { id: 'ko-b2-l2-3-v3', term: '챙기다', translationVi: 'Lo liệu, chuẩn bị chu đáo', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l2-3-s1', usageNoteVi: 'Cách đọc: chaenggida' },
      { id: 'ko-b2-l2-3-v4', term: '포기하다', translationVi: 'Từ bỏ', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l2-3-s2', usageNoteVi: 'Cách đọc: pogihada' },
      { id: 'ko-b2-l2-3-v5', term: '실패하다', translationVi: 'Thất bại', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l2-3-s2', usageNoteVi: 'Cách đọc: silpaehada' },
      { id: 'ko-b2-l2-3-v6', term: '최선을 다하다', translationVi: 'Cố gắng hết sức', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l2-3-s4', usageNoteVi: 'Cách đọc: choeseoneul dahada' },
      { id: 'ko-b2-l2-3-v7', term: '견디다', translationVi: 'Chịu đựng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: gyeondida' },
      { id: 'ko-b2-l2-3-v8', term: '극복하다', translationVi: 'Vượt qua, khắc phục', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: geukbokhada' },
      { id: 'ko-b2-l2-3-v9', term: '상황', translationVi: 'Tình huống', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l2-3-s5', usageNoteVi: 'Cách đọc: sanghwang' },
      { id: 'ko-b2-l2-3-v10', term: '어떤 일이 있어도', translationVi: 'Dù có chuyện gì xảy ra đi nữa', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: eotteon iri isseodo' },
      { id: 'ko-b2-l2-3-v11', term: '후회하다', translationVi: 'Hối hận', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l2-3-s5', usageNoteVi: 'Cách đọc: huhoehada' },
      { id: 'ko-b2-l2-3-v12', term: '도전하다', translationVi: 'Thử sức, thử thách', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: dojeonhada' },
      { id: 'ko-b2-l2-3-v13', term: '행복하다', translationVi: 'Hạnh phúc', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l2-3-s3', usageNoteVi: 'Cách đọc: haengbokhada' },
    ],
    sentences: [
      { id: 'ko-b2-l2-3-s1', text: '아무리 바쁘더라도 밥은 챙겨 먹어야 해요.', translationVi: '(amuri bappeudeorado babeun chaenggyeo meogeoya haeyo.) Dù có bận đến đâu đi nữa thì cũng phải ăn uống đầy đủ.' },
      { id: 'ko-b2-l2-3-s2', text: '실패하더라도 포기하지 않을 거예요.', translationVi: '(silpaehadeorado pogihaji aneul geoyeyo.) Dù có thất bại đi nữa thì tôi cũng sẽ không bỏ cuộc.' },
      { id: 'ko-b2-l2-3-s3', text: '돈이 많더라도 행복하지 않을 수도 있어요.', translationVi: '(doni manteorado haengbokhaji aneul sudo isseoyo.) Dù có nhiều tiền đi nữa thì cũng có thể không hạnh phúc.' },
      { id: 'ko-b2-l2-3-s4', text: '힘들더라도 최선을 다할 거예요.', translationVi: '(himdeuldeorado choeseoneul dahal geoyeyo.) Dù có vất vả đi nữa thì tôi cũng sẽ cố gắng hết sức.' },
      { id: 'ko-b2-l2-3-s5', text: '어떤 상황이 오더라도 저는 후회하지 않을 거예요.', translationVi: '(eotteon sanghwangi odeorado jeoneun huhoehaji aneul geoyeyo.) Dù có tình huống nào xảy ra đi nữa thì tôi cũng sẽ không hối hận.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '아무리 ___ 밥은 챙겨 먹어야 해요.',
        options: ['바쁘더라도', '바쁜 반면에', '바쁠 뿐만 아니라', '바쁠수록'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '실패___ 포기하지 않을 거예요.',
        wordBank: ['하더라도', '하는 바람에', '하기 마련이라서'],
        correctAnswer: '하더라도',
      },
      {
        id: 'ko-b2-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Dù có nhiều tiền đi nữa thì cũng có thể không hạnh phúc."',
        words: ['행복하지 않을 수도 있어요', '돈이', '많더라도'],
        correctOrder: ['돈이', '많더라도', '행복하지 않을 수도 있어요'],
      },
    ],
  },
];
