import type { Lesson } from '../../../types';

export const koreanB2CauseEffectLessons: Lesson[] = [
  {
    id: 'ko-b2-l1-1-neun-barame',
    unitId: 'ko-b2-u1-cause-effect',
    title: '는 바람에',
    titleVi: 'Nguyên nhân ngoài ý muốn 는 바람에',
    objectiveVi: "Diễn tả nguyên nhân bất ngờ, ngoài ý muốn dẫn đến kết quả tiêu cực bằng '는 바람에'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "동사 + 는 바람에 diễn tả nguyên nhân bất ngờ/ngoài ý muốn dẫn đến kết quả TIÊU CỰC, không dùng cho kết quả tích cực hoặc ở tương lai. Trung tính và trang trọng hơn: 기 때문에. Ví dụ: 늦잠을 자다 → 늦잠을 자는 바람에.",
    vocabulary: [
      { id: 'ko-b2-l1-1-v1', term: '는 바람에', translationVi: 'Vì (nguyên nhân ngoài ý muốn dẫn đến kết quả xấu)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: neun barame' },
      { id: 'ko-b2-l1-1-v2', term: '늦잠을 자다', translationVi: 'Ngủ quên', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l1-1-s2', usageNoteVi: 'Cách đọc: neutjameul jada' },
      { id: 'ko-b2-l1-1-v3', term: '놓치다', translationVi: 'Lỡ, bỏ lỡ', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-1-s3', usageNoteVi: 'Cách đọc: notchida' },
      { id: 'ko-b2-l1-1-v4', term: '젖다', translationVi: 'Bị ướt', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-1-s1', usageNoteVi: 'Cách đọc: jeotda' },
      { id: 'ko-b2-l1-1-v5', term: '갑자기', translationVi: 'Đột nhiên', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: gapjagi' },
      { id: 'ko-b2-l1-1-v6', term: '고장 나다', translationVi: 'Bị hỏng (máy móc)', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l1-1-s4', usageNoteVi: 'Cách đọc: gojang nada' },
      { id: 'ko-b2-l1-1-v7', term: '넘어지다', translationVi: 'Bị ngã', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: neomeojida' },
      { id: 'ko-b2-l1-1-v8', term: '다치다', translationVi: 'Bị thương', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: dachida' },
      { id: 'ko-b2-l1-1-v9', term: '정전되다', translationVi: 'Bị mất điện', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-1-s5', usageNoteVi: 'Cách đọc: jeongjeondoeda' },
      { id: 'ko-b2-l1-1-v10', term: '실수로', translationVi: 'Do sơ suất', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: silsuro' },
      { id: 'ko-b2-l1-1-v11', term: '예상치 못하게', translationVi: 'Ngoài dự đoán', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: yesangchi mothage' },
      { id: 'ko-b2-l1-1-v12', term: '사고가 나다', translationVi: 'Xảy ra tai nạn', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: sagoga nada' },
      { id: 'ko-b2-l1-1-v13', term: '헤매다', translationVi: 'Lạc đường, loay hoay', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: hemaeda' },
    ],
    sentences: [
      { id: 'ko-b2-l1-1-s1', text: '갑자기 비가 오는 바람에 우산도 없이 다 젖었어요.', translationVi: '(gapjagi biga oneun barame usando eopsi da jeojeosseoyo.) Vì trời đột nhiên đổ mưa nên tôi bị ướt hết vì không có ô.' },
      { id: 'ko-b2-l1-1-s2', text: '늦잠을 자는 바람에 회의에 늦었어요.', translationVi: '(neutjameul janeun barame hoeuie neujeosseoyo.) Vì ngủ quên nên tôi đã đến trễ cuộc họp.' },
      { id: 'ko-b2-l1-1-s3', text: '길이 막히는 바람에 비행기를 놓쳤어요.', translationVi: '(giri makhineun barame bihaenggireul notchyeosseoyo.) Vì kẹt xe nên tôi đã lỡ chuyến bay.' },
      { id: 'ko-b2-l1-1-s4', text: '컴퓨터가 고장 나는 바람에 일을 다시 해야 했어요.', translationVi: '(keompyuteoga gojang naneun barame ireul dasi haeya haesseoyo.) Vì máy tính bị hỏng nên tôi đã phải làm lại công việc.' },
      { id: 'ko-b2-l1-1-s5', text: '갑자기 정전되는 바람에 아무것도 할 수 없었어요.', translationVi: '(gapjagi jeongjeondoeneun barame amugeotdo hal su eopseosseoyo.) Vì đột nhiên mất điện nên tôi không thể làm được gì cả.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng cho nguyên nhân ngoài ý muốn dẫn đến kết quả xấu.",
        question: '늦잠을 ___ 회의에 늦었어요.',
        options: ['자는 바람에', '자기 때문에', '자서', '자지만'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '길이 막히___ 비행기를 놓쳤어요.',
        wordBank: ['는 바람에', '기 때문에', '지만'],
        correctAnswer: '는 바람에',
      },
      {
        id: 'ko-b2-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì trời đột nhiên đổ mưa nên tôi bị ướt hết."',
        words: ['다 젖었어요', '갑자기 비가', '오는 바람에'],
        correctOrder: ['갑자기 비가', '오는 바람에', '다 젖었어요'],
      },
    ],
  },
  {
    id: 'ko-b2-l1-2-gi-maryeonida',
    unitId: 'ko-b2-u1-cause-effect',
    title: '기 마련이다',
    titleVi: 'Quy luật tất yếu 기 마련이다',
    objectiveVi: "Diễn tả một điều gì đó tất yếu, đương nhiên xảy ra theo quy luật chung bằng '기 마련이다'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사/형용사 어간 + 기 마련이다 diễn tả điều tất yếu, đương nhiên xảy ra theo lẽ tự nhiên hoặc quy luật chung — thường dùng khi nói về chân lý, quy luật cuộc sống. Ví dụ: 실수하다 → 실수하기 마련이다.",
    vocabulary: [
      { id: 'ko-b2-l1-2-v1', term: '기 마련이다', translationVi: 'Tất yếu là, đương nhiên là', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: gi maryeonida' },
      { id: 'ko-b2-l1-2-v2', term: '누구나', translationVi: 'Bất kỳ ai', partOfSpeech: 'pronoun', exampleSentenceId: 'ko-b2-l1-2-s1', usageNoteVi: 'Cách đọc: nuguna' },
      { id: 'ko-b2-l1-2-v3', term: '잊히다', translationVi: 'Bị lãng quên', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-2-s2', usageNoteVi: 'Cách đọc: itchida' },
      { id: 'ko-b2-l1-2-v4', term: '진리', translationVi: 'Chân lý', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: jilli' },
      { id: 'ko-b2-l1-2-v5', term: '자연스럽다', translationVi: 'Tự nhiên', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: jayeonseureopda' },
      { id: 'ko-b2-l1-2-v6', term: '세월이 지나다', translationVi: 'Thời gian trôi qua', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l1-2-s5', usageNoteVi: 'Cách đọc: seworo jinada' },
      { id: 'ko-b2-l1-2-v7', term: '인생', translationVi: 'Cuộc đời, đời người', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l1-2-s4', usageNoteVi: 'Cách đọc: insaeng' },
      { id: 'ko-b2-l1-2-v8', term: '변하다', translationVi: 'Thay đổi', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: byeonhada' },
      { id: 'ko-b2-l1-2-v9', term: '노력하다', translationVi: 'Nỗ lực', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-2-s3', usageNoteVi: 'Cách đọc: noryeokhada' },
      { id: 'ko-b2-l1-2-v10', term: '성장하다', translationVi: 'Trưởng thành, phát triển', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: seongjanghada' },
      { id: 'ko-b2-l1-2-v11', term: '반복되다', translationVi: 'Lặp đi lặp lại', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: banbokdoeda' },
      { id: 'ko-b2-l1-2-v12', term: '당연하다', translationVi: 'Đương nhiên, hiển nhiên', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: dangyeonhada' },
      { id: 'ko-b2-l1-2-v13', term: '겪다', translationVi: 'Trải qua', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-2-s4', usageNoteVi: 'Cách đọc: gyeokda' },
    ],
    sentences: [
      { id: 'ko-b2-l1-2-s1', text: '사람은 누구나 실수하기 마련이에요.', translationVi: '(sarameun nuguna silsuhagi maryeonieyo.) Con người ai cũng tất yếu sẽ mắc sai lầm.' },
      { id: 'ko-b2-l1-2-s2', text: '시간이 지나면 잊히기 마련이에요.', translationVi: '(sigani jinamyeon itchigi maryeonieyo.) Thời gian trôi qua thì tất yếu sẽ bị lãng quên.' },
      { id: 'ko-b2-l1-2-s3', text: '노력하면 좋은 결과가 있기 마련이에요.', translationVi: '(noryeokhamyeon joeun gyeolgwaga itgi maryeonieyo.) Nếu nỗ lực thì tất yếu sẽ có kết quả tốt.' },
      { id: 'ko-b2-l1-2-s4', text: '인생을 살다 보면 힘든 일을 겪기 마련이에요.', translationVi: '(insaengeul salda bomyeon himdeun ireul gyeokgi maryeonieyo.) Sống ở đời thì tất yếu sẽ trải qua những chuyện khó khăn.' },
      { id: 'ko-b2-l1-2-s5', text: '세월이 지나면 사람도 변하기 마련이에요.', translationVi: '(seworo jinamyeon saramdo byeonhagi maryeonieyo.) Thời gian trôi qua thì con người cũng tất yếu sẽ thay đổi.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng cho quy luật tất yếu.',
        question: '사람은 누구나 ___.',
        options: ['실수하기 마련이에요', '실수하는 바람에', '실수할 뿐만 아니라', '실수하는 반면에'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '노력하면 좋은 결과가 ___.',
        wordBank: ['있기 마련이에요', '있는 바람에', '있더라도'],
        correctAnswer: '있기 마련이에요',
      },
      {
        id: 'ko-b2-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Thời gian trôi qua thì tất yếu sẽ bị lãng quên."',
        words: ['잊히기 마련이에요', '시간이', '지나면'],
        correctOrder: ['시간이', '지나면', '잊히기 마련이에요'],
      },
    ],
  },
  {
    id: 'ko-b2-l1-3-lsurok',
    unitId: 'ko-b2-u1-cause-effect',
    title: '(으)ㄹ수록',
    titleVi: 'Tương quan tăng dần (으)ㄹ수록',
    objectiveVi: "Diễn tả mối tương quan tăng dần: điều gì càng tăng thì điều khác cũng tăng theo, bằng '(으)ㄹ수록'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사/형용사 어간 + (으)ㄹ수록 diễn tả mối tương quan tăng dần: càng A thì càng B. Có thể kết hợp với (으)면 để nhấn mạnh: (으)면 (으)ㄹ수록. Ví dụ: 연습하다 → 연습할수록.",
    vocabulary: [
      { id: 'ko-b2-l1-3-v1', term: '(으)ㄹ수록', translationVi: 'Càng...càng...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: (eu)lsurok' },
      { id: 'ko-b2-l1-3-v2', term: '늘다', translationVi: 'Tăng lên, tiến bộ', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-3-s1', usageNoteVi: 'Cách đọc: neulda' },
      { id: 'ko-b2-l1-3-v3', term: '실력', translationVi: 'Thực lực, trình độ', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l1-3-s1', usageNoteVi: 'Cách đọc: sillyeok' },
      { id: 'ko-b2-l1-3-v4', term: '나이가 들다', translationVi: 'Lớn tuổi', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l1-3-s2', usageNoteVi: 'Cách đọc: naiga deulda' },
      { id: 'ko-b2-l1-3-v5', term: '중요해지다', translationVi: 'Trở nên quan trọng', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l1-3-s2', usageNoteVi: 'Cách đọc: jungyohaejida' },
      { id: 'ko-b2-l1-3-v6', term: '이상하다', translationVi: 'Kỳ lạ', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l1-3-s3', usageNoteVi: 'Cách đọc: isanghada' },
      { id: 'ko-b2-l1-3-v7', term: '심해지다', translationVi: 'Trở nên nghiêm trọng hơn', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-3-s4', usageNoteVi: 'Cách đọc: simhaejida' },
      { id: 'ko-b2-l1-3-v8', term: '편해지다', translationVi: 'Trở nên thoải mái hơn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: pyeonhaejida' },
      { id: 'ko-b2-l1-3-v9', term: '익숙해지다', translationVi: 'Trở nên quen thuộc', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: iksukhaejida' },
      { id: 'ko-b2-l1-3-v10', term: '쌓이다', translationVi: 'Tích lũy, chồng chất', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: ssahida' },
      { id: 'ko-b2-l1-3-v11', term: '스트레스', translationVi: 'Căng thẳng', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l1-3-s4', usageNoteVi: 'Cách đọc: seuteureseu' },
      { id: 'ko-b2-l1-3-v12', term: '관계', translationVi: 'Mối quan hệ', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l1-3-s5', usageNoteVi: 'Cách đọc: gwangye' },
      { id: 'ko-b2-l1-3-v13', term: '깊어지다', translationVi: 'Trở nên sâu sắc hơn', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l1-3-s5', usageNoteVi: 'Cách đọc: gipeojida' },
    ],
    sentences: [
      { id: 'ko-b2-l1-3-s1', text: '연습할수록 실력이 늘어요.', translationVi: '(yeonseuphalsurok sillyeogi neureoyo.) Càng luyện tập thì trình độ càng tiến bộ.' },
      { id: 'ko-b2-l1-3-s2', text: '나이가 들수록 건강이 중요해져요.', translationVi: '(naiga deulsurok geongangi jungyohaejyeoyo.) Càng lớn tuổi thì sức khỏe càng trở nên quan trọng.' },
      { id: 'ko-b2-l1-3-s3', text: '생각하면 생각할수록 이상해요.', translationVi: '(saenggakhamyeon saenggakhalsurok isanghaeyo.) Càng nghĩ thì càng thấy lạ.' },
      { id: 'ko-b2-l1-3-s4', text: '시간이 지날수록 스트레스가 심해져요.', translationVi: '(sigani jinalsurok seuteureseuga simhaejyeoyo.) Thời gian càng trôi qua thì căng thẳng càng nghiêm trọng hơn.' },
      { id: 'ko-b2-l1-3-s5', text: '만날수록 관계가 깊어져요.', translationVi: '(mannalsurok gwangyega gipeojyeoyo.) Càng gặp nhau thì mối quan hệ càng trở nên sâu sắc.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '연습___ 실력이 늘어요.',
        options: ['할수록', '하는 바람에', '하기 마련이에요', '하더라도'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '나이가 ___ 건강이 중요해져요.',
        wordBank: ['들수록', '드는 바람에', '들 뿐만 아니라'],
        correctAnswer: '들수록',
      },
      {
        id: 'ko-b2-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Càng nghĩ thì càng thấy lạ."',
        words: ['이상해요', '생각하면', '생각할수록'],
        correctOrder: ['생각하면', '생각할수록', '이상해요'],
      },
    ],
  },
];
