import type { Lesson } from '../../../types';

export const koreanB2FormalLessons: Lesson[] = [
  {
    id: 'ko-b2-l3-1-humble-verbs',
    unitId: 'ko-b2-u3-formal-expression',
    title: '드리다 / 여쭤보다',
    titleVi: 'Khiêm nhường ngữ trong giao tiếp công sở',
    objectiveVi: "Dùng động từ khiêm nhường ('드리다', '여쭤보다', '말씀드리다') khi nói về hành động của chính mình hướng đến người lớn tuổi/cấp trên.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "Khiêm nhường ngữ dùng cho hành động của CHÍNH NGƯỜI NÓI để hạ thấp bản thân, nâng cao đối phương — khác với kính ngữ chủ ngữ -(으)시- (dùng cho hành động của người khác). 주다→드리다 (biếu, đưa cho), 묻다→여쭤보다 (hỏi), 말하다→말씀드리다 (thưa, nói), 보다→뵙다 (gặp).",
    vocabulary: [
      { id: 'ko-b2-l3-1-v1', term: '드리다', translationVi: 'Biếu, tặng, đưa cho (khiêm nhường của 주다)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l3-1-s1', usageNoteVi: 'Cách đọc: deurida' },
      { id: 'ko-b2-l3-1-v2', term: '여쭤보다', translationVi: 'Hỏi (khiêm nhường của 묻다)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l3-1-s2', usageNoteVi: 'Cách đọc: yeojjwoboda' },
      { id: 'ko-b2-l3-1-v3', term: '말씀드리다', translationVi: 'Thưa, nói (khiêm nhường của 말하다)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l3-1-s3', usageNoteVi: 'Cách đọc: malsseumdeurida' },
      { id: 'ko-b2-l3-1-v4', term: '모시다', translationVi: 'Hầu, đưa đi cùng (khiêm nhường)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l3-1-s4', usageNoteVi: 'Cách đọc: mosida' },
      { id: 'ko-b2-l3-1-v5', term: '부장님', translationVi: 'Trưởng phòng', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: bujangnim' },
      { id: 'ko-b2-l3-1-v6', term: '보고하다', translationVi: 'Báo cáo', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: bogohada' },
      { id: 'ko-b2-l3-1-v7', term: '상사', translationVi: 'Cấp trên', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: sangsa' },
      { id: 'ko-b2-l3-1-v8', term: '존중하다', translationVi: 'Tôn trọng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: jonjunghada' },
      { id: 'ko-b2-l3-1-v9', term: '예의', translationVi: 'Phép lịch sự, lễ nghĩa', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: yeui' },
      { id: 'ko-b2-l3-1-v10', term: '겸손하다', translationVi: 'Khiêm tốn', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: gyeomsonhada' },
      { id: 'ko-b2-l3-1-v11', term: '부탁드리다', translationVi: 'Nhờ vả (khiêm nhường, trang trọng)', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: butakdeurida' },
      { id: 'ko-b2-l3-1-v12', term: '감사드리다', translationVi: 'Cảm ơn (khiêm nhường, trang trọng)', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l3-1-s5', usageNoteVi: 'Cách đọc: gamsadeurida' },
      { id: 'ko-b2-l3-1-v13', term: '자세', translationVi: 'Thái độ, tư thế', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: jase' },
    ],
    sentences: [
      { id: 'ko-b2-l3-1-s1', text: '선생님께 선물을 드렸어요.', translationVi: '(seonsaengnimkke seonmureul deuryeosseoyo.) Tôi đã tặng quà cho thầy/cô.' },
      { id: 'ko-b2-l3-1-s2', text: '사장님께 여쭤보고 싶은 것이 있어요.', translationVi: '(sajangnimkke yeojjwobogo sipeun geosi isseoyo.) Tôi có điều muốn hỏi giám đốc.' },
      { id: 'ko-b2-l3-1-s3', text: '부장님께 말씀드릴 게 있습니다.', translationVi: '(bujangnimkke malsseumdeuril ge isseumnida.) Tôi có điều muốn thưa với trưởng phòng.' },
      { id: 'ko-b2-l3-1-s4', text: '어르신을 모시고 병원에 다녀왔어요.', translationVi: '(eoreusineul mosigo byeongwone danyeowasseoyo.) Tôi đã đưa người lớn tuổi đến bệnh viện.' },
      { id: 'ko-b2-l3-1-s5', text: '도와주셔서 감사드립니다.', translationVi: '(dowajusyeoseo gamsadeurimnida.) Cảm ơn anh/chị đã giúp đỡ.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng khiêm nhường đúng của '주다' khi tặng quà cho thầy/cô.",
        question: '선생님께 선물을 ___.',
        options: ['드렸어요', '줬어요', '주셨어요', '드셨어요'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l3-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng khiêm nhường đúng của '묻다'.",
        sentenceTemplate: '사장님께 ___ 싶은 것이 있어요.',
        wordBank: ['여쭤보고', '물어보고', '여쭈시고'],
        correctAnswer: '여쭤보고',
      },
      {
        id: 'ko-b2-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi có điều muốn thưa với trưởng phòng."',
        words: ['있습니다', '부장님께', '말씀드릴 게'],
        correctOrder: ['부장님께', '말씀드릴 게', '있습니다'],
      },
    ],
  },
  {
    id: 'ko-b2-l3-2-neun-semida',
    unitId: 'ko-b2-u3-formal-expression',
    title: '는 셈이다',
    titleVi: 'Tổng kết ý kiến 는 셈이다',
    objectiveVi: "Tổng kết một tình huống phức tạp thành một nhận định đơn giản bằng '는/(으)ㄴ 셈이다' (coi như là...).",
    estimatedMinutes: 8,
    grammarNoteVi:
      "동사 + 는 셈이다, 형용사/명사 + (으)ㄴ/인 셈이다: diễn tả một kết luận/đánh giá tổng quát dựa trên tình huống thực tế, nghĩa gần với 'coi như là, kể như là'. Thường dùng khi tổng kết một tình huống phức tạp thành một nhận định đơn giản.",
    vocabulary: [
      { id: 'ko-b2-l3-2-v1', term: '는/(으)ㄴ 셈이다', translationVi: 'Coi như là, kể như là', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: neun/(eu)n semida' },
      { id: 'ko-b2-l3-2-v2', term: '거의', translationVi: 'Gần như, hầu như', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l3-2-s1', usageNoteVi: 'Cách đọc: geoui' },
      { id: 'ko-b2-l3-2-v3', term: '모으다', translationVi: 'Tích góp, dành dụm', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l3-2-s2', usageNoteVi: 'Cách đọc: moeuda' },
      { id: 'ko-b2-l3-2-v4', term: '결론적으로', translationVi: 'Kết luận là', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: gyeollonjeogeuro' },
      { id: 'ko-b2-l3-2-v5', term: '전체적으로', translationVi: 'Nhìn chung', partOfSpeech: 'phrase', exampleSentenceId: 'ko-b2-l3-2-s5', usageNoteVi: 'Cách đọc: jeonchejeogeuro' },
      { id: 'ko-b2-l3-2-v6', term: '평가하다', translationVi: 'Đánh giá', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: pyeonggahada' },
      { id: 'ko-b2-l3-2-v7', term: '성공적이다', translationVi: 'Thành công', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l3-2-s4', usageNoteVi: 'Cách đọc: seonggongjeogida' },
      { id: 'ko-b2-l3-2-v8', term: '만족스럽다', translationVi: 'Thỏa mãn, hài lòng', partOfSpeech: 'adjective', exampleSentenceId: 'ko-b2-l3-2-s5', usageNoteVi: 'Cách đọc: manjokseureopda' },
      { id: 'ko-b2-l3-2-v9', term: '따지다', translationVi: 'Tính toán, xét kỹ', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: ttajida' },
      { id: 'ko-b2-l3-2-v10', term: '결과적으로', translationVi: 'Kết quả là', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: gyeolgwajeogeuro' },
      { id: 'ko-b2-l3-2-v11', term: '감안하다', translationVi: 'Xét đến, cân nhắc', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: gamanhada' },
      { id: 'ko-b2-l3-2-v12', term: '도달하다', translationVi: 'Đạt đến', partOfSpeech: 'verb', exampleSentenceId: 'ko-b2-l3-2-s4', usageNoteVi: 'Cách đọc: dodalhada' },
      { id: 'ko-b2-l3-2-v13', term: '가족', translationVi: 'Gia đình', partOfSpeech: 'noun', exampleSentenceId: 'ko-b2-l3-2-s3', usageNoteVi: 'Cách đọc: gajok' },
    ],
    sentences: [
      { id: 'ko-b2-l3-2-s1', text: '거의 다 끝났으니까 일은 끝난 셈이에요.', translationVi: '(geoui da kkeunnasseunikka ireun kkeunnan semieyo.) Vì đã gần xong hết rồi nên coi như công việc đã hoàn thành.' },
      { id: 'ko-b2-l3-2-s2', text: '월급의 반을 저축하니까 많이 모으는 셈이에요.', translationVi: '(wolgeubui baneul jeochukhanikka mani moeuneun semieyo.) Vì tiết kiệm một nửa lương nên coi như dành dụm được nhiều.' },
      { id: 'ko-b2-l3-2-s3', text: '3년 동안 같이 살았으니까 가족인 셈이에요.', translationVi: '(samnyeon dongan gachi sarasseunikka gajogin semieyo.) Vì đã sống cùng nhau 3 năm nên coi như là gia đình.' },
      { id: 'ko-b2-l3-2-s4', text: '목표에 거의 도달했으니까 성공한 셈이에요.', translationVi: '(mokpyoe geoui dodalhaesseunikka seonggonghan semieyo.) Vì đã gần đạt được mục tiêu nên coi như thành công.' },
      { id: 'ko-b2-l3-2-s5', text: '전체적으로 보면 이번 프로젝트는 만족스러운 셈이에요.', translationVi: '(jeonchejeogeuro bomyeon ibeon peurojekteuneun manjokseureoun semieyo.) Nhìn chung thì dự án lần này coi như là hài lòng.' },
    ],
    exercises: [
      {
        id: 'ko-b2-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '거의 다 끝났으니까 일은 ___.',
        options: ['끝난 셈이에요', '끝나는 바람에', '끝날 뿐만 아니라', '끝나더라도'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng cho danh từ.',
        sentenceTemplate: '3년 동안 같이 살았으니까 가족___.',
        wordBank: ['인 셈이에요', '이기 마련이에요', '일수록'],
        correctAnswer: '인 셈이에요',
      },
      {
        id: 'ko-b2-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì tiết kiệm một nửa lương nên coi như dành dụm được nhiều."',
        words: ['많이 모으는 셈이에요', '월급의 반을', '저축하니까'],
        correctOrder: ['월급의 반을', '저축하니까', '많이 모으는 셈이에요'],
      },
    ],
  },
];
