import type { ConversationScenario } from '../../types';

export const koreanB1ConversationScenarios: ConversationScenario[] = [
  {
    id: 'ko-b1-conv-jimjak',
    languageCode: 'ko',
    level: 'B1',
    title: '친구 상태 짐작하기',
    titleVi: 'Phỏng đoán về tình trạng của bạn',
    descriptionVi: 'Luyện hội thoại phỏng đoán và nêu lý do bằng 것 같다 và 기 때문에.',
    contextVi: 'An nhận thấy Minh trông không ổn và hỏi thăm.',
    dialogue: [
      { id: 'ko-b1-jimjak-turn-01', speaker: 'A', text: '오늘 표정이 안 좋은 것 같아요. 무슨 일 있어요?', translationVi: '(oneul pyojeongi an joeun geot gatayo. museun il isseoyo?) Hôm nay trông bạn có vẻ không ổn. Có chuyện gì vậy?' },
      { id: 'ko-b1-jimjak-turn-02', speaker: 'B', text: '요즘 일이 많기 때문에 잠을 잘 못 잤어요.', translationVi: '(yojeum iri manki ttaemune jameul jal mot jasseoyo.) Vì dạo này nhiều việc nên tôi ngủ không ngon.' },
      { id: 'ko-b1-jimjak-turn-03', speaker: 'A', text: '많이 피곤해 보여요. 커피라도 마실까요?', translationVi: '(mani pigonhae boyeoyo. keopirado masilkkayo?) Trông bạn có vẻ rất mệt. Uống cà phê nhé?' },
      { id: 'ko-b1-jimjak-turn-04', speaker: 'B', text: '좋아요. 사실은 마감 때문에 스트레스를 많이 받고 있어요.', translationVi: '(joayo. sasireun magam ttaemune seuteureseureul mani batgo isseoyo.) Được đấy. Thực ra vì hạn chót nên tôi đang bị căng thẳng nhiều.' },
      { id: 'ko-b1-jimjak-turn-05', speaker: 'A', text: '아무래도 오늘은 일찍 쉬는 게 좋을 것 같아요.', translationVi: '(amuraedo oneureun iljjik swineun ge joeul geot gatayo.) Có lẽ hôm nay bạn nên nghỉ sớm thì tốt hơn.' },
      { id: 'ko-b1-jimjak-turn-06', speaker: 'B', text: '그렇게 하려고 해요. 조언 고마워요.', translationVi: '(geureoke haryeogo haeyo. joeon gomawoyo.) Tôi định làm vậy. Cảm ơn lời khuyên nhé.' },
      { id: 'ko-b1-jimjak-turn-07', speaker: 'A', text: '마감은 언제까지예요?', translationVi: '(magameun eonjekkajiyeyo?) Hạn chót là đến khi nào vậy?' },
      { id: 'ko-b1-jimjak-turn-08', speaker: 'B', text: '이번 주 금요일까지이기 때문에 조금만 더 힘내야 해요.', translationVi: '(ibeon ju geumyoilkkajiigi ttaemune jogeumman deo himnaeya haeyo.) Vì là đến thứ Sáu tuần này nên tôi phải cố gắng thêm một chút nữa.' },
    ],
    relatedVocabularyIds: ['ko-b1-l1-1-v6', 'ko-b1-l1-2-v4', 'ko-b1-l1-2-v9', 'ko-b1-l1-1-v9'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '오늘 표정이 안 좋은 것 같아요. 무슨 일 있어요?'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: '요즘 일이 많기 때문에 잠을 잘 못 잤어요.' },
        { id: 'o2', text: '이번 주말에 여행을 가려고 해요.' },
        { id: 'o3', text: '사장님께서 회의실에 계세요.' },
        { id: 'o4', text: '친구가 이사한다고 했어요.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về tình trạng của bạn, nên trả lời bằng lý do cụ thể dùng '기 때문에'.",
    },
  },
  {
    id: 'ko-b1-conv-gyehoek',
    languageCode: 'ko',
    level: 'B1',
    title: '계획 이야기하기',
    titleVi: 'Nói về kế hoạch',
    descriptionVi: 'Luyện hội thoại nói về dự định, quyết định và ý định đang cân nhắc bằng 려고 하다, 기로 하다, ㄹ까 하다.',
    contextVi: 'Lan và Minh nói chuyện về kế hoạch cho kỳ nghỉ sắp tới.',
    dialogue: [
      { id: 'ko-b1-plan-turn-01', speaker: 'A', text: '이번 방학에 뭐 하려고 해요?', translationVi: '(ibeon banghage mwo haryeogo haeyo?) Kỳ nghỉ này bạn định làm gì?' },
      { id: 'ko-b1-plan-turn-02', speaker: 'B', text: '아직 잘 모르겠어요. 부산에 갈까 해요.', translationVi: '(ajik jal moreugesseoyo. busane galkka haeyo.) Tôi vẫn chưa rõ lắm. Tôi đang nghĩ là sẽ đi Busan.' },
      { id: 'ko-b1-plan-turn-03', speaker: 'A', text: '좋은 생각이에요. 저는 친구랑 여행 가기로 했어요.', translationVi: '(joeun saenggagieyo. jeoneun chingurang yeohaeng gagiro haesseoyo.) Ý hay đấy. Tôi đã quyết định đi du lịch cùng bạn.' },
      { id: 'ko-b1-plan-turn-04', speaker: 'B', text: '어디로 가기로 했어요?', translationVi: '(eodiro gagiro haesseoyo?) Bạn đã quyết định đi đâu vậy?' },
      { id: 'ko-b1-plan-turn-05', speaker: 'A', text: '제주도로 가기로 했어요. 3일 동안 있을 거예요.', translationVi: '(jejudoro gagiro haesseoyo. samil dongan isseul geoyeyo.) Chúng tôi đã quyết định đi đảo Jeju. Sẽ ở đó 3 ngày.' },
      { id: 'ko-b1-plan-turn-06', speaker: 'B', text: '저도 이번 기회에 새로운 취미를 시작할까 해요.', translationVi: '(jeodo ibeon gihoee saeroun chwimireul sijakhalkka haeyo.) Nhân dịp này tôi cũng đang nghĩ đến việc bắt đầu một sở thích mới.' },
      { id: 'ko-b1-plan-turn-07', speaker: 'A', text: '어떤 취미를 생각하고 있어요?', translationVi: '(eotteon chwimireul saenggakhago isseoyo?) Bạn đang nghĩ đến sở thích nào vậy?' },
      { id: 'ko-b1-plan-turn-08', speaker: 'B', text: '사진 찍는 걸 배워 보려고 해요.', translationVi: '(sajin jjingneun geol baewo boryeogo haeyo.) Tôi định học chụp ảnh thử xem sao.' },
    ],
    relatedVocabularyIds: ['ko-b1-l2-1-v1', 'ko-b1-l2-2-v1', 'ko-b1-l2-3-v1', 'ko-b1-l2-3-v6'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa hỏi '이번 방학에 뭐 하려고 해요?'. Chọn câu trả lời phù hợp nhất cho ý định chưa chắc chắn.",
      options: [
        { id: 'o1', text: '아직 잘 모르겠어요. 부산에 갈까 해요.' },
        { id: 'o2', text: '할머니께서 진지를 드세요.' },
        { id: 'o3', text: '친구가 바쁘다고 했어요.' },
        { id: 'o4', text: '이 옷은 예쁜데 좀 비싸요.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về dự định cho kỳ nghỉ nên trả lời bằng cách nói về ý định (kể cả khi chưa chắc chắn, dùng 'ㄹ까 하다').",
    },
  },
  {
    id: 'ko-b1-conv-jeondalhagi',
    languageCode: 'ko',
    level: 'B1',
    title: '메시지 전달하기',
    titleVi: 'Chuyển lời nhắn',
    descriptionVi: 'Luyện hội thoại dùng kính ngữ khi nói về cấp trên và tường thuật lại lời nói bằng 다고 하다.',
    contextVi: 'An đang báo lại cho Minh thông tin mà giám đốc vừa truyền đạt.',
    dialogue: [
      { id: 'ko-b1-msg-turn-01', speaker: 'A', text: '사장님께서 오늘 회의가 취소됐다고 하셨어요.', translationVi: '(sajangnimkkeseo oneul hoeuiga chwisodwaetdago hasyeosseoyo.) Giám đốc đã nói rằng cuộc họp hôm nay bị hủy.' },
      { id: 'ko-b1-msg-turn-02', speaker: 'B', text: '정말요? 왜 취소됐는지 말씀하셨어요?', translationVi: '(jeongmallyo? wae chwisodwaetneunji malsseumhasyeosseoyo?) Thật sao? Ông ấy có nói lý do vì sao bị hủy không?' },
      { id: 'ko-b1-msg-turn-03', speaker: 'A', text: '사장님께서 출장을 가셨기 때문에 다음 주로 미뤄졌다고 해요.', translationVi: '(sajangnimkkeseo chuljangeul gasyeotgi ttaemune daeum juro miryeojyeotdago haeyo.) Nghe nói vì giám đốc đi công tác nên cuộc họp đã bị dời sang tuần sau.' },
      { id: 'ko-b1-msg-turn-04', speaker: 'B', text: '알겠어요. 새 일정은 확인했어요?', translationVi: '(algesseoyo. sae iljeongeun hwaginhaesseoyo?) Được rồi. Bạn đã xác nhận lịch mới chưa?' },
      { id: 'ko-b1-msg-turn-05', speaker: 'A', text: '아직요. 비서님께 확인해 보려고 해요.', translationVi: '(ajigyo. biseonimkke hwaginhae boryeogo haeyo.) Chưa. Tôi định hỏi thư ký để xác nhận thử.' },
      { id: 'ko-b1-msg-turn-06', speaker: 'B', text: '확인하면 저한테도 알려 주세요.', translationVi: '(hwaginhamyeon jeohantedo allyeo juseyo.) Khi xác nhận được thì báo cho tôi với nhé.' },
      { id: 'ko-b1-msg-turn-07', speaker: 'A', text: '네, 확인하는 대로 바로 전할게요.', translationVi: '(ne, hwaginhaneun daero baro jeonhalgeyo.) Vâng, xác nhận xong tôi sẽ báo ngay.' },
      { id: 'ko-b1-msg-turn-08', speaker: 'B', text: '고마워요. 사장님께서 다른 말씀은 안 하셨어요?', translationVi: '(gomawoyo. sajangnimkkeseo dareun malsseumeun an hasyeosseoyo?) Cảm ơn bạn. Giám đốc có nói gì khác không?' },
    ],
    relatedVocabularyIds: ['ko-b1-l3-1-v2', 'ko-b1-l3-1-v6', 'ko-b1-l3-2-v1', 'ko-b1-l1-2-v1'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn cần chuyển lời của giám đốc cho đồng nghiệp một cách trang trọng, đúng kính ngữ. Chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: '사장님께서 오늘 회의가 취소됐다고 하셨어요.' },
        { id: 'o2', text: '사장이 오늘 회의 취소했대.' },
        { id: 'o3', text: '회의 취소됐어. 사장이 그랬어.' },
        { id: 'o4', text: '오늘 회의 없대, 사장이.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi nói về cấp trên, cần dùng trợ từ kính ngữ '께서' và động từ tường thuật lịch sự '하셨어요', không dùng văn nói suồng sã.",
    },
  },
];
