import type { GrammarTopic } from '../../types';

export const koreanB1GrammarTopics: GrammarTopic[] = [
  {
    id: 'ko-b1-gr-geot-gatda',
    languageCode: 'ko',
    level: 'B1',
    title: '것 같다',
    titleVi: 'Phỏng đoán, nhận định 것 같다',
    explanationVi:
      "'것 같다' dùng để nêu phỏng đoán, nhận định dựa trên quan sát hoặc cảm nhận, nhẹ nhàng và ít chắc chắn hơn khẳng định trực tiếp.",
    structure: '동사 + 는 것 같다 / 형용사 + (으)ㄴ 것 같다 / 명사 + 인 것 같다',
    keyPoints: ['오다 → 오는 것 같다 (động từ hiện tại)', '맵다 → 매운 것 같다 (tính từ, ㅂ bất quy tắc)', '학생 → 학생인 것 같다 (danh từ)'],
    examples: [
      { id: 'ko-b1-gr-geot-s1', text: '오늘 좀 피곤한 것 같아요.', translationVi: 'Hôm nay có vẻ tôi hơi mệt.' },
      { id: 'ko-b1-gr-geot-s2', text: '밖에 눈이 오는 것 같아요.', translationVi: 'Có vẻ như bên ngoài đang có tuyết rơi.' },
      { id: 'ko-b1-gr-geot-s3', text: '저 사람은 외국인인 것 같아요.', translationVi: 'Người kia có vẻ là người nước ngoài.' },
    ],
    commonMistakesVi: "Người mới học hay quên đổi tính từ có ㅂ bất quy tắc, ví dụ nói '맵다 것 같아요' thay vì '매운 것 같아요'.",
    exercises: [
      {
        id: 'ko-b1-gr-geot-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng phỏng đoán đúng của '피곤하다'.",
        question: '오늘 좀 ___.',
        options: ['피곤해요', '피곤한 것 같아요', '피곤했어요', '피곤하기 때문에'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-gr-geot-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '저 사람은 외국인___.',
        wordBank: ['인 것 같아요', '것 같아요', '는 것 같아요'],
        correctAnswer: '인 것 같아요',
        explanationVi: "Danh từ + '인 것 같다' để phỏng đoán.",
      },
      {
        id: 'ko-b1-gr-geot-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Có vẻ như bên ngoài đang có tuyết rơi."',
        words: ['것 같아요', '눈이', '밖에', '오는'],
        correctOrder: ['밖에', '눈이', '오는', '것 같아요'],
      },
    ],
  },
  {
    id: 'ko-b1-gr-gi-ttaemune',
    languageCode: 'ko',
    level: 'B1',
    title: '기 때문에',
    titleVi: 'Nguyên nhân trang trọng 기 때문에',
    explanationVi:
      "'기 때문에' nối hai vế câu theo quan hệ nguyên nhân-kết quả, trang trọng hơn 아/어서, dùng nhiều trong văn viết và giải thích lý do rõ ràng. Danh từ đi trực tiếp với '때문에' mà không cần '기'.",
    structure: '동사/형용사 어간 + 기 때문에 / 명사 + 때문에',
    keyPoints: ['일하다 → 일하기 때문에', '건강 → 건강 때문에 (danh từ không cần 기)', 'Trang trọng hơn 아/어서, thường dùng để giải thích lý do rõ ràng'],
    examples: [
      { id: 'ko-b1-gr-ttaemune-s1', text: '길이 막히기 때문에 늦을 것 같아요.', translationVi: 'Vì đường tắc nên có lẽ tôi sẽ đến muộn.' },
      { id: 'ko-b1-gr-ttaemune-s2', text: '건강 때문에 매일 운동을 해요.', translationVi: 'Vì sức khỏe nên tôi tập thể dục mỗi ngày.' },
      { id: 'ko-b1-gr-ttaemune-s3', text: '바빴기 때문에 전화를 못 받았어요.', translationVi: 'Vì đã bận nên tôi đã không nghe máy được.' },
    ],
    commonMistakesVi: "Người mới học hay thêm '기' sau danh từ, ví dụ nói '건강기 때문에' thay vì '건강 때문에'.",
    exercises: [
      {
        id: 'ko-b1-gr-ttaemune-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng khi nguyên nhân là danh từ.',
        question: '건강 ___ 매일 운동을 해요.',
        options: ['때문에', '기 때문에', '아서', '지만'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b1-gr-ttaemune-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng ở thì quá khứ.',
        sentenceTemplate: '바빴___ 전화를 못 받았어요.',
        wordBank: ['기 때문에', '아서요', '지만'],
        correctAnswer: '기 때문에',
      },
      {
        id: 'ko-b1-gr-ttaemune-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì đường tắc nên có lẽ tôi sẽ đến muộn."',
        words: ['늦을 것 같아요', '길이', '막히기', '때문에'],
        correctOrder: ['길이', '막히기', '때문에', '늦을 것 같아요'],
      },
    ],
  },
  {
    id: 'ko-b1-gr-ryeogo-hada',
    languageCode: 'ko',
    level: 'B1',
    title: '(으)려고 하다',
    titleVi: 'Dự định (으)려고 하다',
    explanationVi:
      "'(으)려고 하다' diễn tả dự định, ý định của người nói, chưa phải quyết định chắc chắn cuối cùng như '기로 하다'.",
    structure: '동사 어간 + (으)려고 하다',
    keyPoints: ['가다 → 가려고 하다', '먹다 → 먹으려고 하다', 'Thường đi cùng thì tương lai gần, có thể thay đổi'],
    examples: [
      { id: 'ko-b1-gr-ryeogo-s1', text: '이번 여름에 운전을 배우려고 해요.', translationVi: 'Mùa hè này tôi định học lái xe.' },
      { id: 'ko-b1-gr-ryeogo-s2', text: '건강을 위해서 채소를 더 먹으려고 해요.', translationVi: 'Vì sức khỏe tôi định ăn nhiều rau hơn.' },
      { id: 'ko-b1-gr-ryeogo-s3', text: '다음 주에 부모님을 뵈려고 해요.', translationVi: 'Tuần sau tôi định về thăm bố mẹ.' },
    ],
    commonMistakesVi: "Người mới học hay nhầm '(으)려고 하다' (dự định) với '기로 하다' (quyết định đã chốt) — dùng sai ngữ cảnh khi nói về một thỏa thuận chắc chắn.",
    exercises: [
      {
        id: 'ko-b1-gr-ryeogo-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng dự định đúng của '배우다'.",
        question: '이번 여름에 운전을 ___.',
        options: ['배워요', '배우려고 해요', '배웠어요', '배우기로 했어요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-gr-ryeogo-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng đúng của '뵈다' (gặp, khiêm nhường).",
        sentenceTemplate: '다음 주에 부모님을 ___.',
        wordBank: ['뵈려고 해요', '뵈어서', '뵈는데'],
        correctAnswer: '뵈려고 해요',
      },
      {
        id: 'ko-b1-gr-ryeogo-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Mùa hè này tôi định học lái xe."',
        words: ['배우려고 해요', '이번 여름에', '운전을'],
        correctOrder: ['이번 여름에', '운전을', '배우려고 해요'],
      },
    ],
  },
  {
    id: 'ko-b1-gr-honorific-si',
    languageCode: 'ko',
    level: 'B1',
    title: '-(으)시-',
    titleVi: 'Kính ngữ chủ ngữ -(으)시-',
    explanationVi:
      "'-(으)시-' gắn vào gốc động từ/tính từ để thể hiện sự tôn trọng với chủ ngữ (người lớn tuổi, cấp trên). Đi cùng trợ từ chủ ngữ kính ngữ '께서'. Một số động từ có dạng kính ngữ đặc biệt (không theo quy tắc thêm -시-).",
    structure: '동사/형용사 어간 + (으)시- (+ 어미) — 께서 thay cho 이/가',
    keyPoints: [
      '읽다 → 읽으시다, 오다 → 오시다 (quy tắc)',
      '먹다 → 드시다, 있다 → 계시다, 자다 → 주무시다 (bất quy tắc, kính ngữ đặc biệt)',
      "Trợ từ chủ ngữ kính ngữ: '께서' (trang trọng hơn 이/가)",
    ],
    examples: [
      { id: 'ko-b1-gr-si-s1', text: '어머니께서 요리하고 계세요.', translationVi: 'Mẹ đang nấu ăn.' },
      { id: 'ko-b1-gr-si-s2', text: '선생님께서 말씀하셨어요.', translationVi: 'Thầy/cô đã nói (dạng kính ngữ).' },
      { id: 'ko-b1-gr-si-s3', text: '할아버지께서는 신문을 읽으세요.', translationVi: 'Ông đang đọc báo.' },
    ],
    commonMistakesVi: "Người mới học hay chia -(으)시- theo quy tắc cho các động từ có dạng kính ngữ đặc biệt, ví dụ nói '먹으세요' thay vì '드세요' khi mời người lớn tuổi.",
    exercises: [
      {
        id: 'ko-b1-gr-si-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng kính ngữ đúng của 말하다.',
        question: '선생님께서 ___.',
        options: ['말해요', '말하세요', '말씀하세요', '말했어요'],
        correctOptionIndex: 2,
        explanationVi: "'말하다' có dạng kính ngữ đặc biệt là '말씀하시다'.",
      },
      {
        id: 'ko-b1-gr-si-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '할아버지___ 신문을 읽으세요.',
        wordBank: ['께서는', '가', '은'],
        correctAnswer: '께서는',
      },
      {
        id: 'ko-b1-gr-si-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Mẹ đang nấu ăn."',
        words: ['계세요', '요리하고', '어머니께서'],
        correctOrder: ['어머니께서', '요리하고', '계세요'],
      },
    ],
  },
  {
    id: 'ko-b1-gr-dago-hada',
    languageCode: 'ko',
    level: 'B1',
    title: '-다고 하다',
    titleVi: 'Lời nói gián tiếp -다고 하다',
    explanationVi:
      "'-다고 하다' dùng để tường thuật lại lời nói của người khác. Dạng chia khác nhau theo loại từ và thì: động từ hiện tại -ㄴ/는다고, quá khứ -았/었다고, tương lai -(으)ㄹ 거라고; tính từ -다고; danh từ (이)라고.",
    structure: '동사(hiện tại) -ㄴ/는다고 하다 / -았/었다고 하다 (quá khứ) / -(으)ㄹ 거라고 하다 (tương lai) / 형용사 -다고 하다 / 명사 (이)라고 하다',
    keyPoints: [
      '가다 → 간다고 해요 (동사 hiện tại)',
      '바쁘다 → 바쁘다고 해요 (형용사)',
      '의사 → 의사라고 해요 (명사)',
    ],
    examples: [
      { id: 'ko-b1-gr-dago-s1', text: '동생이 배가 아프다고 했어요.', translationVi: 'Em tôi nói rằng bị đau bụng.' },
      { id: 'ko-b1-gr-dago-s2', text: '친구가 다음 주에 이사한다고 해요.', translationVi: 'Bạn tôi nói rằng tuần sau sẽ chuyển nhà.' },
      { id: 'ko-b1-gr-dago-s3', text: '그는 의사라고 했어요.', translationVi: 'Anh ấy nói rằng mình là bác sĩ.' },
    ],
    commonMistakesVi: "Người mới học hay quên phân biệt dạng động từ hiện tại (-ㄴ/는다고) với tính từ (-다고), ví dụ chia sai '바쁘다' thành '바쁜다고' thay vì '바쁘다고'.",
    exercises: [
      {
        id: 'ko-b1-gr-dago-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng tường thuật đúng của động từ hiện tại.',
        question: '친구가 다음 주에 ___.',
        options: ['이사하다고 해요', '이사한다고 해요', '이사했다고 해요', '이사할 거예요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-b1-gr-dago-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng tường thuật đúng của danh từ.',
        sentenceTemplate: '그는 의사___ 했어요.',
        wordBank: ['라고', '다고', '이다고'],
        correctAnswer: '라고',
      },
      {
        id: 'ko-b1-gr-dago-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Em tôi nói rằng bị đau bụng."',
        words: ['아프다고', '동생이', '배가', '했어요'],
        correctOrder: ['동생이', '배가', '아프다고', '했어요'],
      },
    ],
  },
];
