import type { Lesson } from '../../../types';

export const japaneseB2CompletionLessons: Lesson[] = [
  {
    id: 'ja-b2-l3-1-te-shimau',
    unitId: 'ja-b2-u3-completion-result',
    title: '～てしまう',
    titleVi: 'Hoàn tất/tiếc nuối ～てしまう',
    objectiveVi: "Diễn tả hành động hoàn tất dứt điểm hoặc mang sắc thái tiếc nuối/lỡ làm bằng '～てしまう'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "動詞(て形) + しまう diễn tả hành động HOÀN TẤT DỨT ĐIỂM (không thể vãn hồi) hoặc mang sắc thái TIẾC NUỐI/LỠ LÀM. Dạng nói tắt thân mật: ～ちゃう (動詞て形+しまう → 動詞+ちゃう), ～じゃう (cho động từ kết thúc bằng で).",
    vocabulary: [
      { id: 'ja-b2-l3-1-v1', term: '～てしまう', translationVi: 'Đã làm xong/lỡ làm mất', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~te shimau' },
      { id: 'ja-b2-l3-1-v2', term: '全部', translationVi: 'Toàn bộ, tất cả', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l3-1-s1', usageNoteVi: 'Cách đọc (romaji): zenbu' },
      { id: 'ja-b2-l3-1-v3', term: 'やる', translationVi: 'Làm', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-1-s1', usageNoteVi: 'Cách đọc (romaji): yaru' },
      { id: 'ja-b2-l3-1-v4', term: '財布', translationVi: 'Ví tiền', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l3-1-s2', usageNoteVi: 'Cách đọc (romaji): saifu' },
      { id: 'ja-b2-l3-1-v5', term: '忘れる', translationVi: 'Quên', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-1-s2', usageNoteVi: 'Cách đọc (romaji): wasureru' },
      { id: 'ja-b2-l3-1-v6', term: '壊す', translationVi: 'Làm hỏng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): kowasu' },
      { id: 'ja-b2-l3-1-v7', term: '遅刻する', translationVi: 'Đi trễ', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): chikoku suru' },
      { id: 'ja-b2-l3-1-v8', term: 'うっかり', translationVi: 'Vô ý, lỡ đãng', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l3-1-s4', usageNoteVi: 'Cách đọc (romaji): ukkari' },
      { id: 'ja-b2-l3-1-v9', term: '間違える', translationVi: 'Làm sai, nhầm lẫn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): machigaeru' },
      { id: 'ja-b2-l3-1-v10', term: '泣く', translationVi: 'Khóc', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-1-s5', usageNoteVi: 'Cách đọc (romaji): naku' },
      { id: 'ja-b2-l3-1-v11', term: '大事だ', translationVi: 'Quan trọng', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b2-l3-1-s4', usageNoteVi: 'Cách đọc (romaji): daiji da' },
      { id: 'ja-b2-l3-1-v12', term: '書類', translationVi: 'Tài liệu, giấy tờ', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l3-1-s4', usageNoteVi: 'Cách đọc (romaji): shorui' },
      { id: 'ja-b2-l3-1-v13', term: '捨てる', translationVi: 'Vứt bỏ', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-1-s4', usageNoteVi: 'Cách đọc (romaji): suteru' },
    ],
    sentences: [
      { id: 'ja-b2-l3-1-s1', text: '宿題を全部やってしまいました。', translationVi: '(Shukudai o zenbu yatte shimaimashita.) Tôi đã làm xong hết bài tập rồi.' },
      { id: 'ja-b2-l3-1-s2', text: '財布を忘れてしまいました。', translationVi: '(Saifu o wasurete shimaimashita.) Tôi đã lỡ quên ví mất rồi.' },
      { id: 'ja-b2-l3-1-s3', text: 'ケーキを全部食べてしまいました。', translationVi: '(Keeki o zenbu tabete shimaimashita.) Tôi đã ăn hết sạch bánh mất rồi.' },
      { id: 'ja-b2-l3-1-s4', text: 'うっかり大事な書類を捨ててしまいました。', translationVi: '(Ukkari daiji na shorui o sutete shimaimashita.) Tôi đã lỡ vứt mất tài liệu quan trọng.' },
      { id: 'ja-b2-l3-1-s5', text: '彼の話を聞いて泣いてしまいました。', translationVi: '(Kare no hanashi o kiite naite shimaimashita.) Tôi đã bật khóc khi nghe câu chuyện của anh ấy.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: hoàn tất dứt điểm.',
        question: '宿題を全部やって___。',
        options: ['しまいました', 'あります', 'います', 'おきました'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng (tiếc nuối, lỡ làm).',
        sentenceTemplate: '財布を忘れて___。',
        wordBank: ['しまいました', 'ください', 'みました'],
        correctAnswer: 'しまいました',
      },
      {
        id: 'ja-b2-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đã lỡ vứt mất tài liệu quan trọng."',
        words: ['大事な書類を', 'うっかり', '捨ててしまいました'],
        correctOrder: ['うっかり', '大事な書類を', '捨ててしまいました'],
      },
    ],
  },
  {
    id: 'ja-b2-l3-2-zaru-wo-enai',
    unitId: 'ja-b2-u3-completion-result',
    title: '～ざるを得ない',
    titleVi: 'Bất đắc dĩ ～ざるを得ない',
    objectiveVi: "Diễn tả việc bất đắc dĩ phải làm, không còn cách nào khác, bằng '～ざるを得ない' — trang trọng, dùng trong văn viết/phát biểu chính thức.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "動詞(ない形，bỏ ない) + ざるを得ない diễn tả 'bất đắc dĩ phải làm, không còn cách nào khác'. する là bất quy tắc: する → せざるを得ない (không phải しざるを得ない).",
    vocabulary: [
      { id: 'ja-b2-l3-2-v1', term: '～ざるを得ない', translationVi: 'Bất đắc dĩ phải làm, không còn cách nào khác', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~zaru wo enai' },
      { id: 'ja-b2-l3-2-v2', term: '状況', translationVi: 'Tình huống, tình hình', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l3-2-s1', usageNoteVi: 'Cách đọc (romaji): joukyou' },
      { id: 'ja-b2-l3-2-v3', term: '変更する', translationVi: 'Thay đổi', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-2-s1', usageNoteVi: 'Cách đọc (romaji): henkou suru' },
      { id: 'ja-b2-l3-2-v4', term: '給料', translationVi: 'Lương', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l3-2-s2', usageNoteVi: 'Cách đọc (romaji): kyuuryou' },
      { id: 'ja-b2-l3-2-v5', term: '辞める', translationVi: 'Nghỉ (việc)', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-2-s2', usageNoteVi: 'Cách đọc (romaji): yameru' },
      { id: 'ja-b2-l3-2-v6', term: '従う', translationVi: 'Tuân theo, nghe theo', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-2-s3', usageNoteVi: 'Cách đọc (romaji): shitagau' },
      { id: 'ja-b2-l3-2-v7', term: '認める', translationVi: 'Thừa nhận, công nhận', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): mitomeru' },
      { id: 'ja-b2-l3-2-v8', term: '諦める', translationVi: 'Từ bỏ', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-2-s5', usageNoteVi: 'Cách đọc (romaji): akirameru' },
      { id: 'ja-b2-l3-2-v9', term: 'やむを得ない', translationVi: 'Bất khả kháng, không thể tránh khỏi', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): yamu wo enai' },
      { id: 'ja-b2-l3-2-v10', term: '選択肢', translationVi: 'Lựa chọn', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l3-2-s5', usageNoteVi: 'Cách đọc (romaji): sentakushi' },
      { id: 'ja-b2-l3-2-v11', term: '責任', translationVi: 'Trách nhiệm', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): sekinin' },
      { id: 'ja-b2-l3-2-v12', term: '現実', translationVi: 'Hiện thực', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l3-2-s4', usageNoteVi: 'Cách đọc (romaji): genjitsu' },
      { id: 'ja-b2-l3-2-v13', term: '受け入れる', translationVi: 'Chấp nhận', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l3-2-s4', usageNoteVi: 'Cách đọc (romaji): ukeireru' },
    ],
    sentences: [
      { id: 'ja-b2-l3-2-s1', text: '状況を考えると、計画を変更せざるを得ません。', translationVi: '(Joukyou o kangaeru to, keikaku o henkou sezaru wo emasen.) Xét đến tình hình, chúng tôi bất đắc dĩ phải thay đổi kế hoạch.' },
      { id: 'ja-b2-l3-2-s2', text: '給料が安いので、辞めざるを得ませんでした。', translationVi: '(Kyuuryou ga yasui node, yamezaru wo emasen deshita.) Vì lương thấp nên tôi đã bất đắc dĩ phải nghỉ việc.' },
      { id: 'ja-b2-l3-2-s3', text: '彼の意見に従わざるを得ない。', translationVi: '(Kare no iken ni shitagawazaru wo enai.) Bất đắc dĩ phải nghe theo ý kiến của anh ấy.' },
      { id: 'ja-b2-l3-2-s4', text: '現実を受け入れざるを得ませんでした。', translationVi: '(Genjitsu o ukeirezaru wo emasen deshita.) Tôi đã bất đắc dĩ phải chấp nhận hiện thực.' },
      { id: 'ja-b2-l3-2-s5', text: '選択肢がないので、諦めざるを得ません。', translationVi: '(Sentakushi ga nai node, akiramezaru wo emasen.) Vì không có lựa chọn nào khác nên bất đắc dĩ phải từ bỏ.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: bất đắc dĩ phải nghỉ việc (quá khứ).',
        question: '給料が安いので、___。',
        options: ['辞めざるを得ませんでした', '辞めるはずでした', '辞めてしまいました', '辞めるように'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '彼の意見に___得ない。',
        wordBank: ['従わざるを', '従うために', '従うように'],
        correctAnswer: '従わざるを',
      },
      {
        id: 'ja-b2-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Xét đến tình hình, chúng tôi bất đắc dĩ phải thay đổi kế hoạch."',
        words: ['計画を変更せざるを得ません', '状況を考えると'],
        correctOrder: ['状況を考えると', '計画を変更せざるを得ません'],
      },
    ],
  },
];
