import type { Lesson } from '../../../types';

export const japaneseB2ConjecturePurposeLessons: Lesson[] = [
  {
    id: 'ja-b2-l2-1-hazu-da',
    unitId: 'ja-b2-u2-conjecture-purpose',
    title: '～はずだ',
    titleVi: 'Suy đoán chắc chắn ～はずだ',
    objectiveVi: "Suy đoán dựa trên logic/thông tin đã biết với mức độ chắc chắn cao bằng '～はずだ' — khác ～ようです (dựa trên quan sát trực tiếp).",
    estimatedMinutes: 9,
    grammarNoteVi:
      "普通形 + はずだ diễn tả suy đoán dựa trên lý lẽ/thông tin đã biết ('chắc hẳn là, đáng lẽ phải'), mức độ chắc chắn cao hơn ようです/みたいです (vốn dựa trên quan sát giác quan). Phủ định 'không thể nào': ～はずがない.",
    vocabulary: [
      { id: 'ja-b2-l2-1-v1', term: '～はずだ', translationVi: 'Chắc hẳn là, đáng lẽ phải', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~hazu da' },
      { id: 'ja-b2-l2-1-v2', term: '～はずがない', translationVi: 'Không thể nào là', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-1-s3', usageNoteVi: 'Cách đọc (romaji): ~hazu ga nai' },
      { id: 'ja-b2-l2-1-v3', term: '出発する', translationVi: 'Xuất phát', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-1-s1', usageNoteVi: 'Cách đọc (romaji): shuppatsu suru' },
      { id: 'ja-b2-l2-1-v4', term: '日曜日', translationVi: 'Chủ nhật', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l2-1-s2', usageNoteVi: 'Cách đọc (romaji): nichiyoubi' },
      { id: 'ja-b2-l2-1-v5', term: '銀行', translationVi: 'Ngân hàng', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l2-1-s2', usageNoteVi: 'Cách đọc (romaji): ginkou' },
      { id: 'ja-b2-l2-1-v6', term: '休み', translationVi: 'Ngày nghỉ', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l2-1-s2', usageNoteVi: 'Cách đọc (romaji): yasumi' },
      { id: 'ja-b2-l2-1-v7', term: '到着する', translationVi: 'Đến nơi', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-1-s4', usageNoteVi: 'Cách đọc (romaji): touchaku suru' },
      { id: 'ja-b2-l2-1-v8', term: '予定', translationVi: 'Dự định, lịch trình', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): yotei' },
      { id: 'ja-b2-l2-1-v9', term: '確認する', translationVi: 'Xác nhận', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): kakunin suru' },
      { id: 'ja-b2-l2-1-v10', term: '間違いない', translationVi: 'Không sai, chắc chắn', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): machigainai' },
      { id: 'ja-b2-l2-1-v11', term: '論理的に', translationVi: 'Một cách logic', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ronriteki ni' },
      { id: 'ja-b2-l2-1-v12', term: '常識', translationVi: 'Lẽ thường, thường thức', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): joushiki' },
      { id: 'ja-b2-l2-1-v13', term: '知らない', translationVi: 'Không biết', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-1-s5', usageNoteVi: 'Cách đọc (romaji): shiranai' },
    ],
    sentences: [
      { id: 'ja-b2-l2-1-s1', text: '彼はもう出発したはずです。', translationVi: '(Kare wa mou shuppatsu shita hazu desu.) Chắc hẳn anh ấy đã xuất phát rồi.' },
      { id: 'ja-b2-l2-1-s2', text: '今日は日曜日だから、銀行は休みのはずです。', translationVi: '(Kyou wa nichiyoubi dakara, ginkou wa yasumi no hazu desu.) Vì hôm nay là Chủ nhật nên chắc hẳn ngân hàng nghỉ.' },
      { id: 'ja-b2-l2-1-s3', text: '彼女がそんなことを言うはずがありません。', translationVi: '(Kanojo ga sonna koto o iu hazu ga arimasen.) Không thể nào cô ấy lại nói điều như vậy.' },
      { id: 'ja-b2-l2-1-s4', text: '飛行機はもう到着しているはずです。', translationVi: '(Hikouki wa mou touchaku shite iru hazu desu.) Chắc hẳn máy bay đã đến nơi rồi.' },
      { id: 'ja-b2-l2-1-s5', text: '彼が知らないはずはありません。', translationVi: '(Kare ga shiranai hazu wa arimasen.) Không thể nào anh ấy lại không biết.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng suy đoán chắc chắn đúng.',
        question: '今日は日曜日だから、銀行は休み___。',
        options: ['のはずです', 'のようです', 'のに', 'のために'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền cụm từ còn thiếu.',
        sentenceTemplate: '彼女がそんなことを言う___ありません。',
        wordBank: ['はずが', 'ようが', 'のに'],
        correctAnswer: 'はずが',
      },
      {
        id: 'ja-b2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Chắc hẳn anh ấy đã xuất phát rồi."',
        words: ['出発したはずです', '彼はもう'],
        correctOrder: ['彼はもう', '出発したはずです'],
      },
    ],
  },
  {
    id: 'ja-b2-l2-2-you-ni',
    unitId: 'ja-b2-u2-conjecture-purpose',
    title: '～ように',
    titleVi: 'Mục đích ～ように',
    objectiveVi: "Diễn tả mục đích với động từ không chủ ý/khả năng (わかる, できる, 聞こえる...) bằng '～ように'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "動詞(辞書形/ない形) + ように diễn tả mục đích, thường đi với động từ KHÔNG chủ ý hoặc động từ khả năng: 忘れないように (để không quên), 聞こえるように (để nghe thấy được). Khác ～ために (dùng với động từ có chủ ý).",
    vocabulary: [
      { id: 'ja-b2-l2-2-v1', term: '～ように', translationVi: 'Để (mục đích, với động từ không chủ ý/khả năng)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~you ni' },
      { id: 'ja-b2-l2-2-v2', term: '忘れない', translationVi: 'Không quên', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-2-s1', usageNoteVi: 'Cách đọc (romaji): wasurenai' },
      { id: 'ja-b2-l2-2-v3', term: 'メモする', translationVi: 'Ghi chú', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-2-s1', usageNoteVi: 'Cách đọc (romaji): memo suru' },
      { id: 'ja-b2-l2-2-v4', term: '聞こえる', translationVi: 'Nghe thấy được', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-2-s2', usageNoteVi: 'Cách đọc (romaji): kikoeru' },
      { id: 'ja-b2-l2-2-v5', term: '見える', translationVi: 'Nhìn thấy được', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): mieru' },
      { id: 'ja-b2-l2-2-v6', term: '大きな声で', translationVi: 'Bằng giọng to', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-2-s2', usageNoteVi: 'Cách đọc (romaji): ookina koe de' },
      { id: 'ja-b2-l2-2-v7', term: '間に合う', translationVi: 'Kịp giờ', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-2-s3', usageNoteVi: 'Cách đọc (romaji): maniau' },
      { id: 'ja-b2-l2-2-v8', term: '早く起きる', translationVi: 'Dậy sớm', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): hayaku okiru' },
      { id: 'ja-b2-l2-2-v9', term: '風邪をひかない', translationVi: 'Không bị cảm', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-2-s4', usageNoteVi: 'Cách đọc (romaji): kaze o hikanai' },
      { id: 'ja-b2-l2-2-v10', term: '気をつける', translationVi: 'Chú ý, cẩn thận', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-2-s4', usageNoteVi: 'Cách đọc (romaji): ki o tsukeru' },
      { id: 'ja-b2-l2-2-v11', term: '話せる', translationVi: 'Có thể nói được', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-2-s5', usageNoteVi: 'Cách đọc (romaji): hanaseru' },
      { id: 'ja-b2-l2-2-v12', term: '練習する', translationVi: 'Luyện tập', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-2-s5', usageNoteVi: 'Cách đọc (romaji): renshuu suru' },
      { id: 'ja-b2-l2-2-v13', term: '上手になる', translationVi: 'Trở nên giỏi', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): jouzu ni naru' },
    ],
    sentences: [
      { id: 'ja-b2-l2-2-s1', text: '忘れないように、メモしてください。', translationVi: '(Wasurenai you ni, memo shite kudasai.) Để không quên, hãy ghi chú lại.' },
      { id: 'ja-b2-l2-2-s2', text: 'みんなに聞こえるように、大きな声で話してください。', translationVi: '(Minna ni kikoeru you ni, ookina koe de hanashite kudasai.) Để mọi người nghe thấy, hãy nói bằng giọng to.' },
      { id: 'ja-b2-l2-2-s3', text: '電車に間に合うように、早く家を出ました。', translationVi: '(Densha ni maniau you ni, hayaku ie o demashita.) Để kịp chuyến tàu, tôi đã ra khỏi nhà sớm.' },
      { id: 'ja-b2-l2-2-s4', text: '風邪をひかないように、気をつけてください。', translationVi: '(Kaze o hikanai you ni, ki o tsukete kudasai.) Để không bị cảm, hãy chú ý cẩn thận.' },
      { id: 'ja-b2-l2-2-s5', text: '上手に話せるように、毎日練習しています。', translationVi: '(Jouzu ni hanaseru you ni, mainichi renshuu shite imasu.) Để có thể nói giỏi, tôi luyện tập mỗi ngày.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '忘れない___、メモしてください。',
        options: ['ように', 'ために', 'のに', 'はずに'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '電車に間に合う___、早く家を出ました。',
        wordBank: ['ように', 'ために', 'のに'],
        correctAnswer: 'ように',
      },
      {
        id: 'ja-b2-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Để không bị cảm, hãy chú ý cẩn thận."',
        words: ['気をつけてください', '風邪をひかないように'],
        correctOrder: ['風邪をひかないように', '気をつけてください'],
      },
    ],
  },
  {
    id: 'ja-b2-l2-3-tame-ni',
    unitId: 'ja-b2-u2-conjecture-purpose',
    title: '～ために',
    titleVi: 'Mục đích ～ために',
    objectiveVi: "Diễn tả mục đích rõ ràng với động từ CÓ chủ ý, hoặc 'vì lợi ích của', bằng '～ために'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "動詞(辞書形) / 名詞 + の + ために diễn tả mục đích với động từ CÓ chủ ý (khác ～ように dùng cho động từ không chủ ý/khả năng), hoặc nghĩa 'vì (lợi ích của)': 健康のために (vì sức khỏe).",
    vocabulary: [
      { id: 'ja-b2-l2-3-v1', term: '～ために', translationVi: 'Để, vì (mục đích, lợi ích)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~tame ni' },
      { id: 'ja-b2-l2-3-v2', term: '健康のために', translationVi: 'Vì sức khỏe', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-3-s1', usageNoteVi: 'Cách đọc (romaji): kenkou no tame ni' },
      { id: 'ja-b2-l2-3-v3', term: '留学する', translationVi: 'Du học', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-3-s2', usageNoteVi: 'Cách đọc (romaji): ryuugaku suru' },
      { id: 'ja-b2-l2-3-v4', term: 'お金を貯める', translationVi: 'Để dành tiền', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-3-s2', usageNoteVi: 'Cách đọc (romaji): okane o tameru' },
      { id: 'ja-b2-l2-3-v5', term: '夢を叶える', translationVi: 'Thực hiện ước mơ', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-3-s3', usageNoteVi: 'Cách đọc (romaji): yume o kanaeru' },
      { id: 'ja-b2-l2-3-v6', term: '家族のために', translationVi: 'Vì gia đình', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-3-s4', usageNoteVi: 'Cách đọc (romaji): kazoku no tame ni' },
      { id: 'ja-b2-l2-3-v7', term: '目標', translationVi: 'Mục tiêu', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): mokuhyou' },
      { id: 'ja-b2-l2-3-v8', term: '達成する', translationVi: 'Đạt được', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): tassei suru' },
      { id: 'ja-b2-l2-3-v9', term: '資格を取る', translationVi: 'Lấy chứng chỉ', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-3-s5', usageNoteVi: 'Cách đọc (romaji): shikaku o toru' },
      { id: 'ja-b2-l2-3-v10', term: '将来', translationVi: 'Tương lai', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): shourai' },
      { id: 'ja-b2-l2-3-v11', term: '犠牲にする', translationVi: 'Hy sinh', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): gisei ni suru' },
      { id: 'ja-b2-l2-3-v12', term: '頑張る', translationVi: 'Cố gắng', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l2-3-s3', usageNoteVi: 'Cách đọc (romaji): ganbaru' },
      { id: 'ja-b2-l2-3-v13', term: '一生懸命働く', translationVi: 'Làm việc hết sức chăm chỉ', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l2-3-s4', usageNoteVi: 'Cách đọc (romaji): isshoukenmei hataraku' },
    ],
    sentences: [
      { id: 'ja-b2-l2-3-s1', text: '健康のために、毎日運動しています。', translationVi: '(Kenkou no tame ni, mainichi undou shite imasu.) Vì sức khỏe, tôi tập thể dục mỗi ngày.' },
      { id: 'ja-b2-l2-3-s2', text: '留学するために、お金を貯めています。', translationVi: '(Ryuugaku suru tame ni, okane o tamete imasu.) Để đi du học, tôi đang để dành tiền.' },
      { id: 'ja-b2-l2-3-s3', text: '夢を叶えるために、頑張っています。', translationVi: '(Yume o kanaeru tame ni, ganbatte imasu.) Để thực hiện ước mơ, tôi đang cố gắng.' },
      { id: 'ja-b2-l2-3-s4', text: '家族のために、一生懸命働いています。', translationVi: '(Kazoku no tame ni, isshoukenmei hataraite imasu.) Vì gia đình, tôi đang làm việc hết sức chăm chỉ.' },
      { id: 'ja-b2-l2-3-s5', text: '資格を取るために、毎晩勉強しています。', translationVi: '(Shikaku o toru tame ni, maiban benkyou shite imasu.) Để lấy chứng chỉ, tôi học mỗi tối.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '健康___、毎日運動しています。',
        options: ['のために', 'のように', 'のに', 'のはずに'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '留学する___、お金を貯めています。',
        wordBank: ['ために', 'ように', 'のに'],
        correctAnswer: 'ために',
      },
      {
        id: 'ja-b2-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Để thực hiện ước mơ, tôi đang cố gắng."',
        words: ['頑張っています', '夢を叶えるために'],
        correctOrder: ['夢を叶えるために', '頑張っています'],
      },
    ],
  },
];
