import type { Lesson } from '../../../types';

export const japaneseB2ContrastLessons: Lesson[] = [
  {
    id: 'ja-b2-l1-1-noni',
    unitId: 'ja-b2-u1-contrast-emphasis',
    title: '～のに',
    titleVi: 'Tương phản bất ngờ ～のに',
    objectiveVi: "Bày tỏ sự tương phản mạnh, mang sắc thái bất ngờ hoặc thất vọng bằng '～のに'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "普通形 + のに nối hai vế mang tính tương phản mạnh, thường kèm sắc thái bất ngờ/thất vọng/phàn nàn — khác けど/が chỉ đơn thuần tương phản trung tính. Danh từ/tính từ đuôi -na cần thêm な trước のに: 静かな→静かなのに.",
    vocabulary: [
      { id: 'ja-b2-l1-1-v1', term: '～のに', translationVi: 'Vậy mà, dù đã...nhưng...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~noni' },
      { id: 'ja-b2-l1-1-v2', term: '一生懸命', translationVi: 'Hết sức, chăm chỉ', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l1-1-s1', usageNoteVi: 'Cách đọc (romaji): isshoukenmei' },
      { id: 'ja-b2-l1-1-v3', term: '試験に落ちる', translationVi: 'Trượt kỳ thi', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l1-1-s1', usageNoteVi: 'Cách đọc (romaji): shiken ni ochiru' },
      { id: 'ja-b2-l1-1-v4', term: '約束する', translationVi: 'Hứa hẹn', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l1-1-s3', usageNoteVi: 'Cách đọc (romaji): yakusoku suru' },
      { id: 'ja-b2-l1-1-v5', term: '残念だ', translationVi: 'Đáng tiếc', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (romaji): zannen da' },
      { id: 'ja-b2-l1-1-v6', term: 'がっかりする', translationVi: 'Thất vọng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): gakkari suru' },
      { id: 'ja-b2-l1-1-v7', term: 'せっかく', translationVi: 'Đã cất công, mất công', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l1-1-s4', usageNoteVi: 'Cách đọc (romaji): sekkaku' },
      { id: 'ja-b2-l1-1-v8', term: '期待する', translationVi: 'Kỳ vọng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): kitai suru' },
      { id: 'ja-b2-l1-1-v9', term: '裏切る', translationVi: 'Phản bội, làm ai đó thất vọng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): uragiru' },
      { id: 'ja-b2-l1-1-v10', term: '準備する', translationVi: 'Chuẩn bị', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l1-1-s4', usageNoteVi: 'Cách đọc (romaji): junbi suru' },
      { id: 'ja-b2-l1-1-v11', term: '台無しになる', translationVi: 'Trở nên hỏng bét', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): dainashi ni naru' },
      { id: 'ja-b2-l1-1-v12', term: '天気予報', translationVi: 'Dự báo thời tiết', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): tenki yohou' },
      { id: 'ja-b2-l1-1-v13', term: 'まだ', translationVi: 'Vẫn còn, chưa', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l1-1-s5', usageNoteVi: 'Cách đọc (romaji): mada' },
    ],
    sentences: [
      { id: 'ja-b2-l1-1-s1', text: '一生懸命勉強したのに、試験に落ちました。', translationVi: '(Isshoukenmei benkyou shita noni, shiken ni ochimashita.) Dù đã học hành chăm chỉ nhưng tôi vẫn trượt kỳ thi.' },
      { id: 'ja-b2-l1-1-s2', text: '天気がいいのに、彼は家にいます。', translationVi: '(Tenki ga ii noni, kare wa ie ni imasu.) Trời đẹp vậy mà anh ấy vẫn ở nhà.' },
      { id: 'ja-b2-l1-1-s3', text: '約束したのに、彼は来ませんでした。', translationVi: '(Yakusoku shita noni, kare wa kimasen deshita.) Đã hứa rồi vậy mà anh ấy đã không đến.' },
      { id: 'ja-b2-l1-1-s4', text: 'せっかく準備したのに、パーティーは中止になりました。', translationVi: '(Sekkaku junbi shita noni, paatii wa chuushi ni narimashita.) Đã cất công chuẩn bị vậy mà bữa tiệc đã bị hủy.' },
      { id: 'ja-b2-l1-1-s5', text: 'もう夜なのに、まだ仕事をしています。', translationVi: '(Mou yoru na noni, mada shigoto o shite imasu.) Đã khuya rồi vậy mà vẫn còn đang làm việc.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng thể hiện sự tương phản bất ngờ.',
        question: '一生懸命勉強した___、試験に落ちました。',
        options: ['のに', 'から', 'ので', 'し'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '約束した___、彼は来ませんでした。',
        wordBank: ['のに', 'から', 'ければ'],
        correctAnswer: 'のに',
      },
      {
        id: 'ja-b2-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Trời đẹp vậy mà anh ấy vẫn ở nhà."',
        words: ['彼は家にいます', '天気がいいのに'],
        correctOrder: ['天気がいいのに', '彼は家にいます'],
      },
    ],
  },
  {
    id: 'ja-b2-l1-2-dake-de-naku-mo',
    unitId: 'ja-b2-u1-contrast-emphasis',
    title: '～だけでなく～も',
    titleVi: 'Liệt kê bổ sung ～だけでなく～も',
    objectiveVi: "Liệt kê hai đặc điểm liên quan, ý sau bổ sung cho ý trước bằng '～だけでなく～も' (không chỉ...mà...cũng...).",
    estimatedMinutes: 9,
    grammarNoteVi:
      "普通形 + だけでなく、～も: không chỉ A mà B cũng... Danh từ/な形容詞 cần thêm な trước だけでなく nếu là thể hiện tại khẳng định: 親切な → 親切なだけでなく.",
    vocabulary: [
      { id: 'ja-b2-l1-2-v1', term: '～だけでなく～も', translationVi: 'Không chỉ...mà...cũng...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~dake de naku ~mo' },
      { id: 'ja-b2-l1-2-v2', term: '話せる', translationVi: 'Có thể nói (được)', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l1-2-s1', usageNoteVi: 'Cách đọc (romaji): hanaseru' },
      { id: 'ja-b2-l1-2-v3', term: '味', translationVi: 'Hương vị', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-2-s2', usageNoteVi: 'Cách đọc (romaji): aji' },
      { id: 'ja-b2-l1-2-v4', term: '見た目', translationVi: 'Vẻ ngoài, hình thức', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-2-s2', usageNoteVi: 'Cách đọc (romaji): mitame' },
      { id: 'ja-b2-l1-2-v5', term: '価格', translationVi: 'Giá cả', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): kakaku' },
      { id: 'ja-b2-l1-2-v6', term: '品質', translationVi: 'Chất lượng', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): hinshitsu' },
      { id: 'ja-b2-l1-2-v7', term: 'スタッフ', translationVi: 'Nhân viên', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-2-s3', usageNoteVi: 'Cách đọc (romaji): sutaffu' },
      { id: 'ja-b2-l1-2-v8', term: '親切だ', translationVi: 'Tử tế, thân thiện', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b2-l1-2-s3', usageNoteVi: 'Cách đọc (romaji): shinsetsu da' },
      { id: 'ja-b2-l1-2-v9', term: '雰囲気', translationVi: 'Bầu không khí', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-2-s3', usageNoteVi: 'Cách đọc (romaji): fun\'iki' },
      { id: 'ja-b2-l1-2-v10', term: '環境問題', translationVi: 'Vấn đề môi trường', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-2-s4', usageNoteVi: 'Cách đọc (romaji): kankyou mondai' },
      { id: 'ja-b2-l1-2-v11', term: '影響する', translationVi: 'Ảnh hưởng', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l1-2-s4', usageNoteVi: 'Cách đọc (romaji): eikyou suru' },
      { id: 'ja-b2-l1-2-v12', term: '経済', translationVi: 'Kinh tế', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-2-s4', usageNoteVi: 'Cách đọc (romaji): keizai' },
      { id: 'ja-b2-l1-2-v13', term: '分野', translationVi: 'Lĩnh vực', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-2-s5', usageNoteVi: 'Cách đọc (romaji): bun\'ya' },
    ],
    sentences: [
      { id: 'ja-b2-l1-2-s1', text: '彼は英語だけでなく中国語も話せます。', translationVi: '(Kare wa eigo dake de naku chuugokugo mo hanasemasu.) Anh ấy không chỉ nói được tiếng Anh mà còn nói được cả tiếng Trung.' },
      { id: 'ja-b2-l1-2-s2', text: 'この店は味だけでなく見た目も素晴らしいです。', translationVi: '(Kono mise wa aji dake de naku mitame mo subarashii desu.) Quán này không chỉ hương vị mà vẻ ngoài của món ăn cũng tuyệt vời.' },
      { id: 'ja-b2-l1-2-s3', text: 'この店はスタッフが親切なだけでなく、雰囲気もいいです。', translationVi: '(Kono mise wa sutaffu ga shinsetsu na dake de naku, fun\'iki mo ii desu.) Quán này không chỉ nhân viên tử tế mà bầu không khí cũng tốt.' },
      { id: 'ja-b2-l1-2-s4', text: '環境問題は健康だけでなく経済にも影響します。', translationVi: '(Kankyou mondai wa kenkou dake de naku keizai ni mo eikyou shimasu.) Vấn đề môi trường không chỉ ảnh hưởng đến sức khỏe mà còn ảnh hưởng đến kinh tế.' },
      { id: 'ja-b2-l1-2-s5', text: 'その分野は日本だけでなく世界でも注目されています。', translationVi: '(Sono bun\'ya wa Nihon dake de naku sekai demo chuumoku sarete imasu.) Lĩnh vực đó không chỉ ở Nhật mà còn được thế giới chú ý đến.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '彼は英語___中国語も話せます。',
        options: ['だけでなく', 'のに', 'はずです', 'ように'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '環境問題は健康だけでなく経済に___影響します。',
        wordBank: ['も', 'は', 'が'],
        correctAnswer: 'も',
      },
      {
        id: 'ja-b2-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Quán này không chỉ hương vị mà vẻ ngoài của món ăn cũng tuyệt vời."',
        words: ['見た目も素晴らしいです', 'この店は', '味だけでなく'],
        correctOrder: ['この店は', '味だけでなく', '見た目も素晴らしいです'],
      },
    ],
  },
  {
    id: 'ja-b2-l1-3-wake-de-wa-nai',
    unitId: 'ja-b2-u1-contrast-emphasis',
    title: '～わけではない',
    titleVi: 'Phủ định một phần ～わけではない',
    objectiveVi: "Làm rõ ý, tránh hiểu lầm bằng cách phủ định một phần, không hoàn toàn, bằng '～わけではない'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "普通形 + わけではない diễn tả 'không hẳn là, không phải là (hoàn toàn)' — thường dùng để làm rõ ý sau khi câu trước có thể gây hiểu lầm là phủ định tuyệt đối.",
    vocabulary: [
      { id: 'ja-b2-l1-3-v1', term: '～わけではない', translationVi: 'Không hẳn là, không phải là (hoàn toàn)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): ~wake de wa nai' },
      { id: 'ja-b2-l1-3-v2', term: '嫌いだ', translationVi: 'Ghét', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b2-l1-3-s1', usageNoteVi: 'Cách đọc (romaji): kirai da' },
      { id: 'ja-b2-l1-3-v3', term: '無駄遣い', translationVi: 'Tiêu xài lãng phí', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-3-s2', usageNoteVi: 'Cách đọc (romaji): mudazukai' },
      { id: 'ja-b2-l1-3-v4', term: '誤解する', translationVi: 'Hiểu lầm', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (romaji): gokai suru' },
      { id: 'ja-b2-l1-3-v5', term: '全部', translationVi: 'Toàn bộ, tất cả', partOfSpeech: 'noun', exampleSentenceId: 'ja-b2-l1-3-s3', usageNoteVi: 'Cách đọc (romaji): zenbu' },
      { id: 'ja-b2-l1-3-v6', term: '完全に', translationVi: 'Hoàn toàn', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): kanzen ni' },
      { id: 'ja-b2-l1-3-v7', term: '必ずしも', translationVi: 'Không nhất thiết', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (romaji): kanarazushimo' },
      { id: 'ja-b2-l1-3-v8', term: '反対する', translationVi: 'Phản đối', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l1-3-s4', usageNoteVi: 'Cách đọc (romaji): hantai suru' },
      { id: 'ja-b2-l1-3-v9', term: '単に', translationVi: 'Chỉ đơn thuần', partOfSpeech: 'phrase', exampleSentenceId: 'ja-b2-l1-3-s4', usageNoteVi: 'Cách đọc (romaji): tan ni' },
      { id: 'ja-b2-l1-3-v10', term: '事情', translationVi: 'Tình hình, lý do', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): jijou' },
      { id: 'ja-b2-l1-3-v11', term: '忙しい', translationVi: 'Bận rộn', partOfSpeech: 'adjective', exampleSentenceId: 'ja-b2-l1-3-s5', usageNoteVi: 'Cách đọc (romaji): isogashii' },
      { id: 'ja-b2-l1-3-v12', term: '苦手だ', translationVi: 'Không giỏi, ngại', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (romaji): nigate da' },
      { id: 'ja-b2-l1-3-v13', term: '心配する', translationVi: 'Lo lắng', partOfSpeech: 'verb', exampleSentenceId: 'ja-b2-l1-3-s4', usageNoteVi: 'Cách đọc (romaji): shinpai suru' },
    ],
    sentences: [
      { id: 'ja-b2-l1-3-s1', text: '嫌いなわけではないですが、あまり食べません。', translationVi: '(Kirai na wake de wa nai desu ga, amari tabemasen.) Không phải là tôi ghét, nhưng tôi không ăn nhiều.' },
      { id: 'ja-b2-l1-3-s2', text: 'お金がないわけではないですが、無駄遣いはしたくないです。', translationVi: '(Okane ga nai wake de wa nai desu ga, mudazukai wa shitakunai desu.) Không phải là tôi không có tiền, nhưng tôi không muốn tiêu xài lãng phí.' },
      { id: 'ja-b2-l1-3-s3', text: '全部わかったわけではありません。', translationVi: '(Zenbu wakatta wake de wa arimasen.) Không phải là tôi đã hiểu hết tất cả.' },
      { id: 'ja-b2-l1-3-s4', text: '反対しているわけではなく、単に心配しているだけです。', translationVi: '(Hantai shite iru wake de wa naku, tan ni shinpai shite iru dake desu.) Không phải là tôi phản đối, chỉ đơn thuần là đang lo lắng thôi.' },
      { id: 'ja-b2-l1-3-s5', text: '忙しいわけではないですが、少し疲れています。', translationVi: '(Isogashii wake de wa nai desu ga, sukoshi tsukarete imasu.) Không phải là tôi bận, nhưng tôi hơi mệt.' },
    ],
    exercises: [
      {
        id: 'ja-b2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '嫌いな___ですが、あまり食べません。',
        options: ['わけではない', 'はずだ', 'のに', 'ために'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền cụm từ còn thiếu.',
        sentenceTemplate: '全部わかった___ありません。',
        wordBank: ['わけでは', 'はずでは', 'ように'],
        correctAnswer: 'わけでは',
      },
      {
        id: 'ja-b2-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Không phải là tôi có tiền, nhưng tôi không muốn tiêu xài lãng phí."',
        words: ['お金がないわけではないですが', '無駄遣いはしたくないです'],
        correctOrder: ['お金がないわけではないですが', '無駄遣いはしたくないです'],
      },
    ],
  },
];
