import type { Lesson } from '../../../types';

export const englishB2DiscourseLessons: Lesson[] = [
  {
    id: 'en-b2-l3-1-discourse-markers',
    unitId: 'en-b2-u3-discourse-nuance',
    title: 'Discourse markers for argumentation',
    titleVi: 'Từ nối diễn ngôn trong lập luận',
    objectiveVi: 'Liên kết ý tưởng một cách mạch lạc, trang trọng trong văn viết và tranh luận bằng các từ nối diễn ngôn.',
    estimatedMinutes: 8,
    grammarNoteVi:
      "Từ nối diễn ngôn giúp câu văn/lập luận mạch lạc hơn: however/nevertheless (tương phản), moreover/furthermore (bổ sung), on the contrary (phản bác), in other words (diễn giải lại), as a result/consequently (kết quả). Thường đứng đầu câu, theo sau là dấu phẩy.",
    vocabulary: [
      { id: 'en-b2-l3-1-v1', term: 'however', translationVi: 'Tuy nhiên', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-1-s1' },
      { id: 'en-b2-l3-1-v2', term: 'nevertheless', translationVi: 'Tuy vậy, dù sao đi nữa', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-1-s2' },
      { id: 'en-b2-l3-1-v3', term: 'moreover', translationVi: 'Hơn nữa', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-1-s3' },
      { id: 'en-b2-l3-1-v4', term: 'furthermore', translationVi: 'Hơn thế nữa', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v5', term: 'on the contrary', translationVi: 'Ngược lại', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v6', term: 'in other words', translationVi: 'Nói cách khác', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v7', term: 'that said', translationVi: 'Dù vậy, dù nói vậy', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v8', term: 'as a result', translationVi: 'Kết quả là', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v9', term: 'consequently', translationVi: 'Do đó, hệ quả là', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v10', term: 'in light of', translationVi: 'Xét đến, trong bối cảnh của', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-1-s4' },
      { id: 'en-b2-l3-1-v11', term: 'with this in mind', translationVi: 'Với điều này trong đầu', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v12', term: 'to put it another way', translationVi: 'Nói theo cách khác', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-1-v13', term: 'all things considered', translationVi: 'Xét mọi mặt thì', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-1-s5' },
    ],
    sentences: [
      { id: 'en-b2-l3-1-s1', text: 'The plan sounds risky; however, it could pay off in the long run.', translationVi: 'Kế hoạch nghe có vẻ mạo hiểm; tuy nhiên, về lâu dài nó có thể mang lại kết quả tốt.' },
      { id: 'en-b2-l3-1-s2', text: 'He had little experience; nevertheless, he got the job.', translationVi: 'Anh ấy có ít kinh nghiệm; tuy vậy, anh ấy vẫn được nhận việc.' },
      { id: 'en-b2-l3-1-s3', text: "The product is expensive. Moreover, it's difficult to find in stores.", translationVi: 'Sản phẩm này đắt. Hơn nữa, nó còn khó tìm mua ở cửa hàng.' },
      { id: 'en-b2-l3-1-s4', text: 'In light of the recent changes, we need to revise our strategy.', translationVi: 'Xét đến những thay đổi gần đây, chúng ta cần điều chỉnh lại chiến lược.' },
      { id: 'en-b2-l3-1-s5', text: 'All things considered, I think we made the right decision.', translationVi: 'Xét mọi mặt thì, tôi nghĩ chúng ta đã đưa ra quyết định đúng đắn.' },
    ],
    exercises: [
      {
        id: 'en-b2-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ nối đúng thể hiện sự tương phản dù có bất lợi.',
        question: 'He had little experience; ___, he got the job.',
        options: ['nevertheless', 'moreover', 'furthermore', 'consequently'],
        correctOptionIndex: 0,
      },
      {
        id: 'en-b2-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ nối đúng thể hiện sự bổ sung.',
        sentenceTemplate: "The product is expensive. ___, it's difficult to find in stores.",
        wordBank: ['Moreover', 'However', 'Consequently'],
        correctAnswer: 'Moreover',
      },
      {
        id: 'en-b2-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['we made the right decision', 'all things considered', 'I think'],
        correctOrder: ['all things considered', 'I think', 'we made the right decision'],
      },
    ],
  },
  {
    id: 'en-b2-l3-2-modal-nuance',
    unitId: 'en-b2-u3-discourse-nuance',
    title: 'Modal nuance and complex verb patterns',
    titleVi: 'Sắc thái động từ khuyết thiếu và mẫu động từ phức tạp',
    objectiveVi: "Nắm sắc thái nâng cao của động từ khuyết thiếu (may well, need not have) và sự thay đổi nghĩa của động từ theo sau bởi gerund/infinitive (remember to do/doing, stop to do/doing).",
    estimatedMinutes: 9,
    grammarNoteVi:
      "may well: khả năng khá cao. needn't have + V3: đã không cần làm nhưng đã làm (khác shouldn't have — lời khuyên/chê trách về việc sai). remember to do (nhớ để LÀM, việc chưa xảy ra) vs remember doing (nhớ ĐÃ làm, việc đã xảy ra). stop to do (dừng lại ĐỂ làm việc khác) vs stop doing (NGỪNG làm việc đang làm).",
    vocabulary: [
      { id: 'en-b2-l3-2-v1', term: 'may well', translationVi: 'Rất có thể', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-2-s1' },
      { id: 'en-b2-l3-2-v2', term: 'need not have', translationVi: 'Đã không cần (nhưng đã làm)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-2-s2' },
      { id: 'en-b2-l3-2-v3', term: 'remember to do', translationVi: 'Nhớ để làm (việc chưa xảy ra)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-2-s3' },
      { id: 'en-b2-l3-2-v4', term: 'remember doing', translationVi: 'Nhớ đã làm (việc đã xảy ra)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-2-s4' },
      { id: 'en-b2-l3-2-v5', term: 'stop to do', translationVi: 'Dừng lại để làm (việc khác)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l3-2-s5' },
      { id: 'en-b2-l3-2-v6', term: 'stop doing', translationVi: 'Ngừng làm (việc đang làm)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-2-v7', term: 'go on to do', translationVi: 'Tiếp tục làm việc tiếp theo (sau việc khác)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-2-v8', term: 'try to do', translationVi: 'Cố gắng làm (nỗ lực)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-2-v9', term: 'try doing', translationVi: 'Thử làm (thử nghiệm cách khác)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-2-v10', term: 'forget to do', translationVi: 'Quên làm (việc cần làm)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-2-v11', term: 'forget doing', translationVi: 'Quên đã từng làm', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-2-v12', term: 'regret to inform', translationVi: 'Lấy làm tiếc phải thông báo', partOfSpeech: 'phrase' },
      { id: 'en-b2-l3-2-v13', term: 'regret doing', translationVi: 'Hối tiếc đã làm', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-b2-l3-2-s1', text: 'She may well be the best candidate for the job.', translationVi: 'Rất có thể cô ấy là ứng viên tốt nhất cho công việc này.' },
      { id: 'en-b2-l3-2-s2', text: "You needn't have brought a gift, but thank you.", translationVi: 'Bạn đã không cần mang quà đến đâu, nhưng cảm ơn nhé.' },
      { id: 'en-b2-l3-2-s3', text: 'Please remember to lock the door before you leave.', translationVi: 'Hãy nhớ khóa cửa trước khi bạn rời đi nhé.' },
      { id: 'en-b2-l3-2-s4', text: "I remember locking the door, but I can't find the key now.", translationVi: 'Tôi nhớ là đã khóa cửa, nhưng bây giờ tôi không tìm thấy chìa khóa.' },
      { id: 'en-b2-l3-2-s5', text: 'He stopped to answer his phone in the middle of the meeting.', translationVi: 'Anh ấy đã dừng lại để nghe điện thoại giữa cuộc họp.' },
    ],
    exercises: [
      {
        id: 'en-b2-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: đã không cần thiết nhưng đã làm.',
        question: 'You ___ brought a gift, but thank you.',
        options: ["needn't have", "shouldn't have", "mustn't have", "couldn't have"],
        correctOptionIndex: 0,
      },
      {
        id: 'en-b2-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng (nhớ để LÀM một việc trong tương lai).',
        sentenceTemplate: 'Please remember ___ the door before you leave.',
        wordBank: ['to lock', 'locking', 'locked'],
        correctAnswer: 'to lock',
      },
      {
        id: 'en-b2-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['in the middle of the meeting', 'he stopped to answer his phone'],
        correctOrder: ['he stopped to answer his phone', 'in the middle of the meeting'],
      },
    ],
  },
];
