import type { Lesson } from '../../../types';

export const englishB2RegretLessons: Lesson[] = [
  {
    id: 'en-b2-l1-1-third-conditional',
    unitId: 'en-b2-u1-regret-unreal',
    title: 'Third conditional',
    titleVi: 'Câu điều kiện loại 3',
    objectiveVi: 'Bày tỏ hối tiếc về một điều không có thật trong quá khứ và kết quả giả định của nó bằng câu điều kiện loại 3.',
    estimatedMinutes: 9,
    grammarNoteVi:
      "Third Conditional: If + S + had + V3, S + would have + V3. Diễn tả một điều kiện không có thật trong quá khứ và kết quả giả định — thường mang sắc thái hối tiếc: 'If I had studied harder, I would have passed the exam.' (Thực tế: tôi đã không học chăm nên đã trượt.)",
    vocabulary: [
      { id: 'en-b2-l1-1-v1', term: 'would have + V3', translationVi: 'Đã sẽ (kết quả giả định trong quá khứ)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-1-s1' },
      { id: 'en-b2-l1-1-v2', term: 'had + V3', translationVi: 'Đã (mệnh đề if quá khứ hoàn thành)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-1-s1' },
      { id: 'en-b2-l1-1-v3', term: 'regret', translationVi: 'Hối tiếc', partOfSpeech: 'verb', exampleSentenceId: 'en-b2-l1-1-s3' },
      { id: 'en-b2-l1-1-v4', term: 'in hindsight', translationVi: 'Nhìn lại thì', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-1-v5', term: 'missed opportunity', translationVi: 'Cơ hội đã bỏ lỡ', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-1-v6', term: 'look back', translationVi: 'Nhìn lại', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-1-s3' },
      { id: 'en-b2-l1-1-v7', term: 'turn out differently', translationVi: 'Diễn ra khác đi', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-1-v8', term: 'blow an opportunity', translationVi: 'Bỏ lỡ/làm hỏng cơ hội', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-1-v9', term: 'what if', translationVi: 'Nếu như... thì sao', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-1-v10', term: 'consequence', translationVi: 'Hậu quả', partOfSpeech: 'noun' },
      { id: 'en-b2-l1-1-v11', term: 'undo', translationVi: 'Hoàn tác, làm lại từ đầu', partOfSpeech: 'verb' },
      { id: 'en-b2-l1-1-v12', term: 'reflect on', translationVi: 'Suy ngẫm về', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-1-v13', term: 'could have', translationVi: 'Đã có thể (nhưng không làm)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-1-s5' },
    ],
    sentences: [
      { id: 'en-b2-l1-1-s1', text: 'If I had studied harder, I would have passed the exam.', translationVi: 'Nếu tôi đã học chăm chỉ hơn thì tôi đã đậu kỳ thi rồi.' },
      { id: 'en-b2-l1-1-s2', text: "If she had left earlier, she wouldn't have missed the flight.", translationVi: 'Nếu cô ấy đã rời đi sớm hơn thì cô ấy đã không lỡ chuyến bay.' },
      { id: 'en-b2-l1-1-s3', text: "Looking back, I regret not taking that job offer.", translationVi: 'Nhìn lại, tôi hối tiếc vì đã không nhận lời mời làm việc đó.' },
      { id: 'en-b2-l1-1-s4', text: 'If we had known about the traffic, we would have left earlier.', translationVi: 'Nếu chúng tôi đã biết về việc kẹt xe thì chúng tôi đã rời đi sớm hơn.' },
      { id: 'en-b2-l1-1-s5', text: 'I could have called you, but I forgot.', translationVi: 'Tôi đã có thể gọi cho bạn, nhưng tôi đã quên mất.' },
    ],
    exercises: [
      {
        id: 'en-b2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng cho mệnh đề if của câu điều kiện loại 3.',
        question: 'If I ___ (study) harder, I would have passed.',
        options: ['study', 'studied', 'had studied', 'have studied'],
        correctOptionIndex: 2,
      },
      {
        id: 'en-b2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng cho mệnh đề kết quả.',
        sentenceTemplate: "If she had left earlier, she ___ (not / miss) the flight.",
        wordBank: ["wouldn't have missed", "won't miss", "didn't miss"],
        correctAnswer: "wouldn't have missed",
      },
      {
        id: 'en-b2-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['earlier', 'we would have left', 'if we had known about the traffic'],
        correctOrder: ['if we had known about the traffic', 'we would have left', 'earlier'],
      },
    ],
  },
  {
    id: 'en-b2-l1-2-mixed-conditionals',
    unitId: 'en-b2-u1-regret-unreal',
    title: 'Mixed conditionals',
    titleVi: 'Câu điều kiện hỗn hợp',
    objectiveVi: 'Diễn tả mối liên hệ giữa một điều kiện không có thật ở một thời điểm và kết quả ở một thời điểm khác bằng câu điều kiện hỗn hợp.',
    estimatedMinutes: 9,
    grammarNoteVi:
      "Câu điều kiện hỗn hợp kết hợp hai mốc thời gian khác nhau. Dạng 1 (quá khứ → hiện tại): If + had + V3, would + V (nguyên mẫu) — 'If I had taken that job, I would be rich now.' Dạng 2 (hiện tại → quá khứ): If + V-ed, would have + V3 — 'If I weren't so busy, I would have gone to the party.'",
    vocabulary: [
      { id: 'en-b2-l1-2-v1', term: 'mixed conditional', translationVi: 'Câu điều kiện hỗn hợp', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-2-v2', term: 'would be', translationVi: 'Sẽ là (kết quả ở hiện tại)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-2-s1' },
      { id: 'en-b2-l1-2-v3', term: 'would have been', translationVi: 'Đã sẽ là (kết quả ở quá khứ)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-2-v4', term: 'career path', translationVi: 'Con đường sự nghiệp', partOfSpeech: 'noun' },
      { id: 'en-b2-l1-2-v5', term: 'financially stable', translationVi: 'Ổn định về tài chính', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-2-s5' },
      { id: 'en-b2-l1-2-v6', term: 'by nature', translationVi: 'Bản chất là, vốn dĩ', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-2-s4' },
      { id: 'en-b2-l1-2-v7', term: 'cautious', translationVi: 'Thận trọng', partOfSpeech: 'adjective', exampleSentenceId: 'en-b2-l1-2-s4' },
      { id: 'en-b2-l1-2-v8', term: 'impulsive', translationVi: 'Bốc đồng', partOfSpeech: 'adjective' },
      { id: 'en-b2-l1-2-v9', term: 'life-changing', translationVi: 'Thay đổi cuộc đời', partOfSpeech: 'adjective' },
      { id: 'en-b2-l1-2-v10', term: 'hypothetically', translationVi: 'Về mặt giả thuyết', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-2-v11', term: 'present circumstances', translationVi: 'Hoàn cảnh hiện tại', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-2-v12', term: 'root cause', translationVi: 'Nguyên nhân gốc rễ', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-2-v13', term: 'trace back to', translationVi: 'Bắt nguồn từ', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-b2-l1-2-s1', text: 'If I had taken that job, I would be rich now.', translationVi: 'Nếu tôi đã nhận công việc đó thì bây giờ tôi đã giàu rồi.' },
      { id: 'en-b2-l1-2-s2', text: "If I weren't so busy today, I would have gone to the party last night.", translationVi: 'Nếu hôm nay tôi không bận như vậy thì tối qua tôi đã đi dự tiệc rồi.' },
      { id: 'en-b2-l1-2-s3', text: "If she hadn't moved abroad, she would still be living near us.", translationVi: 'Nếu cô ấy đã không chuyển ra nước ngoài thì cô ấy vẫn sẽ đang sống gần chúng tôi.' },
      { id: 'en-b2-l1-2-s4', text: "If he were more cautious by nature, he wouldn't have made that impulsive decision.", translationVi: 'Nếu bản chất anh ấy thận trọng hơn thì anh ấy đã không đưa ra quyết định bốc đồng đó.' },
      { id: 'en-b2-l1-2-s5', text: 'If you had invested earlier, you would be financially stable now.', translationVi: 'Nếu bạn đã đầu tư sớm hơn thì bây giờ bạn đã ổn định tài chính rồi.' },
    ],
    exercises: [
      {
        id: 'en-b2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng cho mệnh đề if (quá khứ dẫn đến kết quả ở hiện tại).',
        question: 'If I ___ (take) that job, I would be rich now.',
        options: ['took', 'had taken', 'take', 'have taken'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-b2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng cho kết quả ở hiện tại.',
        sentenceTemplate: "If she hadn't moved abroad, she ___ (still / live) near us.",
        wordBank: ['would still be living', 'would still have lived', 'still lives'],
        correctAnswer: 'would still be living',
      },
      {
        id: 'en-b2-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['now', 'you would be financially stable', 'if you had invested earlier'],
        correctOrder: ['if you had invested earlier', 'you would be financially stable', 'now'],
      },
    ],
  },
  {
    id: 'en-b2-l1-3-wishes-regrets',
    unitId: 'en-b2-u1-regret-unreal',
    title: 'Wishes and regrets',
    titleVi: 'Mong ước và hối tiếc',
    objectiveVi: "Bày tỏ hối tiếc về quá khứ và mong ước khác với thực tại hiện tại bằng 'wish'/'if only'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "I wish/If only + had + V3 diễn tả hối tiếc về quá khứ: 'I wish I had studied harder.' I wish/If only + V-ed diễn tả mong ước khác với thực tại hiện tại: 'I wish I had more time.' (giống cấu trúc câu điều kiện loại 2 về thì).",
    vocabulary: [
      { id: 'en-b2-l1-3-v1', term: 'I wish', translationVi: 'Giá như, tôi ước', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-3-s1' },
      { id: 'en-b2-l1-3-v2', term: 'if only', translationVi: 'Giá như', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-3-s2' },
      { id: 'en-b2-l1-3-v3', term: 'regret', translationVi: 'Hối tiếc', partOfSpeech: 'verb' },
      { id: 'en-b2-l1-3-v4', term: 'take back (words)', translationVi: 'Rút lại (lời nói)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-3-v5', term: "hindsight is 20/20", translationVi: 'Nhìn lại thì mọi thứ đều rõ ràng (thành ngữ)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-3-v6', term: 'dwell on', translationVi: 'Cứ mãi nghĩ về, chìm đắm trong', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-3-s5' },
      { id: 'en-b2-l1-3-v7', term: 'move on', translationVi: 'Bước tiếp, vượt qua', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-3-v8', term: 'let bygones be bygones', translationVi: 'Chuyện gì qua rồi cho qua (thành ngữ)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-3-v9', term: "what's done is done", translationVi: 'Chuyện đã rồi (thành ngữ)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l1-3-s5' },
      { id: 'en-b2-l1-3-v10', term: 'second chance', translationVi: 'Cơ hội thứ hai', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-3-v11', term: 'make amends', translationVi: 'Sửa chữa lỗi lầm, bù đắp', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-3-v12', term: 'come to terms with', translationVi: 'Chấp nhận (một điều khó khăn)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l1-3-v13', term: "learn from one's mistakes", translationVi: 'Rút kinh nghiệm từ sai lầm của mình', partOfSpeech: 'phrase' },
    ],
    sentences: [
      { id: 'en-b2-l1-3-s1', text: 'I wish I had studied harder for the exam.', translationVi: 'Giá như tôi đã học chăm chỉ hơn cho kỳ thi.' },
      { id: 'en-b2-l1-3-s2', text: "If only I hadn't said those things.", translationVi: 'Giá như tôi đã không nói những điều đó.' },
      { id: 'en-b2-l1-3-s3', text: 'I wish I had more free time these days.', translationVi: 'Giá như dạo này tôi có nhiều thời gian rảnh hơn.' },
      { id: 'en-b2-l1-3-s4', text: 'She wishes she had taken the job when she had the chance.', translationVi: 'Cô ấy ước rằng đã nhận công việc đó khi có cơ hội.' },
      { id: 'en-b2-l1-3-s5', text: "There's no point dwelling on the past — what's done is done.", translationVi: 'Chẳng ích gì khi cứ mãi nghĩ về quá khứ — chuyện đã rồi thì cho qua.' },
    ],
    exercises: [
      {
        id: 'en-b2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng để hối tiếc về quá khứ.',
        question: 'I wish I ___ (study) harder.',
        options: ['study', 'studied', 'had studied', 'have studied'],
        correctOptionIndex: 2,
      },
      {
        id: 'en-b2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: 'If only I ___ (not / say) those things.',
        wordBank: ["hadn't said", "didn't say", "wouldn't say"],
        correctAnswer: "hadn't said",
      },
      {
        id: 'en-b2-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['these days', 'I wish', 'I had more free time'],
        correctOrder: ['I wish', 'I had more free time', 'these days'],
      },
    ],
  },
];
