import type { Lesson } from '../../../types';

export const englishB2ReportingLessons: Lesson[] = [
  {
    id: 'en-b2-l2-1-advanced-passive-reporting',
    unitId: 'en-b2-u2-advanced-reporting',
    title: 'Advanced passive reporting',
    titleVi: 'Tường thuật bằng câu bị động nâng cao',
    objectiveVi: "Tường thuật thông tin một cách khách quan, không nêu rõ nguồn, bằng cấu trúc 'It is said/believed that...' và 'S + is said/believed + to + V'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "It + be + said/believed/thought/reported + that + mệnh đề, hoặc S + be + said/believed/thought/reported + to + V (infinitive, hoặc to have + V3 cho thông tin về quá khứ). Dùng để tường thuật khách quan mà không cần nêu ai là người nói: 'It is believed that the ancient city was destroyed by an earthquake.' = 'The ancient city is believed to have been destroyed by an earthquake.'",
    vocabulary: [
      { id: 'en-b2-l2-1-v1', term: 'it is said that', translationVi: 'Người ta nói rằng', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-1-s1' },
      { id: 'en-b2-l2-1-v2', term: 'is believed to', translationVi: 'Được cho là', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-1-s2' },
      { id: 'en-b2-l2-1-v3', term: 'is thought to', translationVi: 'Được nghĩ là', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-1-s5' },
      { id: 'en-b2-l2-1-v4', term: 'is reported to', translationVi: 'Được báo cáo là', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-1-s3' },
      { id: 'en-b2-l2-1-v5', term: 'allegedly', translationVi: 'Được cho là (chưa xác thực)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l2-1-v6', term: 'widely regarded as', translationVi: 'Được xem là (rộng rãi)', partOfSpeech: 'phrase' },
      { id: 'en-b2-l2-1-v7', term: 'rumor has it that', translationVi: 'Có tin đồn rằng', partOfSpeech: 'phrase' },
      { id: 'en-b2-l2-1-v8', term: 'according to sources', translationVi: 'Theo các nguồn tin', partOfSpeech: 'phrase' },
      { id: 'en-b2-l2-1-v9', term: 'unconfirmed', translationVi: 'Chưa được xác nhận', partOfSpeech: 'adjective', exampleSentenceId: 'en-b2-l2-1-s4' },
      { id: 'en-b2-l2-1-v10', term: 'speculation', translationVi: 'Sự suy đoán', partOfSpeech: 'noun' },
      { id: 'en-b2-l2-1-v11', term: 'controversy', translationVi: 'Tranh cãi', partOfSpeech: 'noun' },
      { id: 'en-b2-l2-1-v12', term: 'deny', translationVi: 'Phủ nhận', partOfSpeech: 'verb' },
      { id: 'en-b2-l2-1-v13', term: 'confirm', translationVi: 'Xác nhận', partOfSpeech: 'verb', exampleSentenceId: 'en-b2-l2-1-s4' },
    ],
    sentences: [
      { id: 'en-b2-l2-1-s1', text: 'It is said that the company will announce layoffs next week.', translationVi: 'Người ta nói rằng công ty sẽ công bố sa thải nhân sự vào tuần tới.' },
      { id: 'en-b2-l2-1-s2', text: 'The ancient city is believed to have been destroyed by an earthquake.', translationVi: 'Thành phố cổ đại này được cho là đã bị phá hủy bởi một trận động đất.' },
      { id: 'en-b2-l2-1-s3', text: 'He is reported to have resigned from his position.', translationVi: 'Anh ấy được báo cáo là đã từ chức khỏi vị trí của mình.' },
      { id: 'en-b2-l2-1-s4', text: 'The rumors have not been confirmed yet.', translationVi: 'Những tin đồn vẫn chưa được xác nhận.' },
      { id: 'en-b2-l2-1-s5', text: 'The suspect is thought to be hiding in another country.', translationVi: 'Nghi phạm được cho là đang lẩn trốn ở một quốc gia khác.' },
    ],
    exercises: [
      {
        id: 'en-b2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: 'It ___ that the company will announce layoffs.',
        options: ['is said', 'says', 'was saying', 'said'],
        correctOptionIndex: 0,
      },
      {
        id: 'en-b2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: 'He ___ (report) to have resigned from his position.',
        wordBank: ['is reported', 'reports', 'reported'],
        correctAnswer: 'is reported',
      },
      {
        id: 'en-b2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['destroyed by an earthquake', 'the ancient city', 'is believed to have been'],
        correctOrder: ['the ancient city', 'is believed to have been', 'destroyed by an earthquake'],
      },
    ],
  },
  {
    id: 'en-b2-l2-2-participle-clauses',
    unitId: 'en-b2-u2-advanced-reporting',
    title: 'Participle clauses',
    titleVi: 'Mệnh đề phân từ',
    objectiveVi: 'Viết câu súc tích, trang trọng hơn bằng cách rút gọn mệnh đề quan hệ/trạng ngữ thành mệnh đề phân từ.',
    estimatedMinutes: 9,
    grammarNoteVi:
      "V-ing (phân từ hiện tại, chủ động): 'The man standing there is my boss.' (= who is standing). Having + V3 (hoàn thành, chủ động, hành động xảy ra trước): 'Having finished the report, she left the office.' (= After she had finished). V-ed/V3 (phân từ quá khứ, bị động): 'Written in 1990, the novel became a bestseller.' (= which was written).",
    vocabulary: [
      { id: 'en-b2-l2-2-v1', term: 'standing', translationVi: 'Đang đứng (phân từ chủ động)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-2-s1' },
      { id: 'en-b2-l2-2-v2', term: 'having finished', translationVi: 'Sau khi đã hoàn thành (phân từ hoàn thành)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-2-s2' },
      { id: 'en-b2-l2-2-v3', term: 'written', translationVi: 'Được viết (phân từ bị động)', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-2-s3' },
      { id: 'en-b2-l2-2-v4', term: 'feeling exhausted', translationVi: 'Cảm thấy kiệt sức', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-2-s4' },
      { id: 'en-b2-l2-2-v5', term: 'based on', translationVi: 'Dựa trên', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-2-s5' },
      { id: 'en-b2-l2-2-v6', term: 'given that', translationVi: 'Xét đến việc, cho rằng', partOfSpeech: 'phrase' },
      { id: 'en-b2-l2-2-v7', term: 'bestseller', translationVi: 'Sách bán chạy nhất', partOfSpeech: 'noun' },
      { id: 'en-b2-l2-2-v8', term: 'novel', translationVi: 'Tiểu thuyết', partOfSpeech: 'noun' },
      { id: 'en-b2-l2-2-v9', term: 'deadline', translationVi: 'Hạn chót', partOfSpeech: 'noun' },
      { id: 'en-b2-l2-2-v10', term: 'submit', translationVi: 'Nộp', partOfSpeech: 'verb' },
      { id: 'en-b2-l2-2-v11', term: 'approaching', translationVi: 'Đang đến gần', partOfSpeech: 'phrase' },
      { id: 'en-b2-l2-2-v12', term: 'promising', translationVi: 'Đầy hứa hẹn, triển vọng', partOfSpeech: 'adjective', exampleSentenceId: 'en-b2-l2-2-s5' },
      { id: 'en-b2-l2-2-v13', term: 'overwhelmed', translationVi: 'Quá tải, choáng ngợp', partOfSpeech: 'adjective' },
    ],
    sentences: [
      { id: 'en-b2-l2-2-s1', text: 'The man standing there is my boss.', translationVi: 'Người đàn ông đang đứng ở đó là sếp của tôi.' },
      { id: 'en-b2-l2-2-s2', text: 'Having finished the report, she left the office early.', translationVi: 'Sau khi đã hoàn thành báo cáo, cô ấy đã rời văn phòng sớm.' },
      { id: 'en-b2-l2-2-s3', text: 'Written in 1990, the novel became an instant bestseller.', translationVi: 'Được viết vào năm 1990, cuốn tiểu thuyết đã trở thành sách bán chạy ngay lập tức.' },
      { id: 'en-b2-l2-2-s4', text: 'Feeling exhausted, he decided to take a day off.', translationVi: 'Cảm thấy kiệt sức, anh ấy đã quyết định nghỉ một ngày.' },
      { id: 'en-b2-l2-2-s5', text: 'Based on the research, the results are promising.', translationVi: 'Dựa trên nghiên cứu, kết quả rất đầy hứa hẹn.' },
    ],
    exercises: [
      {
        id: 'en-b2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '___ finished the report, she left the office.',
        options: ['Have', 'Having', 'Had', 'Has'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-b2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: 'The man ___ (stand) there is my boss.',
        wordBank: ['standing', 'stood', 'stands'],
        correctAnswer: 'standing',
      },
      {
        id: 'en-b2-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['the novel became an instant bestseller', 'written in 1990'],
        correctOrder: ['written in 1990', 'the novel became an instant bestseller'],
      },
    ],
  },
  {
    id: 'en-b2-l2-3-advanced-relative-clauses',
    unitId: 'en-b2-u2-advanced-reporting',
    title: 'Advanced relative clauses',
    titleVi: 'Mệnh đề quan hệ nâng cao',
    objectiveVi: "Dùng mệnh đề quan hệ với giới từ và định lượng (some of whom, most of which...) trong văn phong trang trọng, học thuật.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "Mệnh đề quan hệ nâng cao kết hợp định lượng + of + whom/which: some of whom, many of which, most of whom, none of which — thường dùng trong văn viết trang trọng/học thuật. Giới từ + which/whom cũng phổ biến: in which, for whom.",
    vocabulary: [
      { id: 'en-b2-l2-3-v1', term: 'some of whom', translationVi: 'Trong số đó có một vài người mà', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-3-s1' },
      { id: 'en-b2-l2-3-v2', term: 'many of which', translationVi: 'Trong số đó có nhiều cái mà', partOfSpeech: 'phrase' },
      { id: 'en-b2-l2-3-v3', term: 'most of whom', translationVi: 'Phần lớn trong số đó là người mà', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-3-s2' },
      { id: 'en-b2-l2-3-v4', term: 'none of whom', translationVi: 'Không ai trong số đó', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-3-s3' },
      { id: 'en-b2-l2-3-v5', term: 'in which', translationVi: 'Trong đó', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-3-s4' },
      { id: 'en-b2-l2-3-v6', term: 'for whom', translationVi: 'Vì người mà, cho người mà', partOfSpeech: 'phrase', exampleSentenceId: 'en-b2-l2-3-s5' },
      { id: 'en-b2-l2-3-v7', term: 'attendees', translationVi: 'Người tham dự', partOfSpeech: 'noun', exampleSentenceId: 'en-b2-l2-3-s1' },
      { id: 'en-b2-l2-3-v8', term: 'participants', translationVi: 'Người tham gia', partOfSpeech: 'noun' },
      { id: 'en-b2-l2-3-v9', term: 'proposals', translationVi: 'Đề xuất', partOfSpeech: 'noun', exampleSentenceId: 'en-b2-l2-3-s2' },
      { id: 'en-b2-l2-3-v10', term: 'submit', translationVi: 'Nộp, đệ trình', partOfSpeech: 'verb' },
      { id: 'en-b2-l2-3-v11', term: 'approve', translationVi: 'Phê duyệt', partOfSpeech: 'verb' },
      { id: 'en-b2-l2-3-v12', term: 'candidates', translationVi: 'Ứng viên', partOfSpeech: 'noun', exampleSentenceId: 'en-b2-l2-3-s3' },
      { id: 'en-b2-l2-3-v13', term: 'shortlist', translationVi: 'Danh sách rút gọn', partOfSpeech: 'noun' },
    ],
    sentences: [
      { id: 'en-b2-l2-3-s1', text: 'There were fifty attendees, some of whom I had never met.', translationVi: 'Có năm mươi người tham dự, một số trong đó tôi chưa từng gặp bao giờ.' },
      { id: 'en-b2-l2-3-s2', text: 'The committee received twenty proposals, most of which were rejected.', translationVi: 'Hội đồng đã nhận được hai mươi đề xuất, phần lớn trong đó đã bị từ chối.' },
      { id: 'en-b2-l2-3-s3', text: 'She interviewed several candidates, none of whom had the required experience.', translationVi: 'Cô ấy đã phỏng vấn vài ứng viên, không ai trong số đó có đủ kinh nghiệm yêu cầu.' },
      { id: 'en-b2-l2-3-s4', text: 'This is the department in which I used to work.', translationVi: 'Đây là phòng ban mà tôi từng làm việc.' },
      { id: 'en-b2-l2-3-s5', text: 'There are many people for whom this policy will make a real difference.', translationVi: 'Có rất nhiều người mà chính sách này sẽ tạo ra sự khác biệt thực sự.' },
    ],
    exercises: [
      {
        id: 'en-b2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cụm từ đúng.',
        question: 'The committee received twenty proposals, ___ were rejected.',
        options: ['most of which', 'most of whom', 'most of them', 'most which'],
        correctOptionIndex: 0,
        explanationVi: "'Proposals' là vật, nên dùng 'which', không dùng 'whom'.",
      },
      {
        id: 'en-b2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền cụm từ đúng.',
        sentenceTemplate: 'There were fifty attendees, ___ I had never met.',
        wordBank: ['some of whom', 'some of which', 'some of them'],
        correctAnswer: 'some of whom',
      },
      {
        id: 'en-b2-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['I used to work', 'this is the department', 'in which'],
        correctOrder: ['this is the department', 'in which', 'I used to work'],
      },
    ],
  },
];
