import type { ConversationScenario } from '../../types';

export const englishA2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'en-a2-conv-daily-routine',
    languageCode: 'en',
    level: 'A2',
    title: 'Talking about your day',
    titleVi: 'Nói về một ngày của bạn',
    descriptionVi: 'Luyện hội thoại hỏi và kể về thói quen hằng ngày.',
    contextVi: 'Lan và An trò chuyện về lịch trình một ngày bình thường.',
    dialogue: [
      { id: 'en-a2-daily-turn-01', speaker: 'A', text: 'What time do you usually get up?', translationVi: 'Bạn thường thức dậy lúc mấy giờ?' },
      { id: 'en-a2-daily-turn-02', speaker: 'B', text: 'I usually get up at six thirty.', translationVi: 'Tôi thường thức dậy lúc 6 rưỡi.' },
      { id: 'en-a2-daily-turn-03', speaker: 'A', text: 'That early? What do you do first?', translationVi: 'Sớm vậy? Bạn làm gì đầu tiên?' },
      { id: 'en-a2-daily-turn-04', speaker: 'B', text: 'I go jogging, then I get dressed and have breakfast.', translationVi: 'Tôi đi chạy bộ, rồi mặc quần áo và ăn sáng.' },
      { id: 'en-a2-daily-turn-05', speaker: 'A', text: 'How do you commute to work?', translationVi: 'Bạn đi làm bằng gì?' },
      { id: 'en-a2-daily-turn-06', speaker: 'B', text: 'I usually take the bus, but sometimes I walk.', translationVi: 'Tôi thường đi xe buýt, nhưng thỉnh thoảng đi bộ.' },
      { id: 'en-a2-daily-turn-07', speaker: 'A', text: 'What are you doing right now?', translationVi: 'Bây giờ bạn đang làm gì?' },
      { id: 'en-a2-daily-turn-08', speaker: 'B', text: "I'm having lunch with my coworkers.", translationVi: 'Tôi đang ăn trưa với đồng nghiệp.' },
    ],
    relatedVocabularyIds: ['en-a2-l1-1-v1', 'en-a2-l1-1-v6', 'en-a2-l1-2-v4', 'en-a2-l1-3-v2'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi 'What time do you usually get up?'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: 'I usually get up at six thirty.' },
        { id: 'o2', text: 'I would like a coffee.' },
        { id: 'o3', text: 'Turn left at the corner.' },
        { id: 'o4', text: "I'm going to travel next year." },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về thói quen dùng Present Simple, nên trả lời bằng thời gian bạn thường làm việc đó.",
    },
  },
  {
    id: 'en-a2-conv-shopping-trip',
    languageCode: 'en',
    level: 'A2',
    title: 'A shopping trip',
    titleVi: 'Chuyến đi mua sắm',
    descriptionVi: 'Luyện hội thoại hỏi giá và thử đồ khi mua sắm.',
    contextVi: 'Lan đang mua một chiếc áo khoác tại cửa hàng quần áo.',
    dialogue: [
      { id: 'en-a2-shop-turn-01', speaker: 'A', text: 'Excuse me, how much is this jacket?', translationVi: 'Xin lỗi, áo khoác này giá bao nhiêu?' },
      { id: 'en-a2-shop-turn-02', speaker: 'B', text: "It's fifty dollars. Would you like to try it on?", translationVi: 'Giá 50 đô. Bạn có muốn thử không?' },
      { id: 'en-a2-shop-turn-03', speaker: 'A', text: 'Yes, please. Do you have a smaller size?', translationVi: 'Vâng, làm ơn. Bạn có cỡ nhỏ hơn không?' },
      { id: 'en-a2-shop-turn-04', speaker: 'B', text: 'Sure, here you go.', translationVi: 'Được, đây bạn.' },
      { id: 'en-a2-shop-turn-05', speaker: 'A', text: 'This is a bit too expensive for me. Is there a discount?', translationVi: 'Cái này hơi đắt với tôi. Có giảm giá không?' },
      { id: 'en-a2-shop-turn-06', speaker: 'B', text: "Yes, it's 20% off today.", translationVi: 'Có, hôm nay giảm 20%.' },
      { id: 'en-a2-shop-turn-07', speaker: 'A', text: "Great, I'll take it. Can I pay by cash?", translationVi: 'Tuyệt, tôi lấy nó. Tôi trả tiền mặt được không?' },
      { id: 'en-a2-shop-turn-08', speaker: 'B', text: 'Of course. Here is your receipt.', translationVi: 'Được chứ. Đây là hoá đơn của bạn.' },
    ],
    relatedVocabularyIds: ['en-a2-l2-2-v1', 'en-a2-l2-2-v2', 'en-a2-l2-2-v4', 'en-a2-l2-2-v5', 'en-a2-l2-2-v6'],
    task: {
      type: 'choose-reply',
      promptVi: "Nhân viên hỏi 'Would you like to try it on?'. Bạn muốn thử, trả lời thế nào?",
      options: [
        { id: 'o1', text: 'Yes, please.' },
        { id: 'o2', text: 'Turn left, please.' },
        { id: 'o3', text: "I'd like the check." },
        { id: 'o4', text: 'I went there last year.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Đồng ý làm gì đó, cách trả lời tự nhiên và lịch sự nhất là 'Yes, please.'",
    },
  },
  {
    id: 'en-a2-conv-making-plans',
    languageCode: 'en',
    level: 'A2',
    title: 'Making plans',
    titleVi: 'Lên kế hoạch và mời bạn',
    descriptionVi: 'Luyện hội thoại mời bạn bè và nói về kế hoạch tương lai.',
    contextVi: 'Minh mời An đi xem phim vào cuối tuần.',
    dialogue: [
      { id: 'en-a2-plans-turn-01', speaker: 'A', text: 'Would you like to watch a movie this weekend?', translationVi: 'Cuối tuần này bạn có muốn xem phim không?' },
      { id: 'en-a2-plans-turn-02', speaker: 'B', text: 'Sounds great! What time?', translationVi: 'Nghe hay đấy! Mấy giờ vậy?' },
      { id: 'en-a2-plans-turn-03', speaker: 'A', text: "I'm going to book tickets for seven PM.", translationVi: 'Tôi sẽ đặt vé lúc 7 giờ tối.' },
      { id: 'en-a2-plans-turn-04', speaker: 'B', text: "Perfect, I'll meet you there.", translationVi: 'Tuyệt, tôi sẽ gặp bạn ở đó.' },
      { id: 'en-a2-plans-turn-05', speaker: 'A', text: 'Have you seen the new action movie yet?', translationVi: 'Bạn đã xem phim hành động mới chưa?' },
      { id: 'en-a2-plans-turn-06', speaker: 'B', text: 'No, not yet. I heard it was really good.', translationVi: 'Chưa. Tôi nghe nói nó hay lắm.' },
      { id: 'en-a2-plans-turn-07', speaker: 'A', text: 'By the way, are you free next month too?', translationVi: 'À, tháng sau bạn có rảnh không?' },
      { id: 'en-a2-plans-turn-08', speaker: 'B', text: "I'm sorry, I have to decline — I'm traveling.", translationVi: 'Xin lỗi, tôi phải từ chối — tôi sẽ đi du lịch.' },
    ],
    relatedVocabularyIds: ['en-a2-l3-2-v1', 'en-a2-l3-2-v2', 'en-a2-l3-2-v3', 'en-a2-l3-2-v5', 'en-a2-l3-2-v6'],
    task: {
      type: 'complete-reply',
      promptVi: "Hoàn thành câu trả lời phù hợp cho lời mời 'Would you like to...?'",
      options: [
        { id: 'o1', text: 'Sounds great!' },
        { id: 'o2', text: "I'd like a coffee." },
        { id: 'o3', text: 'Turn right at the light.' },
        { id: 'o4', text: 'How much is this?' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi nhận lời mời một cách vui vẻ, cách trả lời tự nhiên là 'Sounds great!'",
    },
  },
];
