import type { GrammarTopic } from '../../types';

export const englishA2GrammarTopics: GrammarTopic[] = [
  {
    id: 'en-a2-gr-present-simple-vs-continuous',
    languageCode: 'en',
    level: 'A2',
    title: 'Present Simple vs Present Continuous',
    titleVi: 'Present Simple và Present Continuous',
    explanationVi:
      "Present Simple diễn tả thói quen, sự thật chung ('I work every day'). Present Continuous diễn tả việc đang diễn ra ngay lúc nói hoặc quanh thời điểm hiện tại ('I'm working right now').",
    structure: 'S + V(s/es) cho thói quen / S + am/is/are + V-ing cho việc đang diễn ra',
    keyPoints: [
      "Dấu hiệu Present Simple: every day, usually, always",
      "Dấu hiệu Present Continuous: now, right now, at the moment",
      'Động từ chỉ trạng thái (like, know, want) thường KHÔNG dùng dạng -ing',
    ],
    examples: [
      { id: 'en-a2-gr-pspc-s1', text: 'I usually walk to work.', translationVi: 'Tôi thường đi bộ đến chỗ làm.' },
      { id: 'en-a2-gr-pspc-s2', text: "I'm walking to work right now.", translationVi: 'Tôi đang đi bộ đến chỗ làm ngay bây giờ.' },
      { id: 'en-a2-gr-pspc-s3', text: 'She works at a bank.', translationVi: 'Cô ấy làm việc ở ngân hàng.' },
    ],
    commonMistakesVi: "Người học hay dùng -ing cho động từ trạng thái, ví dụ nói 'I'm knowing' thay vì 'I know'.",
    exercises: [
      {
        id: 'en-a2-gr-pspc-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: 'She ___ (work) at a bank.',
        options: ['work', 'works', 'is working', 'working'],
        correctOptionIndex: 1,
        explanationVi: "Sự thật chung về công việc dùng Present Simple, ngôi 'she' thêm -s.",
      },
      {
        id: 'en-a2-gr-pspc-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: 'Look! It ___ outside.',
        wordBank: ['is raining', 'rains', 'rain'],
        correctAnswer: 'is raining',
        explanationVi: "'Look!' báo hiệu việc đang xảy ra ngay lúc nói.",
      },
      {
        id: 'en-a2-gr-pspc-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['every', 'coffee', 'drink', 'I', 'morning'],
        correctOrder: ['I', 'drink', 'coffee', 'every', 'morning'],
        explanationVi: 'Thói quen lặp lại dùng Present Simple.',
      },
    ],
  },
  {
    id: 'en-a2-gr-past-simple',
    languageCode: 'en',
    level: 'A2',
    title: 'Past Simple',
    titleVi: 'Thì quá khứ đơn',
    explanationVi:
      "Past Simple diễn tả hành động đã hoàn tất trong quá khứ, thường có mốc thời gian cụ thể. Động từ có quy tắc thêm -ed, động từ bất quy tắc có dạng riêng (go→went, have→had).",
    structure: 'S + V-ed (quy tắc) / S + V2 (bất quy tắc)',
    keyPoints: [
      "Dấu hiệu: yesterday, last week, ... ago, in 2020",
      "Phủ định: didn't + V nguyên mẫu (không chia thêm -ed)",
      'Câu hỏi: Did + S + V nguyên mẫu?',
    ],
    examples: [
      { id: 'en-a2-gr-past-s1', text: 'I visited my grandmother yesterday.', translationVi: 'Tôi đã thăm bà tôi hôm qua.' },
      { id: 'en-a2-gr-past-s2', text: "I didn't watch TV last night.", translationVi: 'Tối qua tôi đã không xem TV.' },
      { id: 'en-a2-gr-past-s3', text: 'Did you finish your homework?', translationVi: 'Bạn đã làm xong bài tập chưa?' },
    ],
    commonMistakesVi: "Sau 'didn't'/'did' người học hay vẫn chia động từ theo quá khứ, ví dụ 'I didn't went' thay vì 'I didn't go'.",
    exercises: [
      {
        id: 'en-a2-gr-past-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: 'I ___ (visit) my grandmother yesterday.',
        options: ['visit', 'visited', 'visits', 'am visiting'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-a2-gr-past-ex2',
        type: 'fill-blank',
        promptVi: "Điền động từ đúng dạng sau 'didn't'.",
        sentenceTemplate: "I didn't ___ TV last night.",
        wordBank: ['watch', 'watched', 'watches'],
        correctAnswer: 'watch',
      },
      {
        id: 'en-a2-gr-past-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu hỏi đúng.',
        words: ['finish', 'your homework', 'did', 'you'],
        correctOrder: ['did', 'you', 'finish', 'your homework'],
      },
    ],
  },
  {
    id: 'en-a2-gr-future-forms',
    languageCode: 'en',
    level: 'A2',
    title: '"Going to" and "will"',
    titleVi: 'Diễn tả tương lai: "going to" và "will"',
    explanationVi:
      "'Going to' dùng cho dự định đã quyết định trước khi nói. 'Will' dùng cho quyết định ngay lúc nói hoặc dự đoán không chắc chắn.",
    structure: 'S + am/is/are + going to + V / S + will + V',
    keyPoints: [
      "'I'm going to travel next month.' (đã lên kế hoạch từ trước)",
      "'I think it will rain.' (dự đoán)",
      "'I'll help you!' (quyết định ngay lúc nói)",
    ],
    examples: [
      { id: 'en-a2-gr-future-s1', text: "I'm going to study abroad.", translationVi: 'Tôi định đi du học.' },
      { id: 'en-a2-gr-future-s2', text: 'I think it will rain tomorrow.', translationVi: 'Tôi nghĩ ngày mai trời sẽ mưa.' },
      { id: 'en-a2-gr-future-s3', text: "OK, I'll call you tonight.", translationVi: 'Được, tối nay tôi sẽ gọi cho bạn.' },
    ],
    commonMistakesVi: "Người học hay dùng 'will' cho kế hoạch đã quyết định từ trước, trong khi 'going to' phù hợp hơn.",
    exercises: [
      {
        id: 'en-a2-gr-future-ex1',
        type: 'multiple-choice',
        promptVi: 'Bạn đã lên kế hoạch từ tuần trước. Chọn dạng đúng.',
        question: 'I ___ (already planned) travel to Japan next month.',
        options: ["am going to", 'will', 'go', 'going'],
        correctOptionIndex: 0,
      },
      {
        id: 'en-a2-gr-future-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu (quyết định ngay lúc nói).',
        sentenceTemplate: "OK, I'll ___ you tonight.",
        wordBank: ['call', 'calling', 'calls'],
        correctAnswer: 'call',
      },
      {
        id: 'en-a2-gr-future-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['abroad', 'to study', "I'm", 'going'],
        correctOrder: ["I'm", 'going', 'to study', 'abroad'],
      },
    ],
  },
  {
    id: 'en-a2-gr-comparatives',
    languageCode: 'en',
    level: 'A2',
    title: 'Comparative adjectives',
    titleVi: 'Tính từ so sánh hơn',
    explanationVi:
      "Tính từ ngắn (1 âm tiết) thêm '-er' ('bigger'). Tính từ dài (2+ âm tiết) dùng 'more' ('more expensive'). Một số tính từ bất quy tắc: good→better, bad→worse.",
    structure: 'Adj-er + than / more + Adj + than',
    keyPoints: [
      "big → bigger, cheap → cheaper",
      "expensive → more expensive, beautiful → more beautiful",
      'good → better, bad → worse (bất quy tắc)',
    ],
    examples: [
      { id: 'en-a2-gr-comp-s1', text: 'This bag is bigger than that one.', translationVi: 'Túi này to hơn túi kia.' },
      { id: 'en-a2-gr-comp-s2', text: 'The blue jacket is more expensive than the red one.', translationVi: 'Áo khoác xanh đắt hơn áo đỏ.' },
      { id: 'en-a2-gr-comp-s3', text: 'My new phone is better than my old one.', translationVi: 'Điện thoại mới của tôi tốt hơn cái cũ.' },
    ],
    commonMistakesVi: "Người học hay nói 'more bigger' (dùng cả 'more' lẫn '-er' cùng lúc), chỉ cần chọn một cách.",
    exercises: [
      {
        id: 'en-a2-gr-comp-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng so sánh đúng của "cheap".',
        question: 'This one is ___ than that one. (cheap)',
        options: ['cheap', 'cheaper', 'more cheap', 'cheapest'],
        correctOptionIndex: 1,
      },
      {
        id: 'en-a2-gr-comp-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng so sánh đúng của "expensive".',
        sentenceTemplate: 'The jacket is ___ than the shirt.',
        wordBank: ['more expensive', 'expensiver', 'expensive'],
        correctAnswer: 'more expensive',
      },
      {
        id: 'en-a2-gr-comp-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng so sánh bất quy tắc đúng của "good".',
        question: 'My new phone is ___ than my old one.',
        options: ['gooder', 'more good', 'better', 'best'],
        correctOptionIndex: 2,
      },
    ],
  },
  {
    id: 'en-a2-gr-adverbs-of-frequency',
    languageCode: 'en',
    level: 'A2',
    title: 'Adverbs of frequency',
    titleVi: 'Trạng từ chỉ tần suất',
    explanationVi:
      "Trạng từ tần suất (always, usually, often, sometimes, rarely, never) diễn tả mức độ thường xuyên. Vị trí: trước động từ thường, sau động từ 'to be'.",
    structure: 'S + adverb + V thường / S + to be + adverb',
    keyPoints: [
      "'I always eat breakfast.' (trước động từ thường)",
      "'She is often late.' (sau to be)",
      'Thứ tự mức độ: always > usually > often > sometimes > rarely > never',
    ],
    examples: [
      { id: 'en-a2-gr-freq-s1', text: 'I always eat breakfast.', translationVi: 'Tôi luôn ăn sáng.' },
      { id: 'en-a2-gr-freq-s2', text: 'She is often late for class.', translationVi: 'Cô ấy thường đi học muộn.' },
      { id: 'en-a2-gr-freq-s3', text: 'We rarely go to the cinema.', translationVi: 'Chúng tôi hiếm khi đi xem phim.' },
    ],
    commonMistakesVi: "Người học hay đặt trạng từ tần suất sai vị trí, ví dụ 'I eat always breakfast' thay vì 'I always eat breakfast'.",
    exercises: [
      {
        id: 'en-a2-gr-freq-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng vị trí trạng từ.',
        question: 'Choose the correct sentence.',
        options: ['I always eat breakfast.', 'I eat always breakfast.', 'Always I eat breakfast.', 'I eat breakfast always never.'],
        correctOptionIndex: 0,
      },
      {
        id: 'en-a2-gr-freq-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trạng từ đúng vị trí với "to be".',
        sentenceTemplate: 'She is ___ late for class.',
        wordBank: ['often', 'commute', 'ago'],
        correctAnswer: 'often',
      },
      {
        id: 'en-a2-gr-freq-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của 'rarely'.",
        question: 'rarely',
        options: ['Luôn luôn', 'Thường xuyên', 'Hiếm khi', 'Không bao giờ'],
        correctOptionIndex: 2,
      },
    ],
  },
];
