import type { Lesson } from '../../../types';

export const chineseA2DailyLifeLessons: Lesson[] = [
  {
    id: 'zh-a2-l1-1-daily-routine',
    unitId: 'zh-a2-u1-daily-life',
    title: '日常生活',
    titleVi: 'Thói quen hằng ngày',
    objectiveVi: "Mô tả các việc bạn làm hằng ngày và kể lại việc đã hoàn thành bằng trợ từ 了.",
    estimatedMinutes: 7,
    grammarNoteVi:
      "了 đặt sau động từ để chỉ hành động đã hoàn thành. Ví dụ: 我起床了 (Tôi đã dậy rồi). Khác 过 (đã từng), 了 nhấn vào việc VỪA XẢY RA/hoàn tất.",
    vocabulary: [
      { id: 'zh-a2-l1-1-v1', term: '起床', translationVi: 'Thức dậy', partOfSpeech: 'verb', exampleSentenceId: 'zh-a2-l1-1-s1', usageNoteVi: 'Cách đọc: qǐchuáng' },
      { id: 'zh-a2-l1-1-v2', term: '洗澡', translationVi: 'Tắm rửa', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: xǐzǎo' },
      { id: 'zh-a2-l1-1-v3', term: '上班', translationVi: 'Đi làm', partOfSpeech: 'verb', exampleSentenceId: 'zh-a2-l1-1-s2', usageNoteVi: 'Cách đọc: shàngbān' },
      { id: 'zh-a2-l1-1-v4', term: '回家', translationVi: 'Về nhà', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: huíjiā' },
      { id: 'zh-a2-l1-1-v5', term: '昨天', translationVi: 'Hôm qua', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l1-1-s3', usageNoteVi: 'Cách đọc: zuótiān' },
      { id: 'zh-a2-l1-1-v6', term: '一般', translationVi: 'Thường thì', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: yìbān' },
    ],
    sentences: [
      { id: 'zh-a2-l1-1-s1', text: '我一般七点起床。', translationVi: '(Wǒ yìbān qī diǎn qǐchuáng.) Tôi thường dậy lúc bảy giờ.' },
      { id: 'zh-a2-l1-1-s2', text: '我九点上班。', translationVi: '(Wǒ jiǔ diǎn shàngbān.) Tôi đi làm lúc chín giờ.' },
      { id: 'zh-a2-l1-1-s3', text: '昨天我六点起床了。', translationVi: '(Zuótiān wǒ liù diǎn qǐchuáng le.) Hôm qua tôi đã dậy lúc sáu giờ.' },
    ],
    exercises: [
      {
        id: 'zh-a2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ đúng để chỉ hành động đã hoàn thành.",
        question: '昨天我六点起床___。',
        options: ['了', '过', '在', '要'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-a2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '我九点___。',
        wordBank: ['上班', '洗澡', '昨天'],
        correctAnswer: '上班',
      },
      {
        id: 'zh-a2-l1-1-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '一般'.",
        question: '一般',
        options: ['Hôm qua', 'Thường thì', 'Hôm nay', 'Ngày mai'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'zh-a2-l1-2-time',
    unitId: 'zh-a2-u1-daily-life',
    title: '时间',
    titleVi: 'Giờ giấc',
    objectiveVi: "Nói giờ và hành động đang diễn ra bằng '在...'.",
    estimatedMinutes: 7,
    grammarNoteVi: "在 đặt trước động từ để diễn tả hành động đang diễn ra (tương đương '-ing'). Ví dụ: 我在吃饭 (Tôi đang ăn cơm).",
    vocabulary: [
      { id: 'zh-a2-l1-2-v1', term: '现在', translationVi: 'Bây giờ', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l1-2-s1', usageNoteVi: 'Cách đọc: xiànzài' },
      { id: 'zh-a2-l1-2-v2', term: '几点了？', translationVi: 'Mấy giờ rồi?', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l1-2-s2', usageNoteVi: 'Cách đọc: jǐ diǎn le?' },
      { id: 'zh-a2-l1-2-v3', term: '半', translationVi: 'Rưỡi (30 phút)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: bàn' },
      { id: 'zh-a2-l1-2-v4', term: '早', translationVi: 'Sớm', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: zǎo' },
      { id: 'zh-a2-l1-2-v5', term: '晚', translationVi: 'Muộn', partOfSpeech: 'adjective', exampleSentenceId: 'zh-a2-l1-2-s3', usageNoteVi: 'Cách đọc: wǎn' },
      { id: 'zh-a2-l1-2-v6', term: '已经', translationVi: 'Đã, rồi', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: yǐjīng' },
    ],
    sentences: [
      { id: 'zh-a2-l1-2-s1', text: '现在几点了？', translationVi: '(Xiànzài jǐ diǎn le?) Bây giờ mấy giờ rồi?' },
      { id: 'zh-a2-l1-2-s2', text: '我在吃饭。', translationVi: '(Wǒ zài chīfàn.) Tôi đang ăn cơm.' },
      { id: 'zh-a2-l1-2-s3', text: '今天我起得很晚。', translationVi: '(Jīntiān wǒ qǐ de hěn wǎn.) Hôm nay tôi dậy rất muộn.' },
    ],
    exercises: [
      {
        id: 'zh-a2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: hành động đang diễn ra.',
        question: '我___吃饭。',
        options: ['在', '了', '过', '会'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-a2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '现在几___了？',
        wordBank: ['点', '半', '晚'],
        correctAnswer: '点',
      },
      {
        id: 'zh-a2-l1-2-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '早'.",
        question: '早',
        options: ['Muộn', 'Sớm', 'Bây giờ', 'Đã rồi'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'zh-a2-l1-3-hobbies',
    unitId: 'zh-a2-u1-daily-life',
    title: '爱好',
    titleVi: 'Sở thích',
    objectiveVi: "Nói về sở thích và so sánh bằng '比' (hơn).",
    estimatedMinutes: 7,
    grammarNoteVi: "比 dùng để so sánh: A 比 B + tính từ, nghĩa là 'A hơn B'. Ví dụ: 音乐比电影有意思 (Âm nhạc thú vị hơn phim).",
    vocabulary: [
      { id: 'zh-a2-l1-3-v1', term: '爱好', translationVi: 'Sở thích', partOfSpeech: 'noun', exampleSentenceId: 'zh-a2-l1-3-s1', usageNoteVi: 'Cách đọc: àihào' },
      { id: 'zh-a2-l1-3-v2', term: '听音乐', translationVi: 'Nghe nhạc', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: tīng yīnyuè' },
      { id: 'zh-a2-l1-3-v3', term: '运动', translationVi: 'Tập thể dục, thể thao', partOfSpeech: 'verb', exampleSentenceId: 'zh-a2-l1-3-s2', usageNoteVi: 'Cách đọc: yùndòng' },
      { id: 'zh-a2-l1-3-v4', term: '比', translationVi: 'So với, hơn', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l1-3-s3', usageNoteVi: 'Cách đọc: bǐ' },
      { id: 'zh-a2-l1-3-v5', term: '看电影', translationVi: 'Xem phim', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: kàn diànyǐng' },
    ],
    sentences: [
      { id: 'zh-a2-l1-3-s1', text: '我的爱好是听音乐。', translationVi: '(Wǒ de àihào shì tīng yīnyuè.) Sở thích của tôi là nghe nhạc.' },
      { id: 'zh-a2-l1-3-s2', text: '我每天运动。', translationVi: '(Wǒ měitiān yùndòng.) Tôi tập thể dục mỗi ngày.' },
      { id: 'zh-a2-l1-3-s3', text: '音乐比电影有意思。', translationVi: '(Yīnyuè bǐ diànyǐng yǒuyìsi.) Âm nhạc thú vị hơn phim.' },
    ],
    exercises: [
      {
        id: 'zh-a2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '爱好'.",
        question: '爱好',
        options: ['Nghề nghiệp', 'Sở thích', 'Gia đình', 'Thời gian'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-a2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ so sánh còn thiếu.',
        sentenceTemplate: '音乐___电影有意思。',
        wordBank: ['比', '在', '了'],
        correctAnswer: '比',
      },
      {
        id: 'zh-a2-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi tập thể dục mỗi ngày."',
        words: ['运动', '我', '每天'],
        correctOrder: ['我', '每天', '运动'],
      },
    ],
  },
];
