import type { Lesson } from '../../../types';

export const chineseA2TravelLessons: Lesson[] = [
  {
    id: 'zh-a2-l2-1-transportation',
    unitId: 'zh-a2-u2-travel',
    title: '交通',
    titleVi: 'Phương tiện giao thông',
    objectiveVi: "Nói cách di chuyển và dùng cấu trúc '要' (sẽ/muốn) khi nói kế hoạch di chuyển.",
    estimatedMinutes: 7,
    grammarNoteVi: "要 trước động từ diễn tả ý định/dự định gần, nghĩa là 'sẽ/muốn'. Ví dụ: 我要坐地铁 (Tôi sẽ đi tàu điện ngầm).",
    vocabulary: [
      { id: 'zh-a2-l2-1-v1', term: '地铁', translationVi: 'Tàu điện ngầm', partOfSpeech: 'noun', exampleSentenceId: 'zh-a2-l2-1-s1', usageNoteVi: 'Cách đọc: dìtiě' },
      { id: 'zh-a2-l2-1-v2', term: '公交车', translationVi: 'Xe buýt', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: gōngjiāochē' },
      { id: 'zh-a2-l2-1-v3', term: '坐', translationVi: 'Đi (phương tiện), ngồi', partOfSpeech: 'verb', exampleSentenceId: 'zh-a2-l2-1-s2', usageNoteVi: 'Cách đọc: zuò' },
      { id: 'zh-a2-l2-1-v4', term: '要多长时间？', translationVi: 'Mất bao lâu?', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l2-1-s3', usageNoteVi: 'Cách đọc: yào duō cháng shíjiān?' },
      { id: 'zh-a2-l2-1-v5', term: '站', translationVi: 'Ga, trạm', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: zhàn' },
      { id: 'zh-a2-l2-1-v6', term: '换乘', translationVi: 'Chuyển tuyến, đổi xe', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: huànchéng' },
    ],
    sentences: [
      { id: 'zh-a2-l2-1-s1', text: '我要坐地铁。', translationVi: '(Wǒ yào zuò dìtiě.) Tôi sẽ đi tàu điện ngầm.' },
      { id: 'zh-a2-l2-1-s2', text: '在这站换乘公交车。', translationVi: '(Zài zhè zhàn huànchéng gōngjiāochē.) Chuyển sang xe buýt ở trạm này.' },
      { id: 'zh-a2-l2-1-s3', text: '从家到公司要多长时间？', translationVi: '(Cóng jiā dào gōngsī yào duō cháng shíjiān?) Từ nhà đến công ty mất bao lâu?' },
    ],
    exercises: [
      {
        id: 'zh-a2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '地铁'.",
        question: '地铁',
        options: ['Xe buýt', 'Tàu điện ngầm', 'Taxi', 'Xe đạp'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-a2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '我___坐地铁。',
        wordBank: ['要', '了', '比'],
        correctAnswer: '要',
      },
      {
        id: 'zh-a2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi sẽ đi tàu điện ngầm."',
        words: ['地铁', '要', '我', '坐'],
        correctOrder: ['我', '要', '坐', '地铁'],
      },
    ],
  },
  {
    id: 'zh-a2-l2-2-shopping',
    unitId: 'zh-a2-u2-travel',
    title: '购物',
    titleVi: 'Mua sắm',
    objectiveVi: 'Hỏi giá và mặc cả khi mua sắm.',
    estimatedMinutes: 7,
    grammarNoteVi: "虽然...但是... nghĩa là 'mặc dù...nhưng...', nối hai vế câu đối lập. Ví dụ: 虽然漂亮，但是贵 (Mặc dù đẹp nhưng đắt).",
    vocabulary: [
      { id: 'zh-a2-l2-2-v1', term: '多少钱？', translationVi: 'Bao nhiêu tiền?', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l2-2-s1', usageNoteVi: 'Cách đọc: duōshao qián?' },
      { id: 'zh-a2-l2-2-v2', term: '贵', translationVi: 'Đắt', partOfSpeech: 'adjective', exampleSentenceId: 'zh-a2-l2-2-s2', usageNoteVi: 'Cách đọc: guì' },
      { id: 'zh-a2-l2-2-v3', term: '便宜', translationVi: 'Rẻ', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: piányi' },
      { id: 'zh-a2-l2-2-v4', term: '便宜一点儿', translationVi: 'Bớt chút được không', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l2-2-s3', usageNoteVi: 'Cách đọc: piányi yìdiǎnr' },
      { id: 'zh-a2-l2-2-v5', term: '试穿', translationVi: 'Mặc thử', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: shìchuān' },
    ],
    sentences: [
      { id: 'zh-a2-l2-2-s1', text: '这个多少钱？', translationVi: '(Zhège duōshao qián?) Cái này bao nhiêu tiền?' },
      { id: 'zh-a2-l2-2-s2', text: '虽然漂亮，但是有点贵。', translationVi: '(Suīrán piàoliang, dànshì yǒudiǎn guì.) Mặc dù đẹp nhưng hơi đắt.' },
      { id: 'zh-a2-l2-2-s3', text: '能便宜一点儿吗？', translationVi: '(Néng piányi yìdiǎnr ma?) Bớt một chút được không?' },
    ],
    exercises: [
      {
        id: 'zh-a2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '贵'.",
        question: '贵',
        options: ['Rẻ', 'Đắt', 'Đẹp', 'Nhỏ'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-a2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: "Điền cặp từ nối 'mặc dù...nhưng...' còn thiếu.",
        sentenceTemplate: '___漂亮，但是贵。',
        wordBank: ['虽然', '因为', '还是'],
        correctAnswer: '虽然',
      },
      {
        id: 'zh-a2-l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi giá.',
        question: '选择正确的问题。',
        options: ['这个多少钱？', '现在几点了？', '你从哪里来？', '你的爱好是什么？'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'zh-a2-l2-3-food',
    unitId: 'zh-a2-u2-travel',
    title: '点餐',
    titleVi: 'Gọi món ăn',
    objectiveVi: "Gọi món tại nhà hàng và chọn lựa bằng '还是' (hay là).",
    estimatedMinutes: 7,
    grammarNoteVi: "还是 dùng trong câu hỏi lựa chọn: A 还是 B?, nghĩa là 'A hay là B?'. Ví dụ: 你要咖啡还是茶？(Bạn muốn cà phê hay trà?)",
    vocabulary: [
      { id: 'zh-a2-l2-3-v1', term: '菜单', translationVi: 'Thực đơn', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: càidān' },
      { id: 'zh-a2-l2-3-v2', term: '推荐', translationVi: 'Gợi ý, đề xuất', partOfSpeech: 'verb', exampleSentenceId: 'zh-a2-l2-3-s1', usageNoteVi: 'Cách đọc: tuījiàn' },
      { id: 'zh-a2-l2-3-v3', term: '辣', translationVi: 'Cay', partOfSpeech: 'adjective', exampleSentenceId: 'zh-a2-l2-3-s2', usageNoteVi: 'Cách đọc: là' },
      { id: 'zh-a2-l2-3-v4', term: '还是', translationVi: 'Hay là', partOfSpeech: 'phrase', exampleSentenceId: 'zh-a2-l2-3-s3', usageNoteVi: 'Cách đọc: háishi' },
      { id: 'zh-a2-l2-3-v5', term: '买单', translationVi: 'Tính tiền, thanh toán', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: mǎidān' },
    ],
    sentences: [
      { id: 'zh-a2-l2-3-s1', text: '你推荐什么菜？', translationVi: '(Nǐ tuījiàn shénme cài?) Bạn gợi ý món gì?' },
      { id: 'zh-a2-l2-3-s2', text: '这个菜辣吗？', translationVi: '(Zhège cài là ma?) Món này có cay không?' },
      { id: 'zh-a2-l2-3-s3', text: '你要咖啡还是茶？', translationVi: '(Nǐ yào kāfēi háishi chá?) Bạn muốn cà phê hay trà?' },
    ],
    exercises: [
      {
        id: 'zh-a2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '辣'.",
        question: '辣',
        options: ['Ngọt', 'Cay', 'Mặn', 'Chua'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-a2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ lựa chọn còn thiếu.',
        sentenceTemplate: '你要咖啡___茶？',
        wordBank: ['还是', '比', '了'],
        correctAnswer: '还是',
      },
      {
        id: 'zh-a2-l2-3-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để xin gợi ý món ăn.',
        question: '选择正确的问题。',
        options: ['你推荐什么菜？', '多少钱？', '几点了？', '你从哪里来？'],
        correctOptionIndex: 0,
      },
    ],
  },
];
