import type { ConversationScenario } from '../../types';

export const chineseB2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'zh-b2-conv-weishenme-chidao',
    languageCode: 'zh',
    level: 'B2',
    title: '为什么没来开会',
    titleVi: 'Vì sao không đến họp',
    descriptionVi: 'Luyện hội thoại giải thích tình huống bằng 是...的, 一...就..., và bổ ngữ khả năng.',
    contextVi: 'An hỏi Minh vì sao hôm qua không đến họp.',
    dialogue: [
      { id: 'zh-b2-weishenme-turn-01', speaker: 'A', text: '你昨天怎么没来开会？', translationVi: '(Nǐ zuótiān zěnme méi lái kāihuì?) Sao hôm qua bạn không đến họp?' },
      { id: 'zh-b2-weishenme-turn-02', speaker: 'B', text: '对不起，我一起床就发现自己生病了。', translationVi: '(Duìbuqǐ, wǒ yì qǐchuáng jiù fāxiàn zìjǐ shēngbìng le.) Xin lỗi, tôi vừa thức dậy đã phát hiện mình bị ốm.' },
      { id: 'zh-b2-weishenme-turn-03', speaker: 'A', text: '是什么时候开始不舒服的？', translationVi: '(Shì shénme shíhou kāishǐ bù shūfu de?) Bạn thấy khó chịu từ khi nào vậy?' },
      { id: 'zh-b2-weishenme-turn-04', speaker: 'B', text: '是昨天晚上开始的。', translationVi: '(Shì zuótiān wǎnshang kāishǐ de.) Là bắt đầu từ tối qua.' },
      { id: 'zh-b2-weishenme-turn-05', speaker: 'A', text: '那你现在好点了吗？', translationVi: '(Nà nǐ xiànzài hǎo diǎn le ma?) Vậy giờ bạn đỡ hơn chưa?' },
      { id: 'zh-b2-weishenme-turn-06', speaker: 'B', text: '好多了，医生说的话我都听得懂，吃了药就好了。', translationVi: '(Hǎo duō le, yīshēng shuō de huà wǒ dōu tīng de dǒng, chī le yào jiù hǎo le.) Đỡ nhiều rồi, lời bác sĩ nói tôi hiểu hết được, uống thuốc là khỏi.' },
      { id: 'zh-b2-weishenme-turn-07', speaker: 'A', text: '那太好了。下次有事一定要提前告诉我。', translationVi: '(Nà tài hǎo le. Xiàcì yǒu shì yídìng yào tíqián gàosu wǒ.) Vậy tốt quá. Lần sau có việc gì nhớ báo trước cho tôi nhé.' },
      { id: 'zh-b2-weishenme-turn-08', speaker: 'B', text: '好的，一有情况我就马上联系你。', translationVi: '(Hǎo de, yì yǒu qíngkuàng wǒ jiù mǎshàng liánxì nǐ.) Được, hễ có tình huống gì là tôi liên lạc với bạn ngay.' },
    ],
    relatedVocabularyIds: ['zh-b2-l1-1-v1', 'zh-b2-l1-2-v1', 'zh-b2-l1-3-v1', 'zh-b2-l1-1-v11'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '是什么时候开始不舒服的？'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: '是昨天晚上开始的。' },
        { id: 'o2', text: '无论多忙，我都会给你打电话。' },
        { id: 'o3', text: '除非你道歉，否则我不会原谅你。' },
        { id: 'o4', text: '尽管天气不好，我们还是决定出发。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi hỏi về thời điểm bắt đầu của một việc đã xảy ra, nên trả lời bằng cấu trúc nhấn mạnh thời gian '是...的'.",
    },
  },
  {
    id: 'zh-b2-conv-wulun-duo-nan',
    languageCode: 'zh',
    level: 'B2',
    title: '无论多难都要完成',
    titleVi: 'Dù khó đến đâu cũng phải hoàn thành',
    descriptionVi: 'Luyện hội thoại thể hiện quyết tâm trước khó khăn bằng 无论都, 连都, 除非否则.',
    contextVi: 'An và Minh đang bàn về một dự án gấp rút với thời hạn ngắn.',
    dialogue: [
      { id: 'zh-b2-wulun-turn-01', speaker: 'A', text: '这个项目太难了，我们真的能完成吗？', translationVi: '(Zhège xiàngmù tài nán le, wǒmen zhēnde néng wánchéng ma?) Dự án này khó quá, chúng ta thực sự có thể hoàn thành không?' },
      { id: 'zh-b2-wulun-turn-02', speaker: 'B', text: '无论多难，我们都要完成，这是我们的责任。', translationVi: '(Wúlùn duō nán, wǒmen dōu yào wánchéng, zhè shì wǒmen de zérèn.) Dù khó đến mấy thì chúng ta cũng phải hoàn thành, đây là trách nhiệm của chúng ta.' },
      { id: 'zh-b2-wulun-turn-03', speaker: 'A', text: '可是时间太紧了，我担心来不及。', translationVi: '(Kěshì shíjiān tài jǐn le, wǒ dānxīn lái bu jí.) Nhưng thời gian gấp quá, tôi lo không kịp.' },
      { id: 'zh-b2-wulun-turn-04', speaker: 'B', text: '除非公司改变计划，否则我们必须按时完成。', translationVi: '(Chúfēi gōngsī gǎibiàn jìhuà, fǒuzé wǒmen bìxū ànshí wánchéng.) Trừ phi công ty thay đổi kế hoạch, nếu không chúng ta phải hoàn thành đúng hạn.' },
      { id: 'zh-b2-wulun-turn-05', speaker: 'A', text: '我明白了，那我们连周末都要加班了。', translationVi: '(Wǒ míngbai le, nà wǒmen lián zhōumò dōu yào jiābān le.) Tôi hiểu rồi, vậy thì thậm chí cuối tuần chúng ta cũng phải làm thêm.' },
      { id: 'zh-b2-wulun-turn-06', speaker: 'B', text: '是的，无论多累，我们都不能放弃。', translationVi: '(Shì de, wúlùn duō lèi, wǒmen dōu bù néng fàngqì.) Đúng vậy, dù mệt đến mấy chúng ta cũng không được bỏ cuộc.' },
      { id: 'zh-b2-wulun-turn-07', speaker: 'A', text: '好，那我现在就开始安排工作。', translationVi: '(Hǎo, nà wǒ xiànzài jiù kāishǐ ānpái gōngzuò.) Được, vậy giờ tôi bắt đầu sắp xếp công việc luôn.' },
      { id: 'zh-b2-wulun-turn-08', speaker: 'B', text: '谢谢你的支持，我们一定能做到。', translationVi: '(Xièxie nǐ de zhīchí, wǒmen yídìng néng zuòdào.) Cảm ơn sự ủng hộ của bạn, chúng ta chắc chắn sẽ làm được.' },
    ],
    relatedVocabularyIds: ['zh-b2-l2-2-v1', 'zh-b2-l2-1-v1', 'zh-b2-l2-3-v1', 'zh-b2-l2-2-v8'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa nói '这个项目太难了，我们真的能完成吗？'. Chọn câu phản hồi thể hiện quyết tâm bất kể khó khăn.",
      options: [
        { id: 'o1', text: '无论多难，我们都要完成，这是我们的责任。' },
        { id: 'o2', text: '我是坐火车来的。' },
        { id: 'o3', text: '这么多菜，我们吃得完吗？' },
        { id: 'o4', text: '总的来说，这次旅行非常愉快。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi thể hiện sự lo lắng về khó khăn, nên phản hồi bằng cách khẳng định quyết tâm bất kể hoàn cảnh dùng '无论...都...'.",
    },
  },
  {
    id: 'zh-b2-conv-lvxing-jihua',
    languageCode: 'zh',
    level: 'B2',
    title: '讨论旅行计划',
    titleVi: 'Thảo luận kế hoạch du lịch',
    descriptionVi: 'Luyện hội thoại thảo luận và tổng kết bằng 尽管...但是... và các cụm từ tổng kết.',
    contextVi: 'An hỏi Minh về kế hoạch chuyến du lịch sắp tới.',
    dialogue: [
      { id: 'zh-b2-lvxing-turn-01', speaker: 'A', text: '这次旅行计划得怎么样了？', translationVi: '(Zhè cì lǚxíng jìhuà de zěnmeyàng le?) Kế hoạch chuyến đi lần này thế nào rồi?' },
      { id: 'zh-b2-lvxing-turn-02', speaker: 'B', text: '尽管天气预报说会下雨，但是我们还是决定按计划出发。', translationVi: '(Jǐnguǎn tiānqì yùbào shuō huì xiàyǔ, dànshì wǒmen háishi juédìng àn jìhuà chūfā.) Mặc dù dự báo thời tiết nói sẽ mưa, nhưng chúng tôi vẫn quyết định xuất phát theo kế hoạch.' },
      { id: 'zh-b2-lvxing-turn-03', speaker: 'A', text: '那如果真的下雨怎么办？', translationVi: '(Nà rúguǒ zhēnde xiàyǔ zěnme bàn?) Vậy nếu thật sự mưa thì sao?' },
      { id: 'zh-b2-lvxing-turn-04', speaker: 'B', text: '我们准备了雨伞，尽管下雨，行程也不会取消。', translationVi: '(Wǒmen zhǔnbèi le yǔsǎn, jǐnguǎn xiàyǔ, xíngchéng yě bú huì qǔxiāo.) Chúng tôi đã chuẩn bị ô, dù có mưa thì hành trình cũng sẽ không bị hủy.' },
      { id: 'zh-b2-lvxing-turn-05', speaker: 'A', text: '你们打算去几天？', translationVi: '(Nǐmen dǎsuàn qù jǐ tiān?) Các bạn định đi mấy ngày?' },
      { id: 'zh-b2-lvxing-turn-06', speaker: 'B', text: '三天，总的来说，这次旅行的安排很轻松。', translationVi: '(Sān tiān, zǒngdeláishuō, zhè cì lǚxíng de ānpái hěn qīngsōng.) Ba ngày, nhìn chung lịch trình chuyến đi lần này khá nhẹ nhàng.' },
      { id: 'zh-b2-lvxing-turn-07', speaker: 'A', text: '听起来不错，祝你们玩得开心。', translationVi: '(Tīng qǐlai búcuò, zhù nǐmen wán de kāixīn.) Nghe hay đấy, chúc các bạn chơi vui vẻ.' },
      { id: 'zh-b2-lvxing-turn-08', speaker: 'B', text: '谢谢，总之，我们都很期待这次旅行。', translationVi: '(Xièxie, zǒngzhī, wǒmen dōu hěn qīdài zhè cì lǚxíng.) Cảm ơn, tóm lại, chúng tôi đều rất mong chờ chuyến đi lần này.' },
    ],
    relatedVocabularyIds: ['zh-b2-l3-1-v1', 'zh-b2-l3-2-v1', 'zh-b2-l3-2-v3', 'zh-b2-l3-1-v13'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn muốn tổng kết cuộc thảo luận một cách rõ ràng, mạch lạc trước khi kết thúc. Chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: '总之，我们都很期待这次旅行。' },
        { id: 'o2', text: '就这样吧，不说了。' },
        { id: 'o3', text: '反正都无所谓。' },
        { id: 'o4', text: '随便你们怎么想。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "'总之' là cách tổng kết mạch lạc, lịch sự để kết thúc một cuộc thảo luận, khác với các cách nói thờ ơ/qua loa.",
    },
  },
];
