import type { GrammarTopic } from '../../types';

export const chineseB2GrammarTopics: GrammarTopic[] = [
  {
    id: 'zh-b2-gr-shi-de',
    languageCode: 'zh',
    level: 'B2',
    title: '是...的',
    titleVi: 'Nhấn mạnh 是...的',
    explanationVi:
      "是...的 dùng để nhấn mạnh thời gian, địa điểm, cách thức hoặc người thực hiện của một hành động đã xảy ra mà người nghe đã biết. Không dùng cho hành động chưa xảy ra hoặc chưa được xác nhận.",
    structure: 'S + 是 + (thông tin cần nhấn mạnh) + V + 的',
    keyPoints: ['我是坐火车来的 (nhấn mạnh phương tiện)', '他是在上海出生的 (nhấn mạnh địa điểm)', "Phủ định: 不是...的 — 我不是坐火车来的"],
    examples: [
      { id: 'zh-b2-gr-shide-s1', text: '我是坐火车来的。', translationVi: 'Tôi đến bằng tàu hỏa.' },
      { id: 'zh-b2-gr-shide-s2', text: '他是在上海出生的。', translationVi: 'Anh ấy sinh ra ở Thượng Hải.' },
      { id: 'zh-b2-gr-shide-s3', text: '这件事是他告诉我的。', translationVi: 'Chuyện này là do anh ấy nói cho tôi biết.' },
    ],
    commonMistakesVi: "Người học hay dùng 是...的 cho hành động chưa xảy ra, ví dụ nói sai '我是明天去的' — 是...的 chỉ dùng cho việc đã xảy ra.",
    exercises: [
      {
        id: 'zh-b2-gr-shide-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp.',
        question: '选择正确的句子。',
        options: ['我是坐火车来的。', '我是坐火车来。', '我坐火车是来的。', '我来是坐火车的。'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-gr-shide-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '他是在上海出生___。',
        wordBank: ['的', '了', '过'],
        correctAnswer: '的',
      },
      {
        id: 'zh-b2-gr-shide-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Chuyện này là do anh ấy nói cho tôi biết."',
        words: ['告诉我的', '这件事', '是他'],
        correctOrder: ['这件事', '是他', '告诉我的'],
      },
    ],
  },
  {
    id: 'zh-b2-gr-potential-complement',
    languageCode: 'zh',
    level: 'B2',
    title: '可能补语',
    titleVi: 'Bổ ngữ khả năng 得/不',
    explanationVi:
      "Chèn 得 (khẳng định: có thể đạt được kết quả) hoặc 不 (phủ định: không thể) vào giữa động từ và bổ ngữ kết quả/xu hướng để diễn tả khả năng thực hiện được hành động đến kết quả đó hay không.",
    structure: '动词 + 得/不 + 结果补语（hoặc 趋向补语）',
    keyPoints: ['做得完/做不完 (làm xong được/không xong được)', '看得见/看不见 (nhìn thấy được/không thấy được)', "Khác với 能 + V + kết quả — bổ ngữ khả năng gắn liền vào cụm động từ-bổ ngữ, tự nhiên hơn trong khẩu ngữ"],
    examples: [
      { id: 'zh-b2-gr-potential-s1', text: '这么多作业，我今天做不完。', translationVi: 'Nhiều bài tập như vậy, hôm nay tôi làm không xong.' },
      { id: 'zh-b2-gr-potential-s2', text: '太远了，我看不见黑板上的字。', translationVi: 'Xa quá, tôi không nhìn thấy chữ trên bảng.' },
      { id: 'zh-b2-gr-potential-s3', text: '别担心，这个问题我们解决得了。', translationVi: 'Đừng lo, vấn đề này chúng ta giải quyết được.' },
    ],
    commonMistakesVi: "Người học hay nhầm vị trí của 得/不 — phải chèn giữa động từ và bổ ngữ, không đặt cuối câu, ví dụ nói sai '我做完不了' thay vì '我做不完'.",
    exercises: [
      {
        id: 'zh-b2-gr-potential-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: không thể làm xong.',
        question: '这么多作业，我今天___。',
        options: ['做不完', '不做完', '做完不', '不完做'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-gr-potential-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ còn thiếu (phủ định: không nhìn thấy).',
        sentenceTemplate: '太远了，我看___见黑板上的字。',
        wordBank: ['不', '得', '了'],
        correctAnswer: '不',
      },
      {
        id: 'zh-b2-gr-potential-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Đừng lo, vấn đề này chúng ta giải quyết được."',
        words: ['我们解决得了', '别担心', '这个问题'],
        correctOrder: ['别担心', '这个问题', '我们解决得了'],
      },
    ],
  },
  {
    id: 'zh-b2-gr-yi-jiu',
    languageCode: 'zh',
    level: 'B2',
    title: '一...就...',
    titleVi: 'Hành động nối tiếp 一...就...',
    explanationVi:
      "一 A 就 B diễn tả hai hành động/sự việc xảy ra nối tiếp nhau rất nhanh, hoặc mối quan hệ nhân quả gần như tức thời giữa A và B.",
    structure: '一 + A（động từ/mệnh đề） + 就 + B',
    keyPoints: ['他一进门就开始工作 (vừa vào cửa là bắt đầu làm việc ngay)', '我一看就明白了 (tôi vừa nhìn là đã hiểu ngay)', 'Có thể dùng cho thói quen lặp lại hoặc một sự việc cụ thể'],
    examples: [
      { id: 'zh-b2-gr-yijiu-s1', text: '他一进门就开始工作。', translationVi: 'Anh ấy vừa vào cửa là bắt đầu làm việc ngay.' },
      { id: 'zh-b2-gr-yijiu-s2', text: '我一看就明白了。', translationVi: 'Tôi vừa nhìn là đã hiểu ngay.' },
      { id: 'zh-b2-gr-yijiu-s3', text: '孩子一见到妈妈就笑了。', translationVi: 'Đứa trẻ vừa thấy mẹ là đã cười ngay.' },
    ],
    commonMistakesVi: "Người học hay quên đặt 就 ở vế sau, chỉ dùng 一 mà không có 就 khiến câu thiếu hoàn chỉnh.",
    exercises: [
      {
        id: 'zh-b2-gr-yijiu-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '他一进门___开始工作。',
        options: ['就', '是', '都', '得'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-gr-yijiu-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '我一看___明白了。',
        wordBank: ['就', '的', '得'],
        correctAnswer: '就',
      },
      {
        id: 'zh-b2-gr-yijiu-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Đứa trẻ vừa thấy mẹ là đã cười ngay."',
        words: ['孩子一见到妈妈', '就笑了'],
        correctOrder: ['孩子一见到妈妈', '就笑了'],
      },
    ],
  },
  {
    id: 'zh-b2-gr-lian-dou',
    languageCode: 'zh',
    level: 'B2',
    title: '连...都/也...',
    titleVi: 'Nhấn mạnh cực đoan 连...都/也...',
    explanationVi:
      "连 A 都/也 B nhấn mạnh một trường hợp cực đoan, không ngờ tới nhất (A) để làm nổi bật rằng B đúng với mọi trường hợp khác càng chắc chắn hơn.",
    structure: '连 + A（trường hợp cực đoan） + 都/也 + B',
    keyPoints: ['连专家都不知道答案 (thậm chí chuyên gia cũng không biết đáp án)', '我累得连话都不想说 (tôi mệt đến mức thậm chí không muốn nói chuyện)', "都 và 也 có thể thay thế nhau trong hầu hết trường hợp"],
    examples: [
      { id: 'zh-b2-gr-liandou-s1', text: '连专家都不知道答案。', translationVi: 'Thậm chí chuyên gia cũng không biết đáp án.' },
      { id: 'zh-b2-gr-liandou-s2', text: '我累得连话都不想说。', translationVi: 'Tôi mệt đến mức thậm chí không muốn nói chuyện.' },
      { id: 'zh-b2-gr-liandou-s3', text: '这件事连我自己都不敢相信。', translationVi: 'Chuyện này thậm chí chính tôi cũng không dám tin.' },
    ],
    commonMistakesVi: "Người học hay bỏ sót 都/也 sau danh từ cực đoan, làm câu mất đi ý nhấn mạnh.",
    exercises: [
      {
        id: 'zh-b2-gr-liandou-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '连专家___不知道答案。',
        options: ['都', '是', '得', '就'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-gr-liandou-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '这件事连我自己___不敢相信。',
        wordBank: ['都', '的', '得'],
        correctAnswer: '都',
      },
      {
        id: 'zh-b2-gr-liandou-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi mệt đến mức thậm chí không muốn nói chuyện."',
        words: ['不想说', '我累得', '连话都'],
        correctOrder: ['我累得', '连话都', '不想说'],
      },
    ],
  },
  {
    id: 'zh-b2-gr-wulun-dou',
    languageCode: 'zh',
    level: 'B2',
    title: '无论...都...',
    titleVi: 'Nhượng bộ tổng quát 无论...都...',
    explanationVi:
      "无论 A 都 B diễn tả tính phổ quát, không có ngoại lệ: bất kể A (câu hỏi nghi vấn hoặc lựa chọn) thì B vẫn luôn đúng/xảy ra.",
    structure: '无论 + 疑问词/A还是B + 都 + B',
    keyPoints: ['无论发生什么，我都会陪着你 (bất kể xảy ra chuyện gì thì tôi vẫn sẽ ở bên bạn)', '无论去哪里，都要小心 (dù đi đâu thì cũng phải cẩn thận)', "无论 khác 尽管: 无论 dùng cho MỌI trường hợp có thể, 尽管 chỉ nói về MỘT trường hợp cụ thể"],
    examples: [
      { id: 'zh-b2-gr-wulun-s1', text: '无论发生什么，我都会陪着你。', translationVi: 'Bất kể xảy ra chuyện gì, tôi vẫn sẽ ở bên bạn.' },
      { id: 'zh-b2-gr-wulun-s2', text: '无论去哪里，都要小心。', translationVi: 'Dù đi đâu thì cũng phải cẩn thận.' },
      { id: 'zh-b2-gr-wulun-s3', text: '无论工作多忙，他都坚持锻炼。', translationVi: 'Dù công việc bận đến mấy thì anh ấy vẫn kiên trì tập luyện.' },
    ],
    commonMistakesVi: "Người học hay nhầm 无论 với 虽然 — 无论 phải đi kèm với từ nghi vấn (什么/谁/哪里...) hoặc cấu trúc lựa chọn (A还是B), không dùng cho một sự việc cụ thể đã xảy ra.",
    exercises: [
      {
        id: 'zh-b2-gr-wulun-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '无论去哪里，___要小心。',
        options: ['都', '也', '才', '就'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-gr-wulun-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '无论工作多忙，他___坚持锻炼。',
        wordBank: ['都', '也', '才'],
        correctAnswer: '都',
      },
      {
        id: 'zh-b2-gr-wulun-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Bất kể xảy ra chuyện gì, tôi vẫn sẽ ở bên bạn."',
        words: ['我都会陪着你', '无论发生什么'],
        correctOrder: ['无论发生什么', '我都会陪着你'],
      },
    ],
  },
];
