import type { ConversationScenario } from '../../types';

export const chineseB1ConversationScenarios: ConversationScenario[] = [
  {
    id: 'zh-b1-conv-dongxi-bujian',
    languageCode: 'zh',
    level: 'B1',
    title: '东西不见了',
    titleVi: 'Đồ vật bị mất',
    descriptionVi: 'Luyện hội thoại miêu tả một đồ vật bị mất/hỏng bằng 把 và 被.',
    contextVi: 'An phát hiện điện thoại của mình không thấy đâu và hỏi Minh.',
    dialogue: [
      { id: 'zh-b1-dongxi-turn-01', speaker: 'A', text: '我的手机不见了，你看到了吗？', translationVi: '(Wǒ de shǒujī bú jiàn le, nǐ kàndào le ma?) Điện thoại của tôi biến mất rồi, bạn có thấy không?' },
      { id: 'zh-b1-dongxi-turn-02', speaker: 'B', text: '没有。你最后把它放在哪儿了？', translationVi: '(Méiyǒu. Nǐ zuìhòu bǎ tā fàng zài nǎr le?) Không thấy. Lần cuối bạn để nó ở đâu vậy?' },
      { id: 'zh-b1-dongxi-turn-03', speaker: 'A', text: '我记得把它放在桌子上了。', translationVi: '(Wǒ jìde bǎ tā fàng zài zhuōzi shàng le.) Tôi nhớ là đã để nó trên bàn.' },
      { id: 'zh-b1-dongxi-turn-04', speaker: 'B', text: '会不会被你弟弟拿走了？', translationVi: '(Huì bú huì bèi nǐ dìdi ná zǒu le?) Có khi nào bị em trai bạn cầm đi không?' },
      { id: 'zh-b1-dongxi-turn-05', speaker: 'A', text: '有可能。他今天早上在这儿。', translationVi: '(Yǒu kěnéng. Tā jīntiān zǎoshang zài zhèr.) Có khả năng đấy. Sáng nay em ấy có ở đây.' },
      { id: 'zh-b1-dongxi-turn-06', speaker: 'B', text: '你先给自己打个电话试试看。', translationVi: '(Nǐ xiān gěi zìjǐ dǎ ge diànhuà shìshi kàn.) Bạn thử gọi cho chính mình xem sao.' },
      { id: 'zh-b1-dongxi-turn-07', speaker: 'A', text: '好主意，我马上试试。', translationVi: '(Hǎo zhǔyi, wǒ mǎshàng shìshi.) Ý hay đấy, tôi thử ngay đây.' },
      { id: 'zh-b1-dongxi-turn-08', speaker: 'B', text: '找到了别忘了把它收好。', translationVi: '(Zhǎodào le bié wàngle bǎ tā shōu hǎo.) Tìm được rồi thì đừng quên cất nó cẩn thận nhé.' },
    ],
    relatedVocabularyIds: ['zh-b1-l1-1-v1', 'zh-b1-l1-2-v1', 'zh-b1-l1-2-v10', 'zh-b1-l1-1-v9'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '你最后把它放在哪儿了？'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: '我记得把它放在桌子上了。' },
        { id: 'o2', text: '我认为教育很重要。' },
        { id: 'o3', text: '天气越来越冷了。' },
        { id: 'o4', text: '要是明天下雨，我们就不去了。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi hỏi vị trí đã đặt đồ vật, nên trả lời bằng câu chữ 把 miêu tả hành động đặt đồ.",
    },
  },
  {
    id: 'zh-b1-conv-gongzuo-yali',
    languageCode: 'zh',
    level: 'B1',
    title: '工作压力',
    titleVi: 'Áp lực công việc',
    descriptionVi: 'Luyện hội thoại nói về xu hướng tăng dần và đặt điều kiện bằng 越来越 và 要是...就...',
    contextVi: 'Lan và Minh nói chuyện về áp lực công việc gần đây.',
    dialogue: [
      { id: 'zh-b1-yali-turn-01', speaker: 'A', text: '最近工作压力越来越大了。', translationVi: '(Zuìjìn gōngzuò yālì yuè lái yuè dà le.) Gần đây áp lực công việc ngày càng lớn.' },
      { id: 'zh-b1-yali-turn-02', speaker: 'B', text: '要是太累，就应该多休息。', translationVi: '(Yàoshi tài lèi, jiù yīnggāi duō xiūxi.) Nếu quá mệt thì nên nghỉ ngơi nhiều hơn.' },
      { id: 'zh-b1-yali-turn-03', speaker: 'A', text: '我也想，但是工作不但多，而且很复杂。', translationVi: '(Wǒ yě xiǎng, dànshì gōngzuò bùdàn duō, érqiě hěn fùzá.) Tôi cũng muốn vậy, nhưng công việc không những nhiều mà còn rất phức tạp.' },
      { id: 'zh-b1-yali-turn-04', speaker: 'B', text: '你越努力工作，身体越容易出问题。', translationVi: '(Nǐ yuè nǔlì gōngzuò, shēntǐ yuè róngyì chū wèntí.) Bạn càng làm việc chăm chỉ thì sức khỏe càng dễ có vấn đề.' },
      { id: 'zh-b1-yali-turn-05', speaker: 'A', text: '你说得有道理，我得想办法调整一下。', translationVi: '(Nǐ shuō de yǒu dàolǐ, wǒ děi xiǎng bànfǎ tiáozhěng yíxià.) Bạn nói cũng có lý, tôi phải tìm cách điều chỉnh một chút.' },
      { id: 'zh-b1-yali-turn-06', speaker: 'B', text: '要是压力一直这样，就跟老板谈谈吧。', translationVi: '(Yàoshi yālì yìzhí zhèyàng, jiù gēn lǎobǎn tántan ba.) Nếu áp lực cứ như vậy thì hãy nói chuyện với sếp đi.' },
      { id: 'zh-b1-yali-turn-07', speaker: 'A', text: '好，我明天就去跟他谈。', translationVi: '(Hǎo, wǒ míngtiān jiù qù gēn tā tán.) Được, ngày mai tôi sẽ đi nói chuyện với ông ấy luôn.' },
      { id: 'zh-b1-yali-turn-08', speaker: 'B', text: '希望一切都会越来越好。', translationVi: '(Xīwàng yíqiè dōu huì yuè lái yuè hǎo.) Hy vọng mọi thứ sẽ ngày càng tốt hơn.' },
    ],
    relatedVocabularyIds: ['zh-b1-l2-1-v2', 'zh-b1-l2-2-v1', 'zh-b1-l2-3-v1', 'zh-b1-l3-1-v12'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa nói '最近工作压力越来越大了。'. Chọn câu phản hồi phù hợp nhất.",
      options: [
        { id: 'o1', text: '要是太累，就应该多休息。' },
        { id: 'o2', text: '除了游泳以外，我还喜欢跑步。' },
        { id: 'o3', text: '我的手机被弟弟拿走了。' },
        { id: 'o4', text: '他打篮球打得很好。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Nghe ai đó than phiền về áp lực, cách phản hồi tự nhiên là đưa ra lời khuyên bằng cấu trúc điều kiện 要是...就...",
    },
  },
  {
    id: 'zh-b1-conv-taolun-jueding',
    languageCode: 'zh',
    level: 'B1',
    title: '讨论一个决定',
    titleVi: 'Thảo luận một quyết định',
    descriptionVi: 'Luyện hội thoại nêu và bảo vệ quan điểm cá nhân bằng 觉得/认为，除了...以外...',
    contextVi: 'An và Minh đang thảo luận về việc chọn nơi làm việc mới.',
    dialogue: [
      { id: 'zh-b1-taolun-turn-01', speaker: 'A', text: '我觉得这家公司不太合适。', translationVi: '(Wǒ juéde zhè jiā gōngsī bú tài héshì.) Tôi cảm thấy công ty này không hợp lắm.' },
      { id: 'zh-b1-taolun-turn-02', speaker: 'B', text: '为什么？我认为工资还不错。', translationVi: '(Wèishénme? Wǒ rènwéi gōngzī hái búcuò.) Tại sao vậy? Tôi cho rằng lương cũng khá đấy.' },
      { id: 'zh-b1-taolun-turn-03', speaker: 'A', text: '除了工资以外，环境也很重要。', translationVi: '(Chúle gōngzī yǐwài, huánjìng yě hěn zhòngyào.) Ngoài lương ra, môi trường làm việc cũng rất quan trọng.' },
      { id: 'zh-b1-taolun-turn-04', speaker: 'B', text: '你说得有道理，不过我们还没了解那里的环境。', translationVi: '(Nǐ shuō de yǒu dàolǐ, búguò wǒmen hái méi liǎojiě nàli de huánjìng.) Bạn nói cũng có lý, nhưng chúng ta vẫn chưa tìm hiểu về môi trường ở đó.' },
      { id: 'zh-b1-taolun-turn-05', speaker: 'A', text: '也许我们应该先去看看再决定。', translationVi: '(Yěxǔ wǒmen yīnggāi xiān qù kànkan zài juédìng.) Có lẽ chúng ta nên đi xem thử trước rồi mới quyết định.' },
      { id: 'zh-b1-taolun-turn-06', speaker: 'B', text: '好，我同意你的看法。', translationVi: '(Hǎo, wǒ tóngyì nǐ de kànfǎ.) Được, tôi đồng ý với quan điểm của bạn.' },
      { id: 'zh-b1-taolun-turn-07', speaker: 'A', text: '那我们这个周末一起去看看吧。', translationVi: '(Nà wǒmen zhège zhōumò yìqǐ qù kànkan ba.) Vậy cuối tuần này chúng ta cùng đi xem thử nhé.' },
      { id: 'zh-b1-taolun-turn-08', speaker: 'B', text: '好主意，我们到时候再讨论。', translationVi: '(Hǎo zhǔyi, wǒmen dào shíhou zài tǎolùn.) Ý hay đấy, đến lúc đó chúng ta thảo luận thêm.' },
    ],
    relatedVocabularyIds: ['zh-b1-l3-1-v1', 'zh-b1-l3-1-v2', 'zh-b1-l3-2-v1', 'zh-b1-l3-1-v12'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn không hoàn toàn đồng ý với ý kiến của bạn mình nhưng muốn diễn đạt một cách lịch sự. Chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: '你说得有道理，不过我们还没了解那里的环境。' },
        { id: 'o2', text: '你错了，工资根本不重要。' },
        { id: 'o3', text: '这个想法太差了。' },
        { id: 'o4', text: '别说了，我不同意。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Cách không đồng ý lịch sự là công nhận phần hợp lý của đối phương trước ('你说得有道理'), rồi mới nêu quan điểm khác nhẹ nhàng bằng '不过'.",
    },
  },
];
