import type { GrammarTopic } from '../../types';

export const chineseB1GrammarTopics: GrammarTopic[] = [
  {
    id: 'zh-b1-gr-ba',
    languageCode: 'zh',
    level: 'B1',
    title: '把字句',
    titleVi: 'Câu chữ 把',
    explanationVi:
      "把 đưa tân ngữ xác định lên trước động từ để nhấn mạnh việc xử lý và kết quả của hành động. Chỉ dùng khi tân ngữ đã được nhắc đến cụ thể và động từ có bổ ngữ/kết quả theo sau.",
    structure: 'S + 把 + O(xác định) + V + bổ ngữ/kết quả',
    keyPoints: ['我把书看完了 (Tôi đã đọc xong quyển sách)', '请把窗户关上 (Làm ơn đóng cửa sổ lại)', "Không dùng 把 nếu câu không có bổ ngữ sau động từ, ví dụ không nói '我把书看'"],
    examples: [
      { id: 'zh-b1-gr-ba-s1', text: '我把书看完了。', translationVi: 'Tôi đã đọc xong quyển sách.' },
      { id: 'zh-b1-gr-ba-s2', text: '请把窗户关上。', translationVi: 'Làm ơn đóng cửa sổ lại.' },
      { id: 'zh-b1-gr-ba-s3', text: '他把车停在外面了。', translationVi: 'Anh ấy đã đỗ xe ở bên ngoài.' },
    ],
    commonMistakesVi: "Người mới học hay dùng 把 mà không thêm bổ ngữ/kết quả sau động từ, ví dụ nói sai '我把书看' thay vì '我把书看完了'.",
    exercises: [
      {
        id: 'zh-b1-gr-ba-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '我___书看完了。',
        options: ['把', '被', '比', '越'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-gr-ba-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '请___窗户关上。',
        wordBank: ['把', '被', '得'],
        correctAnswer: '把',
      },
      {
        id: 'zh-b1-gr-ba-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Anh ấy đã đỗ xe ở bên ngoài."',
        words: ['停在外面了', '他把车'],
        correctOrder: ['他把车', '停在外面了'],
      },
    ],
  },
  {
    id: 'zh-b1-gr-bei',
    languageCode: 'zh',
    level: 'B1',
    title: '被字句',
    titleVi: 'Câu chữ 被 (bị động)',
    explanationVi:
      "被 tạo câu bị động, nhấn mạnh đối tượng chịu tác động thay vì người/vật thực hiện hành động. Tác nhân sau 被 có thể lược bỏ nếu không quan trọng hoặc không rõ.",
    structure: 'S(bị tác động) + 被 + (tác nhân) + V + bổ ngữ/kết quả',
    keyPoints: ['我的钱包被偷了 (Ví của tôi bị mất trộm)', '窗户被打破了 (Cửa sổ bị vỡ)', 'Cũng cần bổ ngữ/kết quả theo sau động từ, giống cấu trúc 把'],
    examples: [
      { id: 'zh-b1-gr-bei-s1', text: '我的钱包被偷了。', translationVi: 'Ví của tôi bị mất trộm.' },
      { id: 'zh-b1-gr-bei-s2', text: '窗户被打破了。', translationVi: 'Cửa sổ bị vỡ.' },
      { id: 'zh-b1-gr-bei-s3', text: '这个问题已经被解决了。', translationVi: 'Vấn đề này đã được giải quyết rồi.' },
    ],
    commonMistakesVi: "Người mới học hay quên thêm bổ ngữ sau động từ trong câu 被, hoặc nhầm 被 với 把 (đối tượng nào chịu tác động, đối tượng nào xử lý).",
    exercises: [
      {
        id: 'zh-b1-gr-bei-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '我的钱包___偷了。',
        options: ['被', '把', '越', '得'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-gr-bei-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '窗户___打破了。',
        wordBank: ['被', '把', '比'],
        correctAnswer: '被',
      },
      {
        id: 'zh-b1-gr-bei-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vấn đề này đã được giải quyết rồi."',
        words: ['已经被解决了', '这个问题'],
        correctOrder: ['这个问题', '已经被解决了'],
      },
    ],
  },
  {
    id: 'zh-b1-gr-de-complement',
    languageCode: 'zh',
    level: 'B1',
    title: '程度补语 得',
    titleVi: 'Bổ ngữ mức độ 得',
    explanationVi:
      "V + 得 + tính từ miêu tả mức độ hoặc kết quả của hành động. Nếu động từ có tân ngữ, cần lặp lại động từ trước 得 (V + O + V + 得 + tính từ).",
    structure: '动词 + 得 + 形容词 / 动词 + 宾语 + 动词 + 得 + 形容词',
    keyPoints: ['他写得很好 (Anh ấy viết rất đẹp/giỏi)', '他写字写得很好 (có tân ngữ, phải lặp động từ)', "Không nhầm 得 (de, bổ ngữ) với 的 (de, sở hữu) hay 地 (de, trạng ngữ)"],
    examples: [
      { id: 'zh-b1-gr-de-s1', text: '他写得很好。', translationVi: 'Anh ấy viết rất đẹp.' },
      { id: 'zh-b1-gr-de-s2', text: '他写字写得很好。', translationVi: 'Anh ấy viết chữ rất đẹp.' },
      { id: 'zh-b1-gr-de-s3', text: '她跳舞跳得很棒。', translationVi: 'Cô ấy nhảy múa rất giỏi.' },
    ],
    commonMistakesVi: "Người mới học hay quên lặp lại động từ khi có tân ngữ, nói sai '他写字得很好' thay vì '他写字写得很好'.",
    exercises: [
      {
        id: 'zh-b1-gr-de-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp khi động từ có tân ngữ.',
        question: '选择正确的句子。',
        options: ['他写字写得很好。', '他写字得很好。', '他写得字很好。', '他很好写字得。'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-gr-de-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ còn thiếu.',
        sentenceTemplate: '她跳舞跳___很棒。',
        wordBank: ['得', '的', '地'],
        correctAnswer: '得',
      },
      {
        id: 'zh-b1-gr-de-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Anh ấy viết rất đẹp."',
        words: ['很好', '他写', '得'],
        correctOrder: ['他写', '得', '很好'],
      },
    ],
  },
  {
    id: 'zh-b1-gr-yue-yue',
    languageCode: 'zh',
    level: 'B1',
    title: '越...越...',
    titleVi: 'Tương quan tăng dần 越...越...',
    explanationVi:
      "越 A 越 B diễn tả A càng tăng thì B càng tăng theo. 越来越 + tính từ diễn tả xu hướng thay đổi 'ngày càng...' theo thời gian, không cần vế A.",
    structure: '越 + A + 越 + B / 越来越 + 形容词',
    keyPoints: ['他越忙越开心 (Anh ấy càng bận càng vui)', '房价越来越高 (Giá nhà ngày càng cao)', 'Vế A và B có thể lặp lại cùng một chủ ngữ hoặc dùng chung một chủ ngữ'],
    examples: [
      { id: 'zh-b1-gr-yueyue-s1', text: '他越忙越开心。', translationVi: 'Anh ấy càng bận càng vui.' },
      { id: 'zh-b1-gr-yueyue-s2', text: '房价越来越高。', translationVi: 'Giá nhà ngày càng cao.' },
      { id: 'zh-b1-gr-yueyue-s3', text: '这个城市越来越现代化了。', translationVi: 'Thành phố này ngày càng hiện đại hóa.' },
    ],
    commonMistakesVi: "Người mới học hay quên lặp lại 越 ở cả hai vế, chỉ dùng một lần, ví dụ nói sai '他忙越开心' thay vì '他越忙越开心'.",
    exercises: [
      {
        id: 'zh-b1-gr-yueyue-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp.',
        question: '选择正确的句子。',
        options: ['他越忙越开心。', '他忙越开心。', '他越忙开心。', '他忙开心越。'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-gr-yueyue-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '房价___高。',
        wordBank: ['越来越', '不但', '除了'],
        correctAnswer: '越来越',
      },
      {
        id: 'zh-b1-gr-yueyue-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Thành phố này ngày càng hiện đại hóa."',
        words: ['现代化了', '这个城市', '越来越'],
        correctOrder: ['这个城市', '越来越', '现代化了'],
      },
    ],
  },
  {
    id: 'zh-b1-gr-budan-erqie',
    languageCode: 'zh',
    level: 'B1',
    title: '不但...而且...',
    titleVi: 'Liên kết bổ sung 不但...而且...',
    explanationVi:
      "不但 A 而且 B nghĩa là 'không những A mà còn B', dùng để liệt kê hai đặc điểm/ý liên quan, ý sau thường nâng cao/bổ sung cho ý trước. Thường kèm 也/还 ở vế B.",
    structure: '不但 + A，而且(也/还) + B',
    keyPoints: ['这家餐厅不但便宜，而且好吃 (Quán này không những rẻ mà còn ngon)', '他不但会说中文，还会说日文 (Anh ấy không những biết nói tiếng Trung mà còn biết nói tiếng Nhật)', "Chủ ngữ chung có thể đặt trước 不但 hoặc sau 不但 tùy câu"],
    examples: [
      { id: 'zh-b1-gr-budan-s1', text: '这家餐厅不但便宜，而且好吃。', translationVi: 'Quán này không những rẻ mà còn ngon.' },
      { id: 'zh-b1-gr-budan-s2', text: '他不但会说中文，还会说日文。', translationVi: 'Anh ấy không những biết nói tiếng Trung mà còn biết nói tiếng Nhật.' },
      { id: 'zh-b1-gr-budan-s3', text: '这份工作不但辛苦，而且工资不高。', translationVi: 'Công việc này không những vất vả mà còn lương không cao.' },
    ],
    commonMistakesVi: "Người mới học hay chỉ dùng một trong hai từ (chỉ 不但 hoặc chỉ 而且) mà không ghép thành cặp đầy đủ.",
    exercises: [
      {
        id: 'zh-b1-gr-budan-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cặp từ đúng.',
        question: '选择正确的关联词。',
        options: ['不但...而且...', '虽然...但是...', '要是...就...', '越...越...'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-gr-budan-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '这家餐厅不但便宜，___好吃。',
        wordBank: ['而且', '但是', '所以'],
        correctAnswer: '而且',
      },
      {
        id: 'zh-b1-gr-budan-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Anh ấy không những biết nói tiếng Trung mà còn biết nói tiếng Nhật."',
        words: ['还会说日文', '他不但会说中文'],
        correctOrder: ['他不但会说中文', '还会说日文'],
      },
    ],
  },
];
