import type { ConversationScenario } from '../../types';

export const koreanB2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'ko-b2-conv-an-joeun-haru',
    languageCode: 'ko',
    level: 'B2',
    title: '안 좋은 하루',
    titleVi: 'Một ngày không suôn sẻ',
    descriptionVi: 'Luyện hội thoại kể lại một chuỗi sự việc ngoài ý muốn bằng 는 바람에, 기 마련이다, (으)ㄹ수록.',
    contextVi: 'An kể cho Minh nghe về một ngày tồi tệ của mình.',
    dialogue: [
      { id: 'ko-b2-haru-turn-01', speaker: 'A', text: '오늘 왜 이렇게 피곤해 보여요?', translationVi: '(oneul wae ireoke pigonhae boyeoyo?) Sao hôm nay bạn trông mệt vậy?' },
      { id: 'ko-b2-haru-turn-02', speaker: 'B', text: '어젯밤에 늦게 자는 바람에 잠을 잘 못 잤어요.', translationVi: '(eojetbame neutge janeun barame jameul jal mot jasseoyo.) Vì tối qua ngủ muộn nên tôi ngủ không ngon.' },
      { id: 'ko-b2-haru-turn-03', speaker: 'A', text: '무슨 일 있었어요?', translationVi: '(museun il isseosseoyo?) Có chuyện gì vậy?' },
      { id: 'ko-b2-haru-turn-04', speaker: 'B', text: '컴퓨터가 갑자기 고장 나는 바람에 밤새 고치느라 힘들었어요.', translationVi: '(keompyuteoga gapjagi gojang naneun barame bamsae gochineura himdeureosseoyo.) Vì máy tính đột nhiên hỏng nên tôi vất vả sửa suốt đêm.' },
      { id: 'ko-b2-haru-turn-05', speaker: 'A', text: '저런, 힘들었겠네요. 그런 일은 누구에게나 생기기 마련이에요.', translationVi: '(jeoreon, himdeureotgenneyo. geureon ireun nuguegena saenggigi maryeonieyo.) Ôi, chắc vất vả lắm. Chuyện đó ai cũng có thể gặp phải mà.' },
      { id: 'ko-b2-haru-turn-06', speaker: 'B', text: '맞아요. 나이가 들수록 이런 일에 스트레스를 더 받는 것 같아요.', translationVi: '(majayo. naiga deulsurok ireon ire seuteureseureul deo batneun geot gatayo.) Đúng vậy. Càng lớn tuổi thì hình như càng bị căng thẳng hơn với những chuyện này.' },
      { id: 'ko-b2-haru-turn-07', speaker: 'A', text: '오늘은 일찍 쉬는 게 좋겠어요.', translationVi: '(oneureun iljjik swineun ge jokesseoyo.) Hôm nay bạn nên nghỉ sớm thì tốt hơn.' },
      { id: 'ko-b2-haru-turn-08', speaker: 'B', text: '네, 그렇게 할게요. 조언 고마워요.', translationVi: '(ne, geureoke halgeyo. joeon gomawoyo.) Vâng, tôi sẽ làm vậy. Cảm ơn lời khuyên nhé.' },
    ],
    relatedVocabularyIds: ['ko-b2-l1-1-v1', 'ko-b2-l1-1-v6', 'ko-b2-l1-2-v1', 'ko-b2-l1-3-v1'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '오늘 왜 이렇게 피곤해 보여요?'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: '어젯밤에 늦게 자는 바람에 잠을 잘 못 잤어요.' },
        { id: 'o2', text: '이 카페는 조용할 뿐만 아니라 커피도 맛있어요.' },
        { id: 'o3', text: '아무리 바쁘더라도 밥은 챙겨 먹어야 해요.' },
        { id: 'o4', text: '사장님께 여쭤보고 싶은 것이 있어요.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi hỏi lý do trông mệt, nên trả lời bằng nguyên nhân ngoài ý muốn dùng '는 바람에'.",
    },
  },
  {
    id: 'ko-b2-conv-jangdanjeom',
    languageCode: 'ko',
    level: 'B2',
    title: '장단점 비교하기',
    titleVi: 'So sánh ưu nhược điểm',
    descriptionVi: 'Luyện hội thoại so sánh ưu nhược điểm của công việc bằng 뿐만 아니라, 반면에, 더라도.',
    contextVi: 'An và Minh đang nói chuyện về công việc mới của An.',
    dialogue: [
      { id: 'ko-b2-jangdan-turn-01', speaker: 'A', text: '새 직장은 어때요?', translationVi: '(sae jikjangeun eottaeyo?) Công việc mới thế nào?' },
      { id: 'ko-b2-jangdan-turn-02', speaker: 'B', text: '월급이 높은 반면에 야근이 많아요.', translationVi: '(wolgeubi nopeun banmyeone yageuni manayo.) Lương cao, nhưng mặt khác lại nhiều tăng ca.' },
      { id: 'ko-b2-jangdan-turn-03', speaker: 'A', text: '그래도 배울 게 많을 것 같아요.', translationVi: '(geuraedo baeul ge maneul geot gatayo.) Nhưng chắc học được nhiều thứ nhỉ.' },
      { id: 'ko-b2-jangdan-turn-04', speaker: 'B', text: '맞아요. 이 일은 전문성을 키울 수 있을 뿐만 아니라 인맥도 넓힐 수 있어요.', translationVi: '(majayo. i ireun jeonmunseongeul kiul su isseul ppunman anira inmaekdo neolpil su isseoyo.) Đúng vậy. Công việc này không chỉ giúp nâng cao chuyên môn mà còn mở rộng được quan hệ.' },
      { id: 'ko-b2-jangdan-turn-05', speaker: 'A', text: '예전 직장이랑 비교하면 어때요?', translationVi: '(yejeon jikjangirang bigyohamyeon eottaeyo?) So với công việc cũ thì sao?' },
      { id: 'ko-b2-jangdan-turn-06', speaker: 'B', text: '예전 직장은 편한 반면에 성장하기 어려웠어요.', translationVi: '(yejeon jikjangeun pyeonhan banmyeone seongjanghagi eoryeowosseoyo.) Công việc cũ thoải mái, nhưng mặt khác lại khó phát triển.' },
      { id: 'ko-b2-jangdan-turn-07', speaker: 'A', text: '그럼 지금 선택이 더 나은 것 같아요.', translationVi: '(geureom jigeum seontaegi deo naeun geot gatayo.) Vậy thì lựa chọn hiện tại có vẻ tốt hơn.' },
      { id: 'ko-b2-jangdan-turn-08', speaker: 'B', text: '네, 힘들더라도 지금 일이 더 보람 있어요.', translationVi: '(ne, himdeuldeorado jigeum iri deo boram isseoyo.) Vâng, dù có vất vả thì công việc hiện tại vẫn ý nghĩa hơn.' },
    ],
    relatedVocabularyIds: ['ko-b2-l2-1-v1', 'ko-b2-l2-2-v1', 'ko-b2-l2-3-v1', 'ko-b2-l2-2-v13'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa hỏi '새 직장은 어때요?'. Chọn câu trả lời phù hợp thể hiện sự đối lập hai mặt.",
      options: [
        { id: 'o1', text: '월급이 높은 반면에 야근이 많아요.' },
        { id: 'o2', text: '어젯밤에 늦게 자는 바람에 잠을 잘 못 잤어요.' },
        { id: 'o3', text: '사람은 누구나 실수하기 마련이에요.' },
        { id: 'o4', text: '3년 동안 같이 살았으니까 가족인 셈이에요.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về nhận xét công việc mới, nên trả lời bằng cách so sánh hai mặt đối lập dùng '반면에'.",
    },
  },
  {
    id: 'ko-b2-conv-jikjang',
    languageCode: 'ko',
    level: 'B2',
    title: '직장에서',
    titleVi: 'Tại nơi làm việc',
    descriptionVi: 'Luyện hội thoại giao tiếp công sở trang trọng bằng khiêm nhường ngữ, 더라도, 는 셈이다.',
    contextVi: 'An đang báo cáo tiến độ dự án với trưởng phòng.',
    dialogue: [
      { id: 'ko-b2-jikjang-turn-01', speaker: 'A', text: '부장님께 여쭤보고 싶은 게 있는데 지금 시간 괜찮으세요?', translationVi: '(bujangnimkke yeojjwobogo sipeun ge inneunde jigeum sigan gwaenchanheuseyo?) Tôi có điều muốn hỏi trưởng phòng, bây giờ anh có rảnh không ạ?' },
      { id: 'ko-b2-jikjang-turn-02', speaker: 'B', text: '네, 말씀하세요.', translationVi: '(ne, malsseumhaseyo.) Vâng, cứ nói đi.' },
      { id: 'ko-b2-jikjang-turn-03', speaker: 'A', text: '이번 프로젝트 보고서를 언제까지 드리면 될까요?', translationVi: '(ibeon peurojekteu bogoseoreul eonjekkaji deurimyeon doelkkayo?) Báo cáo dự án lần này tôi nên nộp đến khi nào ạ?' },
      { id: 'ko-b2-jikjang-turn-04', speaker: 'B', text: '이번 주 금요일까지 주시면 됩니다.', translationVi: '(ibeon ju geumyoilkkaji jusimyeon doemnida.) Nộp đến hết thứ Sáu tuần này là được.' },
      { id: 'ko-b2-jikjang-turn-05', speaker: 'A', text: '네, 알겠습니다. 시간이 부족하더라도 최선을 다하겠습니다.', translationVi: '(ne, algesseumnida. sigani bujokhadeorado choeseoneul dahagesseumnida.) Vâng, tôi hiểu rồi. Dù có thiếu thời gian thì tôi cũng sẽ cố gắng hết sức ạ.' },
      { id: 'ko-b2-jikjang-turn-06', speaker: 'B', text: '지금까지 진행 상황을 보면 거의 다 된 셈이네요.', translationVi: '(jigeumkkaji jinhaeng sanghwangeul bomyeon geoui da doen semineyo.) Nhìn tiến độ đến giờ thì coi như đã gần xong rồi đấy.' },
      { id: 'ko-b2-jikjang-turn-07', speaker: 'A', text: '감사드립니다. 마무리해서 바로 보고드리겠습니다.', translationVi: '(gamsadeurimnida. mamurihaeseo baro bogodeurigesseumnida.) Cảm ơn anh. Tôi sẽ hoàn thiện và báo cáo ngay ạ.' },
      { id: 'ko-b2-jikjang-turn-08', speaker: 'B', text: '네, 수고하세요.', translationVi: '(ne, sugohaseyo.) Được, vất vả rồi nhé.' },
    ],
    relatedVocabularyIds: ['ko-b2-l3-1-v1', 'ko-b2-l3-1-v2', 'ko-b2-l2-3-v1', 'ko-b2-l3-2-v1'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn muốn hỏi trưởng phòng một điều gì đó một cách khiêm nhường, lịch sự trong môi trường công sở. Chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: '부장님께 여쭤보고 싶은 게 있는데 지금 시간 괜찮으세요?' },
        { id: 'o2', text: '부장님한테 물어볼 게 있어요.' },
        { id: 'o3', text: '이거 좀 물어봐도 돼요?' },
        { id: 'o4', text: '나 뭐 좀 물어볼게요.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi hỏi cấp trên, cần dùng động từ khiêm nhường '여쭤보다' thay vì '물어보다' thông thường, cùng với trợ từ kính ngữ '께'.",
    },
  },
];
