import type { GrammarTopic } from '../../types';

export const koreanB2GrammarTopics: GrammarTopic[] = [
  {
    id: 'ko-b2-gr-lsurok',
    languageCode: 'ko',
    level: 'B2',
    title: '(으)ㄹ수록',
    titleVi: 'Tương quan tăng dần (으)ㄹ수록',
    explanationVi:
      "'(으)ㄹ수록' diễn tả mối tương quan tăng dần: điều gì càng tăng thì điều khác cũng tăng theo. Có thể kết hợp với (으)면 để nhấn mạnh: (으)면 (으)ㄹ수록.",
    structure: '동사/형용사 어간 + (으)ㄹ수록',
    keyPoints: ['먹다 → 먹을수록', '비쌀수록 품질이 좋은 것은 아니에요.', "'(으)면 (으)ㄹ수록' nhấn mạnh mối tương quan rõ hơn: 생각하면 생각할수록"],
    examples: [
      { id: 'ko-b2-gr-lsurok-s1', text: '많이 먹을수록 살이 쪄요.', translationVi: 'Ăn càng nhiều thì càng tăng cân.' },
      { id: 'ko-b2-gr-lsurok-s2', text: '값이 비쌀수록 품질이 좋은 것은 아니에요.', translationVi: 'Giá càng đắt thì không có nghĩa là chất lượng càng tốt.' },
      { id: 'ko-b2-gr-lsurok-s3', text: '친해질수록 서로 예의를 지켜야 해요.', translationVi: 'Càng thân thiết thì càng phải giữ phép lịch sự với nhau.' },
    ],
    commonMistakesVi: "Người học hay quên chia đúng dạng (으)ㄹ khi gốc động từ/tính từ kết thúc bằng phụ âm, ví dụ '먹다' phải chia thành '먹을수록', không phải '먹수록'.",
    exercises: [
      {
        id: 'ko-b2-gr-lsurok-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '많이 ___ 살이 쪄요.',
        options: ['먹을수록', '먹는 바람에', '먹을 뿐만 아니라', '먹더라도'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-gr-lsurok-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '값이 ___ 품질이 좋은 것은 아니에요.',
        wordBank: ['비쌀수록', '비싼 반면에', '비싸기 때문에'],
        correctAnswer: '비쌀수록',
      },
      {
        id: 'ko-b2-gr-lsurok-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Càng thân thiết thì càng phải giữ phép lịch sự với nhau."',
        words: ['서로 예의를 지켜야 해요', '친해질수록'],
        correctOrder: ['친해질수록', '서로 예의를 지켜야 해요'],
      },
    ],
  },
  {
    id: 'ko-b2-gr-neun-barame',
    languageCode: 'ko',
    level: 'B2',
    title: '는 바람에',
    titleVi: 'Nguyên nhân ngoài ý muốn 는 바람에',
    explanationVi:
      "'는 바람에' diễn tả nguyên nhân bất ngờ, ngoài ý muốn dẫn đến một kết quả TIÊU CỰC. Không dùng cho kết quả tích cực hoặc câu ở thì tương lai/mệnh lệnh.",
    structure: '동사(hiện tại) + 는 바람에',
    keyPoints: ['넘어지다 → 넘어지는 바람에 (vì bị ngã nên...)', 'Chỉ dùng cho kết quả xấu, không dùng cho kết quả tốt', 'Không dùng ở câu mệnh lệnh/đề nghị'],
    examples: [
      { id: 'ko-b2-gr-barame-s1', text: '급하게 나오는 바람에 지갑을 두고 왔어요.', translationVi: 'Vì ra khỏi nhà vội vàng nên tôi đã để quên ví.' },
      { id: 'ko-b2-gr-barame-s2', text: '아이가 우는 바람에 잠을 설쳤어요.', translationVi: 'Vì đứa trẻ khóc nên tôi đã ngủ không ngon giấc.' },
      { id: 'ko-b2-gr-barame-s3', text: '차가 막히는 바람에 약속에 늦었어요.', translationVi: 'Vì kẹt xe nên tôi đã đến trễ cuộc hẹn.' },
    ],
    commonMistakesVi: "Người học hay dùng '는 바람에' cho kết quả tích cực, ví dụ nói sai '열심히 공부하는 바람에 시험에 합격했어요' — nên dùng '기 때문에' hoặc '아/어서' cho kết quả tốt.",
    exercises: [
      {
        id: 'ko-b2-gr-barame-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp (kết quả tiêu cực, ngoài ý muốn).',
        question: '올바른 문장을 고르세요.',
        options: ['차가 막히는 바람에 약속에 늦었어요.', '열심히 공부하는 바람에 합격했어요.', '내일 비가 오는 바람에 소풍을 갈 거예요.', '차가 막히는 바람에 일찍 도착했어요.'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-gr-barame-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '아이가 우___ 잠을 설쳤어요.',
        wordBank: ['는 바람에', '기 때문에', '지만'],
        correctAnswer: '는 바람에',
      },
      {
        id: 'ko-b2-gr-barame-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì ra khỏi nhà vội vàng nên tôi đã để quên ví."',
        words: ['지갑을 두고 왔어요', '급하게', '나오는 바람에'],
        correctOrder: ['급하게', '나오는 바람에', '지갑을 두고 왔어요'],
      },
    ],
  },
  {
    id: 'ko-b2-gr-lppunman-anira',
    languageCode: 'ko',
    level: 'B2',
    title: '(으)ㄹ 뿐만 아니라',
    titleVi: 'Liệt kê bổ sung (으)ㄹ 뿐만 아니라',
    explanationVi:
      "'(으)ㄹ 뿐만 아니라' nghĩa là 'không chỉ...mà còn...', dùng để liệt kê hai đặc điểm liên quan, ý sau thường nâng cao/bổ sung cho ý trước. Thường kèm 도 ở vế sau.",
    structure: '동사/형용사 어간 + (으)ㄹ 뿐만 아니라, ...도',
    keyPoints: ["이 카페는 조용할 뿐만 아니라 커피도 맛있어요.", "그는 노래를 잘할 뿐만 아니라 춤도 잘 춰요.", '뿐만 아니라 có thể theo sau bởi danh từ + 도: N도, V도'],
    examples: [
      { id: 'ko-b2-gr-ppunman-s1', text: '이 카페는 조용할 뿐만 아니라 커피도 맛있어요.', translationVi: 'Quán cà phê này không chỉ yên tĩnh mà cà phê cũng ngon.' },
      { id: 'ko-b2-gr-ppunman-s2', text: '그는 노래를 잘할 뿐만 아니라 춤도 잘 춰요.', translationVi: 'Anh ấy không chỉ hát hay mà còn nhảy giỏi.' },
      { id: 'ko-b2-gr-ppunman-s3', text: '이 지역은 교통이 편리할 뿐만 아니라 안전해요.', translationVi: 'Khu vực này không chỉ giao thông tiện lợi mà còn an toàn.' },
    ],
    commonMistakesVi: "Người học hay quên thêm '도' ở vế sau để nhấn mạnh sự bổ sung, làm câu nghe thiếu tự nhiên.",
    exercises: [
      {
        id: 'ko-b2-gr-ppunman-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '그는 노래를 잘___ 춤도 잘 춰요.',
        options: ['할 뿐만 아니라', '하는 바람에', '하더라도', '할수록'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-gr-ppunman-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '이 카페는 조용___ 커피도 맛있어요.',
        wordBank: ['할 뿐만 아니라', '해서', '한데'],
        correctAnswer: '할 뿐만 아니라',
      },
      {
        id: 'ko-b2-gr-ppunman-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Khu vực này không chỉ giao thông tiện lợi mà còn an toàn."',
        words: ['안전해요', '교통이 편리할 뿐만 아니라', '이 지역은'],
        correctOrder: ['이 지역은', '교통이 편리할 뿐만 아니라', '안전해요'],
      },
    ],
  },
  {
    id: 'ko-b2-gr-neun-banmyeone',
    languageCode: 'ko',
    level: 'B2',
    title: '는 반면에',
    titleVi: 'Đối lập nâng cao 는 반면에',
    explanationVi:
      "'는/(으)ㄴ 반면에' diễn tả sự tương phản rõ ràng giữa hai mặt của cùng một vấn đề, trang trọng hơn 지만, thường dùng khi phân tích ưu/nhược điểm.",
    structure: '동사 + 는 반면에 / 형용사 + (으)ㄴ 반면에',
    keyPoints: ["이 도시는 물가가 비싼 반면에 편의시설이 많아요.", '자주 dùng trong văn viết phân tích, so sánh', "Khác 지만: 반면에 nhấn mạnh tính CHÍNH THỨC, RÕ RÀNG của sự đối lập"],
    examples: [
      { id: 'ko-b2-gr-banmyeon-s1', text: '이 도시는 물가가 비싼 반면에 편의시설이 많아요.', translationVi: 'Thành phố này vật giá đắt, nhưng mặt khác tiện ích lại nhiều.' },
      { id: 'ko-b2-gr-banmyeon-s2', text: '그 영화는 재미있는 반면에 너무 길어요.', translationVi: 'Bộ phim đó thú vị, nhưng mặt khác lại quá dài.' },
      { id: 'ko-b2-gr-banmyeon-s3', text: '재택근무는 편한 반면에 외로울 수 있어요.', translationVi: 'Làm việc tại nhà thoải mái, nhưng mặt khác có thể cô đơn.' },
    ],
    commonMistakesVi: "Người học hay dùng '는 반면에' cho hai ý không thực sự đối lập, làm câu văn thiếu logic — chỉ dùng khi hai vế thực sự trái ngược.",
    exercises: [
      {
        id: 'ko-b2-gr-banmyeon-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '그 영화는 재미있___ 너무 길어요.',
        options: ['는 반면에', '을 뿐만 아니라', '기 마련이에요', '더라도'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-gr-banmyeon-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '재택근무는 편한 ___ 외로울 수 있어요.',
        wordBank: ['반면에', '바람에', '뿐만 아니라'],
        correctAnswer: '반면에',
      },
      {
        id: 'ko-b2-gr-banmyeon-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Thành phố này vật giá đắt, nhưng tiện ích lại nhiều."',
        words: ['편의시설이 많아요', '이 도시는', '물가가 비싼 반면에'],
        correctOrder: ['이 도시는', '물가가 비싼 반면에', '편의시설이 많아요'],
      },
    ],
  },
  {
    id: 'ko-b2-gr-deorado',
    languageCode: 'ko',
    level: 'B2',
    title: '더라도',
    titleVi: 'Nhượng bộ giả định 더라도',
    explanationVi:
      "'더라도' diễn tả một tình huống giả định, thậm chí cực đoan, nhưng kết quả/quyết định vẫn không thay đổi. Mạnh và trang trọng hơn 아/어도, thường đi cùng '아무리'.",
    structure: '동사/형용사 어간 + 더라도',
    keyPoints: ["아무리 늦더라도 꼭 갈게요.", '더라도 nhấn mạnh tính giả định cực đoan hơn 아/어도', 'Thường dùng để thể hiện quyết tâm/cam kết bất kể hoàn cảnh'],
    examples: [
      { id: 'ko-b2-gr-deorado-s1', text: '아무리 늦더라도 꼭 갈게요.', translationVi: 'Dù có trễ đến đâu đi nữa thì tôi cũng nhất định sẽ đến.' },
      { id: 'ko-b2-gr-deorado-s2', text: '비가 오더라도 경기는 계속될 거예요.', translationVi: 'Dù có mưa đi nữa thì trận đấu vẫn sẽ tiếp tục.' },
      { id: 'ko-b2-gr-deorado-s3', text: '몸이 힘들더라도 약속은 지킬 거예요.', translationVi: 'Dù có mệt trong người đi nữa thì tôi cũng sẽ giữ lời hứa.' },
    ],
    commonMistakesVi: "Người học hay dùng '더라도' cho những tình huống thông thường, ít mang tính giả định/cực đoan — trong trường hợp đó nên dùng 아/어도 nhẹ nhàng hơn.",
    exercises: [
      {
        id: 'ko-b2-gr-deorado-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '비가 ___ 경기는 계속될 거예요.',
        options: ['오더라도', '오는 바람에', '올 뿐만 아니라', '올수록'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-b2-gr-deorado-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '몸이 힘들___ 약속은 지킬 거예요.',
        wordBank: ['더라도', '어서', '지만'],
        correctAnswer: '더라도',
      },
      {
        id: 'ko-b2-gr-deorado-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Dù có trễ đến đâu đi nữa thì tôi cũng nhất định sẽ đến."',
        words: ['꼭 갈게요', '아무리', '늦더라도'],
        correctOrder: ['아무리', '늦더라도', '꼭 갈게요'],
      },
    ],
  },
];
