import type { GrammarTopic } from '../types';

export const englishA1GrammarTopics: GrammarTopic[] = [
  {
    id: 'gr-to-be',
    languageCode: 'en',
    level: 'A1',
    title: 'Verb "to be"',
    titleVi: 'Động từ "to be"',
    explanationVi:
      "Động từ 'to be' (am/is/are) dùng để nói về trạng thái, đặc điểm, hoặc giới thiệu bản thân. Đây là động từ quan trọng và xuất hiện nhiều nhất trong tiếng Anh cơ bản.",
    structure: "I am / He, She, It is / You, We, They are",
    keyPoints: [
      'I + am',
      'He / She / It + is',
      'You / We / They + are',
      "Có thể viết tắt: I'm, He's, You're...",
    ],
    examples: [
      { id: 'gr-to-be-s1', text: 'I am a student.', translationVi: 'Tôi là một sinh viên.' },
      { id: 'gr-to-be-s2', text: 'She is from Vietnam.', translationVi: 'Cô ấy đến từ Việt Nam.' },
      { id: 'gr-to-be-s3', text: 'They are my friends.', translationVi: 'Họ là bạn của tôi.' },
    ],
    commonMistakesVi:
      "Người mới học thường chia sai am/is/are theo chủ ngữ, ví dụ nói 'I is' thay vì 'I am', hoặc 'She are' thay vì 'She is'.",
    exercises: [
      {
        id: 'gr-to-be-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: 'I ___ a teacher.',
        options: ['am', 'is', 'are', 'be'],
        correctOptionIndex: 0,
        explanationVi: "Chủ ngữ 'I' luôn đi với 'am'.",
      },
      {
        id: 'gr-to-be-ex2',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: 'She ___ from Japan.',
        options: ['am', 'is', 'are', 'be'],
        correctOptionIndex: 1,
        explanationVi: "Chủ ngữ số ít (she/he/it) đi với 'is'.",
      },
      {
        id: 'gr-to-be-ex3',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: 'They ___ students.',
        wordBank: ['are', 'is', 'am'],
        correctAnswer: 'are',
        explanationVi: "'They' là chủ ngữ số nhiều, dùng 'are'.",
      },
      {
        id: 'gr-to-be-ex4',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['is', 'a', 'He', 'teacher'],
        correctOrder: ['He', 'is', 'a', 'teacher'],
        explanationVi: 'Trật tự câu khẳng định: Chủ ngữ + is/am/are + phần bổ nghĩa.',
      },
      {
        id: 'gr-to-be-ex5',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng.',
        question: 'Choose the correct sentence.',
        options: ['I is a student.', 'I am a student.', 'I are a student.', 'I be a student.'],
        correctOptionIndex: 1,
        explanationVi: "'I' luôn đi với 'am', không phải 'is' hay 'are'.",
      },
    ],
  },
  {
    id: 'gr-subject-pronouns',
    languageCode: 'en',
    level: 'A1',
    title: 'Subject pronouns',
    titleVi: 'Đại từ nhân xưng làm chủ ngữ',
    explanationVi:
      'Đại từ nhân xưng (I, you, he, she, it, we, they) dùng để thay thế cho danh từ đã biết, đứng ở đầu câu làm chủ ngữ.',
    structure: 'I – you – he – she – it – we – they',
    keyPoints: [
      'I: tôi (luôn viết hoa)',
      'He: dùng cho nam giới, She: dùng cho nữ giới',
      'It: dùng cho vật, động vật, hoặc khái niệm',
      'We: chúng tôi/chúng ta, They: họ/chúng nó',
    ],
    examples: [
      { id: 'gr-pron-s1', text: 'I am Lan.', translationVi: 'Tôi là Lan.' },
      { id: 'gr-pron-s2', text: 'He is my brother.', translationVi: 'Anh ấy là anh trai tôi.' },
      { id: 'gr-pron-s3', text: 'We are from Vietnam.', translationVi: 'Chúng tôi đến từ Việt Nam.' },
    ],
    commonMistakesVi: "Nhầm lẫn giữa He/She khi nói về người, hoặc quên viết hoa chữ 'I'.",
    exercises: [
      {
        id: 'gr-pron-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn đại từ đúng.',
        question: 'Minh is a boy. ___ is a student.',
        options: ['She', 'He', 'It', 'They'],
        correctOptionIndex: 1,
        explanationVi: "Dùng 'He' để thay cho một người nam giới đã nhắc tới.",
      },
      {
        id: 'gr-pron-ex2',
        type: 'multiple-choice',
        promptVi: 'Chọn đại từ đúng.',
        question: 'Lan and Minh are friends. ___ are students.',
        options: ['He', 'She', 'They', 'It'],
        correctOptionIndex: 2,
        explanationVi: "Dùng 'They' khi nói về từ hai người/vật trở lên.",
      },
      {
        id: 'gr-pron-ex3',
        type: 'fill-blank',
        promptVi: 'Điền đại từ còn thiếu.',
        sentenceTemplate: 'My mother is a teacher. ___ is kind.',
        wordBank: ['She', 'He', 'They'],
        correctAnswer: 'She',
        explanationVi: "'Mother' là nữ giới nên dùng 'She'.",
      },
      {
        id: 'gr-pron-ex4',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['is', 'my', 'It', 'book'],
        correctOrder: ['It', 'is', 'my', 'book'],
        explanationVi: "Dùng 'It' cho đồ vật.",
      },
      {
        id: 'gr-pron-ex5',
        type: 'multiple-choice',
        promptVi: 'Chọn đại từ đúng.',
        question: "Choose the correct pronoun for 'a cat'.",
        options: ['He', 'She', 'It', 'They'],
        correctOptionIndex: 2,
        explanationVi: "Động vật/đồ vật dùng 'It'.",
      },
    ],
  },
  {
    id: 'gr-possessive-adjectives',
    languageCode: 'en',
    level: 'A1',
    title: 'Possessive adjectives',
    titleVi: 'Tính từ sở hữu',
    explanationVi:
      'Tính từ sở hữu (my, your, his, her, its, our, their) đứng trước danh từ để chỉ vật/người đó thuộc về ai.',
    structure: 'my / your / his / her / its / our / their + danh từ',
    keyPoints: [
      'my: của tôi, your: của bạn',
      'his: của anh ấy, her: của cô ấy',
      'our: của chúng tôi, their: của họ',
      'Luôn đứng trước danh từ, không đứng một mình',
    ],
    examples: [
      { id: 'gr-poss-s1', text: 'This is my father.', translationVi: 'Đây là bố của tôi.' },
      { id: 'gr-poss-s2', text: 'Her name is Lan.', translationVi: 'Tên của cô ấy là Lan.' },
      { id: 'gr-poss-s3', text: 'Their house is big.', translationVi: 'Nhà của họ to.' },
    ],
    commonMistakesVi: "Nhầm giữa 'his' và 'her', hoặc dùng 'he'/'she' thay vì 'his'/'her' trước danh từ.",
    exercises: [
      {
        id: 'gr-poss-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng. (I)',
        question: 'This is ___ sister.',
        options: ['my', 'your', 'his', 'her'],
        correctOptionIndex: 0,
        explanationVi: "'I' → 'my'.",
      },
      {
        id: 'gr-poss-ex2',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng. (he)',
        question: 'That is ___ car.',
        options: ['my', 'her', 'his', 'their'],
        correctOptionIndex: 2,
        explanationVi: "'He' → 'his'.",
      },
      {
        id: 'gr-poss-ex3',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu. (she)',
        sentenceTemplate: 'She loves ___ family.',
        wordBank: ['her', 'his', 'my'],
        correctAnswer: 'her',
        explanationVi: "'She' → 'her'.",
      },
      {
        id: 'gr-poss-ex4',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng.',
        words: ['is', 'mother', 'my', 'This'],
        correctOrder: ['This', 'is', 'my', 'mother'],
        explanationVi: 'Trật tự: This/That + is + tính từ sở hữu + danh từ.',
      },
      {
        id: 'gr-poss-ex5',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng. (we)',
        question: 'We love ___ parents.',
        options: ['our', 'your', 'their', 'its'],
        correctOptionIndex: 0,
        explanationVi: "'We' → 'our'.",
      },
    ],
  },
];
