import type { Lesson } from '../../types';

export const chineseFamilyLessons: Lesson[] = [
  {
    id: 'zh-l3-1-family-members',
    unitId: 'zh-u3-family',
    title: '家庭成员',
    titleVi: 'Các thành viên trong gia đình',
    objectiveVi: 'Gọi tên được các thành viên cơ bản trong gia đình bằng tiếng Trung.',
    estimatedMinutes: 6,
    grammarNoteVi:
      "Tiếng Trung phân biệt anh/em, chị/em theo THỨ BẬC tuổi: 哥哥 (anh trai, lớn tuổi hơn) khác 弟弟 (em trai, nhỏ tuổi hơn); 姐姐 (chị gái) khác 妹妹 (em gái) — không dùng chung một từ như tiếng Anh 'brother/sister'.",
    vocabulary: [
      {
        id: 'zh-l3-1-v1',
        term: '家',
        translationVi: 'Gia đình / nhà',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l3-1-s1',
        usageNoteVi: 'Cách đọc (pinyin): jiā',
      },
      {
        id: 'zh-l3-1-v2',
        term: '爸爸',
        translationVi: 'Bố',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l3-1-s2',
        usageNoteVi: 'Cách đọc (pinyin): bàba',
      },
      {
        id: 'zh-l3-1-v3',
        term: '妈妈',
        translationVi: 'Mẹ',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l3-1-s2',
        usageNoteVi: 'Cách đọc (pinyin): māma',
      },
      {
        id: 'zh-l3-1-v4',
        term: '哥哥',
        translationVi: 'Anh trai (lớn tuổi hơn)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l3-1-s3',
        usageNoteVi: 'Cách đọc (pinyin): gēge. Em trai (nhỏ tuổi hơn) gọi là 弟弟 (dìdi).',
      },
      {
        id: 'zh-l3-1-v5',
        term: '姐姐',
        translationVi: 'Chị gái (lớn tuổi hơn)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l3-1-s3',
        usageNoteVi: 'Cách đọc (pinyin): jiějiě. Em gái (nhỏ tuổi hơn) gọi là 妹妹 (mèimei).',
      },
      {
        id: 'zh-l3-1-v6',
        term: '父母',
        translationVi: 'Bố mẹ',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc (pinyin): fùmǔ',
      },
    ],
    sentences: [
      { id: 'zh-l3-1-s1', text: '这是我的家。', translationVi: '(Zhè shì wǒ de jiā.) Đây là gia đình của tôi.' },
      {
        id: 'zh-l3-1-s2',
        text: '这是我爸爸和我妈妈。',
        translationVi: '(Zhè shì wǒ bàba hé wǒ māma.) Đây là bố và mẹ của tôi.',
      },
      {
        id: 'zh-l3-1-s3',
        text: '我有一个哥哥和一个姐姐。',
        translationVi: '(Wǒ yǒu yī gè gēge hé yī gè jiějiě.) Tôi có một anh trai và một chị gái.',
      },
    ],
    exercises: [
      {
        id: 'zh-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '妈妈'.",
        question: '妈妈',
        options: ['Bố', 'Mẹ', 'Chị gái', 'Bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '这是我___。',
        wordBank: ['爸爸', '学生', '名字'],
        correctAnswer: '爸爸',
      },
      {
        id: 'zh-l3-1-ex3',
        type: 'multiple-choice',
        promptVi: "Anh trai của bạn LỚN TUỔI hơn bạn. Từ nào đúng?",
        question: '比你大的哥哥怎么说？',
        options: ['哥哥', '弟弟', '姐姐', '妹妹'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'zh-l3-2-talking-about-family',
    unitId: 'zh-u3-family',
    title: '谈论家庭',
    titleVi: 'Nói về gia đình bạn',
    objectiveVi: "Sử dụng '有' để mô tả số lượng thành viên trong gia đình.",
    estimatedMinutes: 6,
    grammarNoteVi: "有 (yǒu) nghĩa là 'có', dùng chung cho mọi chủ ngữ (không chia như have/has trong tiếng Anh). Phủ định: 没有 (méiyǒu), không dùng 不有.",
    vocabulary: [
      {
        id: 'zh-l3-2-v1',
        term: '有',
        translationVi: 'Có',
        partOfSpeech: 'verb',
        exampleSentenceId: 'zh-l3-2-s1',
        usageNoteVi: 'Cách đọc (pinyin): yǒu',
      },
      {
        id: 'zh-l3-2-v2',
        term: '兄弟姐妹',
        translationVi: 'Anh chị em ruột',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l3-2-s1',
        usageNoteVi: 'Cách đọc (pinyin): xiōngdì jiěmèi',
      },
      {
        id: 'zh-l3-2-v3',
        term: '大家庭',
        translationVi: 'Đại gia đình / gia đình đông người',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (pinyin): dà jiātíng',
      },
      {
        id: 'zh-l3-2-v4',
        term: '小家庭',
        translationVi: 'Gia đình nhỏ',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l3-2-s3',
        usageNoteVi: 'Cách đọc (pinyin): xiǎo jiātíng',
      },
      {
        id: 'zh-l3-2-v5',
        term: '一起住',
        translationVi: 'Sống cùng',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l3-2-s2',
        usageNoteVi: 'Cách đọc (pinyin): yīqǐ zhù',
      },
    ],
    sentences: [
      {
        id: 'zh-l3-2-s1',
        text: '我有两个兄弟姐妹。',
        translationVi: '(Wǒ yǒu liǎng gè xiōngdì jiěmèi.) Tôi có hai anh chị em.',
      },
      { id: 'zh-l3-2-s2', text: '我和父母一起住。', translationVi: '(Wǒ hé fùmǔ yīqǐ zhù.) Tôi sống cùng bố mẹ.' },
      { id: 'zh-l3-2-s3', text: '我们是一个小家庭。', translationVi: '(Wǒmen shì yī gè xiǎo jiātíng.) Chúng tôi là một gia đình nhỏ.' },
    ],
    exercises: [
      {
        id: 'zh-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '兄弟姐妹'.",
        question: '兄弟姐妹',
        options: ['Bố mẹ', 'Anh chị em ruột', 'Bạn bè', 'Hàng xóm'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '我___两个兄弟姐妹。',
        wordBank: ['有', '是', '叫'],
        correctAnswer: '有',
      },
      {
        id: 'zh-l3-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp.',
        question: '选择正确的句子。',
        options: ['我有两个兄弟姐妹。', '我们有两个兄弟姐妹有。', '两个兄弟姐妹我有。', '我没兄弟姐妹有。'],
        correctOptionIndex: 0,
      },
    ],
  },
];
