import type { Lesson } from '../../types';

export const chineseGreetingsLessons: Lesson[] = [
  {
    id: 'zh-l1-1-basic-greetings',
    unitId: 'zh-u1-greetings',
    title: '基本问候',
    titleVi: 'Lời chào cơ bản',
    objectiveVi: 'Sử dụng được các lời chào và tạm biệt cơ bản trong giao tiếp hằng ngày bằng tiếng Trung.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "Chữ Hán không biến đổi theo thì hay ngôi như tiếng Anh — 你好 dùng được ở mọi thời điểm trong ngày, không phân biệt sáng/chiều/tối như '早上好'/'晚上好'.",
    vocabulary: [
      {
        id: 'zh-l1-1-v1',
        term: '你好',
        translationVi: 'Xin chào',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'zh-l1-1-s1',
        usageNoteVi: 'Cách đọc (pinyin): nǐ hǎo',
      },
      {
        id: 'zh-l1-1-v2',
        term: '嗨',
        translationVi: 'Chào (thân mật)',
        partOfSpeech: 'greeting',
        usageNoteVi: "Cách đọc (pinyin): hāi. Mượn âm từ tiếng Anh 'hi', dùng với bạn bè thân.",
      },
      {
        id: 'zh-l1-1-v3',
        term: '早上好',
        translationVi: 'Chào buổi sáng',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'zh-l1-1-s2',
        usageNoteVi: 'Cách đọc (pinyin): zǎoshang hǎo',
      },
      {
        id: 'zh-l1-1-v4',
        term: '晚上好',
        translationVi: 'Chào buổi tối',
        partOfSpeech: 'greeting',
        usageNoteVi: 'Cách đọc (pinyin): wǎnshang hǎo',
      },
      {
        id: 'zh-l1-1-v5',
        term: '再见',
        translationVi: 'Tạm biệt',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'zh-l1-1-s3',
        usageNoteVi: 'Cách đọc (pinyin): zàijiàn',
      },
      {
        id: 'zh-l1-1-v6',
        term: '回头见',
        translationVi: 'Hẹn gặp lại',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-1-s3',
        usageNoteVi: 'Cách đọc (pinyin): huítóu jiàn',
      },
    ],
    sentences: [
      { id: 'zh-l1-1-s1', text: '你好，你好吗？', translationVi: '(Nǐ hǎo, nǐ hǎo ma?) Xin chào, bạn khỏe không?' },
      {
        id: 'zh-l1-1-s2',
        text: '早上好！祝你有美好的一天。',
        translationVi: '(Zǎoshang hǎo! Zhù nǐ yǒu měihǎo de yī tiān.) Chào buổi sáng! Chúc bạn một ngày tốt lành.',
      },
      { id: 'zh-l1-1-s3', text: '再见，回头见！', translationVi: '(Zàijiàn, huítóu jiàn!) Tạm biệt, hẹn gặp lại!' },
    ],
    exercises: [
      {
        id: 'zh-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '再见'.",
        question: '再见',
        options: ['Xin chào', 'Tạm biệt', 'Cảm ơn', 'Xin lỗi'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu chào hỏi.',
        sentenceTemplate: '___，你好吗？',
        wordBank: ['你好', '再见', '请'],
        correctAnswer: '你好',
      },
      {
        id: 'zh-l1-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Bây giờ là 8 giờ sáng. Bạn chào ai đó thế nào?',
        question: '现在是早上八点。你怎么打招呼？',
        options: ['晚上好', '早上好', '再见', '回头见'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'zh-l1-2-how-are-you',
    unitId: 'zh-u1-greetings',
    title: '你好吗？',
    titleVi: 'Hỏi thăm sức khỏe',
    objectiveVi: 'Hỏi và trả lời đơn giản về tình trạng sức khỏe, cảm xúc bằng tiếng Trung.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "吗 là trợ từ nghi vấn đặt ở CUỐI câu để tạo câu hỏi có/không, ví dụ '你好' (câu khẳng định) → '你好吗？' (câu hỏi), không cần đảo trật tự từ như tiếng Anh.",
    vocabulary: [
      {
        id: 'zh-l1-2-v1',
        term: '你好吗',
        translationVi: 'Bạn khỏe không',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-2-s1',
        usageNoteVi: 'Cách đọc (pinyin): nǐ hǎo ma',
      },
      {
        id: 'zh-l1-2-v2',
        term: '很好',
        translationVi: 'Rất khỏe / tốt',
        partOfSpeech: 'adjective',
        exampleSentenceId: 'zh-l1-2-s2',
        usageNoteVi: 'Cách đọc (pinyin): hěn hǎo',
      },
      {
        id: 'zh-l1-2-v3',
        term: '还好',
        translationVi: 'Cũng ổn',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (pinyin): hái hǎo. Cách trả lời trung tính, không quá tốt cũng không quá tệ.',
      },
      {
        id: 'zh-l1-2-v4',
        term: '累',
        translationVi: 'Mệt',
        partOfSpeech: 'adjective',
        exampleSentenceId: 'zh-l1-2-s3',
        usageNoteVi: 'Cách đọc (pinyin): lèi',
      },
      {
        id: 'zh-l1-2-v5',
        term: '谢谢',
        translationVi: 'Cảm ơn',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-2-s2',
        usageNoteVi: 'Cách đọc (pinyin): xièxiè',
      },
      {
        id: 'zh-l1-2-v6',
        term: '你呢',
        translationVi: 'Còn bạn thì sao',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-2-s2',
        usageNoteVi: 'Cách đọc (pinyin): nǐ ne',
      },
    ],
    sentences: [
      { id: 'zh-l1-2-s1', text: '你今天好吗？', translationVi: '(Nǐ jīntiān hǎo ma?) Hôm nay bạn khỏe không?' },
      { id: 'zh-l1-2-s2', text: '我很好，谢谢。你呢？', translationVi: '(Wǒ hěn hǎo, xièxiè. Nǐ ne?) Tôi khỏe, cảm ơn. Còn bạn?' },
      { id: 'zh-l1-2-s3', text: '我今天有点累。', translationVi: '(Wǒ jīntiān yǒudiǎn lèi.) Hôm nay tôi hơi mệt.' },
    ],
    exercises: [
      {
        id: 'zh-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: "Đâu là câu trả lời phù hợp cho câu hỏi '你好吗？'",
        question: '你好吗？',
        options: ['我从越南来', '我很好，谢谢', '我叫兰', '回头见'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '我很好，谢谢。___？',
        wordBank: ['你呢', '你好', '再见'],
        correctAnswer: '你呢',
      },
      {
        id: 'zh-l1-2-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '累'.",
        question: '累',
        options: ['Vui', 'Mệt', 'Khỏe', 'Buồn'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'zh-l1-3-politeness',
    unitId: 'zh-u1-greetings',
    title: '基本礼貌',
    titleVi: 'Phép lịch sự cơ bản',
    objectiveVi: 'Sử dụng các từ lịch sự cơ bản: làm ơn, cảm ơn, xin lỗi bằng tiếng Trung.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "对不起 dùng khi bạn thật sự đã làm điều gì sai; 不好意思 nhẹ nhàng hơn, dùng để xin phép, làm phiền hoặc ngại ngùng nhẹ.",
    vocabulary: [
      {
        id: 'zh-l1-3-v1',
        term: '请',
        translationVi: 'Làm ơn / xin mời',
        partOfSpeech: 'phrase',
        usageNoteVi: "Cách đọc (pinyin): qǐng. Đặt ở đầu câu để lịch sự hơn, ví dụ: '请问...' (xin hỏi...).",
      },
      {
        id: 'zh-l1-3-v2',
        term: '不客气',
        translationVi: 'Không có gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-3-s2',
        usageNoteVi: 'Cách đọc (pinyin): bú kèqi',
      },
      {
        id: 'zh-l1-3-v3',
        term: '对不起',
        translationVi: 'Xin lỗi (khi mắc lỗi)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-3-s3',
        usageNoteVi: "Cách đọc (pinyin): duìbuqǐ",
      },
      {
        id: 'zh-l1-3-v4',
        term: '不好意思',
        translationVi: 'Xin lỗi / xin phép (nhẹ nhàng)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-3-s1',
        usageNoteVi: "Cách đọc (pinyin): bù hǎoyìsi. Dùng khi hỏi đường hoặc làm phiền nhẹ, khác 对不起.",
      },
      {
        id: 'zh-l1-3-v5',
        term: '没关系',
        translationVi: 'Không sao',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (pinyin): méi guānxi. Dùng để đáp lại khi ai đó xin lỗi bạn.',
      },
      {
        id: 'zh-l1-3-v6',
        term: '谢谢',
        translationVi: 'Cảm ơn',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l1-3-s2',
        usageNoteVi: 'Cách đọc (pinyin): xièxiè',
      },
    ],
    sentences: [
      {
        id: 'zh-l1-3-s1',
        text: '不好意思，请问洗手间在哪里？',
        translationVi: '(Bù hǎoyìsi, qǐngwèn xǐshǒujiān zài nǎlǐ?) Xin lỗi, cho hỏi nhà vệ sinh ở đâu?',
      },
      {
        id: 'zh-l1-3-s2',
        text: '非常谢谢你！——不客气。',
        translationVi: '(Fēicháng xièxiè nǐ! — Bú kèqi.) Cảm ơn bạn rất nhiều! — Không có gì.',
      },
      { id: 'zh-l1-3-s3', text: '对不起，我迟到了。', translationVi: '(Duìbuqǐ, wǒ chídào le.) Xin lỗi, tôi đến muộn.' },
    ],
    exercises: [
      {
        id: 'zh-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Khi ai đó nói '谢谢' với bạn, bạn đáp lại thế nào?",
        question: '谢谢！',
        options: ['对不起', '不客气', '再见', '请'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '___，请问洗手间在哪里？',
        wordBank: ['不好意思', '谢谢', '再见'],
        correctAnswer: '不好意思',
      },
      {
        id: 'zh-l1-3-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '请'.",
        question: '请',
        options: ['Làm ơn', 'Cảm ơn', 'Xin lỗi', 'Tạm biệt'],
        correctOptionIndex: 0,
      },
    ],
  },
];
