import type { Lesson } from '../../types';

export const chineseIntroductionsLessons: Lesson[] = [
  {
    id: 'zh-l2-1-whats-your-name',
    unitId: 'zh-u2-introductions',
    title: '你叫什么名字？',
    titleVi: 'Tên của bạn là gì?',
    objectiveVi: "Hỏi tên người khác và giới thiệu tên của mình bằng mẫu câu '我叫...'.",
    estimatedMinutes: 6,
    grammarNoteVi: "Dùng '我叫' + tên để nói tên mình (nghĩa đen 'tôi gọi là'), hoặc '我是' + tên cho trang trọng hơn một chút.",
    vocabulary: [
      {
        id: 'zh-l2-1-v1',
        term: '名字',
        translationVi: 'Tên',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l2-1-s2',
        usageNoteVi: 'Cách đọc (pinyin): míngzi',
      },
      {
        id: 'zh-l2-1-v2',
        term: '你叫什么名字',
        translationVi: 'Bạn tên là gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-1-s1',
        usageNoteVi: 'Cách đọc (pinyin): nǐ jiào shénme míngzi',
      },
      {
        id: 'zh-l2-1-v3',
        term: '我叫',
        translationVi: 'Tôi tên là',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-1-s2',
        usageNoteVi: 'Cách đọc (pinyin): wǒ jiào',
      },
      {
        id: 'zh-l2-1-v4',
        term: '很高兴认识你',
        translationVi: 'Rất vui được biết bạn',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-1-s2',
        usageNoteVi: 'Cách đọc (pinyin): hěn gāoxìng rènshi nǐ',
      },
      {
        id: 'zh-l2-1-v5',
        term: '我是',
        translationVi: 'Tôi là',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-1-s3',
        usageNoteVi: 'Cách đọc (pinyin): wǒ shì',
      },
    ],
    sentences: [
      { id: 'zh-l2-1-s1', text: '你叫什么名字？', translationVi: '(Nǐ jiào shénme míngzi?) Bạn tên là gì?' },
      {
        id: 'zh-l2-1-s2',
        text: '我叫兰，很高兴认识你。',
        translationVi: '(Wǒ jiào Lán, hěn gāoxìng rènshi nǐ.) Tôi tên là Lan, rất vui được biết bạn.',
      },
      { id: 'zh-l2-1-s3', text: '我是明。', translationVi: '(Wǒ shì Míng.) Tôi là Minh.' },
    ],
    exercises: [
      {
        id: 'zh-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Câu '你叫什么名字？' có nghĩa là gì?",
        question: '你叫什么名字？',
        options: ['Bạn khỏe không?', 'Tên bạn là gì?', 'Bạn đến từ đâu?', 'Rất vui được biết bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '我___兰。',
        wordBank: ['叫', '很', '请'],
        correctAnswer: '叫',
      },
      {
        id: 'zh-l2-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng để giới thiệu tên của bạn là Minh.',
        question: '选择正确的句子。',
        options: ['我叫明。', '明叫我。', '名字我明。', '叫我明。'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'zh-l2-2-where-are-you-from',
    unitId: 'zh-u2-introductions',
    title: '你从哪里来？',
    titleVi: 'Bạn đến từ đâu?',
    objectiveVi: 'Nói được quốc gia của mình và hỏi người khác đến từ đâu bằng tiếng Trung.',
    estimatedMinutes: 6,
    grammarNoteVi: "Dùng '我从' + địa điểm + '来' để nói 'tôi đến từ...'. Ví dụ: 我从越南来, 我从日本来.",
    vocabulary: [
      {
        id: 'zh-l2-2-v1',
        term: '你从哪里来',
        translationVi: 'Bạn đến từ đâu',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-2-s1',
        usageNoteVi: 'Cách đọc (pinyin): nǐ cóng nǎlǐ lái',
      },
      {
        id: 'zh-l2-2-v2',
        term: '我从…来',
        translationVi: 'Tôi đến từ...',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-2-s2',
        usageNoteVi: 'Cách đọc (pinyin): wǒ cóng…lái',
      },
      {
        id: 'zh-l2-2-v3',
        term: '越南',
        translationVi: 'Việt Nam',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l2-2-s2',
        usageNoteVi: 'Cách đọc (pinyin): Yuènán',
      },
      {
        id: 'zh-l2-2-v4',
        term: '国家',
        translationVi: 'Quốc gia',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc (pinyin): guójiā. Danh từ chỉ một quốc gia nói chung.',
      },
      {
        id: 'zh-l2-2-v5',
        term: '越南人',
        translationVi: 'Người Việt Nam',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l2-2-s3',
        usageNoteVi: 'Cách đọc (pinyin): Yuènánrén',
      },
    ],
    sentences: [
      { id: 'zh-l2-2-s1', text: '你从哪里来？', translationVi: '(Nǐ cóng nǎlǐ lái?) Bạn đến từ đâu?' },
      { id: 'zh-l2-2-s2', text: '我从越南来。', translationVi: '(Wǒ cóng Yuènán lái.) Tôi đến từ Việt Nam.' },
      { id: 'zh-l2-2-s3', text: '我是越南人。', translationVi: '(Wǒ shì Yuènánrén.) Tôi là người Việt Nam.' },
    ],
    exercises: [
      {
        id: 'zh-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '国家'.",
        question: '国家',
        options: ['Thành phố', 'Quốc gia', 'Ngôn ngữ', 'Gia đình'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '我___越南来。',
        wordBank: ['从', '是', '叫'],
        correctAnswer: '从',
      },
      {
        id: 'zh-l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi quê quán của ai đó.',
        question: '选择正确的问题。',
        options: ['你叫什么名字？', '你从哪里来？', '你好吗？', '谢谢。'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'zh-l2-3-age-job',
    unitId: 'zh-u2-introductions',
    title: '年龄和职业',
    titleVi: 'Tuổi và nghề nghiệp',
    objectiveVi: 'Nói được tuổi và nghề nghiệp của bản thân bằng các mẫu câu đơn giản.',
    estimatedMinutes: 6,
    grammarNoteVi: "Khi nói tuổi, tiếng Trung KHÔNG cần động từ 是 — chỉ cần Chủ ngữ + Số tuổi + 岁. Ví dụ: 我二十岁 (tôi 20 tuổi), không nói 我是二十岁.",
    vocabulary: [
      {
        id: 'zh-l2-3-v1',
        term: '你多大了',
        translationVi: 'Bạn bao nhiêu tuổi',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-3-s1',
        usageNoteVi: 'Cách đọc (pinyin): nǐ duō dà le',
      },
      {
        id: 'zh-l2-3-v2',
        term: '岁',
        translationVi: '...tuổi',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'zh-l2-3-s2',
        usageNoteVi: 'Cách đọc (pinyin): suì',
      },
      {
        id: 'zh-l2-3-v3',
        term: '学生',
        translationVi: 'Học sinh / sinh viên',
        partOfSpeech: 'noun',
        exampleSentenceId: 'zh-l2-3-s3',
        usageNoteVi: 'Cách đọc (pinyin): xuésheng',
      },
      { id: 'zh-l2-3-v4', term: '老师', translationVi: 'Giáo viên', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): lǎoshī' },
      {
        id: 'zh-l2-3-v5',
        term: '工程师',
        translationVi: 'Kỹ sư',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc (pinyin): gōngchéngshī',
      },
      { id: 'zh-l2-3-v6', term: '工作', translationVi: 'Công việc / nghề nghiệp', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): gōngzuò' },
    ],
    sentences: [
      { id: 'zh-l2-3-s1', text: '你多大了？', translationVi: '(Nǐ duō dà le?) Bạn bao nhiêu tuổi?' },
      { id: 'zh-l2-3-s2', text: '我二十岁。', translationVi: '(Wǒ èrshí suì.) Tôi hai mươi tuổi.' },
      { id: 'zh-l2-3-s3', text: '我是学生。', translationVi: '(Wǒ shì xuésheng.) Tôi là sinh viên.' },
    ],
    exercises: [
      {
        id: 'zh-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '学生'.",
        question: '学生',
        options: ['Giáo viên', 'Học sinh / sinh viên', 'Kỹ sư', 'Bác sĩ'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu (nghề nghiệp).',
        sentenceTemplate: '我是___。',
        wordBank: ['老师', '从', '好'],
        correctAnswer: '老师',
      },
      {
        id: 'zh-l2-3-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi tuổi của ai đó.',
        question: '选择正确的问题。',
        options: ['你叫什么名字？', '你多大了？', '你从哪里来？', '很高兴认识你。'],
        correctOptionIndex: 1,
      },
    ],
  },
];
