import type { Lesson } from '../../types';

export const koreanFamilyLessons: Lesson[] = [
  {
    id: 'ko-l3-1-family-members',
    unitId: 'ko-u3-family',
    title: '가족 구성원',
    titleVi: 'Các thành viên trong gia đình',
    objectiveVi: 'Gọi tên được các thành viên cơ bản trong gia đình bằng tiếng Hàn.',
    estimatedMinutes: 6,
    grammarNoteVi:
      "Từ chỉ 'anh trai/chị gái' trong tiếng Hàn phụ thuộc giới tính người NÓI: nam gọi anh trai là 형, nữ gọi anh trai là 오빠; nam gọi chị gái là 누나, nữ gọi chị gái là 언니.",
    vocabulary: [
      {
        id: 'ko-l3-1-v1',
        term: '가족',
        translationVi: 'Gia đình',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l3-1-s1',
        usageNoteVi: 'Cách đọc: gajok',
      },
      {
        id: 'ko-l3-1-v2',
        term: '아버지',
        translationVi: 'Bố',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l3-1-s2',
        usageNoteVi: 'Cách đọc: abeoji',
      },
      {
        id: 'ko-l3-1-v3',
        term: '어머니',
        translationVi: 'Mẹ',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l3-1-s2',
        usageNoteVi: 'Cách đọc: eomeoni',
      },
      {
        id: 'ko-l3-1-v4',
        term: '오빠',
        translationVi: 'Anh trai (người nói là nữ)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l3-1-s3',
        usageNoteVi: 'Cách đọc: oppa. Nếu người nói là nam, gọi anh trai là 형 (hyeong).',
      },
      {
        id: 'ko-l3-1-v5',
        term: '언니',
        translationVi: 'Chị gái (người nói là nữ)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l3-1-s3',
        usageNoteVi: 'Cách đọc: eonni. Nếu người nói là nam, gọi chị gái là 누나 (nuna).',
      },
      {
        id: 'ko-l3-1-v6',
        term: '부모님',
        translationVi: 'Bố mẹ',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc: bumonim. Dạng kính ngữ của 부모 (bố mẹ), dùng khi nói với người khác.',
      },
    ],
    sentences: [
      { id: 'ko-l3-1-s1', text: '이것은 제 가족이에요.', translationVi: '(igeoseun je gajogieyo.) Đây là gia đình của tôi.' },
      {
        id: 'ko-l3-1-s2',
        text: '이분은 제 아버지와 어머니예요.',
        translationVi: '(ibuneun je abeojiwa eomeoniyeyo.) Đây là bố và mẹ của tôi.',
      },
      {
        id: 'ko-l3-1-s3',
        text: '저는 오빠 한 명과 언니 한 명이 있어요.',
        translationVi: '(jeoneun oppa han myeonggwa eonni han myeongi isseoyo.) Tôi có một anh trai và một chị gái. (người nói là nữ)',
      },
    ],
    exercises: [
      {
        id: 'ko-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '어머니'.",
        question: '어머니',
        options: ['Bố', 'Mẹ', 'Chị gái', 'Bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '이분은 제 ___예요.',
        wordBank: ['아버지', '학생', '이름'],
        correctAnswer: '아버지',
      },
      {
        id: 'ko-l3-1-ex3',
        type: 'multiple-choice',
        promptVi: "Bạn là NỮ. Bạn muốn gọi anh trai. Từ nào đúng?",
        question: '여자가 오빠를 부를 때 쓰는 말은?',
        options: ['형', '오빠', '누나', '언니'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ko-l3-2-talking-about-family',
    unitId: 'ko-u3-family',
    title: '가족에 대해 이야기하기',
    titleVi: 'Nói về gia đình bạn',
    objectiveVi: "Sử dụng '있어요' để mô tả số lượng thành viên trong gia đình.",
    estimatedMinutes: 6,
    grammarNoteVi:
      "Dùng '...이/가 있어요' để nói 'có...'. Ví dụ: '형제자매가 있어요' (có anh chị em). 이 đi sau phụ âm, 가 đi sau nguyên âm.",
    vocabulary: [
      {
        id: 'ko-l3-2-v1',
        term: '있어요',
        translationVi: 'Có',
        partOfSpeech: 'verb',
        exampleSentenceId: 'ko-l3-2-s1',
        usageNoteVi: 'Cách đọc: isseoyo',
      },
      {
        id: 'ko-l3-2-v2',
        term: '형제자매',
        translationVi: 'Anh chị em ruột',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l3-2-s1',
        usageNoteVi: 'Cách đọc: hyeongjejamae',
      },
      {
        id: 'ko-l3-2-v3',
        term: '대가족',
        translationVi: 'Gia đình đông người',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc: daegajok. Trái nghĩa với 소가족.',
      },
      {
        id: 'ko-l3-2-v4',
        term: '소가족',
        translationVi: 'Gia đình ít người',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l3-2-s3',
        usageNoteVi: 'Cách đọc: sogajok',
      },
      {
        id: 'ko-l3-2-v5',
        term: '같이 살아요',
        translationVi: 'Sống cùng',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l3-2-s2',
        usageNoteVi: 'Cách đọc: gachi sarayo',
      },
    ],
    sentences: [
      {
        id: 'ko-l3-2-s1',
        text: '저는 형제자매가 두 명 있어요.',
        translationVi: '(jeoneun hyeongjejamaega du myeong isseoyo.) Tôi có hai anh chị em.',
      },
      { id: 'ko-l3-2-s2', text: '저는 부모님과 같이 살아요.', translationVi: '(jeoneun bumonimgwa gachi sarayo.) Tôi sống cùng bố mẹ.' },
      { id: 'ko-l3-2-s3', text: '우리는 소가족이에요.', translationVi: '(urineun sogajogieyo.) Chúng tôi là một gia đình nhỏ.' },
    ],
    exercises: [
      {
        id: 'ko-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '형제자매'.",
        question: '형제자매',
        options: ['Bố mẹ', 'Anh chị em ruột', 'Bạn bè', 'Hàng xóm'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '저는 형제자매가 두 명 ___.',
        wordBank: ['있어요', '이에요', '왔어요'],
        correctAnswer: '있어요',
      },
      {
        id: 'ko-l3-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp để nói "Tôi sống cùng bố mẹ".',
        question: '올바른 문장을 고르세요.',
        options: ['저는 부모님과 같이 살아요.', '저는 부모님 같이 살아요.', '부모님이 같이 살아요 저는.', '저는 같이 부모님.'],
        correctOptionIndex: 0,
      },
    ],
  },
];
