import type { Lesson } from '../../types';

export const koreanGreetingsLessons: Lesson[] = [
  {
    id: 'ko-l1-1-basic-greetings',
    unitId: 'ko-u1-greetings',
    title: '기본 인사',
    titleVi: 'Lời chào cơ bản',
    objectiveVi: 'Sử dụng được các lời chào và tạm biệt cơ bản trong giao tiếp hằng ngày bằng tiếng Hàn.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "Người Hàn có 2 cách nói tạm biệt khác nhau tùy ai là người rời đi: 안녕히 가세요 nói với người đang RỜI ĐI, còn 안녕히 계세요 nói với người Ở LẠI.",
    vocabulary: [
      {
        id: 'ko-l1-1-v1',
        term: '안녕하세요',
        translationVi: 'Xin chào',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'ko-l1-1-s1',
        usageNoteVi: 'Cách đọc: annyeonghaseyo',
      },
      {
        id: 'ko-l1-1-v2',
        term: '안녕',
        translationVi: 'Chào (thân mật)',
        partOfSpeech: 'greeting',
        usageNoteVi: "Cách đọc: annyeong. Thân mật hơn 안녕하세요, chỉ dùng với bạn bè ngang hàng hoặc người nhỏ tuổi hơn.",
      },
      {
        id: 'ko-l1-1-v3',
        term: '좋은 아침이에요',
        translationVi: 'Chào buổi sáng',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'ko-l1-1-s2',
        usageNoteVi: 'Cách đọc: joeun achimieyo',
      },
      {
        id: 'ko-l1-1-v4',
        term: '안녕히 가세요',
        translationVi: 'Tạm biệt (nói với người rời đi)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-1-s3',
        usageNoteVi: 'Cách đọc: annyeonghi gaseyo. Người Ở LẠI nói câu này với người đang rời đi.',
      },
      {
        id: 'ko-l1-1-v5',
        term: '안녕히 계세요',
        translationVi: 'Tạm biệt (nói với người ở lại)',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc: annyeonghi gyeseyo. Người RỜI ĐI nói câu này với người còn ở lại.',
      },
      {
        id: 'ko-l1-1-v6',
        term: '또 봐요',
        translationVi: 'Hẹn gặp lại',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-1-s3',
        usageNoteVi: 'Cách đọc: tto bwayo',
      },
    ],
    sentences: [
      { id: 'ko-l1-1-s1', text: '안녕하세요, 잘 지내세요?', translationVi: '(annyeonghaseyo, jal jinaeseyo?) Xin chào, bạn khỏe không?' },
      {
        id: 'ko-l1-1-s2',
        text: '좋은 아침이에요! 좋은 하루 되세요.',
        translationVi: '(joeun achimieyo! joeun haru doeseyo.) Chào buổi sáng! Chúc bạn một ngày tốt lành.',
      },
      { id: 'ko-l1-1-s3', text: '안녕히 가세요, 또 봐요!', translationVi: '(annyeonghi gaseyo, tto bwayo!) Tạm biệt, hẹn gặp lại!' },
    ],
    exercises: [
      {
        id: 'ko-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '안녕히 가세요'.",
        question: '안녕히 가세요',
        options: ['Xin chào', 'Tạm biệt (nói với người rời đi)', 'Cảm ơn', 'Xin lỗi'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu chào hỏi.',
        sentenceTemplate: '___, 잘 지내세요?',
        wordBank: ['안녕하세요', '안녕히 가세요', '감사합니다'],
        correctAnswer: '안녕하세요',
      },
      {
        id: 'ko-l1-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Bạn là người rời khỏi buổi họp trước. Bạn nói gì với người còn ở lại?',
        question: '떠나는 사람이 남아 있는 사람에게 하는 인사는?',
        options: ['안녕히 가세요', '안녕히 계세요', '좋은 아침이에요', '또 봐요'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ko-l1-2-how-are-you',
    unitId: 'ko-u1-greetings',
    title: '잘 지내요?',
    titleVi: 'Hỏi thăm sức khỏe',
    objectiveVi: 'Hỏi và trả lời đơn giản về tình trạng sức khỏe, cảm xúc bằng tiếng Hàn.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "Đuôi câu '-요' làm cho câu nói trở nên lịch sự, phù hợp giao tiếp hằng ngày với người không quá thân. Đây là văn phong 해요체, phổ biến nhất trong hội thoại.",
    vocabulary: [
      {
        id: 'ko-l1-2-v1',
        term: '잘 지내요?',
        translationVi: 'Bạn khỏe không',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-2-s1',
        usageNoteVi: 'Cách đọc: jal jinaeyo?',
      },
      {
        id: 'ko-l1-2-v2',
        term: '좋아요',
        translationVi: 'Tốt / Ổn',
        partOfSpeech: 'adjective',
        exampleSentenceId: 'ko-l1-2-s2',
        usageNoteVi: 'Cách đọc: joayo',
      },
      {
        id: 'ko-l1-2-v3',
        term: '아주 좋아요',
        translationVi: 'Rất tốt',
        partOfSpeech: 'adjective',
        usageNoteVi: "Cách đọc: aju joayo. Diễn tả cảm giác rất tốt, tích cực hơn 좋아요.",
      },
      {
        id: 'ko-l1-2-v4',
        term: '그저 그래요',
        translationVi: 'Cũng bình thường',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc: geujeo geuraeyo. Cách trả lời trung tính, không quá tốt cũng không quá tệ.',
      },
      {
        id: 'ko-l1-2-v5',
        term: '피곤해요',
        translationVi: 'Mệt',
        partOfSpeech: 'adjective',
        exampleSentenceId: 'ko-l1-2-s3',
        usageNoteVi: 'Cách đọc: pigonhaeyo',
      },
      {
        id: 'ko-l1-2-v6',
        term: '당신은요?',
        translationVi: 'Còn bạn thì sao',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-2-s2',
        usageNoteVi: 'Cách đọc: dangsineunyo? Trong hội thoại thân mật, người Hàn thường bỏ chủ ngữ và chỉ nói 그쪽은요?.',
      },
    ],
    sentences: [
      { id: 'ko-l1-2-s1', text: '오늘 잘 지내요?', translationVi: '(oneul jal jinaeyo?) Hôm nay bạn khỏe không?' },
      {
        id: 'ko-l1-2-s2',
        text: '저는 좋아요, 감사합니다. 당신은요?',
        translationVi: '(jeoneun joayo, gamsahamnida. dangsineunyo?) Tôi khỏe, cảm ơn. Còn bạn thì sao?',
      },
      { id: 'ko-l1-2-s3', text: '오늘 조금 피곤해요.', translationVi: '(oneul jogeum pigonhaeyo.) Hôm nay tôi hơi mệt.' },
    ],
    exercises: [
      {
        id: 'ko-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: "Đâu là câu trả lời phù hợp cho câu hỏi '잘 지내요?'",
        question: '잘 지내요?',
        options: ['저는 베트남에서 왔어요', '저는 좋아요, 감사합니다', '제 이름은 란이에요', '또 봐요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '저는 좋아요, 감사합니다. ___?',
        wordBank: ['당신은요', '어디에서', '몇 살'],
        correctAnswer: '당신은요',
      },
      {
        id: 'ko-l1-2-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '피곤해요'.",
        question: '피곤해요',
        options: ['Vui', 'Mệt', 'Khỏe', 'Buồn'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ko-l1-3-politeness',
    unitId: 'ko-u1-greetings',
    title: '기본 예의',
    titleVi: 'Phép lịch sự cơ bản',
    objectiveVi: 'Sử dụng các từ lịch sự cơ bản: cảm ơn, xin lỗi bằng tiếng Hàn.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "감사합니다 (trang trọng, dùng với người lớn tuổi/không quen) và 고마워요 (thân mật hơn) đều có nghĩa 'cảm ơn' nhưng khác sắc thái lịch sự.",
    vocabulary: [
      {
        id: 'ko-l1-3-v1',
        term: '감사합니다',
        translationVi: 'Cảm ơn (trang trọng)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-3-s2',
        usageNoteVi: 'Cách đọc: gamsahamnida',
      },
      {
        id: 'ko-l1-3-v2',
        term: '고마워요',
        translationVi: 'Cảm ơn (thân mật hơn)',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc: gomawoyo',
      },
      {
        id: 'ko-l1-3-v3',
        term: '천만에요',
        translationVi: 'Không có gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-3-s2',
        usageNoteVi: 'Cách đọc: cheonmaneyo',
      },
      {
        id: 'ko-l1-3-v4',
        term: '죄송합니다',
        translationVi: 'Xin lỗi (khi mắc lỗi, trang trọng)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-3-s3',
        usageNoteVi: 'Cách đọc: joesonghamnida',
      },
      {
        id: 'ko-l1-3-v5',
        term: '미안해요',
        translationVi: 'Xin lỗi (thân mật)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l1-3-s1',
        usageNoteVi: 'Cách đọc: mianhaeyo. Thân mật hơn 죄송합니다.',
      },
      {
        id: 'ko-l1-3-v6',
        term: '괜찮아요',
        translationVi: 'Không sao',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc: gwaenchanayo. Dùng để đáp lại khi ai đó xin lỗi bạn.',
      },
    ],
    sentences: [
      {
        id: 'ko-l1-3-s1',
        text: '저기요, 화장실이 어디예요?',
        translationVi: '(jeogiyo, hwajangsiri eodiyeyo?) Xin lỗi, nhà vệ sinh ở đâu ạ?',
      },
      {
        id: 'ko-l1-3-s2',
        text: '정말 감사합니다! — 천만에요.',
        translationVi: '(jeongmal gamsahamnida! — cheonmaneyo.) Cảm ơn bạn rất nhiều! — Không có gì.',
      },
      { id: 'ko-l1-3-s3', text: '죄송합니다, 늦었어요.', translationVi: '(joesonghamnida, neujeosseoyo.) Xin lỗi, tôi đến muộn.' },
    ],
    exercises: [
      {
        id: 'ko-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Khi ai đó nói '감사합니다' với bạn, bạn đáp lại thế nào?",
        question: '감사합니다!',
        options: ['죄송합니다', '천만에요', '안녕히 가세요', '괜찮아요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '___, 화장실이 어디예요?',
        wordBank: ['저기요', '감사합니다', '안녕히 가세요'],
        correctAnswer: '저기요',
      },
      {
        id: 'ko-l1-3-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '죄송합니다'.",
        question: '죄송합니다',
        options: ['Làm ơn', 'Cảm ơn', 'Xin lỗi (trang trọng)', 'Tạm biệt'],
        correctOptionIndex: 2,
      },
    ],
  },
];
