import type { Lesson } from '../../types';

export const koreanIntroductionsLessons: Lesson[] = [
  {
    id: 'ko-l2-1-whats-your-name',
    unitId: 'ko-u2-introductions',
    title: '이름이 뭐예요?',
    titleVi: 'Tên của bạn là gì?',
    objectiveVi: "Hỏi tên người khác và giới thiệu tên của mình bằng mẫu câu '...이에요/예요'.",
    estimatedMinutes: 6,
    grammarNoteVi:
      "Dùng '제 이름은' + tên + '이에요/예요' để giới thiệu bản thân. 이에요 đi sau tên kết thúc phụ âm, 예요 đi sau tên kết thúc nguyên âm.",
    vocabulary: [
      {
        id: 'ko-l2-1-v1',
        term: '이름',
        translationVi: 'Tên',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l2-1-s2',
        usageNoteVi: 'Cách đọc: ireum',
      },
      {
        id: 'ko-l2-1-v2',
        term: '이름이 뭐예요?',
        translationVi: 'Tên bạn là gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-1-s1',
        usageNoteVi: 'Cách đọc: ireumi mwoyeyo?',
      },
      {
        id: 'ko-l2-1-v3',
        term: '제 이름은...이에요',
        translationVi: 'Tên tôi là...',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-1-s2',
        usageNoteVi: 'Cách đọc: je ireumeun...ieyo',
      },
      {
        id: 'ko-l2-1-v4',
        term: '만나서 반가워요',
        translationVi: 'Rất vui được gặp bạn',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-1-s2',
        usageNoteVi: 'Cách đọc: mannaseo bangawoyo',
      },
      {
        id: 'ko-l2-1-v5',
        term: '저는...이에요',
        translationVi: 'Tôi là...',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-1-s3',
        usageNoteVi: 'Cách đọc: jeoneun...ieyo',
      },
    ],
    sentences: [
      { id: 'ko-l2-1-s1', text: '이름이 뭐예요?', translationVi: '(ireumi mwoyeyo?) Tên bạn là gì?' },
      {
        id: 'ko-l2-1-s2',
        text: '제 이름은 란이에요. 만나서 반가워요.',
        translationVi: '(je ireumeun Ran-ieyo. mannaseo bangawoyo.) Tên tôi là Lan. Rất vui được gặp bạn.',
      },
      { id: 'ko-l2-1-s3', text: '저는 민이에요.', translationVi: '(jeoneun Min-ieyo.) Tôi là Minh.' },
    ],
    exercises: [
      {
        id: 'ko-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Câu '이름이 뭐예요?' có nghĩa là gì?",
        question: '이름이 뭐예요?',
        options: ['Bạn khỏe không?', 'Tên bạn là gì?', 'Bạn đến từ đâu?', 'Rất vui được gặp bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '제 ___은 란이에요.',
        wordBank: ['이름', '좋아요', '감사합니다'],
        correctAnswer: '이름',
      },
      {
        id: 'ko-l2-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng để giới thiệu tên của bạn là Minh.',
        question: '이름이 민인 사람의 올바른 자기소개는?',
        options: ['저는 민이에요.', '민은 저예요.', '이름 민 저예요.', '저 이름은.'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'ko-l2-2-where-are-you-from',
    unitId: 'ko-u2-introductions',
    title: '어디에서 왔어요?',
    titleVi: 'Bạn đến từ đâu?',
    objectiveVi: 'Nói được quốc gia của mình và hỏi người khác đến từ đâu bằng tiếng Hàn.',
    estimatedMinutes: 6,
    grammarNoteVi: "Dùng trợ từ '에서' sau tên địa điểm + '왔어요' (đã đến) để nói bạn đến từ đâu. Ví dụ: 베트남에서 왔어요.",
    vocabulary: [
      {
        id: 'ko-l2-2-v1',
        term: '어디에서 왔어요?',
        translationVi: 'Bạn đến từ đâu',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-2-s1',
        usageNoteVi: 'Cách đọc: eodieseo wasseoyo?',
      },
      {
        id: 'ko-l2-2-v2',
        term: '저는...에서 왔어요',
        translationVi: 'Tôi đến từ...',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-2-s2',
        usageNoteVi: 'Cách đọc: jeoneun...eseo wasseoyo',
      },
      {
        id: 'ko-l2-2-v3',
        term: '베트남',
        translationVi: 'Việt Nam',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l2-2-s2',
        usageNoteVi: 'Cách đọc: beteunam',
      },
      {
        id: 'ko-l2-2-v4',
        term: '나라',
        translationVi: 'Quốc gia',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc: nara. Danh từ chỉ một quốc gia nói chung.',
      },
      {
        id: 'ko-l2-2-v5',
        term: '베트남 사람',
        translationVi: 'Người Việt Nam',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l2-2-s3',
        usageNoteVi: 'Cách đọc: beteunam saram',
      },
    ],
    sentences: [
      { id: 'ko-l2-2-s1', text: '어디에서 왔어요?', translationVi: '(eodieseo wasseoyo?) Bạn đến từ đâu?' },
      { id: 'ko-l2-2-s2', text: '저는 베트남에서 왔어요.', translationVi: '(jeoneun beteunam-eseo wasseoyo.) Tôi đến từ Việt Nam.' },
      { id: 'ko-l2-2-s3', text: '저는 베트남 사람이에요.', translationVi: '(jeoneun beteunam saram-ieyo.) Tôi là người Việt Nam.' },
    ],
    exercises: [
      {
        id: 'ko-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '나라'.",
        question: '나라',
        options: ['Thành phố', 'Quốc gia', 'Ngôn ngữ', 'Gia đình'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '저는 베트남___ 왔어요.',
        wordBank: ['에서', '은', '이'],
        correctAnswer: '에서',
      },
      {
        id: 'ko-l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi quê quán của ai đó.',
        question: '누군가의 고향을 물어보는 올바른 질문은?',
        options: ['이름이 뭐예요?', '어디에서 왔어요?', '잘 지내요?', '감사합니다.'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ko-l2-3-age-job',
    unitId: 'ko-u2-introductions',
    title: '나이와 직업',
    titleVi: 'Tuổi và nghề nghiệp',
    objectiveVi: 'Nói được tuổi và nghề nghiệp của bản thân bằng các mẫu câu đơn giản.',
    estimatedMinutes: 6,
    grammarNoteVi:
      "Khi nói tuổi, người Hàn dùng SỐ ĐẾM THUẦN HÀN (하나, 둘, 셋... → 한 살, 두 살) chứ không dùng số Hán-Hàn. Ví dụ: 20 tuổi = 스무 살 (không phải 이십 살).",
    vocabulary: [
      {
        id: 'ko-l2-3-v1',
        term: '나이가 어떻게 되세요?',
        translationVi: 'Bạn bao nhiêu tuổi (lịch sự)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-3-s1',
        usageNoteVi: 'Cách đọc: naiga eotteoke doeseyo?',
      },
      {
        id: 'ko-l2-3-v2',
        term: '살',
        translationVi: '...tuổi',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ko-l2-3-s2',
        usageNoteVi: 'Cách đọc: sal. Đi sau số đếm thuần Hàn, ví dụ 스무 살 (20 tuổi).',
      },
      {
        id: 'ko-l2-3-v3',
        term: '학생',
        translationVi: 'Học sinh / sinh viên',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ko-l2-3-s3',
        usageNoteVi: 'Cách đọc: haksaeng',
      },
      { id: 'ko-l2-3-v4', term: '선생님', translationVi: 'Giáo viên', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: seonsaengnim' },
      {
        id: 'ko-l2-3-v5',
        term: '회사원',
        translationVi: 'Nhân viên công ty',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc: hoesawon',
      },
      { id: 'ko-l2-3-v6', term: '직업', translationVi: 'Nghề nghiệp', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: jigeop' },
    ],
    sentences: [
      { id: 'ko-l2-3-s1', text: '나이가 어떻게 되세요?', translationVi: '(naiga eotteoke doeseyo?) Bạn bao nhiêu tuổi?' },
      { id: 'ko-l2-3-s2', text: '저는 스무 살이에요.', translationVi: '(jeoneun seumu sal-ieyo.) Tôi hai mươi tuổi.' },
      { id: 'ko-l2-3-s3', text: '저는 학생이에요.', translationVi: '(jeoneun haksaeng-ieyo.) Tôi là sinh viên.' },
    ],
    exercises: [
      {
        id: 'ko-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '학생'.",
        question: '학생',
        options: ['Giáo viên', 'Học sinh / sinh viên', 'Kỹ sư', 'Bác sĩ'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu (nghề nghiệp).',
        sentenceTemplate: '저는 ___이에요.',
        wordBank: ['선생님', '나라', '좋아요'],
        correctAnswer: '선생님',
      },
      {
        id: 'ko-l2-3-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi tuổi của ai đó.',
        question: '나이를 물어보는 올바른 질문은?',
        options: ['이름이 뭐예요?', '나이가 어떻게 되세요?', '어디에서 왔어요?', '만나서 반가워요.'],
        correctOptionIndex: 1,
      },
    ],
  },
];
