import type { GrammarTopic } from '../types';

export const koreanA1GrammarTopics: GrammarTopic[] = [
  {
    id: 'ko-gr-ieyo-yeyo',
    languageCode: 'ko',
    level: 'A1',
    title: '이에요/예요',
    titleVi: 'Đuôi câu "이에요/예요" (là...)',
    explanationVi:
      "이에요/예요 là dạng lịch sự của động từ 'là' (tương đương 'to be' + danh từ), dùng phổ biến trong văn nói hằng ngày. Dùng 이에요 khi danh từ đứng trước kết thúc bằng PHỤ ÂM (có batchim), dùng 예요 khi danh từ kết thúc bằng NGUYÊN ÂM.",
    structure: 'Danh từ (kết thúc phụ âm) + 이에요 / Danh từ (kết thúc nguyên âm) + 예요',
    keyPoints: [
      '학생 (kết thúc phụ âm ㅇ) + 이에요 → 학생이에요',
      '저 (kết thúc nguyên âm) + 예요 → 저예요',
      'Dùng cho câu khẳng định lịch sự thông thường (văn phong 해요체)',
      'Phủ định: danh từ + 이/가 아니에요',
    ],
    examples: [
      { id: 'ko-gr-ieyo-s1', text: '저는 학생이에요.', translationVi: '(jeoneun haksaeng-ieyo.) Tôi là sinh viên.' },
      { id: 'ko-gr-ieyo-s2', text: '이것은 책이에요.', translationVi: '(igeoseun chaeg-ieyo.) Đây là quyển sách.' },
      { id: 'ko-gr-ieyo-s3', text: '저는 의사예요.', translationVi: '(jeoneun uisayeyo.) Tôi là bác sĩ.' },
    ],
    commonMistakesVi: "Người mới học thường nhầm lẫn giữa 이에요 và 예요, không để ý danh từ đứng trước kết thúc bằng phụ âm hay nguyên âm (batchim).",
    exercises: [
      {
        id: 'ko-gr-ieyo-ex1',
        type: 'multiple-choice',
        promptVi: "'학생' kết thúc bằng phụ âm. Chọn đuôi câu đúng.",
        question: '학생 + ___',
        options: ['이에요', '예요', '있어요', '왔어요'],
        correctOptionIndex: 0,
        explanationVi: "학생 kết thúc bằng phụ âm ㅇ nên dùng 이에요.",
      },
      {
        id: 'ko-gr-ieyo-ex2',
        type: 'multiple-choice',
        promptVi: "'저' kết thúc bằng nguyên âm. Chọn đuôi câu đúng.",
        question: '저 + ___',
        options: ['이에요', '예요', '이/가', '은/는'],
        correctOptionIndex: 1,
        explanationVi: '저 kết thúc bằng nguyên âm ㅓ nên dùng 예요.',
      },
      {
        id: 'ko-gr-ieyo-ex3',
        type: 'fill-blank',
        promptVi: "'사과' (quả táo) kết thúc bằng nguyên âm. Điền đuôi câu đúng.",
        sentenceTemplate: '이것은 사과___.',
        wordBank: ['예요', '이에요', '있어요'],
        correctAnswer: '예요',
        explanationVi: '사과 kết thúc bằng nguyên âm 아 nên dùng 예요.',
      },
    ],
  },
  {
    id: 'ko-gr-eun-neun',
    languageCode: 'ko',
    level: 'A1',
    title: '은/는',
    titleVi: 'Trợ từ chủ đề "은/는"',
    explanationVi:
      "은/는 là trợ từ chủ đề, dùng để giới thiệu hoặc nhấn mạnh chủ đề đang nói tới trong câu (tương tự 'còn về...' trong tiếng Việt). 은 dùng sau danh từ kết thúc phụ âm, 는 dùng sau danh từ kết thúc nguyên âm.",
    structure: 'Danh từ (kết thúc phụ âm) + 은 / Danh từ (kết thúc nguyên âm) + 는',
    keyPoints: [
      '이름 (kết thúc phụ âm) + 은 → 이름은',
      '저 (kết thúc nguyên âm) + 는 → 저는',
      "Dùng để giới thiệu chủ đề mới hoặc so sánh, khác sắc thái với 이/가",
    ],
    examples: [
      { id: 'ko-gr-eunneun-s1', text: '저는 베트남 사람이에요.', translationVi: '(jeoneun beteunam saram-ieyo.) Tôi (nói về tôi) là người Việt Nam.' },
      { id: 'ko-gr-eunneun-s2', text: '이름은 란이에요.', translationVi: '(ireumeun Ran-ieyo.) (Về) tên (thì) là Lan.' },
      { id: 'ko-gr-eunneun-s3', text: '오늘은 날씨가 좋아요.', translationVi: '(oneureun nalssiga joayo.) Hôm nay thời tiết đẹp.' },
    ],
    commonMistakesVi: '은/는 dễ bị nhầm với 이/가 vì cả hai đều đứng sau danh từ, nhưng 은/는 nhấn vào CHỦ ĐỀ còn 이/가 nhấn vào CHỦ NGỮ mới/thông tin mới.',
    exercises: [
      {
        id: 'ko-gr-eunneun-ex1',
        type: 'multiple-choice',
        promptVi: "'이름' kết thúc bằng phụ âm. Chọn trợ từ đúng.",
        question: '이름 + ___',
        options: ['은', '는', '이', '가'],
        correctOptionIndex: 0,
        explanationVi: '이름 kết thúc bằng phụ âm ㅁ nên dùng 은.',
      },
      {
        id: 'ko-gr-eunneun-ex2',
        type: 'multiple-choice',
        promptVi: "'저' kết thúc bằng nguyên âm. Chọn trợ từ đúng.",
        question: '저 + ___',
        options: ['은', '는', '이', '가'],
        correctOptionIndex: 1,
        explanationVi: '저 kết thúc bằng nguyên âm ㅓ nên dùng 는.',
      },
      {
        id: 'ko-gr-eunneun-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi là người Việt Nam."',
        words: ['사람이에요', '저는', '베트남'],
        correctOrder: ['저는', '베트남', '사람이에요'],
        explanationVi: 'Trật tự câu Hàn: Chủ đề(은/는) + Bổ ngữ + Động từ.',
      },
    ],
  },
  {
    id: 'ko-gr-i-ga',
    languageCode: 'ko',
    level: 'A1',
    title: '이/가',
    titleVi: 'Trợ từ chủ ngữ "이/가"',
    explanationVi:
      "이/가 là trợ từ chủ ngữ, đánh dấu danh từ đứng trước là chủ ngữ của câu, thường dùng khi giới thiệu thông tin MỚI hoặc nhấn mạnh 'chính là ai/cái gì'. 이 dùng sau phụ âm, 가 dùng sau nguyên âm.",
    structure: 'Danh từ (kết thúc phụ âm) + 이 / Danh từ (kết thúc nguyên âm) + 가',
    keyPoints: [
      '이름 (kết thúc phụ âm) + 이 → 이름이',
      '언니 (kết thúc nguyên âm) + 가 → 언니가',
      "Dùng với động từ '있어요/없어요' (có/không có) và khi nhấn mạnh chủ ngữ mới",
    ],
    examples: [
      { id: 'ko-gr-iga-s1', text: '이름이 뭐예요?', translationVi: '(ireumi mwoyeyo?) Tên (của bạn) là gì?' },
      { id: 'ko-gr-iga-s2', text: '형제자매가 있어요.', translationVi: '(hyeongjejamaega isseoyo.) (Tôi) có anh chị em.' },
      { id: 'ko-gr-iga-s3', text: '언니가 학생이에요.', translationVi: '(eonniga haksaeng-ieyo.) Chị gái (chính là người) là sinh viên.' },
    ],
    commonMistakesVi: 'Người mới học thường dùng 이/가 và 은/는 thay thế cho nhau tuỳ tiện dù hai trợ từ mang sắc thái nhấn mạnh khác nhau.',
    exercises: [
      {
        id: 'ko-gr-iga-ex1',
        type: 'multiple-choice',
        promptVi: "'이름' kết thúc bằng phụ âm. Chọn trợ từ đúng.",
        question: '이름 + ___ 뭐예요?',
        options: ['이', '가', '은', '는'],
        correctOptionIndex: 0,
        explanationVi: '이름 kết thúc bằng phụ âm nên dùng 이.',
      },
      {
        id: 'ko-gr-iga-ex2',
        type: 'fill-blank',
        promptVi: "'언니' kết thúc bằng nguyên âm. Điền trợ từ đúng.",
        sentenceTemplate: '언니___ 있어요.',
        wordBank: ['가', '이', '은'],
        correctAnswer: '가',
        explanationVi: '언니 kết thúc bằng nguyên âm ㅣ nên dùng 가.',
      },
      {
        id: 'ko-gr-iga-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng để nói "Tôi có anh chị em."',
        question: '올바른 문장을 고르세요.',
        options: ['형제자매가 있어요.', '형제자매는 있어요.', '형제자매 있어요가.', '있어요 형제자매가.'],
        correctOptionIndex: 0,
        explanationVi: "Với động từ '있어요', chủ ngữ thường đi kèm trợ từ 이/가.",
      },
    ],
  },
];
