import type { ConversationScenario } from '../../types';

export const japaneseB2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'ja-b2-conv-gakkari-shita-hanashi',
    languageCode: 'ja',
    level: 'B2',
    title: 'がっかりした話',
    titleVi: 'Câu chuyện đáng thất vọng',
    descriptionVi: 'Luyện hội thoại kể về một tình huống thất vọng bằng ～のに và ～てしまう.',
    contextVi: 'Minh hỏi An về chuyến du lịch cuối tuần của cô ấy.',
    dialogue: [
      { id: 'ja-b2-gakkari-turn-01', speaker: 'A', text: '週末の旅行はどうでしたか。', translationVi: '(Shuumatsu no ryokou wa dou deshita ka?) Chuyến đi cuối tuần thế nào?' },
      { id: 'ja-b2-gakkari-turn-02', speaker: 'B', text: 'それが、せっかく準備したのに、台風で中止になってしまいました。', translationVi: '(Sore ga, sekkaku junbi shita noni, taifuu de chuushi ni natte shimaimashita.) À, dù đã cất công chuẩn bị nhưng vì bão nên đã bị hủy mất rồi.' },
      { id: 'ja-b2-gakkari-turn-03', speaker: 'A', text: 'それは残念でしたね。', translationVi: '(Sore wa zannen deshita ne.) Tiếc quá nhỉ.' },
      { id: 'ja-b2-gakkari-turn-04', speaker: 'B', text: 'はい、飛行機のチケットも払ってしまったので、お金も無駄になりました。', translationVi: '(Hai, hikouki no chiketto mo haratte shimatta node, okane mo muda ni narimashita.) Vâng, vé máy bay cũng đã trả tiền rồi nên tiền cũng bị lãng phí.' },
      { id: 'ja-b2-gakkari-turn-05', speaker: 'A', text: '天気予報は見なかったんですか。', translationVi: '(Tenki yohou wa minakattan desu ka?) Bạn không xem dự báo thời tiết à?' },
      { id: 'ja-b2-gakkari-turn-06', speaker: 'B', text: '見たんですが、台風が来るとは思わなかったんです。', translationVi: '(Mitan desu ga, taifuu ga kuru to wa omowanakattan desu.) Có xem, nhưng tôi không nghĩ là bão sẽ đến.' },
      { id: 'ja-b2-gakkari-turn-07', speaker: 'A', text: '次はもっと早く確認したほうがいいですね。', translationVi: '(Tsugi wa motto hayaku kakunin shita hou ga ii desu ne.) Lần sau nên kiểm tra sớm hơn nhỉ.' },
      { id: 'ja-b2-gakkari-turn-08', speaker: 'B', text: 'そうですね。今度は気をつけます。', translationVi: '(Sou desu ne. Kondo wa ki o tsukemasu.) Đúng vậy. Lần sau tôi sẽ chú ý.' },
    ],
    relatedVocabularyIds: ['ja-b2-l1-1-v1', 'ja-b2-l1-1-v7', 'ja-b2-l3-1-v1', 'ja-b2-l1-1-v5'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '週末の旅行はどうでしたか。'. Bạn muốn kể lại một tình huống đáng thất vọng, chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: 'それが、せっかく準備したのに、台風で中止になってしまいました。' },
        { id: 'o2', text: '健康のために、毎日運動しています。' },
        { id: 'o3', text: '彼はもう出発したはずです。' },
        { id: 'o4', text: '彼は英語だけでなく中国語も話せます。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu trả lời cần thể hiện sự tương phản bất ngờ/thất vọng ('のに') và kết quả hoàn tất ngoài ý muốn ('てしまう').",
    },
  },
  {
    id: 'ja-b2-conv-shikaku-shiken',
    languageCode: 'ja',
    level: 'B2',
    title: '資格試験に向けて',
    titleVi: 'Chuẩn bị cho kỳ thi chứng chỉ',
    descriptionVi: 'Luyện hội thoại nói về mục đích và suy đoán bằng ～ために, ～ように, ～はずだ.',
    contextVi: 'Minh hỏi An về việc chuẩn bị thi JLPT.',
    dialogue: [
      { id: 'ja-b2-shikaku-turn-01', speaker: 'A', text: 'JLPTの試験、順調に準備できていますか。', translationVi: '(JLPT no shiken, junchou ni junbi dekite imasu ka?) Bạn chuẩn bị thi JLPT thuận lợi chứ?' },
      { id: 'ja-b2-shikaku-turn-02', speaker: 'B', text: 'はい、合格するために、毎日勉強しています。', translationVi: '(Hai, goukaku suru tame ni, mainichi benkyou shite imasu.) Vâng, để đậu kỳ thi, tôi học mỗi ngày.' },
      { id: 'ja-b2-shikaku-turn-03', speaker: 'A', text: '漢字も覚えられるように、練習していますか。', translationVi: '(Kanji mo oboerareru you ni, renshuu shite imasu ka?) Bạn cũng luyện tập để nhớ được chữ Hán chứ?' },
      { id: 'ja-b2-shikaku-turn-04', speaker: 'B', text: 'はい、忘れないように、ノートに書いています。', translationVi: '(Hai, wasurenai you ni, nooto ni kaite imasu.) Vâng, để không quên, tôi ghi vào vở.' },
      { id: 'ja-b2-shikaku-turn-05', speaker: 'A', text: '前回のテストの結果はどうでしたか。', translationVi: '(Zenkai no tesuto no kekka wa dou deshita ka?) Kết quả bài kiểm tra lần trước thế nào?' },
      { id: 'ja-b2-shikaku-turn-06', speaker: 'B', text: 'まだ結果が出ていませんが、たぶん合格しているはずです。', translationVi: '(Mada kekka ga dete imasen ga, tabun goukaku shite iru hazu desu.) Vẫn chưa có kết quả nhưng chắc là tôi đã đậu rồi.' },
      { id: 'ja-b2-shikaku-turn-07', speaker: 'A', text: 'それは良かったですね。頑張った甲斐がありますね。', translationVi: '(Sore wa yokatta desu ne. Ganbatta kai ga arimasu ne.) Vậy tốt quá. Xứng đáng với công sức bạn bỏ ra nhỉ.' },
      { id: 'ja-b2-shikaku-turn-08', speaker: 'B', text: 'ありがとうございます。結果が出るまで、緊張しています。', translationVi: '(Arigatou gozaimasu. Kekka ga deru made, kinchou shite imasu.) Cảm ơn bạn. Cho đến khi có kết quả, tôi vẫn thấy hồi hộp.' },
    ],
    relatedVocabularyIds: ['ja-b2-l2-3-v1', 'ja-b2-l2-2-v1', 'ja-b2-l2-1-v1', 'ja-b2-l2-3-v9'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa hỏi '前回のテストの結果はどうでしたか。'. Chọn câu trả lời phù hợp thể hiện suy đoán chắc chắn dựa trên căn cứ.",
      options: [
        { id: 'o1', text: 'まだ結果が出ていませんが、たぶん合格しているはずです。' },
        { id: 'o2', text: 'それが、台風で中止になってしまいました。' },
        { id: 'o3', text: '嫌いなわけではないですが、あまり食べません。' },
        { id: 'o4', text: '彼は歌だけでなく、ダンスも上手です。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về kết quả một bài kiểm tra, nên trả lời bằng suy đoán dựa trên căn cứ đã có (quá trình học tập) dùng '～はずだ'.",
    },
  },
  {
    id: 'ja-b2-conv-shigoto-soudan',
    languageCode: 'ja',
    level: 'B2',
    title: '仕事の相談',
    titleVi: 'Tâm sự về công việc',
    descriptionVi: 'Luyện hội thoại tâm sự về công việc bằng ～わけではない, ～だけでなく, ～ざるを得ない.',
    contextVi: 'An hỏi thăm Minh về công việc gần đây của anh ấy.',
    dialogue: [
      { id: 'ja-b2-shigoto-turn-01', speaker: 'A', text: '最近仕事はどうですか。', translationVi: '(Saikin shigoto wa dou desu ka?) Dạo này công việc thế nào?' },
      { id: 'ja-b2-shigoto-turn-02', speaker: 'B', text: '忙しいですが、この仕事が嫌いなわけではないです。', translationVi: '(Isogashii desu ga, kono shigoto ga kirai na wake de wa nai desu.) Bận nhưng không phải là tôi ghét công việc này.' },
      { id: 'ja-b2-shigoto-turn-03', speaker: 'A', text: 'それなら良かったです。何か悩みがあるんですか。', translationVi: '(Sorenara yokatta desu. Nanika nayami ga arun desu ka?) Vậy thì tốt rồi. Có điều gì bạn đang lo lắng à?' },
      { id: 'ja-b2-shigoto-turn-04', speaker: 'B', text: '上司の指示に従わざるを得ないことが多くて、少しストレスです。', translationVi: '(Joushi no shiji ni shitagawazaru wo enai koto ga ookute, sukoshi sutoresu desu.) Có nhiều lúc bất đắc dĩ phải nghe theo chỉ thị của sếp, hơi căng thẳng.' },
      { id: 'ja-b2-shigoto-turn-05', speaker: 'A', text: '給料だけでなく、やりがいも大切ですよね。', translationVi: '(Kyuuryou dake de naku, yarigai mo taisetsu desu yo ne.) Không chỉ lương mà cảm giác có ý nghĩa trong công việc cũng quan trọng nhỉ.' },
      { id: 'ja-b2-shigoto-turn-06', speaker: 'B', text: 'そうですね。転職を考えたこともありますが、まだ決めていません。', translationVi: '(Sou desu ne. Tenshoku o kangaeta koto mo arimasu ga, mada kimete imasen.) Đúng vậy. Tôi cũng từng nghĩ đến chuyện chuyển việc, nhưng vẫn chưa quyết định.' },
      { id: 'ja-b2-shigoto-turn-07', speaker: 'A', text: 'ゆっくり考えたほうがいいと思います。', translationVi: '(Yukkuri kangaeta hou ga ii to omoimasu.) Tôi nghĩ bạn nên suy nghĩ từ từ.' },
      { id: 'ja-b2-shigoto-turn-08', speaker: 'B', text: 'ありがとうございます。もう少し考えてみます。', translationVi: '(Arigatou gozaimasu. Mou sukoshi kangaete mimasu.) Cảm ơn bạn. Tôi sẽ suy nghĩ thêm một chút.' },
    ],
    relatedVocabularyIds: ['ja-b2-l1-3-v1', 'ja-b2-l3-2-v1', 'ja-b2-l1-2-v1', 'ja-b2-l3-2-v6'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn muốn làm rõ rằng mình không hoàn toàn ghét công việc, tránh gây hiểu lầm. Chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: 'この仕事が嫌いなわけではないです。' },
        { id: 'o2', text: 'この仕事、本当に大嫌いです。' },
        { id: 'o3', text: 'もう仕事したくないです。' },
        { id: 'o4', text: '仕事なんてどうでもいいです。' },
      ],
      correctOptionId: 'o1',
      explanationVi: "'～わけではない' cho phép làm rõ rằng không phải là ghét hoàn toàn, tránh gây hiểu lầm tiêu cực khi thực ra chỉ đang mệt mỏi tạm thời.",
    },
  },
];
