import type { GrammarTopic } from '../../types';

export const japaneseB2GrammarTopics: GrammarTopic[] = [
  {
    id: 'ja-b2-gr-noni',
    languageCode: 'ja',
    level: 'B2',
    title: '～のに',
    titleVi: 'Tương phản bất ngờ ～のに',
    explanationVi:
      "～のに nối hai vế mang tính tương phản mạnh, thường kèm sắc thái bất ngờ/thất vọng/phàn nàn — khác けど/が chỉ đơn thuần tương phản trung tính, không mang cảm xúc.",
    structure: '普通形 + のに（な形容詞/名詞 + な + のに）',
    keyPoints: ['頑張ったのに、うまくいきませんでした。 (Đã cố gắng vậy mà không thành công.)', '高いのに、あまり美味しくないです。 (Đắt vậy mà không ngon lắm.)', 'Mang sắc thái cảm xúc (thất vọng/ngạc nhiên) mà けど không có'],
    examples: [
      { id: 'ja-b2-gr-noni-s1', text: '頑張ったのに、うまくいきませんでした。', translationVi: 'Đã cố gắng vậy mà không thành công.' },
      { id: 'ja-b2-gr-noni-s2', text: '高いのに、あまり美味しくないです。', translationVi: 'Đắt vậy mà không ngon lắm.' },
      { id: 'ja-b2-gr-noni-s3', text: '呼んだのに、誰も返事をしませんでした。', translationVi: 'Đã gọi vậy mà không ai trả lời.' },
    ],
    commonMistakesVi: "Người học hay dùng ～のに cho câu đề nghị/mệnh lệnh ở vế sau, điều này không đúng ngữ pháp — ～のに chỉ dùng để miêu tả, không dùng để đề nghị.",
    exercises: [
      {
        id: 'ja-b2-gr-noni-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '頑張った___、うまくいきませんでした。',
        options: ['のに', 'ので', 'なら', 'し'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-gr-noni-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '高い___、あまり美味しくないです。',
        wordBank: ['のに', 'なら', 'ければ'],
        correctAnswer: 'のに',
      },
      {
        id: 'ja-b2-gr-noni-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Đã gọi vậy mà không ai trả lời."',
        words: ['誰も返事をしませんでした', '呼んだのに'],
        correctOrder: ['呼んだのに', '誰も返事をしませんでした'],
      },
    ],
  },
  {
    id: 'ja-b2-gr-dake-de-naku-mo',
    languageCode: 'ja',
    level: 'B2',
    title: '～だけでなく～も',
    titleVi: 'Liệt kê bổ sung ～だけでなく～も',
    explanationVi:
      "～だけでなく～も nghĩa là 'không chỉ...mà...cũng...', dùng để liệt kê hai đặc điểm liên quan, ý sau thường bổ sung/nâng cao ý trước.",
    structure: '普通形 + だけでなく、～も（な形容詞/名詞 + な/である + だけでなく）',
    keyPoints: ['彼は歌だけでなく、ダンスも上手です。', '値段だけでなく、デザインも気に入りました。', 'Có thể thay ～も bằng ～まで để nhấn mạnh mức độ cao hơn'],
    examples: [
      { id: 'ja-b2-gr-dakedenaku-s1', text: '彼は歌だけでなく、ダンスも上手です。', translationVi: 'Anh ấy không chỉ hát hay mà còn nhảy giỏi.' },
      { id: 'ja-b2-gr-dakedenaku-s2', text: '値段だけでなく、デザインも気に入りました。', translationVi: 'Không chỉ giá cả mà thiết kế cũng khiến tôi ưng ý.' },
      { id: 'ja-b2-gr-dakedenaku-s3', text: 'この薬は効果があるだけでなく、副作用も少ないです。', translationVi: 'Loại thuốc này không chỉ có hiệu quả mà tác dụng phụ cũng ít.' },
    ],
    commonMistakesVi: "Người học hay quên thêm な trước だけでなく khi từ đứng trước là な形容詞, ví dụ nói sai '便利だけでなく' thay vì '便利なだけでなく'.",
    exercises: [
      {
        id: 'ja-b2-gr-dakedenaku-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '彼は歌___、ダンスも上手です。',
        options: ['だけでなく', 'のに', 'はずで', 'ように'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-gr-dakedenaku-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: 'この薬は効果がある___、副作用も少ないです。',
        wordBank: ['だけでなく', 'のに', 'ために'],
        correctAnswer: 'だけでなく',
      },
      {
        id: 'ja-b2-gr-dakedenaku-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Không chỉ giá cả mà thiết kế cũng khiến tôi ưng ý."',
        words: ['デザインも気に入りました', '値段だけでなく'],
        correctOrder: ['値段だけでなく', 'デザインも気に入りました'],
      },
    ],
  },
  {
    id: 'ja-b2-gr-hazu-da',
    languageCode: 'ja',
    level: 'B2',
    title: '～はずだ',
    titleVi: 'Suy đoán chắc chắn ～はずだ',
    explanationVi:
      "～はずだ diễn tả suy đoán dựa trên lý lẽ/thông tin đã biết, mức độ chắc chắn cao — khác ～ようです/みたいです (dựa trên quan sát trực tiếp bằng giác quan).",
    structure: '普通形 + はずだ（な形容詞/名詞 + な/の + はずだ）',
    keyPoints: ['彼は忙しいはずです。 (dựa trên thông tin đã biết về lịch trình của anh ấy)', '成田空港に着くはずです。', '～はずがない: phủ định mạnh, "không thể nào là"'],
    examples: [
      { id: 'ja-b2-gr-hazuda-s1', text: '会議はもう始まっているはずです。', translationVi: 'Chắc hẳn cuộc họp đã bắt đầu rồi.' },
      { id: 'ja-b2-gr-hazuda-s2', text: '彼はまだ学生のはずです。', translationVi: 'Chắc hẳn anh ấy vẫn còn là sinh viên.' },
      { id: 'ja-b2-gr-hazuda-s3', text: 'そんなに簡単なはずがありません。', translationVi: 'Không thể nào lại đơn giản như vậy được.' },
    ],
    commonMistakesVi: "Người học hay nhầm ～はずだ (suy đoán từ logic/thông tin đã biết) với ～と思います (ý kiến chủ quan) — ～はずだ mang tính khách quan hơn, dựa trên căn cứ cụ thể.",
    exercises: [
      {
        id: 'ja-b2-gr-hazuda-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '会議はもう始まっている___。',
        options: ['はずです', 'のにです', 'ようだです', 'ためです'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-gr-hazuda-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng cho danh từ.',
        sentenceTemplate: '彼はまだ学生___はずです。',
        wordBank: ['の', 'な', 'だ'],
        correctAnswer: 'の',
      },
      {
        id: 'ja-b2-gr-hazuda-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Không thể nào lại đơn giản như vậy được."',
        words: ['はずがありません', 'そんなに簡単な'],
        correctOrder: ['そんなに簡単な', 'はずがありません'],
      },
    ],
  },
  {
    id: 'ja-b2-gr-youni-tameni',
    languageCode: 'ja',
    level: 'B2',
    title: '～ように・～ために',
    titleVi: 'Mục đích ～ように và ～ために',
    explanationVi:
      "Cả hai đều diễn tả mục đích, nhưng khác nhau về loại động từ: ～ように đi với động từ KHÔNG chủ ý/khả năng (わかる, できる, 聞こえる...); ～ために đi với động từ CÓ chủ ý, hoặc mang nghĩa 'vì lợi ích của'.",
    structure: '動詞(khả năng/không chủ ý) + ように / 動詞(có chủ ý)・名詞の + ために',
    keyPoints: ['見えるように、大きく書いてください。 (không chủ ý → ように)', '合格するために、毎日勉強します。 (có chủ ý → ために)', "Không thể dùng ために với động từ không chủ ý như 'わかる', 'できる'"],
    examples: [
      { id: 'ja-b2-gr-youtame-s1', text: '見えるように、大きく書いてください。', translationVi: 'Để nhìn thấy được, hãy viết to lên.' },
      { id: 'ja-b2-gr-youtame-s2', text: '合格するために、毎日勉強します。', translationVi: 'Để đậu kỳ thi, tôi học mỗi ngày.' },
      { id: 'ja-b2-gr-youtame-s3', text: '子供のために、早く帰ります。', translationVi: 'Vì con, tôi về nhà sớm.' },
    ],
    commonMistakesVi: "Người học hay dùng ために với động từ không chủ ý, ví dụ nói sai '聞こえるために' thay vì '聞こえるように'.",
    exercises: [
      {
        id: 'ja-b2-gr-youtame-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng (động từ không chủ ý).',
        question: '見える___、大きく書いてください。',
        options: ['ように', 'ために', 'のに', 'はずに'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-gr-youtame-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng (động từ có chủ ý).',
        sentenceTemplate: '合格する___、毎日勉強します。',
        wordBank: ['ために', 'ように', 'のに'],
        correctAnswer: 'ために',
      },
      {
        id: 'ja-b2-gr-youtame-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì con, tôi về nhà sớm."',
        words: ['早く帰ります', '子供のために'],
        correctOrder: ['子供のために', '早く帰ります'],
      },
    ],
  },
  {
    id: 'ja-b2-gr-te-shimau',
    languageCode: 'ja',
    level: 'B2',
    title: '～てしまう',
    titleVi: 'Hoàn tất/tiếc nuối ～てしまう',
    explanationVi:
      "～てしまう diễn tả hành động hoàn tất dứt điểm (không thể vãn hồi) hoặc mang sắc thái tiếc nuối/lỡ làm — ngữ cảnh quyết định nghĩa nào được hiểu.",
    structure: '動詞(て形) + しまう',
    keyPoints: ['全部読んでしまいました。 (đã đọc xong hết — hoàn tất dứt điểm)', '大切な物を壊してしまいました。 (đã lỡ làm hỏng đồ quan trọng — tiếc nuối)', 'Dạng nói tắt thân mật: ～ちゃう/～じゃう'],
    examples: [
      { id: 'ja-b2-gr-teshimau-s1', text: '全部読んでしまいました。', translationVi: 'Tôi đã đọc xong hết rồi.' },
      { id: 'ja-b2-gr-teshimau-s2', text: '大切な物を壊してしまいました。', translationVi: 'Tôi đã lỡ làm hỏng đồ quan trọng.' },
      { id: 'ja-b2-gr-teshimau-s3', text: '約束の時間に遅れてしまいました。', translationVi: 'Tôi đã lỡ đến trễ giờ hẹn.' },
    ],
    commonMistakesVi: "Người học hay dùng ～てしまう cho hành động chưa hoàn thành hoặc đang diễn ra, trong khi ～てしまう chỉ dùng cho hành động ĐÃ hoàn tất.",
    exercises: [
      {
        id: 'ja-b2-gr-teshimau-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng.',
        question: '全部読んで___。',
        options: ['しまいました', 'います', 'あります', 'おきます'],
        correctOptionIndex: 0,
      },
      {
        id: 'ja-b2-gr-teshimau-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '約束の時間に遅れて___。',
        wordBank: ['しまいました', 'あります', 'おきました'],
        correctAnswer: 'しまいました',
      },
      {
        id: 'ja-b2-gr-teshimau-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đã lỡ làm hỏng đồ quan trọng."',
        words: ['壊してしまいました', '大切な物を'],
        correctOrder: ['大切な物を', '壊してしまいました'],
      },
    ],
  },
];
