import type { Lesson } from '../../types';

export const japaneseFamilyLessons: Lesson[] = [
  {
    id: 'ja-l3-1-family-members',
    unitId: 'ja-u3-family',
    title: '家族の呼び方',
    titleVi: 'Các thành viên trong gia đình',
    objectiveVi: 'Gọi tên được các thành viên cơ bản trong gia đình bằng tiếng Nhật.',
    estimatedMinutes: 6,
    grammarNoteVi:
      "Tiếng Nhật dùng từ KHÁC NHAU khi nói về gia đình MÌNH với người ngoài (khiêm nhường ngữ: 父, 母, 兄, 姉) so với khi nói về gia đình NGƯỜI KHÁC (tôn kính ngữ: お父さん, お母さん, お兄さん, お姉さん).",
    vocabulary: [
      {
        id: 'ja-l3-1-v1',
        term: '家族',
        translationVi: 'Gia đình',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l3-1-s1',
        usageNoteVi: 'Cách đọc (romaji): kazoku',
      },
      {
        id: 'ja-l3-1-v2',
        term: '父',
        translationVi: 'Bố (khi nói với người ngoài)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l3-1-s2',
        usageNoteVi: 'Cách đọc (romaji): chichi. Khi nói về bố người khác, dùng お父さん (otousan).',
      },
      {
        id: 'ja-l3-1-v3',
        term: '母',
        translationVi: 'Mẹ (khi nói với người ngoài)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l3-1-s2',
        usageNoteVi: 'Cách đọc (romaji): haha. Khi nói về mẹ người khác, dùng お母さん (okaasan).',
      },
      {
        id: 'ja-l3-1-v4',
        term: '兄',
        translationVi: 'Anh trai (khi nói với người ngoài)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l3-1-s3',
        usageNoteVi: 'Cách đọc (romaji): ani',
      },
      {
        id: 'ja-l3-1-v5',
        term: '姉',
        translationVi: 'Chị gái (khi nói với người ngoài)',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l3-1-s3',
        usageNoteVi: 'Cách đọc (romaji): ane',
      },
      {
        id: 'ja-l3-1-v6',
        term: '両親',
        translationVi: 'Bố mẹ',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc (romaji): ryoushin',
      },
    ],
    sentences: [
      { id: 'ja-l3-1-s1', text: 'これは私の家族です。', translationVi: '(Kore wa watashi no kazoku desu.) Đây là gia đình của tôi.' },
      {
        id: 'ja-l3-1-s2',
        text: 'こちらは私の父と母です。',
        translationVi: '(Kochira wa watashi no chichi to haha desu.) Đây là bố và mẹ của tôi.',
      },
      {
        id: 'ja-l3-1-s3',
        text: '私は兄が一人、姉が一人います。',
        translationVi: '(Watashi wa ani ga hitori, ane ga hitori imasu.) Tôi có một anh trai và một chị gái.',
      },
    ],
    exercises: [
      {
        id: 'ja-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '母'.",
        question: '母',
        options: ['Bố', 'Mẹ', 'Chị gái', 'Bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: 'こちらは私の___です。',
        wordBank: ['父', '学生', '名前'],
        correctAnswer: '父',
      },
      {
        id: 'ja-l3-1-ex3',
        type: 'multiple-choice',
        promptVi: "Bạn muốn hỏi về bố của NGƯỜI KHÁC (không phải bố mình). Từ nào đúng?",
        question: '他人のお父さんについて話すときの言葉は？',
        options: ['父', 'お父さん', '母', '兄'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ja-l3-2-talking-about-family',
    unitId: 'ja-u3-family',
    title: '家族について話す',
    titleVi: 'Nói về gia đình bạn',
    objectiveVi: "Sử dụng 'います' để mô tả số lượng thành viên trong gia đình.",
    estimatedMinutes: 6,
    grammarNoteVi:
      "います dùng cho NGƯỜI và ĐỘNG VẬT (vật sống, có thể di chuyển), còn あります dùng cho VẬT VÔ TRI. Khi nói về số lượng người trong gia đình, luôn dùng います.",
    vocabulary: [
      {
        id: 'ja-l3-2-v1',
        term: 'います',
        translationVi: 'Có (dùng cho người/động vật)',
        partOfSpeech: 'verb',
        exampleSentenceId: 'ja-l3-2-s1',
        usageNoteVi: 'Cách đọc (romaji): imasu. Khác あります dùng cho vật vô tri.',
      },
      {
        id: 'ja-l3-2-v2',
        term: '兄弟姉妹',
        translationVi: 'Anh chị em ruột',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l3-2-s1',
        usageNoteVi: 'Cách đọc (romaji): kyoudai shimai',
      },
      {
        id: 'ja-l3-2-v3',
        term: '大家族',
        translationVi: 'Đại gia đình / gia đình đông người',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (romaji): daikazoku',
      },
      {
        id: 'ja-l3-2-v4',
        term: '小家族',
        translationVi: 'Gia đình nhỏ',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l3-2-s3',
        usageNoteVi: 'Cách đọc (romaji): shoukazoku',
      },
      {
        id: 'ja-l3-2-v5',
        term: '一緒に住んでいます',
        translationVi: 'Sống cùng',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l3-2-s2',
        usageNoteVi: 'Cách đọc (romaji): issho ni sunde imasu',
      },
    ],
    sentences: [
      {
        id: 'ja-l3-2-s1',
        text: '私は兄弟姉妹が二人います。',
        translationVi: '(Watashi wa kyoudai shimai ga futari imasu.) Tôi có hai anh chị em.',
      },
      {
        id: 'ja-l3-2-s2',
        text: '私は両親と一緒に住んでいます。',
        translationVi: '(Watashi wa ryoushin to issho ni sunde imasu.) Tôi sống cùng bố mẹ.',
      },
      { id: 'ja-l3-2-s3', text: '私たちは小家族です。', translationVi: '(Watashitachi wa shoukazoku desu.) Chúng tôi là một gia đình nhỏ.' },
    ],
    exercises: [
      {
        id: 'ja-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '兄弟姉妹'.",
        question: '兄弟姉妹',
        options: ['Bố mẹ', 'Anh chị em ruột', 'Bạn bè', 'Hàng xóm'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '私は兄弟姉妹が二人___。',
        wordBank: ['います', 'あります', 'です'],
        correctAnswer: 'います',
      },
      {
        id: 'ja-l3-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng ngữ pháp để nói "Tôi sống cùng bố mẹ".',
        question: '正しい文を選んでください。',
        options: [
          '私は両親と一緒に住んでいます。',
          '私は両親一緒に住んでいますと。',
          '両親と私は住んでいます一緒に。',
          '一緒に私は両親住んでいます。',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
];
