import type { Lesson } from '../../types';

export const japaneseGreetingsLessons: Lesson[] = [
  {
    id: 'ja-l1-1-basic-greetings',
    unitId: 'ja-u1-greetings',
    title: '基本のあいさつ',
    titleVi: 'Lời chào cơ bản',
    objectiveVi: 'Sử dụng được các lời chào và tạm biệt cơ bản trong giao tiếp hằng ngày bằng tiếng Nhật.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "Tiếng Nhật có lời chào riêng cho từng buổi trong ngày: おはようございます (sáng), こんにちは (trưa/chiều), こんばんは (tối) — khác với chỉ 1 từ 'hello' dùng chung như tiếng Anh.",
    vocabulary: [
      {
        id: 'ja-l1-1-v1',
        term: 'こんにちは',
        translationVi: 'Xin chào (ban ngày)',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'ja-l1-1-s1',
        usageNoteVi: 'Cách đọc (romaji): konnichiwa',
      },
      {
        id: 'ja-l1-1-v2',
        term: 'おはようございます',
        translationVi: 'Chào buổi sáng',
        partOfSpeech: 'greeting',
        exampleSentenceId: 'ja-l1-1-s2',
        usageNoteVi: 'Cách đọc (romaji): ohayou gozaimasu',
      },
      {
        id: 'ja-l1-1-v3',
        term: 'こんばんは',
        translationVi: 'Chào buổi tối',
        partOfSpeech: 'greeting',
        usageNoteVi: 'Cách đọc (romaji): konbanwa',
      },
      {
        id: 'ja-l1-1-v4',
        term: 'さようなら',
        translationVi: 'Tạm biệt',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-1-s3',
        usageNoteVi: 'Cách đọc (romaji): sayounara. Khá trang trọng, thường dùng khi lâu không gặp lại.',
      },
      {
        id: 'ja-l1-1-v5',
        term: 'じゃあね',
        translationVi: 'Hẹn gặp lại (thân mật)',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (romaji): jaa ne',
      },
      {
        id: 'ja-l1-1-v6',
        term: 'また会いましょう',
        translationVi: 'Hẹn gặp lại (lịch sự)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-1-s3',
        usageNoteVi: 'Cách đọc (romaji): mata aimashou',
      },
    ],
    sentences: [
      { id: 'ja-l1-1-s1', text: 'こんにちは、お元気ですか？', translationVi: '(Konnichiwa, ogenki desu ka?) Xin chào, bạn khỏe không?' },
      {
        id: 'ja-l1-1-s2',
        text: 'おはようございます！良い一日を。',
        translationVi: '(Ohayou gozaimasu! Yoi ichinichi o.) Chào buổi sáng! Chúc bạn một ngày tốt lành.',
      },
      {
        id: 'ja-l1-1-s3',
        text: 'さようなら、また会いましょう！',
        translationVi: '(Sayounara, mata aimashou!) Tạm biệt, hẹn gặp lại!',
      },
    ],
    exercises: [
      {
        id: 'ja-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'さようなら'.",
        question: 'さようなら',
        options: ['Xin chào', 'Tạm biệt', 'Cảm ơn', 'Xin lỗi'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu chào hỏi.',
        sentenceTemplate: '___、お元気ですか？',
        wordBank: ['こんにちは', 'さようなら', 'ありがとう'],
        correctAnswer: 'こんにちは',
      },
      {
        id: 'ja-l1-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Bây giờ là 8 giờ sáng. Bạn nói gì khi gặp ai đó?',
        question: '今は朝8時です。何と言いますか？',
        options: ['こんばんは', 'おはようございます', 'さようなら', 'じゃあね'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ja-l1-2-how-are-you',
    unitId: 'ja-u1-greetings',
    title: 'お元気ですか？',
    titleVi: 'Hỏi thăm sức khỏe',
    objectiveVi: 'Hỏi và trả lời đơn giản về tình trạng sức khỏe, cảm xúc bằng tiếng Nhật.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "です là đuôi lịch sự đặt ở CUỐI câu (khác tiếng Việt/Anh đặt động từ ở giữa câu), ví dụ '元気です' nghĩa đen là '(tôi) khỏe là'.",
    vocabulary: [
      {
        id: 'ja-l1-2-v1',
        term: 'お元気ですか',
        translationVi: 'Bạn khỏe không',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-2-s1',
        usageNoteVi: 'Cách đọc (romaji): ogenki desu ka',
      },
      {
        id: 'ja-l1-2-v2',
        term: '元気です',
        translationVi: 'Tôi khỏe',
        partOfSpeech: 'adjective',
        exampleSentenceId: 'ja-l1-2-s2',
        usageNoteVi: 'Cách đọc (romaji): genki desu',
      },
      {
        id: 'ja-l1-2-v3',
        term: 'とても元気です',
        translationVi: 'Tôi rất khỏe',
        partOfSpeech: 'adjective',
        usageNoteVi: 'Cách đọc (romaji): totemo genki desu',
      },
      {
        id: 'ja-l1-2-v4',
        term: 'まあまあです',
        translationVi: 'Cũng bình thường',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (romaji): maamaa desu',
      },
      {
        id: 'ja-l1-2-v5',
        term: '疲れています',
        translationVi: 'Tôi mệt',
        partOfSpeech: 'adjective',
        exampleSentenceId: 'ja-l1-2-s3',
        usageNoteVi: 'Cách đọc (romaji): tsukarete imasu',
      },
      {
        id: 'ja-l1-2-v6',
        term: 'あなたは',
        translationVi: 'Còn bạn thì sao',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-2-s2',
        usageNoteVi: 'Cách đọc (romaji): anata wa',
      },
    ],
    sentences: [
      { id: 'ja-l1-2-s1', text: '今日はお元気ですか？', translationVi: '(Kyou wa ogenki desu ka?) Hôm nay bạn khỏe không?' },
      {
        id: 'ja-l1-2-s2',
        text: '元気です、ありがとう。あなたは？',
        translationVi: '(Genki desu, arigatou. Anata wa?) Tôi khỏe, cảm ơn. Còn bạn?',
      },
      { id: 'ja-l1-2-s3', text: '今日は少し疲れています。', translationVi: '(Kyou wa sukoshi tsukarete imasu.) Hôm nay tôi hơi mệt.' },
    ],
    exercises: [
      {
        id: 'ja-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: "Đâu là câu trả lời phù hợp cho câu hỏi 'お元気ですか？'",
        question: 'お元気ですか？',
        options: ['ベトナムから来ました', '元気です、ありがとう', '私の名前はランです', 'じゃあね'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '元気です、ありがとう。___？',
        wordBank: ['あなたは', 'どこから', '何歳'],
        correctAnswer: 'あなたは',
      },
      {
        id: 'ja-l1-2-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '疲れています'.",
        question: '疲れています',
        options: ['Vui', 'Mệt', 'Khỏe', 'Buồn'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ja-l1-3-politeness',
    unitId: 'ja-u1-greetings',
    title: '基本のマナー',
    titleVi: 'Phép lịch sự cơ bản',
    objectiveVi: 'Sử dụng các từ lịch sự cơ bản: cảm ơn, xin lỗi bằng tiếng Nhật.',
    estimatedMinutes: 5,
    grammarNoteVi:
      "すみません dùng đa dụng để gọi ai đó, xin phép hoặc xin lỗi nhẹ; ごめんなさい thân mật hơn, dùng khi thật sự đã làm điều gì sai.",
    vocabulary: [
      {
        id: 'ja-l1-3-v1',
        term: 'お願いします',
        translationVi: 'Làm ơn / xin nhờ',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (romaji): onegaishimasu',
      },
      {
        id: 'ja-l1-3-v2',
        term: 'ありがとうございます',
        translationVi: 'Cảm ơn (trang trọng)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-3-s2',
        usageNoteVi: 'Cách đọc (romaji): arigatou gozaimasu',
      },
      {
        id: 'ja-l1-3-v3',
        term: 'どういたしまして',
        translationVi: 'Không có gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-3-s2',
        usageNoteVi: 'Cách đọc (romaji): dou itashimashite',
      },
      {
        id: 'ja-l1-3-v4',
        term: 'すみません',
        translationVi: 'Xin lỗi / xin phép',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-3-s1',
        usageNoteVi: 'Cách đọc (romaji): sumimasen. Dùng đa dụng: gọi ai đó, xin phép, hoặc xin lỗi nhẹ.',
      },
      {
        id: 'ja-l1-3-v5',
        term: 'ごめんなさい',
        translationVi: 'Xin lỗi (khi mắc lỗi)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l1-3-s3',
        usageNoteVi: 'Cách đọc (romaji): gomennasai. Thân mật hơn すみません.',
      },
      {
        id: 'ja-l1-3-v6',
        term: '大丈夫です',
        translationVi: 'Không sao / ổn',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (romaji): daijoubu desu',
      },
    ],
    sentences: [
      {
        id: 'ja-l1-3-s1',
        text: 'すみません、お手洗いはどこですか？',
        translationVi: '(Sumimasen, otearai wa doko desu ka?) Xin lỗi, nhà vệ sinh ở đâu ạ?',
      },
      {
        id: 'ja-l1-3-s2',
        text: '本当にありがとうございます！——どういたしまして。',
        translationVi: '(Hontou ni arigatou gozaimasu! — Dou itashimashite.) Cảm ơn bạn rất nhiều! — Không có gì.',
      },
      { id: 'ja-l1-3-s3', text: 'ごめんなさい、遅れました。', translationVi: '(Gomennasai, okuremashita.) Xin lỗi, tôi đến muộn.' },
    ],
    exercises: [
      {
        id: 'ja-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Khi ai đó nói 'ありがとうございます' với bạn, bạn đáp lại thế nào?",
        question: 'ありがとうございます！',
        options: ['ごめんなさい', 'どういたしまして', 'さようなら', '大丈夫です'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '___、お手洗いはどこですか？',
        wordBank: ['すみません', 'ありがとうございます', 'さようなら'],
        correctAnswer: 'すみません',
      },
      {
        id: 'ja-l1-3-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ 'お願いします'.",
        question: 'お願いします',
        options: ['Làm ơn', 'Cảm ơn', 'Xin lỗi', 'Tạm biệt'],
        correctOptionIndex: 0,
      },
    ],
  },
];
