import type { Lesson } from '../../types';

export const japaneseIntroductionsLessons: Lesson[] = [
  {
    id: 'ja-l2-1-whats-your-name',
    unitId: 'ja-u2-introductions',
    title: 'お名前は何ですか？',
    titleVi: 'Tên của bạn là gì?',
    objectiveVi: "Hỏi tên người khác và giới thiệu tên của mình bằng mẫu câu '...です'.",
    estimatedMinutes: 6,
    grammarNoteVi: "はじめまして chỉ dùng khi gặp ai đó LẦN ĐẦU TIÊN, không dùng lại ở những lần gặp sau.",
    vocabulary: [
      {
        id: 'ja-l2-1-v1',
        term: '名前',
        translationVi: 'Tên',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l2-1-s2',
        usageNoteVi: 'Cách đọc (romaji): namae',
      },
      {
        id: 'ja-l2-1-v2',
        term: 'お名前は何ですか',
        translationVi: 'Tên bạn là gì',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l2-1-s1',
        usageNoteVi: 'Cách đọc (romaji): onamae wa nan desu ka',
      },
      {
        id: 'ja-l2-1-v3',
        term: '私の名前は…です',
        translationVi: 'Tên tôi là...',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l2-1-s2',
        usageNoteVi: 'Cách đọc (romaji): watashi no namae wa...desu',
      },
      {
        id: 'ja-l2-1-v4',
        term: 'はじめまして',
        translationVi: 'Rất vui được gặp bạn (lần đầu)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l2-1-s2',
        usageNoteVi: 'Cách đọc (romaji): hajimemashite',
      },
      {
        id: 'ja-l2-1-v5',
        term: '私は…です',
        translationVi: 'Tôi là...',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l2-1-s3',
        usageNoteVi: 'Cách đọc (romaji): watashi wa...desu',
      },
    ],
    sentences: [
      { id: 'ja-l2-1-s1', text: 'お名前は何ですか？', translationVi: '(Onamae wa nan desu ka?) Tên bạn là gì?' },
      {
        id: 'ja-l2-1-s2',
        text: '私の名前はランです。はじめまして。',
        translationVi: '(Watashi no namae wa Ran desu. Hajimemashite.) Tên tôi là Lan. Rất vui được gặp bạn.',
      },
      { id: 'ja-l2-1-s3', text: '私はミンです。', translationVi: '(Watashi wa Min desu.) Tôi là Minh.' },
    ],
    exercises: [
      {
        id: 'ja-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Câu 'お名前は何ですか？' có nghĩa là gì?",
        question: 'お名前は何ですか？',
        options: ['Bạn khỏe không?', 'Tên bạn là gì?', 'Bạn đến từ đâu?', 'Rất vui được gặp bạn'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: '私の___はランです。',
        wordBank: ['名前', '元気', 'ありがとう'],
        correctAnswer: '名前',
      },
      {
        id: 'ja-l2-1-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu đúng để giới thiệu tên của bạn là Minh.',
        question: '正しい文を選んでください。',
        options: ['私はミンです。', 'ミンは私です。', '名前ミン私です。', '私名前はミン。'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'ja-l2-2-where-are-you-from',
    unitId: 'ja-u2-introductions',
    title: 'どこから来ましたか？',
    titleVi: 'Bạn đến từ đâu?',
    objectiveVi: 'Nói được quốc gia của mình và hỏi người khác đến từ đâu bằng tiếng Nhật.',
    estimatedMinutes: 6,
    grammarNoteVi: "Dùng trợ từ 'から' (từ) sau tên địa điểm + '来ました' (đã đến) để nói bạn đến từ đâu.",
    vocabulary: [
      {
        id: 'ja-l2-2-v1',
        term: 'どこから来ましたか',
        translationVi: 'Bạn đến từ đâu',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l2-2-s1',
        usageNoteVi: 'Cách đọc (romaji): doko kara kimashita ka',
      },
      {
        id: 'ja-l2-2-v2',
        term: '…から来ました',
        translationVi: 'Tôi đến từ...',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l2-2-s2',
        usageNoteVi: 'Cách đọc (romaji): ...kara kimashita',
      },
      {
        id: 'ja-l2-2-v3',
        term: 'ベトナム',
        translationVi: 'Việt Nam',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l2-2-s2',
        usageNoteVi: 'Cách đọc (romaji): betonamu',
      },
      {
        id: 'ja-l2-2-v4',
        term: '国',
        translationVi: 'Quốc gia',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc (romaji): kuni',
      },
      {
        id: 'ja-l2-2-v5',
        term: 'ベトナム人',
        translationVi: 'Người Việt Nam',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l2-2-s3',
        usageNoteVi: 'Cách đọc (romaji): betonamujin',
      },
    ],
    sentences: [
      { id: 'ja-l2-2-s1', text: 'どこから来ましたか？', translationVi: '(Doko kara kimashita ka?) Bạn đến từ đâu?' },
      { id: 'ja-l2-2-s2', text: 'ベトナムから来ました。', translationVi: '(Betonamu kara kimashita.) Tôi đến từ Việt Nam.' },
      { id: 'ja-l2-2-s3', text: '私はベトナム人です。', translationVi: '(Watashi wa betonamujin desu.) Tôi là người Việt Nam.' },
    ],
    exercises: [
      {
        id: 'ja-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '国'.",
        question: '国',
        options: ['Thành phố', 'Quốc gia', 'Ngôn ngữ', 'Gia đình'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: 'ベトナム___来ました。',
        wordBank: ['から', 'は', 'です'],
        correctAnswer: 'から',
      },
      {
        id: 'ja-l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi quê quán của ai đó.',
        question: '正しい質問を選んでください。',
        options: ['お名前は何ですか？', 'どこから来ましたか？', 'お元気ですか？', 'ありがとうございます。'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ja-l2-3-age-job',
    unitId: 'ja-u2-introductions',
    title: '年齢と仕事',
    titleVi: 'Tuổi và nghề nghiệp',
    objectiveVi: 'Nói được tuổi và nghề nghiệp của bản thân bằng các mẫu câu đơn giản.',
    estimatedMinutes: 6,
    grammarNoteVi: "20 tuổi có cách đọc đặc biệt là 'はたち' (hatachi), khác quy luật đếm tuổi thông thường '...歳' (…sai) dùng cho các số tuổi khác.",
    vocabulary: [
      {
        id: 'ja-l2-3-v1',
        term: 'おいくつですか',
        translationVi: 'Bạn bao nhiêu tuổi (lịch sự)',
        partOfSpeech: 'phrase',
        exampleSentenceId: 'ja-l2-3-s1',
        usageNoteVi: 'Cách đọc (romaji): oikutsu desu ka',
      },
      {
        id: 'ja-l2-3-v2',
        term: '歳',
        translationVi: '...tuổi',
        partOfSpeech: 'phrase',
        usageNoteVi: 'Cách đọc (romaji): sai. Riêng 20 tuổi đọc đặc biệt là はたち (hatachi), không phải にじゅっさい.',
      },
      {
        id: 'ja-l2-3-v3',
        term: '学生',
        translationVi: 'Học sinh / sinh viên',
        partOfSpeech: 'noun',
        exampleSentenceId: 'ja-l2-3-s3',
        usageNoteVi: 'Cách đọc (romaji): gakusei',
      },
      { id: 'ja-l2-3-v4', term: '先生', translationVi: 'Giáo viên', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): sensei' },
      {
        id: 'ja-l2-3-v5',
        term: 'エンジニア',
        translationVi: 'Kỹ sư',
        partOfSpeech: 'noun',
        usageNoteVi: 'Cách đọc (romaji): enjinia',
      },
      { id: 'ja-l2-3-v6', term: '仕事', translationVi: 'Công việc / nghề nghiệp', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (romaji): shigoto' },
    ],
    sentences: [
      { id: 'ja-l2-3-s1', text: 'おいくつですか？', translationVi: '(Oikutsu desu ka?) Bạn bao nhiêu tuổi?' },
      { id: 'ja-l2-3-s2', text: '二十歳です。', translationVi: '(Hatachi desu.) Tôi hai mươi tuổi.' },
      { id: 'ja-l2-3-s3', text: '私は学生です。', translationVi: '(Watashi wa gakusei desu.) Tôi là sinh viên.' },
    ],
    exercises: [
      {
        id: 'ja-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của từ '学生'.",
        question: '学生',
        options: ['Giáo viên', 'Học sinh / sinh viên', 'Kỹ sư', 'Bác sĩ'],
        correctOptionIndex: 1,
      },
      {
        id: 'ja-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu (nghề nghiệp).',
        sentenceTemplate: '私は___です。',
        wordBank: ['先生', 'から', '元気'],
        correctAnswer: '先生',
      },
      {
        id: 'ja-l2-3-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi tuổi của ai đó.',
        question: '正しい質問を選んでください。',
        options: ['お名前は何ですか？', 'おいくつですか？', 'どこから来ましたか？', 'はじめまして。'],
        correctOptionIndex: 1,
      },
    ],
  },
];
