import type { Lesson } from '../../../types';

export const chineseB1ConnectorsLessons: Lesson[] = [
  {
    id: 'zh-b1-l2-1-yue-yue',
    unitId: 'zh-b1-u2-connectors',
    title: '越...越...',
    titleVi: 'Tương quan tăng dần 越...越...',
    objectiveVi: "Diễn tả mối tương quan tăng dần: điều gì càng tăng thì kết quả cũng tăng theo, bằng '越...越...' và '越来越'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "越 A 越 B: A càng tăng thì B cũng tăng theo, có thể lặp chủ ngữ ở giữa. 越来越 + tính từ diễn tả 'ngày càng...' theo thời gian, không cần vế A. Ví dụ: 天气越来越冷了 (Trời ngày càng lạnh).",
    vocabulary: [
      { id: 'zh-b1-l2-1-v1', term: '越...越...', translationVi: 'Càng...càng...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): yuè...yuè...' },
      { id: 'zh-b1-l2-1-v2', term: '越来越', translationVi: 'Ngày càng', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l2-1-s1', usageNoteVi: 'Cách đọc (pinyin): yuè lái yuè' },
      { id: 'zh-b1-l2-1-v3', term: '练习', translationVi: 'Luyện tập', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l2-1-s2', usageNoteVi: 'Cách đọc (pinyin): liànxí' },
      { id: 'zh-b1-l2-1-v4', term: '有意思', translationVi: 'Thú vị', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b1-l2-1-s3', usageNoteVi: 'Cách đọc (pinyin): yǒu yìsi' },
      { id: 'zh-b1-l2-1-v5', term: '天气', translationVi: 'Thời tiết', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): tiānqì' },
      { id: 'zh-b1-l2-1-v6', term: '冷', translationVi: 'Lạnh', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): lěng' },
      { id: 'zh-b1-l2-1-v7', term: '热闹', translationVi: 'Náo nhiệt', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): rènao' },
      { id: 'zh-b1-l2-1-v8', term: '压力', translationVi: 'Áp lực', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l2-1-s4', usageNoteVi: 'Cách đọc (pinyin): yālì' },
      { id: 'zh-b1-l2-1-v9', term: '增加', translationVi: 'Tăng lên', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): zēngjiā' },
      { id: 'zh-b1-l2-1-v10', term: '复杂', translationVi: 'Phức tạp', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): fùzá' },
      { id: 'zh-b1-l2-1-v11', term: '简单', translationVi: 'Đơn giản', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): jiǎndān' },
      { id: 'zh-b1-l2-1-v12', term: '了解', translationVi: 'Hiểu, tìm hiểu', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l2-1-s5', usageNoteVi: 'Cách đọc (pinyin): liǎojiě' },
      { id: 'zh-b1-l2-1-v13', term: '适应', translationVi: 'Thích nghi', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): shìyìng' },
    ],
    sentences: [
      { id: 'zh-b1-l2-1-s1', text: '天气越来越冷了。', translationVi: '(Tiānqì yuè lái yuè lěng le.) Thời tiết ngày càng lạnh.' },
      { id: 'zh-b1-l2-1-s2', text: '你越练习，中文越流利。', translationVi: '(Nǐ yuè liànxí, Zhōngwén yuè liúlì.) Bạn càng luyện tập, tiếng Trung càng lưu loát.' },
      { id: 'zh-b1-l2-1-s3', text: '这本书越看越有意思。', translationVi: '(Zhè běn shū yuè kàn yuè yǒuyìsi.) Cuốn sách này càng đọc càng thú vị.' },
      { id: 'zh-b1-l2-1-s4', text: '工作压力越来越大。', translationVi: '(Gōngzuò yālì yuè lái yuè dà.) Áp lực công việc ngày càng lớn.' },
      { id: 'zh-b1-l2-1-s5', text: '我越了解他，越喜欢他。', translationVi: '(Wǒ yuè liǎojiě tā, yuè xǐhuan tā.) Tôi càng hiểu anh ấy, càng thích anh ấy.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn cụm từ đúng cho 'ngày càng lạnh'.",
        question: '天气___冷了。',
        options: ['越来越', '不但', '要是', '除了'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '这本书___看越有意思。',
        wordBank: ['越', '得', '比'],
        correctAnswer: '越',
      },
      {
        id: 'zh-b1-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Thời tiết ngày càng lạnh."',
        words: ['冷了', '天气', '越来越'],
        correctOrder: ['天气', '越来越', '冷了'],
      },
    ],
  },
  {
    id: 'zh-b1-l2-2-budan-erqie',
    unitId: 'zh-b1-u2-connectors',
    title: '不但...而且...',
    titleVi: 'Liên kết bổ sung 不但...而且...',
    objectiveVi: "Liệt kê hai ý liên quan, ý sau bổ sung/nâng cao ý trước bằng '不但...而且...'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "不但 A 而且 B: không những A mà còn B, thường kèm 也/还 ở vế B để nhấn mạnh thêm. Ví dụ: 她不但漂亮，而且很聪明 (Cô ấy không những xinh đẹp mà còn rất thông minh).",
    vocabulary: [
      { id: 'zh-b1-l2-2-v1', term: '不但...而且...', translationVi: 'Không những...mà còn...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): bùdàn...érqiě...' },
      { id: 'zh-b1-l2-2-v2', term: '聪明', translationVi: 'Thông minh', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b1-l2-2-s1', usageNoteVi: 'Cách đọc (pinyin): cōngming' },
      { id: 'zh-b1-l2-2-v3', term: '勤奋', translationVi: 'Chăm chỉ, cần cù', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): qínfèn' },
      { id: 'zh-b1-l2-2-v4', term: '方便', translationVi: 'Tiện lợi', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b1-l2-2-s2', usageNoteVi: 'Cách đọc (pinyin): fāngbiàn' },
      { id: 'zh-b1-l2-2-v5', term: '健康', translationVi: 'Khỏe mạnh, sức khỏe', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b1-l2-2-s3', usageNoteVi: 'Cách đọc (pinyin): jiànkāng' },
      { id: 'zh-b1-l2-2-v6', term: '环境', translationVi: 'Môi trường', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): huánjìng' },
      { id: 'zh-b1-l2-2-v7', term: '污染', translationVi: 'Ô nhiễm', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l2-2-s4', usageNoteVi: 'Cách đọc (pinyin): wūrǎn' },
      { id: 'zh-b1-l2-2-v8', term: '严重', translationVi: 'Nghiêm trọng', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): yánzhòng' },
      { id: 'zh-b1-l2-2-v9', term: '提高', translationVi: 'Nâng cao', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l2-2-s5', usageNoteVi: 'Cách đọc (pinyin): tígāo' },
      { id: 'zh-b1-l2-2-v10', term: '效率', translationVi: 'Hiệu suất', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): xiàolǜ' },
      { id: 'zh-b1-l2-2-v11', term: '节省', translationVi: 'Tiết kiệm', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): jiéshěng' },
      { id: 'zh-b1-l2-2-v12', term: '好处', translationVi: 'Lợi ích', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): hǎochù' },
      { id: 'zh-b1-l2-2-v13', term: '减轻', translationVi: 'Giảm nhẹ', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): jiǎnqīng' },
    ],
    sentences: [
      { id: 'zh-b1-l2-2-s1', text: '她不但漂亮，而且很聪明。', translationVi: '(Tā bùdàn piàoliang, érqiě hěn cōngming.) Cô ấy không những xinh đẹp mà còn rất thông minh.' },
      { id: 'zh-b1-l2-2-s2', text: '这个方法不但简单，而且方便。', translationVi: '(Zhège fāngfǎ bùdàn jiǎndān, érqiě fāngbiàn.) Phương pháp này không những đơn giản mà còn tiện lợi.' },
      { id: 'zh-b1-l2-2-s3', text: '运动不但对健康好，而且能减轻压力。', translationVi: '(Yùndòng bùdàn duì jiànkāng hǎo, érqiě néng jiǎnqīng yālì.) Tập thể dục không những tốt cho sức khỏe mà còn giúp giảm áp lực.' },
      { id: 'zh-b1-l2-2-s4', text: '空气污染不但严重，而且越来越难解决。', translationVi: '(Kōngqì wūrǎn bùdàn yánzhòng, érqiě yuè lái yuè nán jiějué.) Ô nhiễm không khí không những nghiêm trọng mà còn ngày càng khó giải quyết.' },
      { id: 'zh-b1-l2-2-s5', text: '这样做不但节省时间，而且提高效率。', translationVi: '(Zhèyàng zuò bùdàn jiéshěng shíjiān, érqiě tígāo xiàolǜ.) Làm như vậy không những tiết kiệm thời gian mà còn nâng cao hiệu suất.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ đúng cho 'không những...'.",
        question: '她___漂亮，而且很聪明。',
        options: ['不但', '虽然', '因为', '越'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '这个方法不但简单，___方便。',
        wordBank: ['而且', '但是', '所以'],
        correctAnswer: '而且',
      },
      {
        id: 'zh-b1-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Cô ấy không những xinh đẹp mà còn rất thông minh."',
        words: ['很聪明', '而且', '她不但漂亮'],
        correctOrder: ['她不但漂亮', '而且', '很聪明'],
      },
    ],
  },
  {
    id: 'zh-b1-l2-3-yaoshi-jiu',
    unitId: 'zh-b1-u2-connectors',
    title: '要是...就...',
    titleVi: 'Câu điều kiện 要是...就...',
    objectiveVi: "Đặt ra điều kiện và kết quả một cách thân mật, tự nhiên bằng '要是...就...'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "要是 A，就 B: nếu A thì B — cách nói điều kiện thân mật, dùng nhiều trong khẩu ngữ, tương tự 如果...就... nhưng ít trang trọng hơn. Ví dụ: 要是明天下雨，我们就不去了 (Nếu ngày mai trời mưa thì chúng ta sẽ không đi nữa).",
    vocabulary: [
      { id: 'zh-b1-l2-3-v1', term: '要是...就...', translationVi: 'Nếu...thì... (thân mật)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): yàoshi...jiù...' },
      { id: 'zh-b1-l2-3-v2', term: '如果', translationVi: 'Nếu (trang trọng hơn 要是)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): rúguǒ' },
      { id: 'zh-b1-l2-3-v3', term: '万一', translationVi: 'Lỡ như, nhỡ đâu', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): wànyī' },
      { id: 'zh-b1-l2-3-v4', term: '取消', translationVi: 'Hủy bỏ', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): qǔxiāo' },
      { id: 'zh-b1-l2-3-v5', term: '迟到', translationVi: 'Đến trễ', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l2-3-s3', usageNoteVi: 'Cách đọc (pinyin): chídào' },
      { id: 'zh-b1-l2-3-v6', term: '提前', translationVi: 'Trước (thời gian)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): tíqián' },
      { id: 'zh-b1-l2-3-v7', term: '联系', translationVi: 'Liên lạc', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l2-3-s3', usageNoteVi: 'Cách đọc (pinyin): liánxì' },
      { id: 'zh-b1-l2-3-v8', term: '改变主意', translationVi: 'Đổi ý', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): gǎibiàn zhǔyì' },
      { id: 'zh-b1-l2-3-v9', term: '计划', translationVi: 'Kế hoạch', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l2-3-s4', usageNoteVi: 'Cách đọc (pinyin): jìhuà' },
      { id: 'zh-b1-l2-3-v10', term: '顺利', translationVi: 'Thuận lợi', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): shùnlì' },
      { id: 'zh-b1-l2-3-v11', term: '麻烦', translationVi: 'Phiền phức', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): máfan' },
      { id: 'zh-b1-l2-3-v12', term: '满意', translationVi: 'Hài lòng', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b1-l2-3-s5', usageNoteVi: 'Cách đọc (pinyin): mǎnyì' },
      { id: 'zh-b1-l2-3-v13', term: '后悔', translationVi: 'Hối hận', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): hòuhuǐ' },
    ],
    sentences: [
      { id: 'zh-b1-l2-3-s1', text: '要是明天下雨，我们就不去了。', translationVi: '(Yàoshi míngtiān xiàyǔ, wǒmen jiù bú qù le.) Nếu ngày mai trời mưa thì chúng ta sẽ không đi nữa.' },
      { id: 'zh-b1-l2-3-s2', text: '要是你有时间，就来找我吧。', translationVi: '(Yàoshi nǐ yǒu shíjiān, jiù lái zhǎo wǒ ba.) Nếu bạn có thời gian thì hãy đến tìm tôi nhé.' },
      { id: 'zh-b1-l2-3-s3', text: '要是迟到了，请提前联系我。', translationVi: '(Yàoshi chídào le, qǐng tíqián liánxì wǒ.) Nếu đến trễ, làm ơn liên lạc trước với tôi.' },
      { id: 'zh-b1-l2-3-s4', text: '要是计划有变化，我会马上告诉你。', translationVi: '(Yàoshi jìhuà yǒu biànhuà, wǒ huì mǎshàng gàosu nǐ.) Nếu kế hoạch có thay đổi, tôi sẽ báo cho bạn ngay.' },
      { id: 'zh-b1-l2-3-s5', text: '要是你不满意，就换一个。', translationVi: '(Yàoshi nǐ bù mǎnyì, jiù huàn yí gè.) Nếu bạn không hài lòng thì đổi cái khác đi.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ đúng cho 'nếu' thân mật.",
        question: '___明天下雨，我们就不去了。',
        options: ['要是', '虽然', '因为', '越'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '要是你有时间，___来找我吧。',
        wordBank: ['就', '也', '还'],
        correctAnswer: '就',
      },
      {
        id: 'zh-b1-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Nếu đến trễ, làm ơn liên lạc trước với tôi."',
        words: ['请提前联系我', '要是迟到了'],
        correctOrder: ['要是迟到了', '请提前联系我'],
      },
    ],
  },
];
