import type { Lesson } from '../../../types';

export const chineseB1OpinionsLessons: Lesson[] = [
  {
    id: 'zh-b1-l3-1-juede-renwei',
    unitId: 'zh-b1-u3-opinions',
    title: '觉得 / 认为',
    titleVi: 'Nêu quan điểm 觉得 / 认为',
    objectiveVi: "Nêu ý kiến cá nhân bằng '觉得'/'认为', và đồng ý/không đồng ý một cách lịch sự.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "觉得 (cảm thấy, thân mật hơn) và 认为 (cho rằng, trang trọng hơn) đều đứng trước một mệnh đề để nêu ý kiến. Đồng ý: 我同意你的看法/说得对. Không đồng ý lịch sự: 你说得有道理，不过.../也许是这样，但是...",
    vocabulary: [
      { id: 'zh-b1-l3-1-v1', term: '觉得', translationVi: 'Cảm thấy, nghĩ rằng', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l3-1-s1', usageNoteVi: 'Cách đọc (pinyin): juéde' },
      { id: 'zh-b1-l3-1-v2', term: '认为', translationVi: 'Cho rằng (trang trọng hơn)', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l3-1-s2', usageNoteVi: 'Cách đọc (pinyin): rènwéi' },
      { id: 'zh-b1-l3-1-v3', term: '同意', translationVi: 'Đồng ý', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l3-1-s3', usageNoteVi: 'Cách đọc (pinyin): tóngyì' },
      { id: 'zh-b1-l3-1-v4', term: '看法', translationVi: 'Quan điểm, cách nhìn', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): kànfǎ' },
      { id: 'zh-b1-l3-1-v5', term: '不过', translationVi: 'Tuy nhiên, nhưng', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l3-1-s4', usageNoteVi: 'Cách đọc (pinyin): búguò' },
      { id: 'zh-b1-l3-1-v6', term: '也许', translationVi: 'Có lẽ', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l3-1-s5', usageNoteVi: 'Cách đọc (pinyin): yěxǔ' },
      { id: 'zh-b1-l3-1-v7', term: '反对', translationVi: 'Phản đối', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): fǎnduì' },
      { id: 'zh-b1-l3-1-v8', term: '观点', translationVi: 'Quan điểm', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): guāndiǎn' },
      { id: 'zh-b1-l3-1-v9', term: '理由', translationVi: 'Lý do', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): lǐyóu' },
      { id: 'zh-b1-l3-1-v10', term: '证据', translationVi: 'Bằng chứng', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): zhèngjù' },
      { id: 'zh-b1-l3-1-v11', term: '说得对', translationVi: 'Nói đúng', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): shuō de duì' },
      { id: 'zh-b1-l3-1-v12', term: '有道理', translationVi: 'Có lý', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): yǒu dàolǐ' },
      { id: 'zh-b1-l3-1-v13', term: '讨论', translationVi: 'Thảo luận', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): tǎolùn' },
    ],
    sentences: [
      { id: 'zh-b1-l3-1-s1', text: '我觉得这个决定不太合适。', translationVi: '(Wǒ juéde zhège juédìng bú tài héshì.) Tôi cảm thấy quyết định này không hợp lý lắm.' },
      { id: 'zh-b1-l3-1-s2', text: '我认为教育很重要。', translationVi: '(Wǒ rènwéi jiàoyù hěn zhòngyào.) Tôi cho rằng giáo dục rất quan trọng.' },
      { id: 'zh-b1-l3-1-s3', text: '我同意你的看法。', translationVi: '(Wǒ tóngyì nǐ de kànfǎ.) Tôi đồng ý với quan điểm của bạn.' },
      { id: 'zh-b1-l3-1-s4', text: '你说得有道理，不过我还有别的想法。', translationVi: '(Nǐ shuō de yǒu dàolǐ, búguò wǒ hái yǒu bié de xiǎngfǎ.) Bạn nói cũng có lý, nhưng tôi vẫn có ý kiến khác.' },
      { id: 'zh-b1-l3-1-s5', text: '也许你是对的，但是我需要更多证据。', translationVi: '(Yěxǔ nǐ shì duì de, dànshì wǒ xūyào gèng duō zhèngjù.) Có lẽ bạn đúng, nhưng tôi cần thêm bằng chứng.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cách diễn đạt lịch sự nhất để không đồng ý.',
        question: '选择最礼貌的说法。',
        options: ['你错了。', '你说得有道理，不过我还有别的想法。', '这不对。', '别开玩笑了。'],
        correctOptionIndex: 1,
      },
      {
        id: 'zh-b1-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ đúng (trang trọng hơn).',
        sentenceTemplate: '我___教育很重要。',
        wordBank: ['认为', '觉得', '同意'],
        correctAnswer: '认为',
      },
      {
        id: 'zh-b1-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đồng ý với quan điểm của bạn."',
        words: ['你的看法', '我同意'],
        correctOrder: ['我同意', '你的看法'],
      },
    ],
  },
  {
    id: 'zh-b1-l3-2-chule-yiwai',
    unitId: 'zh-b1-u3-opinions',
    title: '除了...以外...',
    titleVi: 'Bổ sung/ngoại lệ 除了...以外...',
    objectiveVi: "Liệt kê ngoại lệ hoặc thông tin bổ sung bằng '除了...以外...'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "除了 A 以外，(B 也/还 C): ngoài A ra, B cũng/còn C — mang nghĩa bao gồm thêm khi đi với 也/还, hoặc nghĩa loại trừ khi đi với 都. Ví dụ: 除了中文以外，我还会说英文 (Ngoài tiếng Trung ra, tôi còn biết nói tiếng Anh — nghĩa bao gồm thêm); 除了他以外，大家都来了 (Ngoài anh ấy ra, mọi người đều đã đến — nghĩa loại trừ).",
    vocabulary: [
      { id: 'zh-b1-l3-2-v1', term: '除了...以外...', translationVi: 'Ngoài...ra', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): chúle...yǐwài...' },
      { id: 'zh-b1-l3-2-v2', term: '大家', translationVi: 'Mọi người', partOfSpeech: 'pronoun', exampleSentenceId: 'zh-b1-l3-2-s2', usageNoteVi: 'Cách đọc (pinyin): dàjiā' },
      { id: 'zh-b1-l3-2-v3', term: '都', translationVi: 'Đều', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): dōu' },
      { id: 'zh-b1-l3-2-v4', term: '也', translationVi: 'Cũng', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l3-2-s5', usageNoteVi: 'Cách đọc (pinyin): yě' },
      { id: 'zh-b1-l3-2-v5', term: '还', translationVi: 'Còn, vẫn', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l3-2-s1', usageNoteVi: 'Cách đọc (pinyin): hái' },
      { id: 'zh-b1-l3-2-v6', term: '参加', translationVi: 'Tham gia', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): cānjiā' },
      { id: 'zh-b1-l3-2-v7', term: '活动', translationVi: 'Hoạt động', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): huódòng' },
      { id: 'zh-b1-l3-2-v8', term: '特别', translationVi: 'Đặc biệt', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): tèbié' },
      { id: 'zh-b1-l3-2-v9', term: '兴趣', translationVi: 'Sở thích, hứng thú', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): xìngqù' },
      { id: 'zh-b1-l3-2-v10', term: '爱好', translationVi: 'Sở thích', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l3-2-s3', usageNoteVi: 'Cách đọc (pinyin): àihào' },
      { id: 'zh-b1-l3-2-v11', term: '全部', translationVi: 'Toàn bộ', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): quánbù' },
      { id: 'zh-b1-l3-2-v12', term: '质量', translationVi: 'Chất lượng', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l3-2-s5', usageNoteVi: 'Cách đọc (pinyin): zhìliàng' },
      { id: 'zh-b1-l3-2-v13', term: '价格', translationVi: 'Giá cả', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l3-2-s5', usageNoteVi: 'Cách đọc (pinyin): jiàgé' },
    ],
    sentences: [
      { id: 'zh-b1-l3-2-s1', text: '除了中文以外，我还会说英文。', translationVi: '(Chúle Zhōngwén yǐwài, wǒ hái huì shuō Yīngwén.) Ngoài tiếng Trung ra, tôi còn biết nói tiếng Anh.' },
      { id: 'zh-b1-l3-2-s2', text: '除了他以外，大家都来了。', translationVi: '(Chúle tā yǐwài, dàjiā dōu lái le.) Ngoài anh ấy ra, mọi người đều đã đến.' },
      { id: 'zh-b1-l3-2-s3', text: '除了游泳以外，我还喜欢跑步。', translationVi: '(Chúle yóuyǒng yǐwài, wǒ hái xǐhuan pǎobù.) Ngoài bơi lội ra, tôi còn thích chạy bộ. (爱好: sở thích)' },
      { id: 'zh-b1-l3-2-s4', text: '除了周末以外，他每天都上班。', translationVi: '(Chúle zhōumò yǐwài, tā měitiān dōu shàngbān.) Ngoài cuối tuần ra, anh ấy ngày nào cũng đi làm.' },
      { id: 'zh-b1-l3-2-s5', text: '除了价格以外，质量也很重要。', translationVi: '(Chúle jiàgé yǐwài, zhìliàng yě hěn zhòngyào.) Ngoài giá cả ra, chất lượng cũng rất quan trọng.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ đúng cho 'ngoài...ra'.",
        question: '___中文以外，我还会说英文。',
        options: ['除了', '虽然', '要是', '越'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu (nghĩa loại trừ).',
        sentenceTemplate: '除了他以外，大家___来了。',
        wordBank: ['都', '也', '还'],
        correctAnswer: '都',
      },
      {
        id: 'zh-b1-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Ngoài bơi lội ra, tôi còn thích chạy bộ."',
        words: ['我还喜欢跑步', '除了游泳以外'],
        correctOrder: ['除了游泳以外', '我还喜欢跑步'],
      },
    ],
  },
];
