import type { Lesson } from '../../../types';

export const chineseB1StructuresLessons: Lesson[] = [
  {
    id: 'zh-b1-l1-1-ba',
    unitId: 'zh-b1-u1-structures',
    title: '把字句',
    titleVi: 'Câu chữ 把',
    objectiveVi: "Dùng '把' để nhấn mạnh việc xử lý một tân ngữ xác định và kết quả của hành động.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "把 đặt tân ngữ xác định lên trước động từ: S + 把 + O + V + (bổ ngữ/kết quả). Dùng khi tân ngữ đã được nhắc đến cụ thể và hành động có kết quả rõ ràng (hoàn thành, thay đổi vị trí...). Không dùng 把 nếu sau động từ không có gì thêm.",
    vocabulary: [
      { id: 'zh-b1-l1-1-v1', term: '把', translationVi: 'Đem, dùng để nhấn mạnh tân ngữ xác định', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): bǎ' },
      { id: 'zh-b1-l1-1-v2', term: '作业', translationVi: 'Bài tập', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l1-1-s1', usageNoteVi: 'Cách đọc (pinyin): zuòyè' },
      { id: 'zh-b1-l1-1-v3', term: '做完', translationVi: 'Làm xong', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): zuò wán' },
      { id: 'zh-b1-l1-1-v4', term: '打开', translationVi: 'Mở ra', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l1-1-s2', usageNoteVi: 'Cách đọc (pinyin): dǎkāi' },
      { id: 'zh-b1-l1-1-v5', term: '关上', translationVi: 'Đóng lại', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): guān shàng' },
      { id: 'zh-b1-l1-1-v6', term: '放', translationVi: 'Đặt, để', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): fàng' },
      { id: 'zh-b1-l1-1-v7', term: '桌子', translationVi: 'Cái bàn', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l1-1-s5', usageNoteVi: 'Cách đọc (pinyin): zhuōzi' },
      { id: 'zh-b1-l1-1-v8', term: '钥匙', translationVi: 'Chìa khóa', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l1-1-s3', usageNoteVi: 'Cách đọc (pinyin): yàoshi' },
      { id: 'zh-b1-l1-1-v9', term: '忘记', translationVi: 'Quên', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): wàngjì' },
      { id: 'zh-b1-l1-1-v10', term: '拿走', translationVi: 'Cầm đi, lấy đi', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): ná zǒu' },
      { id: 'zh-b1-l1-1-v11', term: '打扫', translationVi: 'Dọn dẹp', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l1-1-s4', usageNoteVi: 'Cách đọc (pinyin): dǎsǎo' },
      { id: 'zh-b1-l1-1-v12', term: '房间', translationVi: 'Căn phòng', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): fángjiān' },
      { id: 'zh-b1-l1-1-v13', term: '整理', translationVi: 'Sắp xếp, thu dọn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): zhěnglǐ' },
    ],
    sentences: [
      { id: 'zh-b1-l1-1-s1', text: '我把作业做完了。', translationVi: '(Wǒ bǎ zuòyè zuò wán le.) Tôi đã làm xong bài tập.' },
      { id: 'zh-b1-l1-1-s2', text: '请把门打开。', translationVi: '(Qǐng bǎ mén dǎkāi.) Làm ơn mở cửa ra.' },
      { id: 'zh-b1-l1-1-s3', text: '我把钥匙忘记在家里了。', translationVi: '(Wǒ bǎ yàoshi wàngjì zài jiā lǐ le.) Tôi đã quên chìa khóa ở nhà rồi.' },
      { id: 'zh-b1-l1-1-s4', text: '他把房间打扫干净了。', translationVi: '(Tā bǎ fángjiān dǎsǎo gānjìng le.) Anh ấy đã dọn dẹp phòng sạch sẽ.' },
      { id: 'zh-b1-l1-1-s5', text: '请把桌子上的东西拿走。', translationVi: '(Qǐng bǎ zhuōzi shàng de dōngxi ná zǒu.) Làm ơn lấy đồ trên bàn đi.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ đúng để nhấn mạnh tân ngữ xác định.",
        question: '我___作业做完了。',
        options: ['把', '被', '比', '了'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '请___门打开。',
        wordBank: ['把', '被', '比'],
        correctAnswer: '把',
      },
      {
        id: 'zh-b1-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đã quên chìa khóa ở nhà rồi."',
        words: ['忘记在家里了', '我把', '钥匙'],
        correctOrder: ['我把', '钥匙', '忘记在家里了'],
      },
    ],
  },
  {
    id: 'zh-b1-l1-2-bei',
    unitId: 'zh-b1-u1-structures',
    title: '被字句',
    titleVi: 'Câu chữ 被 (bị động)',
    objectiveVi: "Dùng '被' để tạo câu bị động, nhấn mạnh đối tượng chịu tác động.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "被 tạo câu bị động: S(bị tác động) + 被 + (tác nhân, có thể lược bỏ) + V + bổ ngữ. Ví dụ: 我的手机被弟弟拿走了 (Điện thoại của tôi bị em trai lấy đi mất). Sau động từ thường cần thêm bổ ngữ/kết quả, giống cấu trúc 把.",
    vocabulary: [
      { id: 'zh-b1-l1-2-v1', term: '被', translationVi: 'Bị (câu bị động)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): bèi' },
      { id: 'zh-b1-l1-2-v2', term: '手机', translationVi: 'Điện thoại di động', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l1-2-s1', usageNoteVi: 'Cách đọc (pinyin): shǒujī' },
      { id: 'zh-b1-l1-2-v3', term: '弄坏', translationVi: 'Làm hỏng', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): nòng huài' },
      { id: 'zh-b1-l1-2-v4', term: '偷', translationVi: 'Trộm, ăn cắp', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): tōu' },
      { id: 'zh-b1-l1-2-v5', term: '发现', translationVi: 'Phát hiện', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): fāxiàn' },
      { id: 'zh-b1-l1-2-v6', term: '批评', translationVi: 'Phê bình', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l1-2-s2', usageNoteVi: 'Cách đọc (pinyin): pīpíng' },
      { id: 'zh-b1-l1-2-v7', term: '老板', translationVi: 'Ông chủ, sếp', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): lǎobǎn' },
      { id: 'zh-b1-l1-2-v8', term: '错误', translationVi: 'Lỗi sai', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): cuòwù' },
      { id: 'zh-b1-l1-2-v9', term: '骗', translationVi: 'Lừa', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): piàn' },
      { id: 'zh-b1-l1-2-v10', term: '修好', translationVi: 'Sửa xong', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l1-2-s5', usageNoteVi: 'Cách đọc (pinyin): xiū hǎo' },
      { id: 'zh-b1-l1-2-v11', term: '淋湿', translationVi: 'Bị ướt (do mưa)', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l1-2-s3', usageNoteVi: 'Cách đọc (pinyin): lín shī' },
      { id: 'zh-b1-l1-2-v12', term: '感动', translationVi: 'Cảm động', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l1-2-s4', usageNoteVi: 'Cách đọc (pinyin): gǎndòng' },
      { id: 'zh-b1-l1-2-v13', term: '邀请', translationVi: 'Mời', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): yāoqǐng' },
    ],
    sentences: [
      { id: 'zh-b1-l1-2-s1', text: '我的手机被弟弟拿走了。', translationVi: '(Wǒ de shǒujī bèi dìdi ná zǒu le.) Điện thoại của tôi bị em trai lấy đi mất.' },
      { id: 'zh-b1-l1-2-s2', text: '我被老板批评了。', translationVi: '(Wǒ bèi lǎobǎn pīpíng le.) Tôi đã bị sếp phê bình.' },
      { id: 'zh-b1-l1-2-s3', text: '车被雨淋湿了。', translationVi: '(Chē bèi yǔ lín shī le.) Xe bị ướt vì mưa.' },
      { id: 'zh-b1-l1-2-s4', text: '我被他的故事感动了。', translationVi: '(Wǒ bèi tā de gùshì gǎndòng le.) Tôi đã bị câu chuyện của anh ấy làm cho cảm động.' },
      { id: 'zh-b1-l1-2-s5', text: '电脑已经被修好了。', translationVi: '(Diànnǎo yǐjīng bèi xiū hǎo le.) Máy tính đã được sửa xong rồi.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng cho câu bị động.',
        question: '我___老板批评了。',
        options: ['被', '把', '比', '了'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '车___雨淋湿了。',
        wordBank: ['被', '把', '比'],
        correctAnswer: '被',
      },
      {
        id: 'zh-b1-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Điện thoại của tôi bị em trai lấy đi mất."',
        words: ['拿走了', '我的手机', '被弟弟'],
        correctOrder: ['我的手机', '被弟弟', '拿走了'],
      },
    ],
  },
  {
    id: 'zh-b1-l1-3-de-complement',
    unitId: 'zh-b1-u1-structures',
    title: '程度补语 得',
    titleVi: 'Bổ ngữ mức độ 得',
    objectiveVi: "Miêu tả mức độ hoặc kết quả của một hành động bằng cấu trúc 'V + 得 + tính từ'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "动词 + 得 + 形容词 miêu tả mức độ thực hiện hành động. Nếu động từ có tân ngữ, phải lặp lại động từ trước 得: 他打篮球打得很好 (Anh ấy chơi bóng rổ rất giỏi). Đừng nhầm 得 (de, bổ ngữ) với 的 (de, sở hữu) hay 地 (de, trạng ngữ).",
    vocabulary: [
      { id: 'zh-b1-l1-3-v1', term: '得', translationVi: 'Trợ từ chỉ mức độ/kết quả', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): de' },
      { id: 'zh-b1-l1-3-v2', term: '跑', translationVi: 'Chạy', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l1-3-s1', usageNoteVi: 'Cách đọc (pinyin): pǎo' },
      { id: 'zh-b1-l1-3-v3', term: '快', translationVi: 'Nhanh', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): kuài' },
      { id: 'zh-b1-l1-3-v4', term: '清楚', translationVi: 'Rõ ràng', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b1-l1-3-s2', usageNoteVi: 'Cách đọc (pinyin): qīngchu' },
      { id: 'zh-b1-l1-3-v5', term: '唱歌', translationVi: 'Hát', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): chànggē' },
      { id: 'zh-b1-l1-3-v6', term: '篮球', translationVi: 'Bóng rổ', partOfSpeech: 'noun', exampleSentenceId: 'zh-b1-l1-3-s3', usageNoteVi: 'Cách đọc (pinyin): lánqiú' },
      { id: 'zh-b1-l1-3-v7', term: '弹钢琴', translationVi: 'Chơi đàn piano', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b1-l1-3-s4', usageNoteVi: 'Cách đọc (pinyin): tán gāngqín' },
      { id: 'zh-b1-l1-3-v8', term: '流利', translationVi: 'Lưu loát, trôi chảy', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): liúlì' },
      { id: 'zh-b1-l1-3-v9', term: '认真', translationVi: 'Nghiêm túc, chăm chỉ', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): rènzhēn' },
      { id: 'zh-b1-l1-3-v10', term: '表现', translationVi: 'Biểu hiện, thể hiện', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): biǎoxiàn' },
      { id: 'zh-b1-l1-3-v11', term: '进步', translationVi: 'Tiến bộ', partOfSpeech: 'verb', exampleSentenceId: 'zh-b1-l1-3-s5', usageNoteVi: 'Cách đọc (pinyin): jìnbù' },
      { id: 'zh-b1-l1-3-v12', term: '熟练', translationVi: 'Thành thạo', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): shúliàn' },
      { id: 'zh-b1-l1-3-v13', term: '努力', translationVi: 'Nỗ lực, chăm chỉ', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): nǔlì' },
    ],
    sentences: [
      { id: 'zh-b1-l1-3-s1', text: '他跑得很快。', translationVi: '(Tā pǎo de hěn kuài.) Anh ấy chạy rất nhanh.' },
      { id: 'zh-b1-l1-3-s2', text: '她说得很清楚。', translationVi: '(Tā shuō de hěn qīngchu.) Cô ấy nói rất rõ ràng.' },
      { id: 'zh-b1-l1-3-s3', text: '他打篮球打得很好。', translationVi: '(Tā dǎ lánqiú dǎ de hěn hǎo.) Anh ấy chơi bóng rổ rất giỏi.' },
      { id: 'zh-b1-l1-3-s4', text: '我妹妹钢琴弹得很熟练。', translationVi: '(Wǒ mèimei gāngqín tán de hěn shúliàn.) Em gái tôi chơi đàn piano rất thành thạo.' },
      { id: 'zh-b1-l1-3-s5', text: '你最近进步得很快。', translationVi: '(Nǐ zuìjìn jìnbù de hěn kuài.) Gần đây bạn tiến bộ rất nhanh.' },
    ],
    exercises: [
      {
        id: 'zh-b1-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn trợ từ đúng cho bổ ngữ mức độ.',
        question: '他跑___很快。',
        options: ['得', '的', '地', '了'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b1-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ còn thiếu.',
        sentenceTemplate: '她说___很清楚。',
        wordBank: ['得', '的', '地'],
        correctAnswer: '得',
      },
      {
        id: 'zh-b1-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Anh ấy chơi bóng rổ rất giỏi."',
        words: ['很好', '他打篮球', '打得'],
        correctOrder: ['他打篮球', '打得', '很好'],
      },
    ],
  },
];
