import type { ConversationScenario } from '../../types';

export const koreanA2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'ko-a2-conv-daily-routine',
    languageCode: 'ko',
    level: 'A2',
    title: '하루 일과 이야기하기',
    titleVi: 'Nói về một ngày của bạn',
    descriptionVi: 'Luyện hội thoại hỏi và kể về thói quen hằng ngày bằng tiếng Hàn.',
    contextVi: 'Lan và An trò chuyện về lịch trình một ngày bình thường.',
    dialogue: [
      { id: 'ko-a2-daily-turn-01', speaker: 'A', text: '보통 몇 시에 일어나요?', translationVi: '(botong myeot sie ireonayo?) Bạn thường thức dậy lúc mấy giờ?' },
      { id: 'ko-a2-daily-turn-02', speaker: 'B', text: '저는 보통 일곱 시에 일어나요.', translationVi: '(jeoneun botong ilgop sie ireonayo.) Tôi thường thức dậy lúc bảy giờ.' },
      { id: 'ko-a2-daily-turn-03', speaker: 'A', text: '그렇게 일찍이요? 그 다음에 뭐 해요?', translationVi: '(geureoke iljjigiyo? geu daeume mwo haeyo?) Sớm vậy? Sau đó bạn làm gì?' },
      { id: 'ko-a2-daily-turn-04', speaker: 'B', text: '씻고 아침을 먹어요.', translationVi: '(ssitgo achimeul meogeoyo.) Tôi tắm rửa rồi ăn sáng.' },
      { id: 'ko-a2-daily-turn-05', speaker: 'A', text: '회사까지 어떻게 가요?', translationVi: '(hoesakkaji eotteoke gayo?) Bạn đi đến công ty bằng gì?' },
      { id: 'ko-a2-daily-turn-06', speaker: 'B', text: '지하철을 타요.', translationVi: '(jihacheoreul tayo.) Tôi đi tàu điện ngầm.' },
      { id: 'ko-a2-daily-turn-07', speaker: 'A', text: '지금 뭐 하고 있어요?', translationVi: '(jigeum mwo hago isseoyo?) Bây giờ bạn đang làm gì?' },
      { id: 'ko-a2-daily-turn-08', speaker: 'B', text: '동료들과 점심을 먹고 있어요.', translationVi: '(dongnyodeulgwa jeomsimeul meokgo isseoyo.) Tôi đang ăn trưa với đồng nghiệp.' },
    ],
    relatedVocabularyIds: ['ko-a2-l1-1-v1', 'ko-a2-l1-1-v6', 'ko-a2-l1-2-v1', 'ko-a2-l2-1-v3'],
    task: {
      type: 'choose-reply',
      promptVi: "Ai đó hỏi '보통 몇 시에 일어나요?'. Bạn trả lời thế nào?",
      options: [
        { id: 'o1', text: '저는 보통 일곱 시에 일어나요.' },
        { id: 'o2', text: '이거 얼마예요?' },
        { id: 'o3', text: '다음 달에 여행 갈 거예요.' },
        { id: 'o4', text: '맵지만 맛있어요.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi về thói quen dùng để hỏi giờ giấc, nên trả lời bằng thời gian bạn thường thức dậy.",
    },
  },
  {
    id: 'ko-a2-conv-shopping-trip',
    languageCode: 'ko',
    level: 'A2',
    title: '쇼핑하기',
    titleVi: 'Chuyến đi mua sắm',
    descriptionVi: 'Luyện hội thoại hỏi giá và mặc cả khi mua sắm bằng tiếng Hàn.',
    contextVi: 'Lan đang mua một chiếc áo khoác tại cửa hàng quần áo.',
    dialogue: [
      { id: 'ko-a2-shop-turn-01', speaker: 'A', text: '이 재킷 얼마예요?', translationVi: '(i jaekit eolmayeyo?) Áo khoác này giá bao nhiêu?' },
      { id: 'ko-a2-shop-turn-02', speaker: 'B', text: '오만 원이에요. 입어 보실래요?', translationVi: '(oman woniyeyo. ibeo bosillaeyo?) Giá 50,000 won. Bạn muốn mặc thử không?' },
      { id: 'ko-a2-shop-turn-03', speaker: 'A', text: '네, 좋아요. 더 작은 사이즈 있어요?', translationVi: '(ne, joayo. deo jageun saijeu isseoyo?) Vâng. Bạn có cỡ nhỏ hơn không?' },
      { id: 'ko-a2-shop-turn-04', speaker: 'B', text: '네, 여기 있어요.', translationVi: '(ne, yeogi isseoyo.) Có, đây bạn.' },
      { id: 'ko-a2-shop-turn-05', speaker: 'A', text: '예쁘지만 조금 비싸요. 깎아 주세요.', translationVi: '(yeppeujiman jogeum bissayo. kkakka juseyo.) Đẹp nhưng hơi đắt. Bớt cho tôi nhé.' },
      { id: 'ko-a2-shop-turn-06', speaker: 'B', text: '알겠어요, 조금 깎아 드릴게요.', translationVi: '(algesseoyo, jogeum kkakka deurilgeyo.) Được, tôi sẽ bớt một chút.' },
      { id: 'ko-a2-shop-turn-07', speaker: 'A', text: '감사합니다. 현금으로 계산할게요.', translationVi: '(gamsahamnida. hyeongeumeuro gyesanhalgeyo.) Cảm ơn. Tôi trả tiền mặt.' },
      { id: 'ko-a2-shop-turn-08', speaker: 'B', text: '네, 여기 계산서예요.', translationVi: '(ne, yeogi gyesanseoyeyo.) Vâng, đây là hoá đơn của bạn.' },
    ],
    relatedVocabularyIds: ['ko-a2-l2-2-v1', 'ko-a2-l2-2-v2', 'ko-a2-l2-2-v4', 'ko-a2-l2-2-v5'],
    task: {
      type: 'choose-reply',
      promptVi: "Nhân viên hỏi '입어 보실래요?'. Bạn muốn thử, trả lời thế nào?",
      options: [
        { id: 'o1', text: '네, 좋아요.' },
        { id: 'o2', text: '얼마나 걸려요?' },
        { id: 'o3', text: '계산서 주세요.' },
        { id: 'o4', text: '작년에 여행했어요.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Đồng ý làm gì đó, cách trả lời tự nhiên và lịch sự nhất là '네, 좋아요.'",
    },
  },
  {
    id: 'ko-a2-conv-making-plans',
    languageCode: 'ko',
    level: 'A2',
    title: '계획 세우기',
    titleVi: 'Lên kế hoạch và mời bạn',
    descriptionVi: 'Luyện hội thoại mời bạn bè và nói về kế hoạch tương lai bằng tiếng Hàn.',
    contextVi: 'Minh mời An đi xem phim vào cuối tuần.',
    dialogue: [
      { id: 'ko-a2-plans-turn-01', speaker: 'A', text: '이번 주말에 영화 같이 보실래요?', translationVi: '(ibeon jumare yeonghwa gachi bosillaeyo?) Cuối tuần này bạn có muốn xem phim cùng tôi không?' },
      { id: 'ko-a2-plans-turn-02', speaker: 'B', text: '좋아요! 몇 시예요?', translationVi: '(joayo! myeot siyeyo?) Được đấy! Mấy giờ vậy?' },
      { id: 'ko-a2-plans-turn-03', speaker: 'A', text: '저녁 일곱 시 표를 예매할 거예요.', translationVi: '(jeonyeok ilgop si pyoreul yemaehal geoyeyo.) Tôi sẽ đặt vé lúc 7 giờ tối.' },
      { id: 'ko-a2-plans-turn-04', speaker: 'B', text: '좋아요, 거기서 만나요.', translationVi: '(joayo, geogiseo mannayo.) Được, gặp nhau ở đó nhé.' },
      { id: 'ko-a2-plans-turn-05', speaker: 'A', text: '새 액션 영화 봤어요?', translationVi: '(sae aeksyeon yeonghwa bwasseoyo?) Bạn đã xem phim hành động mới chưa?' },
      { id: 'ko-a2-plans-turn-06', speaker: 'B', text: '아직요. 재미있다고 들었어요.', translationVi: '(ajigyo. jaemiitdago deureosseoyo.) Chưa. Tôi nghe nói hay lắm.' },
      { id: 'ko-a2-plans-turn-07', speaker: 'A', text: '그런데 다음 달에도 시간 있어요?', translationVi: '(geureonde daeum dareado sigan isseoyo?) À, tháng sau bạn có rảnh không?' },
      { id: 'ko-a2-plans-turn-08', speaker: 'B', text: '미안하지만 못 가요. 여행 갈 거예요.', translationVi: '(mianhajiman mot gayo. yeohaeng gal geoyeyo.) Xin lỗi nhưng tôi không đi được. Tôi sẽ đi du lịch.' },
    ],
    relatedVocabularyIds: ['ko-a2-l3-2-v1', 'ko-a2-l3-2-v2', 'ko-a2-l3-2-v3', 'ko-a2-l3-2-v4'],
    task: {
      type: 'complete-reply',
      promptVi: "Hoàn thành câu trả lời phù hợp cho lời mời '같이 보실래요?'",
      options: [
        { id: 'o1', text: '좋아요, 갈게요.' },
        { id: 'o2', text: '이거 얼마예요?' },
        { id: 'o3', text: '지하철을 타요.' },
        { id: 'o4', text: '몇 시예요?' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi nhận lời mời một cách vui vẻ, cách trả lời tự nhiên là '좋아요, 갈게요.'",
    },
  },
];
