import type { GrammarTopic } from '../../types';

export const koreanA2GrammarTopics: GrammarTopic[] = [
  {
    id: 'ko-a2-gr-past-tense',
    languageCode: 'ko',
    level: 'A2',
    title: '았/었어요',
    titleVi: 'Thì quá khứ 았/었어요',
    explanationVi:
      "았/었어요 là đuôi quá khứ lịch sự. Gốc động từ có nguyên âm cuối ㅏ/ㅗ dùng 았어요, các nguyên âm khác dùng 었어요. 하다 đổi thành 했어요.",
    structure: '어간(ㅏ/ㅗ) + 았어요 / 어간(khác) + 었어요 / 하다 → 했어요',
    keyPoints: ['가다 → 갔어요', '먹다 → 먹었어요', '하다 → 했어요 (bất quy tắc thường gặp)'],
    examples: [
      { id: 'ko-a2-gr-past-s1', text: '어제 학교에 갔어요.', translationVi: 'Hôm qua tôi đã đi học.' },
      { id: 'ko-a2-gr-past-s2', text: '점심을 먹었어요.', translationVi: 'Tôi đã ăn trưa.' },
      { id: 'ko-a2-gr-past-s3', text: '어제 숙제를 했어요.', translationVi: 'Hôm qua tôi đã làm bài tập.' },
    ],
    commonMistakesVi: "Người mới học hay quên đổi 하다 thành 했어요 mà chia theo quy tắc thông thường.",
    exercises: [
      {
        id: 'ko-a2-gr-past-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng quá khứ đúng của '가다'.",
        question: '가다 → 어제 학교에 ___.',
        options: ['가요', '갔어요', '가서', '갈 거예요'],
        correctOptionIndex: 1,
        explanationVi: '가다 có nguyên âm cuối ㅏ nên dùng 았어요 → 갔어요.',
      },
      {
        id: 'ko-a2-gr-past-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng quá khứ đúng của '하다'.",
        sentenceTemplate: '어제 숙제를 ___.',
        wordBank: ['했어요', '하요', '할 거예요'],
        correctAnswer: '했어요',
        explanationVi: '하다 luôn đổi thành 했어요 ở thì quá khứ.',
      },
      {
        id: 'ko-a2-gr-past-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đã ăn trưa."',
        words: ['먹었어요', '점심을', '저는'],
        correctOrder: ['저는', '점심을', '먹었어요'],
      },
    ],
  },
  {
    id: 'ko-a2-gr-present-progressive',
    languageCode: 'ko',
    level: 'A2',
    title: '고 있어요',
    titleVi: 'Hành động đang diễn ra 고 있어요',
    explanationVi: "고 있어요 gắn trực tiếp vào gốc động từ để diễn tả hành động đang diễn ra, tương đương '-ing' trong tiếng Anh.",
    structure: '동사 어간 + 고 있어요',
    keyPoints: ['먹다 → 먹고 있어요 (đang ăn)', '가다 → 가고 있어요 (đang đi)', "Không đổi theo nguyên âm cuối, luôn thêm trực tiếp 고 있어요"],
    examples: [
      { id: 'ko-a2-gr-prog-s1', text: '저는 지금 공부하고 있어요.', translationVi: 'Tôi đang học bây giờ.' },
      { id: 'ko-a2-gr-prog-s2', text: '그는 밥을 먹고 있어요.', translationVi: 'Anh ấy đang ăn cơm.' },
      { id: 'ko-a2-gr-prog-s3', text: '우리는 영화를 보고 있어요.', translationVi: 'Chúng tôi đang xem phim.' },
    ],
    commonMistakesVi: "Người mới học hay nhầm 고 있어요 (đang làm) với 았/었어요 (đã làm) vì cả hai đều thêm vào gốc động từ.",
    exercises: [
      {
        id: 'ko-a2-gr-prog-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: hành động đang diễn ra.',
        question: '저는 지금 공부___.',
        options: ['했어요', '하고 있어요', '할 거예요', '해서'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-a2-gr-prog-ex2',
        type: 'fill-blank',
        promptVi: 'Điền dạng đúng.',
        sentenceTemplate: '그는 밥을 먹___ 있어요.',
        wordBank: ['고', '어서', '지만'],
        correctAnswer: '고',
      },
      {
        id: 'ko-a2-gr-prog-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Chúng tôi đang xem phim."',
        words: ['보고 있어요', '영화를', '우리는'],
        correctOrder: ['우리는', '영화를', '보고 있어요'],
      },
    ],
  },
  {
    id: 'ko-a2-gr-future',
    languageCode: 'ko',
    level: 'A2',
    title: '-(으)ㄹ 거예요',
    titleVi: 'Thì tương lai -(으)ㄹ 거예요',
    explanationVi:
      "-(으)ㄹ 거예요 diễn tả dự định/kế hoạch trong tương lai. Gốc động từ kết thúc phụ âm thêm 을 거예요, kết thúc nguyên âm thêm ㄹ 거예요.",
    structure: '어간(phụ âm) + 을 거예요 / 어간(nguyên âm) + ㄹ 거예요',
    keyPoints: ['먹다 → 먹을 거예요', '가다 → 갈 거예요', 'Dùng cho dự định đã nghĩ tới, không phải quyết định tức thời'],
    examples: [
      { id: 'ko-a2-gr-future-s1', text: '내일 저는 여행 갈 거예요.', translationVi: 'Ngày mai tôi sẽ đi du lịch.' },
      { id: 'ko-a2-gr-future-s2', text: '저는 저녁에 운동할 거예요.', translationVi: 'Tối nay tôi sẽ tập thể dục.' },
      { id: 'ko-a2-gr-future-s3', text: '다음 주에 시험이 있을 거예요.', translationVi: 'Tuần sau sẽ có kỳ thi.' },
    ],
    commonMistakesVi: "Người mới học hay quên phân biệt 을 거예요 (sau phụ âm) và 거예요 (sau nguyên âm, gắn ㄹ vào gốc).",
    exercises: [
      {
        id: 'ko-a2-gr-future-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng tương lai đúng của '가다'.",
        question: '내일 저는 여행 ___. (가다)',
        options: ['가요', '갔어요', '갈 거예요', '가고 있어요'],
        correctOptionIndex: 2,
      },
      {
        id: 'ko-a2-gr-future-ex2',
        type: 'fill-blank',
        promptVi: "Điền dạng tương lai đúng của '먹다'.",
        sentenceTemplate: '내일 저녁을 ___.',
        wordBank: ['먹을 거예요', '먹어요', '먹었어요'],
        correctAnswer: '먹을 거예요',
      },
      {
        id: 'ko-a2-gr-future-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tối nay tôi sẽ tập thể dục."',
        words: ['운동할 거예요', '저녁에', '저는'],
        correctOrder: ['저는', '저녁에', '운동할 거예요'],
      },
    ],
  },
  {
    id: 'ko-a2-gr-aseo',
    languageCode: 'ko',
    level: 'A2',
    title: '아/어서',
    titleVi: 'Nối câu nguyên nhân-kết quả 아/어서',
    explanationVi:
      "아/어서 nối hai vế câu theo quan hệ nguyên nhân-kết quả hoặc trình tự. Nguyên âm cuối ㅏ/ㅗ dùng 아서, còn lại dùng 어서.",
    structure: '어간(ㅏ/ㅗ) + 아서 / 어간(khác) + 어서',
    keyPoints: ['비가 와서 못 갔어요 (Vì trời mưa nên không đi được)', '피곤해서 일찍 잤어요 (Vì mệt nên đã ngủ sớm)', 'Vế sau KHÔNG dùng dạng mệnh lệnh/đề nghị với 아/어서'],
    examples: [
      { id: 'ko-a2-gr-aseo-s1', text: '시간이 없어서 못 갔어요.', translationVi: 'Vì không có thời gian nên tôi đã không đi được.' },
      { id: 'ko-a2-gr-aseo-s2', text: '피곤해서 일찍 잤어요.', translationVi: 'Vì mệt nên tôi đã ngủ sớm.' },
      { id: 'ko-a2-gr-aseo-s3', text: '배가 고파서 밥을 먹었어요.', translationVi: 'Vì đói bụng nên tôi đã ăn cơm.' },
    ],
    commonMistakesVi: "Người mới học hay dùng 아/어서 với câu mệnh lệnh ở vế sau, điều này không đúng ngữ pháp trong tiếng Hàn chuẩn.",
    exercises: [
      {
        id: 'ko-a2-gr-aseo-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ nối đúng cho 'vì mệt nên...'.",
        question: '피곤___ 일찍 잤어요.',
        options: ['해서', '지만', '보다'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-a2-gr-aseo-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ nối còn thiếu.',
        sentenceTemplate: '배가 고파___ 밥을 먹었어요.',
        wordBank: ['서', '지만', '고'],
        correctAnswer: '서',
      },
      {
        id: 'ko-a2-gr-aseo-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Vì không có thời gian nên tôi đã không đi được."',
        words: ['못 갔어요', '시간이', '없어서'],
        correctOrder: ['시간이', '없어서', '못 갔어요'],
      },
    ],
  },
  {
    id: 'ko-a2-gr-jiman',
    languageCode: 'ko',
    level: 'A2',
    title: '지만',
    titleVi: 'Nối câu đối lập 지만',
    explanationVi: "지만 nghĩa là 'nhưng', nối hai vế câu có ý đối lập, gắn trực tiếp vào gốc động từ/tính từ.",
    structure: '어간 + 지만',
    keyPoints: ['예쁘지만 비싸요 (Đẹp nhưng đắt)', '맵지만 맛있어요 (Cay nhưng ngon)', 'Dùng được với cả động từ và tính từ'],
    examples: [
      { id: 'ko-a2-gr-jiman-s1', text: '예쁘지만 비싸요.', translationVi: 'Đẹp nhưng đắt.' },
      { id: 'ko-a2-gr-jiman-s2', text: '맵지만 맛있어요.', translationVi: 'Cay nhưng ngon.' },
      { id: 'ko-a2-gr-jiman-s3', text: '피곤하지만 일해야 해요.', translationVi: 'Mệt nhưng tôi phải làm việc.' },
    ],
    commonMistakesVi: "Người mới học hay nhầm 지만 (nhưng) với 아/어서 (vì nên) do cả hai đều nối 2 vế câu.",
    exercises: [
      {
        id: 'ko-a2-gr-jiman-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn từ nối đúng cho 'cay nhưng ngon'.",
        question: '맵___ 맛있어요.',
        options: ['지만', '어서', '보다'],
        correctOptionIndex: 0,
      },
      {
        id: 'ko-a2-gr-jiman-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ nối còn thiếu.',
        sentenceTemplate: '예쁘___ 비싸요.',
        wordBank: ['지만', '고', '서'],
        correctAnswer: '지만',
      },
      {
        id: 'ko-a2-gr-jiman-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Mệt nhưng tôi phải làm việc."',
        words: ['일해야 해요', '피곤하지만'],
        correctOrder: ['피곤하지만', '일해야 해요'],
      },
    ],
  },
];
