import type { GrammarTopic } from '../types';

export const japaneseA1GrammarTopics: GrammarTopic[] = [
  {
    id: 'ja-gr-desu',
    languageCode: 'ja',
    level: 'A1',
    title: 'です (desu)',
    titleVi: 'Đuôi câu "です" (là...)',
    explanationVi:
      "です là dạng lịch sự của động từ 'là', đặt ở CUỐI câu (khác tiếng Việt/Anh đặt động từ ở giữa câu), dùng để giới thiệu, mô tả danh tính hoặc tính chất.",
    structure: 'Chủ ngữ + は + Danh từ/Tính từ + です',
    keyPoints: [
      '私は学生です。(Watashi wa gakusei desu.) - Tôi là sinh viên.',
      'です luôn đứng CUỐI câu, không đứng giữa như tiếng Anh/Việt',
      'Phủ định: Danh từ + じゃありません (hoặc ではありません, trang trọng hơn)',
    ],
    examples: [
      { id: 'ja-gr-desu-s1', text: '私は学生です。', translationVi: '(Watashi wa gakusei desu.) Tôi là sinh viên.' },
      { id: 'ja-gr-desu-s2', text: 'これは本です。', translationVi: '(Kore wa hon desu.) Đây là quyển sách.' },
      { id: 'ja-gr-desu-s3', text: '彼女は先生です。', translationVi: '(Kanojo wa sensei desu.) Cô ấy là giáo viên.' },
    ],
    commonMistakesVi: "Người mới học hay đặt です ở giữa câu theo thói quen tiếng Việt/Anh, thay vì đặt ở cuối câu.",
    exercises: [
      {
        id: 'ja-gr-desu-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn vị trí đúng của です trong câu "Tôi là sinh viên".',
        question: '正しい文を選んでください。',
        options: ['私は学生です。', '私はです学生。', 'です私は学生。', '学生です私は。'],
        correctOptionIndex: 0,
        explanationVi: 'です luôn đứng cuối câu.',
      },
      {
        id: 'ja-gr-desu-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu vào câu.',
        sentenceTemplate: 'これは本___。',
        wordBank: ['です', 'は', 'から'],
        correctAnswer: 'です',
        explanationVi: 'です đặt cuối câu để hoàn thành câu khẳng định lịch sự.',
      },
      {
        id: 'ja-gr-desu-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Cô ấy là giáo viên."',
        words: ['です', '彼女は', '先生'],
        correctOrder: ['彼女は', '先生', 'です'],
        explanationVi: 'Trật tự câu Nhật: Chủ ngữ + は + Bổ ngữ + です.',
      },
    ],
  },
  {
    id: 'ja-gr-wa',
    languageCode: 'ja',
    level: 'A1',
    title: 'は (wa)',
    titleVi: 'Trợ từ chủ đề "は"',
    explanationVi:
      "は (viết bằng chữ HA nhưng khi làm trợ từ thì ĐỌC LÀ 'wa') là trợ từ chủ đề, đặt sau danh từ để đánh dấu đó là chủ đề đang nói tới trong câu.",
    structure: 'Danh từ (chủ đề) + は + ...',
    keyPoints: [
      "は viết bằng chữ は (ha) nhưng đọc là 'wa' khi làm trợ từ — đây là ngoại lệ cần nhớ",
      'Đánh dấu chủ đề của câu, tương tự 은/는 trong tiếng Hàn',
      "Khác trợ từ chủ ngữ が (ga) — が nhấn mạnh thông tin MỚI, は giới thiệu chủ đề CHUNG",
    ],
    examples: [
      { id: 'ja-gr-wa-s1', text: '私は学生です。', translationVi: '(Watashi wa gakusei desu.) Tôi (nói về tôi) là sinh viên.' },
      { id: 'ja-gr-wa-s2', text: '名前はランです。', translationVi: '(Namae wa Ran desu.) (Về) tên (thì) là Lan.' },
      { id: 'ja-gr-wa-s3', text: '今日は天気がいいです。', translationVi: '(Kyou wa tenki ga ii desu.) Hôm nay thời tiết đẹp.' },
    ],
    commonMistakesVi: "Người mới học thường đọc nhầm は thành 'ha' thay vì 'wa' khi nó làm trợ từ chủ đề.",
    exercises: [
      {
        id: 'ja-gr-wa-ex1',
        type: 'multiple-choice',
        promptVi: "Khi làm trợ từ, は được đọc là gì?",
        question: 'は as a particle is pronounced...',
        options: ['ha', 'wa', 'ba', 'pa'],
        correctOptionIndex: 1,
        explanationVi: "は khi làm trợ từ chủ đề luôn đọc là 'wa'.",
      },
      {
        id: 'ja-gr-wa-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ chủ đề còn thiếu.',
        sentenceTemplate: '私___学生です。',
        wordBank: ['は', 'を', 'に'],
        correctAnswer: 'は',
        explanationVi: 'は đứng sau danh từ chủ đề 私 (tôi).',
      },
      {
        id: 'ja-gr-wa-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi là người Việt Nam."',
        words: ['です', '私は', 'ベトナム人'],
        correctOrder: ['私は', 'ベトナム人', 'です'],
        explanationVi: 'Trật tự: Chủ đề(は) + Bổ ngữ + です.',
      },
    ],
  },
  {
    id: 'ja-gr-no',
    languageCode: 'ja',
    level: 'A1',
    title: 'の (no)',
    titleVi: 'Trợ từ sở hữu "の"',
    explanationVi: "の là trợ từ sở hữu, đặt giữa người/vật sở hữu và danh từ được sở hữu, tương đương 's trong tiếng Anh hoặc 'của' trong tiếng Việt.",
    structure: 'Người/vật sở hữu + の + Danh từ',
    keyPoints: [
      '私の名前 (watashi no namae) - tên của tôi',
      "Đặt SAU người sở hữu, TRƯỚC danh từ được sở hữu",
      'Có thể nối nhiều lần liên tiếp: 私の母の名前 (tên của mẹ tôi)',
    ],
    examples: [
      { id: 'ja-gr-no-s1', text: 'これは私の家族です。', translationVi: '(Kore wa watashi no kazoku desu.) Đây là gia đình của tôi.' },
      { id: 'ja-gr-no-s2', text: '彼女の母は先生です。', translationVi: '(Kanojo no haha wa sensei desu.) Mẹ của cô ấy là giáo viên.' },
      { id: 'ja-gr-no-s3', text: 'これは私の名前です。', translationVi: '(Kore wa watashi no namae desu.) Đây là tên của tôi.' },
    ],
    commonMistakesVi: 'Người mới học thường quên の hoặc đặt sai vị trí khi ghép hai danh từ theo quan hệ sở hữu.',
    exercises: [
      {
        id: 'ja-gr-no-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cách nói đúng "tên của tôi".',
        question: '正しい言い方を選んでください。',
        options: ['私の名前', '名前私の', 'の私名前', '私名前の'],
        correctOptionIndex: 0,
        explanationVi: 'Trật tự đúng: Người sở hữu + の + Danh từ.',
      },
      {
        id: 'ja-gr-no-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ sở hữu còn thiếu.',
        sentenceTemplate: 'これは私___家族です。',
        wordBank: ['の', 'は', 'です'],
        correctAnswer: 'の',
        explanationVi: 'の nối giữa người sở hữu (私) và danh từ (家族).',
      },
      {
        id: 'ja-gr-no-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Mẹ của cô ấy là giáo viên."',
        words: ['です', '彼女の', '先生', '母は'],
        correctOrder: ['彼女の', '母は', '先生', 'です'],
        explanationVi: '彼女の母 (mẹ của cô ấy) là cụm chủ ngữ, đứng trước は.',
      },
    ],
  },
];
