import type { ConversationScenario } from '../../types';

export const englishB2ConversationScenarios: ConversationScenario[] = [
  {
    id: 'en-b2-conv-looking-back',
    languageCode: 'en',
    level: 'B2',
    title: 'Looking back on a decision',
    titleVi: 'Nhìn lại một quyết định',
    descriptionVi: 'Luyện hội thoại bày tỏ hối tiếc và giả định phức tạp bằng câu điều kiện loại 3 và cấu trúc wish.',
    contextVi: 'An và Minh đang nói chuyện về quyết định nghỉ việc của An năm ngoái.',
    dialogue: [
      { id: 'en-b2-lookback-turn-01', speaker: 'A', text: "Sometimes I wonder if I made the right choice leaving my old job.", translationVi: 'Đôi khi tôi tự hỏi liệu mình có đưa ra lựa chọn đúng khi rời công việc cũ không.' },
      { id: 'en-b2-lookback-turn-02', speaker: 'B', text: 'If you had stayed, do you think you would be happier now?', translationVi: 'Nếu bạn đã ở lại, bạn nghĩ bây giờ mình sẽ hạnh phúc hơn không?' },
      { id: 'en-b2-lookback-turn-03', speaker: 'A', text: "Honestly, I'm not sure. I wish I had thought it through more carefully.", translationVi: 'Thành thật mà nói, tôi không chắc. Giá như tôi đã suy nghĩ kỹ lưỡng hơn.' },
      { id: 'en-b2-lookback-turn-04', speaker: 'B', text: "If you hadn't quit, you might never have started your own business, though.", translationVi: 'Nhưng nếu bạn đã không nghỉ việc thì có lẽ bạn sẽ không bao giờ khởi nghiệp riêng đâu.' },
      { id: 'en-b2-lookback-turn-05', speaker: 'A', text: "That's true. In hindsight, it may well have been the right decision after all.", translationVi: 'Đúng vậy. Nhìn lại thì có lẽ rốt cuộc đó cũng là quyết định đúng đắn.' },
      { id: 'en-b2-lookback-turn-06', speaker: 'B', text: "Exactly. There's no point dwelling on it — what's done is done.", translationVi: 'Chính xác. Chẳng ích gì khi cứ mãi nghĩ về nó — chuyện đã rồi thì cho qua.' },
      { id: 'en-b2-lookback-turn-07', speaker: 'A', text: 'You\'re right. If I hadn\'t taken that risk, I wouldn\'t have learned so much.', translationVi: 'Bạn nói đúng. Nếu tôi đã không chấp nhận rủi ro đó thì tôi đã không học được nhiều như vậy.' },
      { id: 'en-b2-lookback-turn-08', speaker: 'B', text: "That's a much healthier way to look at it.", translationVi: 'Đó là cách nhìn nhận lành mạnh hơn nhiều.' },
    ],
    relatedVocabularyIds: ['en-b2-l1-1-v3', 'en-b2-l1-3-v1', 'en-b2-l1-3-v9', 'en-b2-l3-2-v1'],
    task: {
      type: 'choose-reply',
      promptVi: "B hỏi 'If you had stayed, do you think you would be happier now?'. Chọn câu trả lời phù hợp nhất, dùng cấu trúc điều kiện hỗn hợp/wish.",
      options: [
        { id: 'o1', text: "Honestly, I'm not sure. I wish I had thought it through more carefully." },
        { id: 'o2', text: 'It is believed that the company will announce layoffs.' },
        { id: 'o3', text: 'The man standing there is my boss.' },
        { id: 'o4', text: 'All things considered, the report was rejected.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "Câu hỏi mời gọi suy ngẫm về một quyết định trong quá khứ, nên trả lời bằng cách bày tỏ hối tiếc/không chắc chắn qua cấu trúc wish.",
    },
  },
  {
    id: 'en-b2-conv-office-rumors',
    languageCode: 'en',
    level: 'B2',
    title: 'Office rumors',
    titleVi: 'Tin đồn ở công ty',
    descriptionVi: 'Luyện hội thoại tường thuật thông tin chưa xác thực bằng câu bị động nâng cao.',
    contextVi: 'Lan và Minh đang bàn tán về tin đồn tái cơ cấu công ty.',
    dialogue: [
      { id: 'en-b2-rumors-turn-01', speaker: 'A', text: 'Have you heard? It is said that the company is planning a restructuring.', translationVi: 'Bạn nghe chưa? Người ta nói rằng công ty đang có kế hoạch tái cơ cấu.' },
      { id: 'en-b2-rumors-turn-02', speaker: 'B', text: 'Really? Where did you hear that?', translationVi: 'Thật sao? Bạn nghe được ở đâu vậy?' },
      { id: 'en-b2-rumors-turn-03', speaker: 'A', text: 'A few people in marketing are said to have already been notified.', translationVi: 'Vài người ở phòng marketing được cho là đã được thông báo rồi.' },
      { id: 'en-b2-rumors-turn-04', speaker: 'B', text: "That's concerning. Is it confirmed, though?", translationVi: 'Nghe cũng đáng lo. Nhưng đã được xác nhận chưa?' },
      { id: 'en-b2-rumors-turn-05', speaker: 'A', text: "No, it's still unconfirmed. It's just speculation for now.", translationVi: 'Chưa, vẫn chưa được xác nhận. Hiện tại chỉ là suy đoán thôi.' },
      { id: 'en-b2-rumors-turn-06', speaker: 'B', text: "The CEO is thought to be making an announcement next week.", translationVi: 'CEO được cho là sẽ đưa ra thông báo vào tuần tới.' },
      { id: 'en-b2-rumors-turn-07', speaker: 'A', text: "Let's not panic. Rumors may well turn out to be wrong.", translationVi: 'Đừng hoảng loạn. Tin đồn rất có thể là sai sự thật.' },
      { id: 'en-b2-rumors-turn-08', speaker: 'B', text: "Good point. We'll know for sure soon enough.", translationVi: 'Nói đúng. Chúng ta sẽ sớm biết chắc chắn thôi.' },
    ],
    relatedVocabularyIds: ['en-b2-l2-1-v1', 'en-b2-l2-1-v3', 'en-b2-l2-1-v9', 'en-b2-l3-2-v1'],
    task: {
      type: 'choose-next-line',
      promptVi: "A vừa nói 'Have you heard? It is said that the company is planning a restructuring.'. Chọn phản hồi tự nhiên nhất.",
      options: [
        { id: 'o1', text: 'Really? Where did you hear that?' },
        { id: 'o2', text: 'If I had known, I would have told you.' },
        { id: 'o3', text: 'The report, the conclusions of which are alarming, was published today.' },
        { id: 'o4', text: "You needn't have worried about the exam." },
      ],
      correctOptionId: 'o1',
      explanationVi: "Khi nghe một tin đồn/thông tin bị động chưa rõ nguồn, phản hồi tự nhiên nhất là hỏi thêm về nguồn tin.",
    },
  },
  {
    id: 'en-b2-conv-team-debate',
    languageCode: 'en',
    level: 'B2',
    title: 'A team debate',
    titleVi: 'Một cuộc tranh luận nhóm',
    descriptionVi: 'Luyện hội thoại tranh luận, liên kết lập luận bằng từ nối diễn ngôn.',
    contextVi: 'Nhóm của An đang tranh luận về việc có nên chuyển sang làm việc từ xa hoàn toàn hay không.',
    dialogue: [
      { id: 'en-b2-debate-turn-01', speaker: 'A', text: "I think we should switch to fully remote work. It would save everyone commuting time.", translationVi: 'Tôi nghĩ chúng ta nên chuyển sang làm việc từ xa hoàn toàn. Nó sẽ tiết kiệm thời gian đi lại cho mọi người.' },
      { id: 'en-b2-debate-turn-02', speaker: 'B', text: 'That sounds appealing; however, it might hurt team collaboration.', translationVi: 'Nghe cũng hấp dẫn đấy; tuy nhiên, nó có thể gây hại cho sự hợp tác nhóm.' },
      { id: 'en-b2-debate-turn-03', speaker: 'A', text: "That's a fair concern. Moreover, some employees prefer working from an office anyway.", translationVi: 'Đó là một mối lo hợp lý. Hơn nữa, một số nhân viên vẫn thích làm việc tại văn phòng hơn.' },
      { id: 'en-b2-debate-turn-04', speaker: 'B', text: "On the contrary, our recent survey showed most people want more flexibility.", translationVi: 'Ngược lại, khảo sát gần đây của chúng ta cho thấy phần lớn mọi người muốn có sự linh hoạt hơn.' },
      { id: 'en-b2-debate-turn-05', speaker: 'A', text: "In light of that data, maybe a hybrid model would work better.", translationVi: 'Xét đến dữ liệu đó, có lẽ mô hình kết hợp sẽ hiệu quả hơn.' },
      { id: 'en-b2-debate-turn-06', speaker: 'B', text: "I agree. That said, we still need clear guidelines on office days.", translationVi: 'Tôi đồng ý. Dù vậy, chúng ta vẫn cần quy định rõ ràng về những ngày lên văn phòng.' },
      { id: 'en-b2-debate-turn-07', speaker: 'A', text: "Consequently, I'll draft a proposal for a hybrid schedule this week.", translationVi: 'Do đó, tuần này tôi sẽ soạn một đề xuất về lịch làm việc kết hợp.' },
      { id: 'en-b2-debate-turn-08', speaker: 'B', text: "Sounds good. All things considered, that seems like the fairest option.", translationVi: 'Nghe hay đấy. Xét mọi mặt thì, đó có vẻ là lựa chọn công bằng nhất.' },
    ],
    relatedVocabularyIds: ['en-b2-l3-1-v1', 'en-b2-l3-1-v3', 'en-b2-l3-1-v5', 'en-b2-l3-1-v13'],
    task: {
      type: 'choose-polite-version',
      promptVi: "Bạn muốn phản bác nhẹ nhàng nhưng rõ ràng một ý kiến trong cuộc họp, dựa trên dữ liệu thực tế. Chọn câu phù hợp nhất.",
      options: [
        { id: 'o1', text: 'On the contrary, our recent survey showed most people want more flexibility.' },
        { id: 'o2', text: "That's completely wrong, the survey proves it." },
        { id: 'o3', text: "I don't agree with you at all." },
        { id: 'o4', text: 'Your idea makes no sense.' },
      ],
      correctOptionId: 'o1',
      explanationVi: "'On the contrary' cho phép phản bác một cách trang trọng, dẫn chứng bằng dữ liệu thay vì phủ nhận trực tiếp gây mất lịch sự.",
    },
  },
];
