import type { Lesson } from '../../../types';

export const koreanA2DailyLifeLessons: Lesson[] = [
  {
    id: 'ko-a2-l1-1-daily-routine',
    unitId: 'ko-a2-u1-daily-life',
    title: '하루 일과',
    titleVi: 'Thói quen hằng ngày',
    objectiveVi: "Mô tả các việc bạn làm hằng ngày và kể lại bằng thì quá khứ 았/었어요.",
    estimatedMinutes: 7,
    grammarNoteVi:
      "았/었어요 là đuôi quá khứ: động từ có nguyên âm cuối là ㅏ/ㅗ dùng 았어요, các trường hợp còn lại dùng 었어요. Ví dụ: 가다→갔어요, 먹다→먹었어요.",
    vocabulary: [
      { id: 'ko-a2-l1-1-v1', term: '일어나다', translationVi: 'Thức dậy', partOfSpeech: 'verb', exampleSentenceId: 'ko-a2-l1-1-s1', usageNoteVi: 'Cách đọc: ireonada' },
      { id: 'ko-a2-l1-1-v2', term: '씻다', translationVi: 'Rửa mặt / tắm rửa', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: ssitda' },
      { id: 'ko-a2-l1-1-v3', term: '출근하다', translationVi: 'Đi làm', partOfSpeech: 'verb', exampleSentenceId: 'ko-a2-l1-1-s2', usageNoteVi: 'Cách đọc: chulgeunhada' },
      { id: 'ko-a2-l1-1-v4', term: '집에 오다', translationVi: 'Về nhà', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: jibe oda' },
      { id: 'ko-a2-l1-1-v5', term: '어제', translationVi: 'Hôm qua', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l1-1-s3', usageNoteVi: 'Cách đọc: eoje' },
      { id: 'ko-a2-l1-1-v6', term: '보통', translationVi: 'Thường thì', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: botong' },
    ],
    sentences: [
      { id: 'ko-a2-l1-1-s1', text: '저는 보통 일곱 시에 일어나요.', translationVi: '(jeoneun botong ilgop sie ireonayo.) Tôi thường thức dậy lúc bảy giờ.' },
      { id: 'ko-a2-l1-1-s2', text: '저는 아홉 시에 출근해요.', translationVi: '(jeoneun ahop sie chulgeunhaeyo.) Tôi đi làm lúc chín giờ.' },
      { id: 'ko-a2-l1-1-s3', text: '어제 저는 여섯 시에 일어났어요.', translationVi: '(eoje jeoneun yeoseot sie ireonasseoyo.) Hôm qua tôi đã thức dậy lúc sáu giờ.' },
    ],
    exercises: [
      {
        id: 'ko-a2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng quá khứ đúng của '일어나다' (thức dậy).",
        question: '일어나다 → 어제 저는 여섯 시에 ___.',
        options: ['일어나요', '일어났어요', '일어나서', '일어나고 있어요'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-a2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '저는 아홉 시에 ___.',
        wordBank: ['출근해요', '씻어요', '어제'],
        correctAnswer: '출근해요',
      },
      {
        id: 'ko-a2-l1-1-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '보통'.",
        question: '보통',
        options: ['Hôm qua', 'Thường thì', 'Hôm nay', 'Ngày mai'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ko-a2-l1-2-time',
    unitId: 'ko-a2-u1-daily-life',
    title: '시간',
    titleVi: 'Giờ giấc',
    objectiveVi: "Nói giờ và hành động đang diễn ra bằng '고 있어요'.",
    estimatedMinutes: 7,
    grammarNoteVi:
      "고 있어요 diễn tả hành động đang diễn ra (tương đương '-ing'). Gắn trực tiếp vào gốc động từ: 먹다→먹고 있어요 (đang ăn).",
    vocabulary: [
      { id: 'ko-a2-l1-2-v1', term: '지금', translationVi: 'Bây giờ', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l1-2-s1', usageNoteVi: 'Cách đọc: jigeum' },
      { id: 'ko-a2-l1-2-v2', term: '몇 시예요?', translationVi: 'Mấy giờ rồi?', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l1-2-s2', usageNoteVi: 'Cách đọc: myeot siyeyo?' },
      { id: 'ko-a2-l1-2-v3', term: '반', translationVi: 'Rưỡi (30 phút)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: ban' },
      { id: 'ko-a2-l1-2-v4', term: '일찍', translationVi: 'Sớm', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: iljjik' },
      { id: 'ko-a2-l1-2-v5', term: '늦게', translationVi: 'Muộn', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l1-2-s3', usageNoteVi: 'Cách đọc: neutge' },
      { id: 'ko-a2-l1-2-v6', term: '벌써', translationVi: 'Đã, rồi (sớm hơn dự kiến)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: beolsseo' },
    ],
    sentences: [
      { id: 'ko-a2-l1-2-s1', text: '지금 몇 시예요?', translationVi: '(jigeum myeot siyeyo?) Bây giờ mấy giờ rồi?' },
      { id: 'ko-a2-l1-2-s2', text: '저는 지금 밥을 먹고 있어요.', translationVi: '(jeoneun jigeum babeul meokgo isseoyo.) Tôi đang ăn cơm bây giờ.' },
      { id: 'ko-a2-l1-2-s3', text: '오늘 저는 늦게 일어났어요.', translationVi: '(oneul jeoneun neutge ireonasseoyo.) Hôm nay tôi đã dậy muộn.' },
    ],
    exercises: [
      {
        id: 'ko-a2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn dạng đúng: hành động đang diễn ra ngay lúc nói.",
        question: '저는 지금 밥을 ___. (먹다)',
        options: ['먹어요', '먹었어요', '먹고 있어요', '먹을 거예요'],
        correctOptionIndex: 2,
      },
      {
        id: 'ko-a2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '지금 몇 ___예요?',
        wordBank: ['시', '반', '늦게'],
        correctAnswer: '시',
      },
      {
        id: 'ko-a2-l1-2-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '일찍'.",
        question: '일찍',
        options: ['Muộn', 'Sớm', 'Bây giờ', 'Đã rồi'],
        correctOptionIndex: 1,
      },
    ],
  },
  {
    id: 'ko-a2-l1-3-hobbies',
    unitId: 'ko-a2-u1-daily-life',
    title: '취미',
    titleVi: 'Sở thích',
    objectiveVi: "Nói về sở thích và so sánh bằng '보다' (hơn).",
    estimatedMinutes: 7,
    grammarNoteVi:
      "보다 gắn sau danh từ để so sánh, nghĩa là 'hơn'. Ví dụ: 저는 영화보다 음악을 더 좋아해요 (Tôi thích âm nhạc hơn phim).",
    vocabulary: [
      { id: 'ko-a2-l1-3-v1', term: '취미', translationVi: 'Sở thích', partOfSpeech: 'noun', exampleSentenceId: 'ko-a2-l1-3-s1', usageNoteVi: 'Cách đọc: chwimi' },
      { id: 'ko-a2-l1-3-v2', term: '음악을 듣다', translationVi: 'Nghe nhạc', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: eumageul deutda' },
      { id: 'ko-a2-l1-3-v3', term: '운동하다', translationVi: 'Tập thể dục', partOfSpeech: 'verb', exampleSentenceId: 'ko-a2-l1-3-s2', usageNoteVi: 'Cách đọc: undonghada' },
      { id: 'ko-a2-l1-3-v4', term: '더', translationVi: 'Hơn, thêm', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l1-3-s3', usageNoteVi: 'Cách đọc: deo' },
      { id: 'ko-a2-l1-3-v5', term: '영화를 보다', translationVi: 'Xem phim', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: yeonghwareul boda' },
    ],
    sentences: [
      { id: 'ko-a2-l1-3-s1', text: '제 취미는 음악을 듣는 거예요.', translationVi: '(je chwimineun eumageul deutneun geoyeyo.) Sở thích của tôi là nghe nhạc.' },
      { id: 'ko-a2-l1-3-s2', text: '저는 매일 운동해요.', translationVi: '(jeoneun maeil undonghaeyo.) Tôi tập thể dục mỗi ngày.' },
      { id: 'ko-a2-l1-3-s3', text: '저는 영화보다 음악을 더 좋아해요.', translationVi: '(jeoneun yeonghwaboda eumageul deo joahaeyo.) Tôi thích âm nhạc hơn phim.' },
    ],
    exercises: [
      {
        id: 'ko-a2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '취미'.",
        question: '취미',
        options: ['Nghề nghiệp', 'Sở thích', 'Gia đình', 'Thời gian'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-a2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu để so sánh.',
        sentenceTemplate: '저는 영화___ 음악을 더 좋아해요.',
        wordBank: ['보다', '에서', '은'],
        correctAnswer: '보다',
      },
      {
        id: 'ko-a2-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi tập thể dục mỗi ngày."',
        words: ['운동해요', '저는', '매일'],
        correctOrder: ['저는', '매일', '운동해요'],
      },
    ],
  },
];
