import type { Lesson } from '../../../types';

export const koreanA2TravelLessons: Lesson[] = [
  {
    id: 'ko-a2-l2-1-transportation',
    unitId: 'ko-a2-u2-travel',
    title: '교통',
    titleVi: 'Phương tiện giao thông',
    objectiveVi: "Nói cách di chuyển và dùng trợ từ '에서...까지' (từ...đến).",
    estimatedMinutes: 7,
    grammarNoteVi:
      "에서...까지 nghĩa là 'từ...đến', dùng để chỉ điểm bắt đầu và điểm kết thúc. Ví dụ: 집에서 회사까지 (từ nhà đến công ty).",
    vocabulary: [
      { id: 'ko-a2-l2-1-v1', term: '지하철', translationVi: 'Tàu điện ngầm', partOfSpeech: 'noun', exampleSentenceId: 'ko-a2-l2-1-s1', usageNoteVi: 'Cách đọc: jihacheol' },
      { id: 'ko-a2-l2-1-v2', term: '버스', translationVi: 'Xe buýt', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: beoseu' },
      { id: 'ko-a2-l2-1-v3', term: '타다', translationVi: 'Đi (phương tiện), lên xe', partOfSpeech: 'verb', exampleSentenceId: 'ko-a2-l2-1-s2', usageNoteVi: 'Cách đọc: tada' },
      { id: 'ko-a2-l2-1-v4', term: '얼마나 걸려요?', translationVi: 'Mất bao lâu?', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l2-1-s3', usageNoteVi: 'Cách đọc: eolmana geollyeoyo?' },
      { id: 'ko-a2-l2-1-v5', term: '역', translationVi: 'Ga (tàu điện)', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: yeok' },
      { id: 'ko-a2-l2-1-v6', term: '갈아타다', translationVi: 'Chuyển tuyến, đổi xe', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc: garatada' },
    ],
    sentences: [
      { id: 'ko-a2-l2-1-s1', text: '저는 지하철을 타요.', translationVi: '(jeoneun jihacheoreul tayo.) Tôi đi tàu điện ngầm.' },
      { id: 'ko-a2-l2-1-s2', text: '역에서 버스로 갈아타세요.', translationVi: '(yeogeseo beoseuro garatasseyo.) Hãy chuyển sang xe buýt ở ga.' },
      { id: 'ko-a2-l2-1-s3', text: '집에서 회사까지 얼마나 걸려요?', translationVi: '(jibeseo hoesakkaji eolmana geollyeoyo?) Từ nhà đến công ty mất bao lâu?' },
    ],
    exercises: [
      {
        id: 'ko-a2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '지하철'.",
        question: '지하철',
        options: ['Xe buýt', 'Tàu điện ngầm', 'Taxi', 'Xe đạp'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-a2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: "Điền trợ từ 'từ...đến' còn thiếu.",
        sentenceTemplate: '집___ 회사까지 얼마나 걸려요?',
        wordBank: ['에서', '은', '가'],
        correctAnswer: '에서',
      },
      {
        id: 'ko-a2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đi tàu điện ngầm."',
        words: ['타요', '저는', '지하철을'],
        correctOrder: ['저는', '지하철을', '타요'],
      },
    ],
  },
  {
    id: 'ko-a2-l2-2-shopping',
    unitId: 'ko-a2-u2-travel',
    title: '쇼핑',
    titleVi: 'Mua sắm',
    objectiveVi: 'Hỏi giá và mặc cả khi mua sắm.',
    estimatedMinutes: 7,
    grammarNoteVi:
      "지만 nghĩa là 'nhưng', nối hai vế câu có ý đối lập. Ví dụ: 예쁘지만 비싸요 (Đẹp nhưng đắt).",
    vocabulary: [
      { id: 'ko-a2-l2-2-v1', term: '얼마예요?', translationVi: 'Bao nhiêu tiền?', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l2-2-s1', usageNoteVi: 'Cách đọc: eolmayeyo?' },
      { id: 'ko-a2-l2-2-v2', term: '비싸다', translationVi: 'Đắt', partOfSpeech: 'adjective', exampleSentenceId: 'ko-a2-l2-2-s2', usageNoteVi: 'Cách đọc: bissada' },
      { id: 'ko-a2-l2-2-v3', term: '싸다', translationVi: 'Rẻ', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc: ssada' },
      { id: 'ko-a2-l2-2-v4', term: '깎아 주세요', translationVi: 'Bớt giá giúp tôi', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l2-2-s3', usageNoteVi: 'Cách đọc: kkakka juseyo' },
      { id: 'ko-a2-l2-2-v5', term: '입어 보다', translationVi: 'Mặc thử', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc: ibeo boda' },
    ],
    sentences: [
      { id: 'ko-a2-l2-2-s1', text: '이거 얼마예요?', translationVi: '(igeo eolmayeyo?) Cái này bao nhiêu tiền?' },
      { id: 'ko-a2-l2-2-s2', text: '예쁘지만 조금 비싸요.', translationVi: '(yeppeujiman jogeum bissayo.) Đẹp nhưng hơi đắt.' },
      { id: 'ko-a2-l2-2-s3', text: '조금 깎아 주세요.', translationVi: '(jogeum kkakka juseyo.) Bớt một chút cho tôi nhé.' },
    ],
    exercises: [
      {
        id: 'ko-a2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '비싸다'.",
        question: '비싸다',
        options: ['Rẻ', 'Đắt', 'Đẹp', 'Nhỏ'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-a2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: "Điền từ nối 'nhưng' còn thiếu.",
        sentenceTemplate: '예쁘___ 비싸요.',
        wordBank: ['지만', '에서', '보다'],
        correctAnswer: '지만',
      },
      {
        id: 'ko-a2-l2-2-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để hỏi giá.',
        question: '가격을 물어보는 올바른 질문은?',
        options: ['이거 얼마예요?', '지금 몇 시예요?', '어디에서 왔어요?', '취미가 뭐예요?'],
        correctOptionIndex: 0,
      },
    ],
  },
  {
    id: 'ko-a2-l2-3-food',
    unitId: 'ko-a2-u2-travel',
    title: '음식 주문',
    titleVi: 'Gọi món ăn',
    objectiveVi: "Gọi món tại nhà hàng bằng '...주세요' (cho tôi...).",
    estimatedMinutes: 7,
    grammarNoteVi: "...주세요 gắn sau danh từ để yêu cầu lịch sự, nghĩa là 'cho tôi...'. Ví dụ: 물 주세요 (Cho tôi nước).",
    vocabulary: [
      { id: 'ko-a2-l2-3-v1', term: '메뉴', translationVi: 'Thực đơn', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: menyu' },
      { id: 'ko-a2-l2-3-v2', term: '추천하다', translationVi: 'Gợi ý, đề xuất', partOfSpeech: 'verb', exampleSentenceId: 'ko-a2-l2-3-s1', usageNoteVi: 'Cách đọc: chucheonhada' },
      { id: 'ko-a2-l2-3-v3', term: '맵다', translationVi: 'Cay', partOfSpeech: 'adjective', exampleSentenceId: 'ko-a2-l2-3-s2', usageNoteVi: 'Cách đọc: maepda' },
      { id: 'ko-a2-l2-3-v4', term: '주세요', translationVi: 'Cho tôi... (yêu cầu lịch sự)', partOfSpeech: 'phrase', exampleSentenceId: 'ko-a2-l2-3-s3', usageNoteVi: 'Cách đọc: juseyo' },
      { id: 'ko-a2-l2-3-v5', term: '계산서', translationVi: 'Hoá đơn', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc: gyesanseo' },
    ],
    sentences: [
      { id: 'ko-a2-l2-3-s1', text: '뭘 추천하세요?', translationVi: '(mwol chucheonhaseyo?) Bạn gợi ý món gì?' },
      { id: 'ko-a2-l2-3-s2', text: '이 음식은 매워요?', translationVi: '(i eumsigeun maewoyo?) Món này có cay không?' },
      { id: 'ko-a2-l2-3-s3', text: '계산서 주세요.', translationVi: '(gyesanseo juseyo.) Cho tôi xin hoá đơn.' },
    ],
    exercises: [
      {
        id: 'ko-a2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: "Chọn nghĩa đúng của '맵다'.",
        question: '맵다',
        options: ['Ngọt', 'Cay', 'Mặn', 'Chua'],
        correctOptionIndex: 1,
      },
      {
        id: 'ko-a2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu để yêu cầu lịch sự.',
        sentenceTemplate: '계산서 ___.',
        wordBank: ['주세요', '맵다', '메뉴'],
        correctAnswer: '주세요',
      },
      {
        id: 'ko-a2-l2-3-ex3',
        type: 'multiple-choice',
        promptVi: 'Chọn câu hỏi đúng để xin gợi ý món ăn.',
        question: '메뉴 추천을 물어보는 질문은?',
        options: ['뭘 추천하세요?', '얼마예요?', '몇 시예요?', '어디에서 왔어요?'],
        correctOptionIndex: 0,
      },
    ],
  },
];
