import type { GrammarTopic } from '../types';

export const chineseA1GrammarTopics: GrammarTopic[] = [
  {
    id: 'zh-gr-shi',
    languageCode: 'zh',
    level: 'A1',
    title: '是 (shì)',
    titleVi: 'Động từ "是" (là)',
    explanationVi:
      "是 là động từ 'là' trong tiếng Trung, dùng để nối chủ ngữ với danh từ chỉ danh tính, nghề nghiệp, quốc tịch... Khác với tiếng Anh, 是 KHÔNG chia theo ngôi hay thì — luôn giữ nguyên dạng 是 dù chủ ngữ là ai.",
    structure: 'Chủ ngữ + 是 + Danh từ',
    keyPoints: [
      '我是学生。(Wǒ shì xuésheng.) - Tôi là sinh viên.',
      '是 không đổi dạng theo chủ ngữ (khác am/is/are trong tiếng Anh)',
      'Phủ định: Chủ ngữ + 不是 + Danh từ',
    ],
    examples: [
      { id: 'zh-gr-shi-s1', text: '我是学生。', translationVi: '(Wǒ shì xuésheng.) Tôi là sinh viên.' },
      { id: 'zh-gr-shi-s2', text: '她是老师。', translationVi: '(Tā shì lǎoshī.) Cô ấy là giáo viên.' },
      { id: 'zh-gr-shi-s3', text: '他们是我的朋友。', translationVi: '(Tāmen shì wǒ de péngyou.) Họ là bạn của tôi.' },
    ],
    commonMistakesVi: "Người mới học đôi khi cố chia 是 giống động từ tiếng Anh, hoặc quên dùng 不是 (không phải 不是是) khi phủ định.",
    exercises: [
      {
        id: 'zh-gr-shi-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '我___老师。',
        options: ['是', '不是', '吗', '的'],
        correctOptionIndex: 0,
        explanationVi: "Câu khẳng định dùng 是.",
      },
      {
        id: 'zh-gr-shi-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu (câu phủ định).',
        sentenceTemplate: '我___学生。（我不是学生）',
        wordBank: ['不是', '是', '吗'],
        correctAnswer: '不是',
        explanationVi: 'Phủ định của 是 luôn là 不是.',
      },
      {
        id: 'zh-gr-shi-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Cô ấy là giáo viên."',
        words: ['老师', '她', '是'],
        correctOrder: ['她', '是', '老师'],
        explanationVi: 'Trật tự câu tiếng Trung: Chủ ngữ + 是 + Danh từ.',
      },
    ],
  },
  {
    id: 'zh-gr-ma',
    languageCode: 'zh',
    level: 'A1',
    title: '吗 (ma)',
    titleVi: 'Trợ từ nghi vấn "吗"',
    explanationVi:
      '吗 là trợ từ đặt ở CUỐI câu để biến một câu khẳng định thành câu hỏi có/không (yes/no question), mà không cần thay đổi trật tự từ trong câu — khác hẳn tiếng Anh phải đảo động từ lên đầu câu.',
    structure: 'Câu khẳng định + 吗？',
    keyPoints: [
      '你是学生。(khẳng định) → 你是学生吗？(câu hỏi)',
      'Không cần đảo trật tự từ như tiếng Anh (is he... → he is...)',
      'Trả lời: 是 (đúng) / 不是 (không phải)',
    ],
    examples: [
      { id: 'zh-gr-ma-s1', text: '你是学生吗？', translationVi: '(Nǐ shì xuésheng ma?) Bạn là sinh viên phải không?' },
      { id: 'zh-gr-ma-s2', text: '你好吗？', translationVi: '(Nǐ hǎo ma?) Bạn khỏe không?' },
      { id: 'zh-gr-ma-s3', text: '你是越南人吗？', translationVi: '(Nǐ shì Yuènánrén ma?) Bạn là người Việt Nam phải không?' },
    ],
    commonMistakesVi: "Người mới học hay quên đặt 吗 ở cuối câu, hoặc cố đảo trật tự từ như đặt câu hỏi tiếng Anh.",
    exercises: [
      {
        id: 'zh-gr-ma-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cách đặt câu hỏi đúng từ câu "你是老师" (bạn là giáo viên).',
        question: '你是老师。→ ?',
        options: ['你是老师吗？', '吗你是老师？', '是你老师吗？', '你老师是吗？'],
        correctOptionIndex: 0,
        explanationVi: '吗 luôn đặt ở cuối câu.',
      },
      {
        id: 'zh-gr-ma-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ nghi vấn còn thiếu.',
        sentenceTemplate: '你从越南来___？',
        wordBank: ['吗', '的', '是'],
        correctAnswer: '吗',
        explanationVi: 'Câu hỏi có/không luôn kết thúc bằng 吗.',
      },
      {
        id: 'zh-gr-ma-ex3',
        type: 'multiple-choice',
        promptVi: "Chọn câu trả lời phù hợp cho '你是学生吗？'.",
        question: '你是学生吗？',
        options: ['是，我是学生。', '吗，我是学生。', '好，我是学生。', '的，我是学生。'],
        correctOptionIndex: 0,
        explanationVi: "Trả lời khẳng định cho câu hỏi 吗 bằng 是.",
      },
    ],
  },
  {
    id: 'zh-gr-de',
    languageCode: 'zh',
    level: 'A1',
    title: '的 (de)',
    titleVi: 'Trợ từ sở hữu "的"',
    explanationVi:
      "的 là trợ từ sở hữu, đặt giữa người/vật sở hữu và danh từ được sở hữu, tương đương với 's trong tiếng Anh hoặc 'của' trong tiếng Việt.",
    structure: 'Người/vật sở hữu + 的 + Danh từ',
    keyPoints: [
      '我的名字 (wǒ de míngzi) - tên của tôi',
      "Đặt SAU người sở hữu, TRƯỚC danh từ được sở hữu — ngược trật tự tiếng Việt 'tên của tôi'",
      'Có thể lược bỏ的với quan hệ gia đình/tổ chức rất gần gũi, nhưng ở A1 nên dùng đầy đủ',
    ],
    examples: [
      { id: 'zh-gr-de-s1', text: '这是我的家。', translationVi: '(Zhè shì wǒ de jiā.) Đây là nhà của tôi.' },
      { id: 'zh-gr-de-s2', text: '她的妈妈是老师。', translationVi: '(Tā de māma shì lǎoshī.) Mẹ của cô ấy là giáo viên.' },
      { id: 'zh-gr-de-s3', text: '这是我的名字。', translationVi: '(Zhè shì wǒ de míngzi.) Đây là tên của tôi.' },
    ],
    commonMistakesVi: 'Người mới học thường đặt 的 sai vị trí hoặc quên hẳn 的 khi nói câu sở hữu dài.',
    exercises: [
      {
        id: 'zh-gr-de-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn cách nói đúng "nhà của tôi".',
        question: '选择正确的说法。',
        options: ['我的家', '家我的', '的我家', '我家的'],
        correctOptionIndex: 0,
        explanationVi: 'Trật tự đúng: Người sở hữu + 的 + Danh từ.',
      },
      {
        id: 'zh-gr-de-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ sở hữu còn thiếu.',
        sentenceTemplate: '这是我___爸爸。',
        wordBank: ['的', '是', '吗'],
        correctAnswer: '的',
        explanationVi: '的 nối giữa người sở hữu (我) và danh từ (爸爸).',
      },
      {
        id: 'zh-gr-de-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Mẹ của cô ấy là giáo viên."',
        words: ['老师', '她的', '是', '妈妈'],
        correctOrder: ['她的', '妈妈', '是', '老师'],
        explanationVi: '她的妈妈 (mẹ của cô ấy) là cụm chủ ngữ, đứng trước 是.',
      },
    ],
  },
];
