import type { Lesson } from '../../../types';

export const chineseB2DiscussionConclusionLessons: Lesson[] = [
  {
    id: 'zh-b2-l3-1-jinguan-danshi',
    unitId: 'zh-b2-u3-discussion-conclusion',
    title: '尽管...但是...',
    titleVi: 'Nhượng bộ trang trọng 尽管...但是...',
    objectiveVi: "Diễn tả sự nhượng bộ một cách trang trọng, nhấn mạnh hơn 虽然...但是..., bằng '尽管...但是...'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "尽管 A，但是/可是 B: mặc dù A, nhưng B — trang trọng và nhấn mạnh hơn 虽然...但是..., thường dùng trong văn viết, diễn thuyết, hoặc khi muốn nhấn mạnh sự kiên định dù hoàn cảnh khó khăn.",
    vocabulary: [
      { id: 'zh-b2-l3-1-v1', term: '尽管...但是...', translationVi: 'Mặc dù...nhưng...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): jǐnguǎn...dànshì...' },
      { id: 'zh-b2-l3-1-v2', term: '出发', translationVi: 'Xuất phát', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l3-1-s1', usageNoteVi: 'Cách đọc (pinyin): chūfā' },
      { id: 'zh-b2-l3-1-v3', term: '遇到', translationVi: 'Gặp phải', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l3-1-s2', usageNoteVi: 'Cách đọc (pinyin): yùdào' },
      { id: 'zh-b2-l3-1-v4', term: '从未', translationVi: 'Chưa từng', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-1-s2', usageNoteVi: 'Cách đọc (pinyin): cóngwèi' },
      { id: 'zh-b2-l3-1-v5', term: '放弃', translationVi: 'Từ bỏ', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l3-1-s2', usageNoteVi: 'Cách đọc (pinyin): fàngqì' },
      { id: 'zh-b2-l3-1-v6', term: '年纪', translationVi: 'Tuổi tác', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l3-1-s3', usageNoteVi: 'Cách đọc (pinyin): niánjì' },
      { id: 'zh-b2-l3-1-v7', term: '身体', translationVi: 'Sức khỏe, cơ thể', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l3-1-s3', usageNoteVi: 'Cách đọc (pinyin): shēntǐ' },
      { id: 'zh-b2-l3-1-v8', term: '依然', translationVi: 'Vẫn, vẫn còn', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-1-s3', usageNoteVi: 'Cách đọc (pinyin): yīrán' },
      { id: 'zh-b2-l3-1-v9', term: '坚强', translationVi: 'Kiên cường', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): jiānqiáng' },
      { id: 'zh-b2-l3-1-v10', term: '面对', translationVi: 'Đối mặt', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): miànduì' },
      { id: 'zh-b2-l3-1-v11', term: '挑战', translationVi: 'Thử thách', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l3-1-s5', usageNoteVi: 'Cách đọc (pinyin): tiǎozhàn' },
      { id: 'zh-b2-l3-1-v12', term: '克服', translationVi: 'Khắc phục, vượt qua', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l3-1-s5', usageNoteVi: 'Cách đọc (pinyin): kèfú' },
      { id: 'zh-b2-l3-1-v13', term: '依旧', translationVi: 'Vẫn như cũ', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-1-s4', usageNoteVi: 'Cách đọc (pinyin): yījiù' },
    ],
    sentences: [
      { id: 'zh-b2-l3-1-s1', text: '尽管天气不好，我们还是决定出发。', translationVi: '(Jǐnguǎn tiānqì bù hǎo, wǒmen háishi juédìng chūfā.) Mặc dù thời tiết không tốt, chúng tôi vẫn quyết định xuất phát.' },
      { id: 'zh-b2-l3-1-s2', text: '尽管遇到很多困难，他从未放弃。', translationVi: '(Jǐnguǎn yùdào hěn duō kùnnan, tā cóngwèi fàngqì.) Mặc dù gặp nhiều khó khăn, anh ấy chưa bao giờ từ bỏ.' },
      { id: 'zh-b2-l3-1-s3', text: '尽管年纪大了，他的身体依然很健康。', translationVi: '(Jǐnguǎn niánjì dà le, tā de shēntǐ yīrán hěn jiànkāng.) Mặc dù tuổi đã cao, sức khỏe của ông ấy vẫn rất tốt.' },
      { id: 'zh-b2-l3-1-s4', text: '尽管压力很大，她依旧保持微笑。', translationVi: '(Jǐnguǎn yālì hěn dà, tā yījiù bǎochí wēixiào.) Mặc dù áp lực rất lớn, cô ấy vẫn giữ nụ cười.' },
      { id: 'zh-b2-l3-1-s5', text: '尽管这个挑战很大，我们一定能克服。', translationVi: '(Jǐnguǎn zhège tiǎozhàn hěn dà, wǒmen yídìng néng kèfú.) Mặc dù thử thách này rất lớn, chúng ta chắc chắn có thể vượt qua.' },
    ],
    exercises: [
      {
        id: 'zh-b2-l3-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '___天气不好，我们还是决定出发。',
        options: ['尽管', '无论', '除非', '连'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l3-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '尽管遇到很多困难，他从未___。',
        wordBank: ['放弃', '坚持', '克服'],
        correctAnswer: '放弃',
      },
      {
        id: 'zh-b2-l3-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Mặc dù tuổi đã cao, sức khỏe của ông ấy vẫn rất tốt."',
        words: ['他的身体依然很健康', '尽管年纪大了'],
        correctOrder: ['尽管年纪大了', '他的身体依然很健康'],
      },
    ],
  },
  {
    id: 'zh-b2-l3-2-summary-markers',
    unitId: 'zh-b2-u3-discussion-conclusion',
    title: '总的来说 / 总而言之',
    titleVi: 'Tổng kết lập luận',
    objectiveVi: "Tổng kết, đưa ra kết luận sau khi đã trình bày nhiều ý bằng '总的来说'/'总而言之'/'总之'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "总的来说/总而言之/总之 dùng để tổng kết, đưa ra kết luận sau khi đã trình bày nhiều ý — tương đương 'nhìn chung/tóm lại' trong tiếng Việt, đứng đầu câu và theo sau là dấu phẩy.",
    vocabulary: [
      { id: 'zh-b2-l3-2-v1', term: '总的来说', translationVi: 'Nhìn chung', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-2-s1', usageNoteVi: 'Cách đọc (pinyin): zǒngdeláishuō' },
      { id: 'zh-b2-l3-2-v2', term: '总而言之', translationVi: 'Tóm lại', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-2-s2', usageNoteVi: 'Cách đọc (pinyin): zǒng\'éryánzhī' },
      { id: 'zh-b2-l3-2-v3', term: '总之', translationVi: 'Tóm lại, nói chung', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-2-s3', usageNoteVi: 'Cách đọc (pinyin): zǒngzhī' },
      { id: 'zh-b2-l3-2-v4', term: '换句话说', translationVi: 'Nói cách khác', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-2-s4', usageNoteVi: 'Cách đọc (pinyin): huàn jù huà shuō' },
      { id: 'zh-b2-l3-2-v5', term: '由此可见', translationVi: 'Từ đó có thể thấy', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l3-2-s5', usageNoteVi: 'Cách đọc (pinyin): yóucǐkějiàn' },
      { id: 'zh-b2-l3-2-v6', term: '值得注意的是', translationVi: 'Điều đáng chú ý là', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): zhídé zhùyì de shì' },
      { id: 'zh-b2-l3-2-v7', term: '换言之', translationVi: 'Nói cách khác (trang trọng)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): huànyánzhī' },
      { id: 'zh-b2-l3-2-v8', term: '愉快', translationVi: 'Vui vẻ', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b2-l3-2-s1', usageNoteVi: 'Cách đọc (pinyin): yúkuài' },
      { id: 'zh-b2-l3-2-v9', term: '讨论', translationVi: 'Thảo luận', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l3-2-s2', usageNoteVi: 'Cách đọc (pinyin): tǎolùn' },
      { id: 'zh-b2-l3-2-v10', term: '好处', translationVi: 'Lợi ích', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l3-2-s3', usageNoteVi: 'Cách đọc (pinyin): hǎochù' },
      { id: 'zh-b2-l3-2-v11', term: '综合', translationVi: 'Tổng hợp', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): zōnghé' },
      { id: 'zh-b2-l3-2-v12', term: '观点', translationVi: 'Quan điểm', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): guāndiǎn' },
      { id: 'zh-b2-l3-2-v13', term: '建议', translationVi: 'Đề xuất, kiến nghị', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): jiànyì' },
    ],
    sentences: [
      { id: 'zh-b2-l3-2-s1', text: '总的来说，这次旅行非常愉快。', translationVi: '(Zǒngdeláishuō, zhè cì lǚxíng fēicháng yúkuài.) Nhìn chung, chuyến đi lần này rất vui vẻ.' },
      { id: 'zh-b2-l3-2-s2', text: '总而言之，我们需要更多时间来讨论。', translationVi: '(Zǒng\'éryánzhī, wǒmen xūyào gèng duō shíjiān lái tǎolùn.) Tóm lại, chúng ta cần thêm thời gian để thảo luận.' },
      { id: 'zh-b2-l3-2-s3', text: '总之，这个决定对大家都有好处。', translationVi: '(Zǒngzhī, zhège juédìng duì dàjiā dōu yǒu hǎochù.) Tóm lại, quyết định này có lợi cho tất cả mọi người.' },
      { id: 'zh-b2-l3-2-s4', text: '换句话说，我们必须马上做出选择。', translationVi: '(Huàn jù huà shuō, wǒmen bìxū mǎshàng zuòchū xuǎnzé.) Nói cách khác, chúng ta phải đưa ra lựa chọn ngay lập tức.' },
      { id: 'zh-b2-l3-2-s5', text: '由此可见，努力是成功的关键。', translationVi: '(Yóucǐkějiàn, nǔlì shì chénggōng de guānjiàn.) Từ đó có thể thấy, nỗ lực là chìa khóa của thành công.' },
    ],
    exercises: [
      {
        id: 'zh-b2-l3-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng để mở đầu câu tổng kết.',
        question: '___，这次旅行非常愉快。',
        options: ['总的来说', '无论如何', '除非', '连'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l3-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '___，我们需要更多时间来讨论。',
        wordBank: ['总而言之', '尽管', '虽然'],
        correctAnswer: '总而言之',
      },
      {
        id: 'zh-b2-l3-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Từ đó có thể thấy, nỗ lực là chìa khóa của thành công."',
        words: ['努力是成功的关键', '由此可见'],
        correctOrder: ['由此可见', '努力是成功的关键'],
      },
    ],
  },
];
