import type { Lesson } from '../../../types';

export const chineseB2EmphasisOutcomesLessons: Lesson[] = [
  {
    id: 'zh-b2-l1-1-shi-de',
    unitId: 'zh-b2-u1-emphasis-outcomes',
    title: '是...的',
    titleVi: 'Nhấn mạnh 是...的',
    objectiveVi: "Nhấn mạnh thời gian, địa điểm, cách thức hoặc người thực hiện của một hành động ĐÃ XẢY RA bằng '是...的'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "是...的 dùng để nhấn mạnh THỜI GIAN/ĐỊA ĐIỂM/CÁCH THỨC/NGƯỜI THỰC HIỆN của một hành động đã xảy ra và người nghe đã biết hành động đó xảy ra rồi (không phải hỏi hành động có xảy ra hay không). Cấu trúc: S + 是 + (thông tin cần nhấn mạnh) + V + 的. Ví dụ: 我是昨天来的 (nhấn mạnh 'hôm qua').",
    vocabulary: [
      { id: 'zh-b2-l1-1-v1', term: '是...的', translationVi: 'Nhấn mạnh thời gian/địa điểm/cách thức của hành động đã xảy ra', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): shì...de' },
      { id: 'zh-b2-l1-1-v2', term: '坐飞机', translationVi: 'Đi bằng máy bay', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-1-s2', usageNoteVi: 'Cách đọc (pinyin): zuò fēijī' },
      { id: 'zh-b2-l1-1-v3', term: '出生', translationVi: 'Sinh ra', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): chūshēng' },
      { id: 'zh-b2-l1-1-v4', term: '结婚', translationVi: 'Kết hôn', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): jiéhūn' },
      { id: 'zh-b2-l1-1-v5', term: '毕业', translationVi: 'Tốt nghiệp', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l1-1-s4', usageNoteVi: 'Cách đọc (pinyin): bìyè' },
      { id: 'zh-b2-l1-1-v6', term: '认识', translationVi: 'Quen biết', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l1-1-s3', usageNoteVi: 'Cách đọc (pinyin): rènshi' },
      { id: 'zh-b2-l1-1-v7', term: '特意', translationVi: 'Cố tình, đặc biệt', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): tèyì' },
      { id: 'zh-b2-l1-1-v8', term: '亲自', translationVi: 'Đích thân', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): qīnzì' },
      { id: 'zh-b2-l1-1-v9', term: '顺便', translationVi: 'Tiện thể', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): shùnbiàn' },
      { id: 'zh-b2-l1-1-v10', term: '怎么', translationVi: 'Như thế nào', partOfSpeech: 'pronoun', usageNoteVi: 'Cách đọc (pinyin): zěnme' },
      { id: 'zh-b2-l1-1-v11', term: '什么时候', translationVi: 'Khi nào', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): shénme shíhou' },
      { id: 'zh-b2-l1-1-v12', term: '在哪儿', translationVi: 'Ở đâu', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): zài nǎr' },
      { id: 'zh-b2-l1-1-v13', term: '一个人', translationVi: 'Một mình', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-1-s5', usageNoteVi: 'Cách đọc (pinyin): yí ge rén' },
    ],
    sentences: [
      { id: 'zh-b2-l1-1-s1', text: '我是昨天来的。', translationVi: '(Wǒ shì zuótiān lái de.) Tôi đến vào ngày hôm qua.' },
      { id: 'zh-b2-l1-1-s2', text: '他是坐飞机来的。', translationVi: '(Tā shì zuò fēijī lái de.) Anh ấy đến bằng máy bay.' },
      { id: 'zh-b2-l1-1-s3', text: '我们是在北京认识的。', translationVi: '(Wǒmen shì zài Běijīng rènshi de.) Chúng tôi quen nhau ở Bắc Kinh.' },
      { id: 'zh-b2-l1-1-s4', text: '她是去年毕业的。', translationVi: '(Tā shì qùnián bìyè de.) Cô ấy tốt nghiệp vào năm ngoái.' },
      { id: 'zh-b2-l1-1-s5', text: '你是一个人来的吗？', translationVi: '(Nǐ shì yí ge rén lái de ma?) Bạn đến một mình à?' },
    ],
    exercises: [
      {
        id: 'zh-b2-l1-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng để nhấn mạnh cách thức.',
        question: '他___坐飞机来的。',
        options: ['是', '把', '被', '越'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l1-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '我们是在北京认识___。',
        wordBank: ['的', '了', '过'],
        correctAnswer: '的',
      },
      {
        id: 'zh-b2-l1-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi đến vào ngày hôm qua."',
        words: ['来的', '我是', '昨天'],
        correctOrder: ['我是', '昨天', '来的'],
      },
    ],
  },
  {
    id: 'zh-b2-l1-2-potential-complement',
    unitId: 'zh-b2-u1-emphasis-outcomes',
    title: '可能补语 得/不',
    titleVi: 'Bổ ngữ khả năng 得/不',
    objectiveVi: "Diễn tả khả năng đạt được (hoặc không đạt được) một kết quả bằng cách chèn '得'/'不' vào giữa động từ và bổ ngữ kết quả.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "Chèn 得 (khẳng định: có thể) hoặc 不 (phủ định: không thể) vào giữa động từ và bổ ngữ kết quả/xu hướng: 听懂 (nghe hiểu) → 听得懂/听不懂; 看完 (xem xong) → 看得完/看不完.",
    vocabulary: [
      { id: 'zh-b2-l1-2-v1', term: '听得懂', translationVi: 'Nghe hiểu được', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-2-s1', usageNoteVi: 'Cách đọc (pinyin): tīng de dǒng' },
      { id: 'zh-b2-l1-2-v2', term: '听不懂', translationVi: 'Không nghe hiểu được', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-2-s1', usageNoteVi: 'Cách đọc (pinyin): tīng bu dǒng' },
      { id: 'zh-b2-l1-2-v3', term: '看得完', translationVi: 'Xem/đọc xong được', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): kàn de wán' },
      { id: 'zh-b2-l1-2-v4', term: '看不完', translationVi: 'Không xem/đọc xong được', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-2-s2', usageNoteVi: 'Cách đọc (pinyin): kàn bu wán' },
      { id: 'zh-b2-l1-2-v5', term: '吃得完', translationVi: 'Ăn hết được', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-2-s3', usageNoteVi: 'Cách đọc (pinyin): chī de wán' },
      { id: 'zh-b2-l1-2-v6', term: '做得到', translationVi: 'Làm được', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): zuò de dào' },
      { id: 'zh-b2-l1-2-v7', term: '找得到', translationVi: 'Tìm được', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): zhǎo de dào' },
      { id: 'zh-b2-l1-2-v8', term: '来得及', translationVi: 'Kịp', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-2-s4', usageNoteVi: 'Cách đọc (pinyin): lái de jí' },
      { id: 'zh-b2-l1-2-v9', term: '来不及', translationVi: 'Không kịp', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): lái bu jí' },
      { id: 'zh-b2-l1-2-v10', term: '受得了', translationVi: 'Chịu đựng được', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): shòu de liǎo' },
      { id: 'zh-b2-l1-2-v11', term: '受不了', translationVi: 'Không chịu đựng được', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): shòu bu liǎo' },
      { id: 'zh-b2-l1-2-v12', term: '买得起', translationVi: 'Mua nổi (đủ tiền)', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): mǎi de qǐ' },
      { id: 'zh-b2-l1-2-v13', term: '买不起', translationVi: 'Không mua nổi', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-2-s5', usageNoteVi: 'Cách đọc (pinyin): mǎi bu qǐ' },
    ],
    sentences: [
      { id: 'zh-b2-l1-2-s1', text: '老师说得太快，我听不懂。', translationVi: '(Lǎoshī shuō de tài kuài, wǒ tīng bu dǒng.) Thầy nói nhanh quá, tôi nghe không hiểu.' },
      { id: 'zh-b2-l1-2-s2', text: '这本书太厚了，我今天看不完。', translationVi: '(Zhè běn shū tài hòu le, wǒ jīntiān kàn bu wán.) Cuốn sách này dày quá, hôm nay tôi đọc không xong.' },
      { id: 'zh-b2-l1-2-s3', text: '这么多菜，我们吃得完吗？', translationVi: '(Zhème duō cài, wǒmen chī de wán ma?) Nhiều món ăn như vậy, chúng ta ăn hết được không?' },
      { id: 'zh-b2-l1-2-s4', text: '别担心，还来得及。', translationVi: '(Bié dānxīn, hái lái de jí.) Đừng lo, vẫn còn kịp.' },
      { id: 'zh-b2-l1-2-s5', text: '这个房子太贵了，我买不起。', translationVi: '(Zhège fángzi tài guì le, wǒ mǎi bu qǐ.) Căn nhà này đắt quá, tôi không mua nổi.' },
    ],
    exercises: [
      {
        id: 'zh-b2-l1-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn dạng đúng: không thể hiểu được vì nói quá nhanh.',
        question: '老师说得太快，我___。',
        options: ['听不懂', '听得懂', '听了', '在听'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l1-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền trợ từ còn thiếu (khẳng định: vẫn kịp).',
        sentenceTemplate: '别担心，还来___及。',
        wordBank: ['得', '不', '了'],
        correctAnswer: '得',
      },
      {
        id: 'zh-b2-l1-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Căn nhà này đắt quá, tôi không mua nổi."',
        words: ['我买不起', '这个房子', '太贵了'],
        correctOrder: ['这个房子', '太贵了', '我买不起'],
      },
    ],
  },
  {
    id: 'zh-b2-l1-3-yi-jiu',
    unitId: 'zh-b2-u1-emphasis-outcomes',
    title: '一...就...',
    titleVi: 'Hành động nối tiếp 一...就...',
    objectiveVi: "Diễn tả hai hành động/sự việc xảy ra nối tiếp nhau rất nhanh bằng '一...就...'.",
    estimatedMinutes: 8,
    grammarNoteVi:
      "一 A 就 B: vừa A thì (ngay lập tức) B, diễn tả hai hành động/sự việc xảy ra nối tiếp nhau rất nhanh, hoặc mối quan hệ nhân quả tức thời. Ví dụ: 一到家就洗澡 (vừa về đến nhà là tắm ngay).",
    vocabulary: [
      { id: 'zh-b2-l1-3-v1', term: '一...就...', translationVi: 'Vừa...thì đã...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): yī...jiù...' },
      { id: 'zh-b2-l1-3-v2', term: '到家', translationVi: 'Về đến nhà', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l1-3-s1', usageNoteVi: 'Cách đọc (pinyin): dào jiā' },
      { id: 'zh-b2-l1-3-v3', term: '洗澡', translationVi: 'Tắm', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l1-3-s1', usageNoteVi: 'Cách đọc (pinyin): xǐzǎo' },
      { id: 'zh-b2-l1-3-v4', term: '消息', translationVi: 'Tin tức', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l1-3-s2', usageNoteVi: 'Cách đọc (pinyin): xiāoxi' },
      { id: 'zh-b2-l1-3-v5', term: '堵车', translationVi: 'Kẹt xe', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l1-3-s3', usageNoteVi: 'Cách đọc (pinyin): dǔchē' },
      { id: 'zh-b2-l1-3-v6', term: '马上', translationVi: 'Ngay lập tức', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): mǎshàng' },
      { id: 'zh-b2-l1-3-v7', term: '立刻', translationVi: 'Lập tức', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): lìkè' },
      { id: 'zh-b2-l1-3-v8', term: '起床', translationVi: 'Thức dậy', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): qǐchuáng' },
      { id: 'zh-b2-l1-3-v9', term: '睡着', translationVi: 'Ngủ thiếp đi', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l1-3-s4', usageNoteVi: 'Cách đọc (pinyin): shuìzháo' },
      { id: 'zh-b2-l1-3-v10', term: '躺下', translationVi: 'Nằm xuống', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l1-3-s4', usageNoteVi: 'Cách đọc (pinyin): tǎngxià' },
      { id: 'zh-b2-l1-3-v11', term: '紧张', translationVi: 'Căng thẳng, hồi hộp', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b2-l1-3-s5', usageNoteVi: 'Cách đọc (pinyin): jǐnzhāng' },
      { id: 'zh-b2-l1-3-v12', term: '忘记', translationVi: 'Quên', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l1-3-s5', usageNoteVi: 'Cách đọc (pinyin): wàngjì' },
      { id: 'zh-b2-l1-3-v13', term: '习惯', translationVi: 'Thói quen, quen với', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): xíguàn' },
    ],
    sentences: [
      { id: 'zh-b2-l1-3-s1', text: '我一到家就洗澡。', translationVi: '(Wǒ yí dào jiā jiù xǐzǎo.) Tôi vừa về đến nhà là tắm ngay.' },
      { id: 'zh-b2-l1-3-s2', text: '他一听到消息就哭了。', translationVi: '(Tā yì tīngdào xiāoxi jiù kū le.) Anh ấy vừa nghe tin thì đã khóc.' },
      { id: 'zh-b2-l1-3-s3', text: '一下雨，路上就堵车。', translationVi: '(Yí xiàyǔ, lùshang jiù dǔchē.) Vừa mưa là đường liền kẹt xe.' },
      { id: 'zh-b2-l1-3-s4', text: '我一躺下就睡着了。', translationVi: '(Wǒ yì tǎngxià jiù shuìzháo le.) Tôi vừa nằm xuống là ngủ thiếp đi ngay.' },
      { id: 'zh-b2-l1-3-s5', text: '他一紧张就忘记要说什么。', translationVi: '(Tā yì jǐnzhāng jiù wàngjì yào shuō shénme.) Anh ấy vừa hồi hộp là quên mất mình định nói gì.' },
    ],
    exercises: [
      {
        id: 'zh-b2-l1-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '我一到家___洗澡。',
        options: ['就', '是', '得', '都'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l1-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '一下雨，路上___堵车。',
        wordBank: ['就', '的', '得'],
        correctAnswer: '就',
      },
      {
        id: 'zh-b2-l1-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Anh ấy vừa nghe tin thì đã khóc."',
        words: ['哭了', '他一听到消息就'],
        correctOrder: ['他一听到消息就', '哭了'],
      },
    ],
  },
];
