import type { Lesson } from '../../../types';

export const chineseB2EmphasisConcessionLessons: Lesson[] = [
  {
    id: 'zh-b2-l2-1-lian-dou',
    unitId: 'zh-b2-u2-emphasis-concession',
    title: '连...都/也...',
    titleVi: 'Nhấn mạnh cực đoan 连...都/也...',
    objectiveVi: "Nhấn mạnh một trường hợp cực đoan, không ngờ tới bằng '连...都/也...' (thậm chí...cũng...).",
    estimatedMinutes: 9,
    grammarNoteVi:
      "连 A 都/也 B: thậm chí A cũng B, nhấn mạnh trường hợp cực đoan/không ngờ tới nhất để làm nổi bật mức độ của B. A thường là trường hợp 'nhỏ nhất/dễ nhất' để nhấn mạnh B càng đúng với mọi trường hợp khác.",
    vocabulary: [
      { id: 'zh-b2-l2-1-v1', term: '连...都/也...', translationVi: 'Thậm chí...cũng...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): lián...dōu/yě...' },
      { id: 'zh-b2-l2-1-v2', term: '一句话', translationVi: 'Một câu nói', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l2-1-s1', usageNoteVi: 'Cách đọc (pinyin): yí jù huà' },
      { id: 'zh-b2-l2-1-v3', term: '答案', translationVi: 'Đáp án', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l2-1-s2', usageNoteVi: 'Cách đọc (pinyin): dá\'àn' },
      { id: 'zh-b2-l2-1-v4', term: '忙得', translationVi: 'Bận đến mức', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l2-1-s3', usageNoteVi: 'Cách đọc (pinyin): máng de' },
      { id: 'zh-b2-l2-1-v5', term: '时间', translationVi: 'Thời gian', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l2-1-s3', usageNoteVi: 'Cách đọc (pinyin): shíjiān' },
      { id: 'zh-b2-l2-1-v6', term: '一分钟', translationVi: 'Một phút', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): yì fēnzhōng' },
      { id: 'zh-b2-l2-1-v7', term: '相信', translationVi: 'Tin tưởng', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): xiāngxìn' },
      { id: 'zh-b2-l2-1-v8', term: '简单', translationVi: 'Đơn giản', partOfSpeech: 'adjective', exampleSentenceId: 'zh-b2-l2-1-s4', usageNoteVi: 'Cách đọc (pinyin): jiǎndān' },
      { id: 'zh-b2-l2-1-v9', term: '复杂', translationVi: 'Phức tạp', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): fùzá' },
      { id: 'zh-b2-l2-1-v10', term: '承认', translationVi: 'Thừa nhận', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-1-s5', usageNoteVi: 'Cách đọc (pinyin): chéngrèn' },
      { id: 'zh-b2-l2-1-v11', term: '犯错', translationVi: 'Phạm sai lầm', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): fàncuò' },
      { id: 'zh-b2-l2-1-v12', term: '细节', translationVi: 'Chi tiết', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): xìjié' },
      { id: 'zh-b2-l2-1-v13', term: '注意', translationVi: 'Chú ý', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): zhùyì' },
    ],
    sentences: [
      { id: 'zh-b2-l2-1-s1', text: '他连一句话都不说。', translationVi: '(Tā lián yí jù huà dōu bù shuō.) Anh ấy thậm chí một câu cũng không nói.' },
      { id: 'zh-b2-l2-1-s2', text: '这个问题连老师都不知道答案。', translationVi: '(Zhège wèntí lián lǎoshī dōu bù zhīdào dá\'àn.) Câu hỏi này thậm chí giáo viên cũng không biết đáp án.' },
      { id: 'zh-b2-l2-1-s3', text: '我忙得连饭都没时间吃。', translationVi: '(Wǒ máng de lián fàn dōu méi shíjiān chī.) Tôi bận đến mức thậm chí cơm cũng không có thời gian ăn.' },
      { id: 'zh-b2-l2-1-s4', text: '这么简单的问题，连小孩子也会。', translationVi: '(Zhème jiǎndān de wèntí, lián xiǎoháizi yě huì.) Câu hỏi đơn giản thế này, thậm chí trẻ con cũng biết.' },
      { id: 'zh-b2-l2-1-s5', text: '他连自己的错误都不承认。', translationVi: '(Tā lián zìjǐ de cuòwù dōu bù chéngrèn.) Anh ấy thậm chí sai lầm của chính mình cũng không thừa nhận.' },
    ],
    exercises: [
      {
        id: 'zh-b2-l2-1-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '他连一句话___不说。',
        options: ['都', '是', '得', '才'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l2-1-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '这么简单的问题，连小孩子___会。',
        wordBank: ['也', '的', '得'],
        correctAnswer: '也',
      },
      {
        id: 'zh-b2-l2-1-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Tôi bận đến mức thậm chí cơm cũng không có thời gian ăn."',
        words: ['没时间吃', '我忙得', '连饭都'],
        correctOrder: ['我忙得', '连饭都', '没时间吃'],
      },
    ],
  },
  {
    id: 'zh-b2-l2-2-wulun-dou',
    unitId: 'zh-b2-u2-emphasis-concession',
    title: '无论...都...',
    titleVi: 'Nhượng bộ tổng quát 无论...都...',
    objectiveVi: "Diễn tả tính phổ quát, không có ngoại lệ, bất kể điều kiện nào bằng '无论...都...'.",
    estimatedMinutes: 9,
    grammarNoteVi:
      "无论 A 都 B: bất kể A (thế nào) thì B vẫn xảy ra. A thường là câu hỏi nghi vấn (什么/谁/怎么/多么...) hoặc lựa chọn (A还是B). Diễn tả tính phổ quát, không có ngoại lệ.",
    vocabulary: [
      { id: 'zh-b2-l2-2-v1', term: '无论...都...', translationVi: 'Bất kể...đều/vẫn...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): wúlùn...dōu...' },
      { id: 'zh-b2-l2-2-v2', term: '改变主意', translationVi: 'Đổi ý', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l2-2-s2', usageNoteVi: 'Cách đọc (pinyin): gǎibiàn zhǔyì' },
      { id: 'zh-b2-l2-2-v3', term: '坚持', translationVi: 'Kiên trì', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-2-s3', usageNoteVi: 'Cách đọc (pinyin): jiānchí' },
      { id: 'zh-b2-l2-2-v4', term: '晴天', translationVi: 'Trời nắng', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l2-2-s3', usageNoteVi: 'Cách đọc (pinyin): qíngtiān' },
      { id: 'zh-b2-l2-2-v5', term: '雨天', translationVi: 'Trời mưa', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l2-2-s3', usageNoteVi: 'Cách đọc (pinyin): yǔtiān' },
      { id: 'zh-b2-l2-2-v6', term: '多么', translationVi: 'Đến mức nào, biết bao', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): duōme' },
      { id: 'zh-b2-l2-2-v7', term: '困难', translationVi: 'Khó khăn', partOfSpeech: 'noun', exampleSentenceId: 'zh-b2-l2-2-s4', usageNoteVi: 'Cách đọc (pinyin): kùnnan' },
      { id: 'zh-b2-l2-2-v8', term: '支持', translationVi: 'Ủng hộ', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-2-s5', usageNoteVi: 'Cách đọc (pinyin): zhīchí' },
      { id: 'zh-b2-l2-2-v9', term: '反对', translationVi: 'Phản đối', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): fǎnduì' },
      { id: 'zh-b2-l2-2-v10', term: '结果', translationVi: 'Kết quả', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): jiéguǒ' },
      { id: 'zh-b2-l2-2-v11', term: '无论如何', translationVi: 'Dù thế nào đi nữa', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l2-2-s5', usageNoteVi: 'Cách đọc (pinyin): wúlùn rúhé' },
      { id: 'zh-b2-l2-2-v12', term: '态度', translationVi: 'Thái độ', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): tàidu' },
      { id: 'zh-b2-l2-2-v13', term: '坚定', translationVi: 'Kiên định', partOfSpeech: 'adjective', usageNoteVi: 'Cách đọc (pinyin): jiāndìng' },
    ],
    sentences: [
      { id: 'zh-b2-l2-2-s1', text: '无论多忙，我都会给你打电话。', translationVi: '(Wúlùn duō máng, wǒ dōu huì gěi nǐ dǎ diànhuà.) Dù bận đến mấy thì tôi cũng sẽ gọi điện cho bạn.' },
      { id: 'zh-b2-l2-2-s2', text: '无论谁说什么，他都不会改变主意。', translationVi: '(Wúlùn shéi shuō shénme, tā dōu bú huì gǎibiàn zhǔyì.) Bất kể ai nói gì thì anh ấy cũng sẽ không đổi ý.' },
      { id: 'zh-b2-l2-2-s3', text: '无论晴天还是雨天，他都坚持跑步。', translationVi: '(Wúlùn qíngtiān háishi yǔtiān, tā dōu jiānchí pǎobù.) Dù trời nắng hay mưa thì anh ấy vẫn kiên trì chạy bộ.' },
      { id: 'zh-b2-l2-2-s4', text: '无论多困难，我们都要完成任务。', translationVi: '(Wúlùn duō kùnnan, wǒmen dōu yào wánchéng rènwu.) Dù khó khăn đến đâu thì chúng ta cũng phải hoàn thành nhiệm vụ.' },
      { id: 'zh-b2-l2-2-s5', text: '无论如何，我都会支持你的决定。', translationVi: '(Wúlùn rúhé, wǒ dōu huì zhīchí nǐ de juédìng.) Dù thế nào đi nữa thì tôi cũng sẽ ủng hộ quyết định của bạn.' },
    ],
    exercises: [
      {
        id: 'zh-b2-l2-2-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '无论多忙，我___会给你打电话。',
        options: ['都', '也', '才', '就'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l2-2-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '无论谁说什么，他___不会改变主意。',
        wordBank: ['都', '也', '才'],
        correctAnswer: '都',
      },
      {
        id: 'zh-b2-l2-2-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Dù trời nắng hay mưa thì anh ấy vẫn kiên trì chạy bộ."',
        words: ['他都坚持跑步', '无论晴天还是雨天'],
        correctOrder: ['无论晴天还是雨天', '他都坚持跑步'],
      },
    ],
  },
  {
    id: 'zh-b2-l2-3-chufei-fouze',
    unitId: 'zh-b2-u2-emphasis-concession',
    title: '除非...否则...',
    titleVi: 'Điều kiện duy nhất 除非...否则...',
    objectiveVi: "Diễn tả một điều kiện bắt buộc duy nhất bằng '除非...否则...' (trừ phi...nếu không thì...).",
    estimatedMinutes: 8,
    grammarNoteVi:
      "除非 A，否则 B: trừ phi A, nếu không thì B (thường B là kết quả tiêu cực/không mong muốn). Diễn tả điều kiện bắt buộc duy nhất để tránh kết quả B.",
    vocabulary: [
      { id: 'zh-b2-l2-3-v1', term: '除非...否则...', translationVi: 'Trừ phi...nếu không thì...', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): chúfēi...fǒuzé...' },
      { id: 'zh-b2-l2-3-v2', term: '道歉', translationVi: 'Xin lỗi', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-3-s1', usageNoteVi: 'Cách đọc (pinyin): dàoqiàn' },
      { id: 'zh-b2-l2-3-v3', term: '原谅', translationVi: 'Tha thứ', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-3-s1', usageNoteVi: 'Cách đọc (pinyin): yuánliàng' },
      { id: 'zh-b2-l2-3-v4', term: '照常', translationVi: 'Như thường lệ', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l2-3-s2', usageNoteVi: 'Cách đọc (pinyin): zhàocháng' },
      { id: 'zh-b2-l2-3-v5', term: '进行', translationVi: 'Tiến hành', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-3-s2', usageNoteVi: 'Cách đọc (pinyin): jìnxíng' },
      { id: 'zh-b2-l2-3-v6', term: '特殊情况', translationVi: 'Tình huống đặc biệt', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l2-3-s3', usageNoteVi: 'Cách đọc (pinyin): tèshū qíngkuàng' },
      { id: 'zh-b2-l2-3-v7', term: '准时', translationVi: 'Đúng giờ', partOfSpeech: 'phrase', exampleSentenceId: 'zh-b2-l2-3-s3', usageNoteVi: 'Cách đọc (pinyin): zhǔnshí' },
      { id: 'zh-b2-l2-3-v8', term: '取消', translationVi: 'Hủy bỏ', partOfSpeech: 'verb', usageNoteVi: 'Cách đọc (pinyin): qǔxiāo' },
      { id: 'zh-b2-l2-3-v9', term: '允许', translationVi: 'Cho phép', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-3-s4', usageNoteVi: 'Cách đọc (pinyin): yǔnxǔ' },
      { id: 'zh-b2-l2-3-v10', term: '条件', translationVi: 'Điều kiện', partOfSpeech: 'noun', usageNoteVi: 'Cách đọc (pinyin): tiáojiàn' },
      { id: 'zh-b2-l2-3-v11', term: '必须', translationVi: 'Bắt buộc phải', partOfSpeech: 'phrase', usageNoteVi: 'Cách đọc (pinyin): bìxū' },
      { id: 'zh-b2-l2-3-v12', term: '保证', translationVi: 'Đảm bảo', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-3-s5', usageNoteVi: 'Cách đọc (pinyin): bǎozhèng' },
      { id: 'zh-b2-l2-3-v13', term: '请假', translationVi: 'Xin nghỉ (phép)', partOfSpeech: 'verb', exampleSentenceId: 'zh-b2-l2-3-s4', usageNoteVi: 'Cách đọc (pinyin): qǐngjià' },
    ],
    sentences: [
      { id: 'zh-b2-l2-3-s1', text: '除非你道歉，否则我不会原谅你。', translationVi: '(Chúfēi nǐ dàoqiàn, fǒuzé wǒ bú huì yuánliàng nǐ.) Trừ phi bạn xin lỗi, nếu không tôi sẽ không tha thứ cho bạn.' },
      { id: 'zh-b2-l2-3-s2', text: '除非下雨，否则比赛照常进行。', translationVi: '(Chúfēi xiàyǔ, fǒuzé bǐsài zhàocháng jìnxíng.) Trừ phi trời mưa, nếu không trận đấu vẫn diễn ra như thường.' },
      { id: 'zh-b2-l2-3-s3', text: '除非有特殊情况，否则请准时到。', translationVi: '(Chúfēi yǒu tèshū qíngkuàng, fǒuzé qǐng zhǔnshí dào.) Trừ phi có tình huống đặc biệt, nếu không xin hãy đến đúng giờ.' },
      { id: 'zh-b2-l2-3-s4', text: '除非公司允许，否则不能请假。', translationVi: '(Chúfēi gōngsī yǔnxǔ, fǒuzé bù néng qǐngjià.) Trừ phi công ty cho phép, nếu không thì không được xin nghỉ.' },
      { id: 'zh-b2-l2-3-s5', text: '除非你能保证按时完成，否则我不能答应。', translationVi: '(Chúfēi nǐ néng bǎozhèng ànshí wánchéng, fǒuzé wǒ bù néng dāying.) Trừ phi bạn có thể đảm bảo hoàn thành đúng hạn, nếu không tôi không thể đồng ý.' },
    ],
    exercises: [
      {
        id: 'zh-b2-l2-3-ex1',
        type: 'multiple-choice',
        promptVi: 'Chọn từ đúng.',
        question: '___你道歉，否则我不会原谅你。',
        options: ['除非', '无论', '连', '一'],
        correctOptionIndex: 0,
      },
      {
        id: 'zh-b2-l2-3-ex2',
        type: 'fill-blank',
        promptVi: 'Điền từ còn thiếu.',
        sentenceTemplate: '除非下雨，___比赛照常进行。',
        wordBank: ['否则', '而且', '所以'],
        correctAnswer: '否则',
      },
      {
        id: 'zh-b2-l2-3-ex3',
        type: 'word-order',
        promptVi: 'Sắp xếp thành câu đúng: "Trừ phi có tình huống đặc biệt, nếu không xin hãy đến đúng giờ."',
        words: ['请准时到', '除非有特殊情况', '否则'],
        correctOrder: ['除非有特殊情况', '否则', '请准时到'],
      },
    ],
  },
];
